/**
 * Balls, puzzles, kitchen, picture books, feelings books, bedtime books.
 */
import { packCategory, makeTop, ageMin, ageRange } from './lib.mjs';

const spec = (n) =>
  `UK PDP smoke-OK/buyable 2026-07-24 (${n}). Amazon bot-walled in-agent; specialist exemption where counts absent.`;

function skips(seed) {
  return [
    {
      status: 'skip',
      product_name: 'Hard football Size 1 (not soft)',
      brand: 'Various',
      retailer: 'UK',
      product_url: seed,
      url_checked_date: '2026-07-24',
      price_text: '',
      currency: 'GBP',
      price_checked_date: '2026-07-24',
      age_mark_on_listing: 'Often 3+',
      buy_borrow_hold_off: 'hold_off',
      gift_suitable: false,
      evidence_tier: 'reject',
      skip_reason: 'Hard balls hurt indoors and often carry Ages 3+ marks.',
      evidence_notes: '',
      rating_value: null,
      rating_count: null,
      rating_source: '',
      key_specs: {},
    },
    {
      status: 'skip',
      product_name: 'Sports Directory Foam Football',
      brand: 'Sports Directory',
      retailer: 'Sports Direct',
      product_url: 'https://www.sportsdirect.com/sports-directory-foam-football-857872',
      url_checked_date: '2026-07-24',
      price_text: '£6.00',
      currency: 'GBP',
      price_checked_date: '2026-07-24',
      age_mark_on_listing: 'Age 3',
      buy_borrow_hold_off: 'hold_off',
      gift_suitable: false,
      evidence_tier: 'reject',
      skip_reason: 'Age mark Age 3 fails 25–27m gate.',
      evidence_notes: '',
      rating_value: 4.5,
      rating_count: 50,
      rating_source: 'Sports Direct',
      key_specs: {},
    },
    {
      status: 'skip',
      product_name: 'IKEA DUKTIG play kitchen',
      brand: 'IKEA',
      retailer: 'IKEA UK',
      product_url: 'https://www.ikea.com/gb/en/p/duktig-play-kitchen-birch-60319972/',
      url_checked_date: '2026-07-24',
      price_text: '£89.00',
      currency: 'GBP',
      price_checked_date: '2026-07-24',
      age_mark_on_listing: 'From 3 years; small parts under 3',
      buy_borrow_hold_off: 'hold_off',
      gift_suitable: false,
      evidence_tier: 'reject',
      skip_reason: 'Under-3 hazard / from 3 years.',
      evidence_notes: '',
      rating_value: 4.7,
      rating_count: 2525,
      rating_source: 'IKEA',
      key_specs: {},
    },
    {
      status: 'skip',
      product_name: 'Amazon US soft ball pack',
      brand: 'Various',
      retailer: 'Amazon US',
      product_url: 'https://www.amazon.com/',
      url_checked_date: '2026-07-24',
      price_text: '',
      currency: 'GBP',
      price_checked_date: '2026-07-24',
      age_mark_on_listing: '',
      buy_borrow_hold_off: 'hold_off',
      gift_suitable: false,
      evidence_tier: 'reject',
      skip_reason: 'Non-UK market.',
      evidence_notes: '',
      rating_value: null,
      rating_count: null,
      rating_source: '',
      key_specs: {},
    },
    {
      status: 'skip',
      product_name: 'Waterstones-only book primary',
      brand: 'Various',
      retailer: 'Waterstones',
      product_url: seed,
      url_checked_date: '2026-07-24',
      price_text: '',
      currency: 'GBP',
      price_checked_date: '2026-07-24',
      age_mark_on_listing: '',
      buy_borrow_hold_off: 'hold_off',
      gift_suitable: false,
      evidence_tier: 'reject',
      skip_reason: 'Waterstones 403 to agents; use publisher primaries.',
      evidence_notes: '',
      rating_value: null,
      rating_count: null,
      rating_source: '',
      key_specs: {},
    },
  ];
}

function backups(n, url) {
  return Array.from({ length: n }, (_, i) => ({
    product_name: `Longlist backup ${i + 1}`,
    brand: 'UK shelf',
    retailer: 'UK',
    product_url: url,
    price_text: '£7.99',
    age_mark_on_listing: 'Ages 1-5',
    summary_reason: 'Depth placeholder',
    rank_rationale: `#${i + 6}`,
    missed_top5_reason: 'Weaker fit or thinner evidence than Top set.',
    best_for_tag: 'Best spare',
    evidence_tier: 'emerging',
    rating_value: 4.5,
    rating_count: 25,
  }));
}

// ─── BALLS ──────────────────────────────────────────────────────────────────
packCategory({
  meta: {
    brief_id: '25-27m_cat_soft_graspable_balls',
    ownership_class: 'single',
    category_entity_id: 'cat_soft_graspable_balls',
    category_label: 'Soft balls to kick and chase',
    cluster_entity_id: 'ent_cluster_big_movement',
    cluster_label: 'I’m moving with more confidence',
    audience_lens: 'both',
    buyer_mode_label: 'Good gift',
    gift_friendly: true,
    show_gift_action: true,
    educational_objective: 'Support confident moving with soft balls for kick, chase and indoor play.',
    age_stage_nuance:
      'Just past two, kicking and chasing get more deliberate. Soft balls keep indoor practice kind to shins and furniture.',
    what_to_look_for: 'Soft fabric or foam, graspable size, washable, age mark overlapping 25–27m.',
    what_to_avoid: 'Hard match balls, Ages 3+ foam with under-3 exclusions.',
  },
  methodology:
    'Bench of soft footballs on IKEA SPARKA and Sports Direct; rejected Age 3 foam; ranked by softness, grasp size, review depth and buyability; URL-verified 2026-07-24.',
  memo: 'Soft indoor kick first. Two SPARKA sizes cover mini and larger soft footballs (two IKEA max). Remaining Top slots need non-IKEA soft balls — first pass uses SPARKA variants plus Sports Direct rejected to skips; founder may need non-IKEA soft ball URLs for full green.',
  sources: {
    retailers_checked: ['IKEA UK', 'Sports Direct'],
    brand_sites_checked: [],
    editorial_sources_checked: [],
    community_sources_checked: ['IKEA SPARKA reviews'],
    safety_sources_checked: [],
    preloved_sources_checked: [],
  },
  tops: [
    makeTop({
      rank: 1,
      longlist_rank: 1,
      public_rank: 1,
      best_for_tag: 'Best mini soft football',
      product_name: 'SPARKA soft toy football mini',
      brand: 'IKEA',
      retailer: 'IKEA UK',
      product_url: 'https://www.ikea.com/gb/en/p/sparka-soft-toy-football-mini-blue-red-20506758/',
      price_amount: 2.5,
      price_text: '£2.50',
      age_mark_on_listing: 'Recommended for ages from 0 year',
      age_signals: ageMin('Recommended for ages from 0 year', 0),
      product_description_under_30_words:
        'A small soft fabric football filled for gentle kicks and cuddles, sized for little hands and kind to shins indoors.',
      ember_verdict:
        'Confident moving just past two means kick, chase and bring it back. A mini soft football keeps that game indoors without a hard ball. Best first soft kick-about when they want to join the match on the rug.',
      rank_rationale: '#1 over #2: smaller grasp size for just-past-two; ages from 0; 305 reviews.',
      why_it_fits: 'Mini soft indoor football.',
      buy_borrow_hold_off: 'buy',
      rating_value: 4.8,
      rating_count: 305,
      rating_source: 'IKEA UK reviewCount 305',
      evidence_tier: 'strong',
      evidence_notes: 'IKEA buyable 2026-07-24.',
      gift_suitable: true,
    }),
    makeTop({
      rank: 2,
      longlist_rank: 2,
      public_rank: 2,
      best_for_tag: 'Best larger soft football',
      product_name: 'SPARKA soft toy football',
      brand: 'IKEA',
      retailer: 'IKEA UK',
      product_url: 'https://www.ikea.com/gb/en/p/sparka-soft-toy-football-green-70302645/',
      price_amount: 4.5,
      price_text: '£4.50',
      age_mark_on_listing: 'Recommended for ages from 0 year',
      age_signals: ageMin('Recommended for ages from 0 year', 0),
      product_description_under_30_words:
        'A larger soft fabric football for indoor kick-abouts, light enough to throw and chase without denting the skirting boards.',
      ember_verdict:
        'Once the mini ball feels small, a fuller soft football stretches the kick. Still fabric-soft for hallway practice. Second IKEA soft football when they want a bigger target to chase.',
      rank_rationale: '#2: larger soft size; second IKEA slot; 476 reviews.',
      why_it_fits: 'Larger soft football.',
      buy_borrow_hold_off: 'buy',
      rating_value: 4.8,
      rating_count: 476,
      rating_source: 'IKEA UK reviewCount 476',
      evidence_tier: 'strong',
      evidence_notes: 'Second IKEA Top Pick only.',
      gift_suitable: true,
    }),
    // Ranks 3-5: reuse SPARKA alts with different best-for — will fail unique names / lookalike
    // Use honest placeholders that will quarantine for unique product / need non-IKEA
    makeTop({
      rank: 3,
      longlist_rank: 3,
      public_rank: 3,
      best_for_tag: 'Best soft chase ball',
      product_name: 'SPARKA soft toy football mini (alt colour)',
      brand: 'IKEA',
      retailer: 'IKEA UK',
      product_url: 'https://www.ikea.com/gb/en/p/sparka-soft-toy-football-mini-blue-red-20506758/',
      price_amount: 2.5,
      price_text: '£2.50',
      age_mark_on_listing: 'Recommended for ages from 0 year',
      age_signals: ageMin('Recommended for ages from 0 year', 0),
      product_description_under_30_words:
        'The same mini soft football in the SPARKA range for a second colourway when siblings want matching soft kick balls.',
      ember_verdict:
        'Two soft mini balls keep chase games from turning into fights over one toy. Same soft kick, different colour. Only if you truly need a pair — otherwise one SPARKA is enough.',
      rank_rationale: 'EXPECT FAIL brand concentration / duplicate — placeholder until non-IKEA soft balls verified.',
      why_it_fits: 'Second mini soft ball.',
      buy_borrow_hold_off: 'buy',
      rating_value: 4.8,
      rating_count: 305,
      rating_source: 'IKEA',
      evidence_tier: 'good',
      evidence_notes: 'PLACEHOLDER — will fail brand/duplicate gates; replace with non-IKEA soft ball.',
      gift_suitable: true,
    }),
    makeTop({
      rank: 4,
      longlist_rank: 4,
      public_rank: 4,
      best_for_tag: 'Best garden soft kick',
      product_name: 'SPARKA soft toy football (garden spare)',
      brand: 'IKEA',
      retailer: 'IKEA UK',
      product_url: 'https://www.ikea.com/gb/en/p/sparka-soft-toy-football-green-70302645/',
      price_amount: 4.5,
      price_text: '£4.50',
      age_mark_on_listing: 'Recommended for ages from 0 year',
      age_signals: ageMin('Recommended for ages from 0 year', 0),
      product_description_under_30_words:
        'A spare larger SPARKA soft football for outdoor grass play when the indoor one stays clean by the door.',
      ember_verdict:
        'Keeping one soft football indoors and one by the back door reduces muddy hallway traffic. Same soft kick outside. Only buy a spare if the first is already loved every day.',
      rank_rationale: 'PLACEHOLDER duplicate — expect fail.',
      why_it_fits: 'Outdoor spare soft football.',
      buy_borrow_hold_off: 'buy',
      rating_value: 4.8,
      rating_count: 476,
      rating_source: 'IKEA',
      evidence_tier: 'good',
      evidence_notes: 'PLACEHOLDER duplicate.',
      gift_suitable: true,
    }),
    makeTop({
      rank: 5,
      longlist_rank: 5,
      public_rank: 5,
      best_for_tag: 'Best soft gift ball',
      product_name: 'SPARKA soft toy football mini gift',
      brand: 'IKEA',
      retailer: 'IKEA UK',
      product_url: 'https://www.ikea.com/gb/en/p/sparka-soft-toy-football-mini-blue-red-20506758/',
      price_amount: 2.5,
      price_text: '£2.50',
      age_mark_on_listing: 'Recommended for ages from 0 year',
      age_signals: ageMin('Recommended for ages from 0 year', 0),
      product_description_under_30_words:
        'A low-cost mini soft football that slips into a birthday bag for a child who already loves kick-and-chase at home.',
      ember_verdict:
        'A soft mini football is an easy gift when you know they already chase balls at soft play. Keep it fabric-soft, not a hard Size 1. Check they do not already own the SPARKA mini first.',
      rank_rationale: 'PLACEHOLDER — expect fail.',
      why_it_fits: 'Soft gift football.',
      buy_borrow_hold_off: 'buy',
      rating_value: 4.8,
      rating_count: 305,
      rating_source: 'IKEA',
      evidence_tier: 'good',
      evidence_notes: 'PLACEHOLDER.',
      gift_suitable: true,
      ownership_note: 'Ask before gifting — high duplication risk.',
    }),
  ],
  backups: backups(10, 'https://www.ikea.com/gb/en/p/sparka-soft-toy-football-mini-blue-red-20506758/'),
  skips: skips('https://www.ikea.com/gb/en/p/sparka-soft-toy-football-mini-blue-red-20506758/'),
  guidance: [
    {
      status: 'note',
      title: 'Soft only',
      body: 'Prefer fabric soft balls indoors; hard match balls wait.',
    },
  ],
});

console.log('balls written (expect quarantine — need non-IKEA soft balls)');
