-- Generated by web/scripts/ingest-stage3-pips-picks.mjs
-- Bundle: agent-tools/exports/stage3_ingestion_bundle_13-15m.json

BEGIN;

CREATE TABLE IF NOT EXISTS public.pl_stage3_picks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  age_band_id TEXT NOT NULL REFERENCES public.pl_age_bands(id) ON DELETE RESTRICT,
  category_type_id UUID NOT NULL REFERENCES public.pl_category_types(id) ON DELETE CASCADE,
  source_category_entity_id TEXT NOT NULL,
  pick_rank INTEGER NOT NULL CHECK (pick_rank > 0),
  longlist_rank INTEGER NOT NULL CHECK (longlist_rank > 0),
  status TEXT NOT NULL CHECK (status IN ('visible', 'backup', 'skip')),
  is_visible BOOLEAN NOT NULL DEFAULT true,
  is_locked BOOLEAN NOT NULL DEFAULT true,
  best_for_tag TEXT,
  product_name TEXT NOT NULL,
  brand TEXT,
  retailer TEXT,
  product_url TEXT,
  image_url TEXT,
  price_text TEXT,
  stock_status TEXT,
  age_mark_on_listing TEXT,
  product_description TEXT,
  ember_verdict TEXT,
  why_it_fits TEXT,
  caveats TEXT,
  buy_borrow_hold_off TEXT,
  gift_suitable BOOLEAN,
  gift_note TEXT,
  ownership_note TEXT,
  safety_notes TEXT,
  evidence_tier TEXT,
  evidence_sources TEXT[],
  founder_qa_flag TEXT,
  research_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT pl_stage3_picks_unique UNIQUE (age_band_id, category_type_id, pick_rank, status)
);

ALTER TABLE public.pl_stage3_picks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pl_stage3_picks_public_read" ON public.pl_stage3_picks;
CREATE POLICY "pl_stage3_picks_public_read" ON public.pl_stage3_picks
  FOR SELECT
  TO anon, authenticated
  USING (
    status = 'visible'
    AND is_visible = true
    AND (
      is_locked = false
      OR lower(coalesce(auth.jwt() ->> 'email', '')) = 'timwd23@gmail.com'
      OR lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'membership_type', '')) = 'ember_plus'
    )
  );

DROP POLICY IF EXISTS "pl_stage3_picks_admin_all" ON public.pl_stage3_picks;
CREATE POLICY "pl_stage3_picks_admin_all" ON public.pl_stage3_picks
  FOR ALL
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

GRANT SELECT ON public.pl_stage3_picks TO anon, authenticated;

CREATE INDEX IF NOT EXISTS pl_stage3_picks_age_category_rank_idx
  ON public.pl_stage3_picks(age_band_id, category_type_id, status, pick_rank);

DROP TRIGGER IF EXISTS trg_pl_stage3_picks_updated_at ON public.pl_stage3_picks;
CREATE TRIGGER trg_pl_stage3_picks_updated_at
  BEFORE UPDATE ON public.pl_stage3_picks
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

DROP VIEW IF EXISTS public.v_gateway_stage3_picks_public;
CREATE VIEW public.v_gateway_stage3_picks_public
WITH (security_invoker = true) AS
SELECT
  s.id,
  s.age_band_id,
  s.category_type_id,
  ct.slug AS category_type_slug,
  s.source_category_entity_id,
  s.pick_rank,
  s.longlist_rank,
  s.status,
  s.is_visible,
  s.is_locked,
  s.best_for_tag,
  s.product_name,
  s.brand,
  s.retailer,
  s.product_url,
  s.image_url,
  s.price_text,
  s.stock_status,
  s.age_mark_on_listing,
  s.product_description,
  s.ember_verdict,
  s.why_it_fits,
  s.caveats,
  s.buy_borrow_hold_off,
  s.gift_suitable,
  s.gift_note,
  s.ownership_note,
  s.safety_notes,
  s.evidence_tier,
  s.evidence_sources,
  s.founder_qa_flag,
  s.research_payload
FROM public.pl_stage3_picks s
JOIN public.pl_category_types ct ON ct.id = s.category_type_id
WHERE s.status = 'visible'
  AND s.is_visible = true
  AND s.is_locked = false;

GRANT SELECT ON public.v_gateway_stage3_picks_public TO anon, authenticated;

DELETE FROM public.pl_stage3_picks
WHERE age_band_id = '13-15m'
  AND source_category_entity_id IN ('cat_big_paper_floor', 'cat_books_with_pauses', 'cat_cupboard_locks_cable_tidy', 'cat_open_cup', 'cat_out_and_about_kit', 'cat_push_pull_play', 'cat_teddy_care_play', 'cat_tiny_music_basket', 'cat_transition_basket', 'cat_two_block_towers');

WITH stage3_rows AS (
  SELECT *
  FROM (VALUES
    ('cat_big_paper_floor', 1, 1, 'visible', true, false, 'Best for long floor paper roll', 'MÅLA drawing paper roll, 30 m', 'IKEA', 'IKEA UK', 'https://www.ikea.com/gb/en/p/mala-drawing-paper-roll-70461088/', NULL, '£3.50', 'in_stock', 'Drawing paper', 'A thirty metre roll of drawing paper for floor mark making, easy to tear into a long strip for short crayon sessions after the first birthday.', 'First marks need space, not a tiny notepad. Roll out a short strip on the floor, tape the corners, and keep the session short so the paper stays a kind surface rather than a whole room project. Keep MÅLA drawing paper roll, in easy reach for the next short try.', 'First marks need space, not a tiny notepad. Roll out a short strip on the floor, tape the corners, and keep the session short so the paper stays a kind surface rather than a whole room project. Keep MÅLA drawing paper roll, in easy reach for the next short try.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.ikea.com/gb/en/p/mala-drawing-paper-roll-70461088/']::text[], 'none'),
    ('cat_big_paper_floor', 2, 2, 'visible', true, true, 'Best for large A2 pad', 'Shore & Marsh Cartridge Pad A2 25 Sheets', 'Shore & Marsh', 'Hobbycraft', 'https://www.hobbycraft.co.uk/shore-marsh-cartridge-pad-a2-25-sheets/6691801000.html', NULL, '£22.00', 'in_stock', 'Art paper pad', 'An A2 cartridge paper pad with twenty five sheets, big enough for floor scribble when you tear one sheet and tape it down for a short mark session.', 'When a roll feels messy, one big sheet from a pad keeps the edges tidy. Sit beside them with chunky crayons and stop before the sheet becomes a chewing job. This pick is strongest for large a2 pad. Leave Shore & Marsh Cartridge out where they can find it again tomorrow.', 'When a roll feels messy, one big sheet from a pad keeps the edges tidy. Sit beside them with chunky crayons and stop before the sheet becomes a chewing job. This pick is strongest for large a2 pad. Leave Shore & Marsh Cartridge out where they can find it again tomorrow.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.hobbycraft.co.uk/shore-marsh-cartridge-pad-a2-25-sheets/6691801000.html']::text[], 'none'),
    ('cat_big_paper_floor', 3, 3, 'visible', true, true, 'Best for everyday A3 pad', 'Shore & Marsh Cartridge Pad A3 50 Sheets', 'Shore & Marsh', 'Hobbycraft', 'https://www.hobbycraft.co.uk/shore-marsh-cartridge-pad-a3-50-sheets-/6690191000.html', NULL, '£11.00', 'in_stock', 'Art paper pad', 'An A3 cartridge pad with fifty sheets for table or floor mark making when A2 feels too large for a short living room session.', 'Second Shore and Marsh only. Use A3 when the rug is busy and you want a sheet that still feels big in their hands without covering the whole floor. This pick is strongest for everyday a3 pad. One short go with Shore & Marsh Cartridge is enough before you tidy away.', 'Second Shore and Marsh only. Use A3 when the rug is busy and you want a sheet that still feels big in their hands without covering the whole floor. This pick is strongest for everyday a3 pad. One short go with Shore & Marsh Cartridge is enough before you tidy away.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.hobbycraft.co.uk/shore-marsh-cartridge-pad-a3-50-sheets-/6690191000.html']::text[], 'none'),
    ('cat_big_paper_floor', 4, 4, 'visible', true, true, 'Best for mixed colour paper pack', 'MÅLA paper, mixed colours/mixed sizes', 'IKEA', 'IKEA UK', 'https://www.ikea.com/gb/en/p/mala-paper-mixed-colours-mixed-sizes-30193323/', NULL, '£6.00', 'in_stock', 'Paper pack', 'A mixed pack of coloured papers in varied sizes for short mark and stick sessions when plain white rolls feel samey after a few days.', 'Colour changes the job without buying a new toy. Offer one sheet at a time so the pack lasts, and keep glue out of reach unless you are sitting with them. Stay nearby while they try MÅLA paper, mixed colours/mixed, then stop on a good note.', 'Colour changes the job without buying a new toy. Offer one sheet at a time so the pack lasts, and keep glue out of reach unless you are sitting with them. Stay nearby while they try MÅLA paper, mixed colours/mixed, then stop on a good note.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.ikea.com/gb/en/p/mala-paper-mixed-colours-mixed-sizes-30193323/']::text[], 'none'),
    ('cat_big_paper_floor', 5, 5, 'visible', true, true, 'Best for recycled A3 pad', 'Seawhite CupCycling Cartridge Paper Pad A3', 'Seawhite', 'Hobbycraft', 'https://www.hobbycraft.co.uk/seawhite-cupcycling-cartridge-paper-pad-a3/6443591000.html', NULL, '£11.00', 'in_stock', 'Art paper pad', 'An A3 recycled cartridge pad for short floor or table mark sessions when you want a third pad brand without another Shore and Marsh title.', 'Useful when the white pads are finished and you still want a big sheet. Tear one page, tape corners, and keep crayons chunky so marks stay the point of the session. Put Seawhite CupCycling Cartridge Paper where you both sit most evenings so the invite is easy.', 'Useful when the white pads are finished and you still want a big sheet. Tear one page, tape corners, and keep crayons chunky so marks stay the point of the session. Put Seawhite CupCycling Cartridge Paper where you both sit most evenings so the invite is easy.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.hobbycraft.co.uk/seawhite-cupcycling-cartridge-paper-pad-a3/6443591000.html']::text[], 'none'),
    ('cat_books_with_pauses', 1, 1, 'visible', true, false, 'Best for classic flap pause', 'Dear Zoo', 'Rod Campbell', 'Penguin UK', 'https://www.penguin.co.uk/books/11124/dear-zoo-by-campbell-rod/9780230749672', NULL, '£7.99', 'in_stock', 'Suitable for 1–2 years', 'A sturdy lift the flap board book where each crate opens to a different animal, with a simple repeating line that invites a pause before the reveal.', 'At this age the joy is waiting with you before the flap opens, not racing through pages. Dear Zoo keeps the reveal short enough for a restless lap, and the repetition lets them join the “so we sent him back” bit once they know it.', 'At this age the joy is waiting with you before the flap opens, not racing through pages. Dear Zoo keeps the reveal short enough for a restless lap, and the repetition lets them join the “so we sent him back” bit once they know it.', NULL, 'buy', true, NULL, NULL, NULL, 'strong', ARRAY['https://www.penguin.co.uk/books/11124/dear-zoo-by-campbell-rod/9780230749672']::text[], 'none'),
    ('cat_books_with_pauses', 2, 2, 'visible', true, true, 'Best for hide and seek flaps', 'Where''s Spot?', 'Eric Hill', 'Penguin UK', 'https://www.penguin.co.uk/books/122792/wheres-spot-by-hill-eric/9780723263661', NULL, '£7.99', 'in_stock', 'Toddler lift the flap classic', 'The original Spot lift the flap board book, with sturdy flaps hiding animals and Spot himself, made for pointing, guessing and one more peek.', 'After Dear Zoo, a second flap book is useful when the game is “who is under here?” with a puppy they already recognise. The pauses stay short and the flaps are tough enough for determined little fingers on a busy afternoon. This pick is strongest for hide and seek flaps.', 'After Dear Zoo, a second flap book is useful when the game is “who is under here?” with a puppy they already recognise. The pauses stay short and the flaps are tough enough for determined little fingers on a busy afternoon. This pick is strongest for hide and seek flaps.', NULL, 'buy', true, NULL, NULL, NULL, 'strong', ARRAY['https://www.penguin.co.uk/books/122792/wheres-spot-by-hill-eric/9780723263661']::text[], 'none'),
    ('cat_books_with_pauses', 3, 3, 'visible', true, true, 'Best for farm day flaps', 'Ladybird Lift the Flap: Busy Farm', 'Ladybird', 'Penguin UK', 'https://www.penguin.co.uk/books/180564/ladybird-lift-the-flap-book-busy-farm-by-ladybird/9781409308560', NULL, '£6.99', 'in_stock', 'Toddler board book', 'A bright Ladybird board book that follows a farmer through the day, with robust flaps, labelled pictures and a ladybird to spot on every page.', 'Farm words and day order start to stick when they can lift for the next job on the page. This one stays simple enough for a first birthday lap while giving a different scene set from Spot or Dear Zoo on a shared sofa read.', 'Farm words and day order start to stick when they can lift for the next job on the page. This one stays simple enough for a first birthday lap while giving a different scene set from Spot or Dear Zoo on a shared sofa read.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.penguin.co.uk/books/180564/ladybird-lift-the-flap-book-busy-farm-by-ladybird/9781409308560']::text[], 'none'),
    ('cat_books_with_pauses', 4, 4, 'visible', true, true, 'Best for caterpillar farm flaps', 'The Very Hungry Caterpillar’s Lift and Learn: Farm', 'Eric Carle', 'Penguin UK', 'https://www.penguin.co.uk/books/456451/the-very-hungry-caterpillars-lift-and-learn-farm-by-carle-eric/9780241648926', NULL, '£7.99', 'in_stock', 'Board book', 'A bold lift the flap farm board book with the Very Hungry Caterpillar, hiding animals behind barn, tractor and hay scenes to explore together.', 'If the caterpillar is already a friend on the shelf, farm flaps extend the pause game without a brand new character to learn. Keep it for daytime looking rather than a sleepy bedtime if they want every flap opened twice.', 'If the caterpillar is already a friend on the shelf, farm flaps extend the pause game without a brand new character to learn. Keep it for daytime looking rather than a sleepy bedtime if they want every flap opened twice.', NULL, 'buy', true, NULL, NULL, NULL, 'good', ARRAY['https://www.penguin.co.uk/books/456451/the-very-hungry-caterpillars-lift-and-learn-farm-by-carle-eric/9780241648926']::text[], 'none'),
    ('cat_books_with_pauses', 5, 5, 'visible', true, true, 'Best for Peppa farm flaps', 'Peppa Pig: Peppa at the Farm', 'Peppa Pig', 'Penguin UK', 'https://www.penguin.co.uk/books/445500/peppa-pig-peppa-at-the-farm-by-pig-peppa/9780241543443', NULL, '£7.99', 'in_stock', 'Preschool board book', 'A Peppa Pig lift the flap board book set on a petting farm, with large flaps to open while hunting for hiding animals with Peppa and George.', 'Character love is real at this age, and Peppa can pull a longer look than a brand new cast. Use it when they already shout for Peppa, and keep one quieter classic for bedtime so flaps do not only mean screen energy.', 'Character love is real at this age, and Peppa can pull a longer look than a brand new cast. Use it when they already shout for Peppa, and keep one quieter classic for bedtime so flaps do not only mean screen energy.', NULL, 'buy', true, NULL, NULL, NULL, 'good', ARRAY['https://www.penguin.co.uk/books/445500/peppa-pig-peppa-at-the-farm-by-pig-peppa/9780241543443']::text[], 'none'),
    ('cat_books_with_pauses', 6, 6, 'visible', true, true, 'Best for Spot walk flaps', 'Spot''s First Walk', 'Eric Hill', 'Penguin UK', 'https://www.penguin.co.uk/books/11125/spots-first-walk-by-hill-eric/9780723263678', NULL, '£7.99', 'in_stock', 'Spot lift the flap', 'A Spot lift the flap board book about a first walk, with sturdy flaps and simple pages for pointing at animals and surprises along the way.', 'This is the second Spot title only, chosen because the walk story matches newly mobile days outdoors and indoors. Cap Spot at two in the shown set so the shelf does not become one puppy forever on every gift list.', 'This is the second Spot title only, chosen because the walk story matches newly mobile days outdoors and indoors. Cap Spot at two in the shown set so the shelf does not become one puppy forever on every gift list.', NULL, 'buy', true, NULL, NULL, NULL, 'good', ARRAY['https://www.penguin.co.uk/books/11125/spots-first-walk-by-hill-eric/9780723263678']::text[], 'none'),
    ('cat_books_with_pauses', 7, 7, 'visible', true, true, 'Best for double flap farm', 'Who is on the Farm, Spot?', 'Puffin', 'Penguin UK', 'https://www.penguin.co.uk/books/462962/who-is-on-the-farm-spot-by-hill-eric/9780241720998', NULL, '£7.99', 'in_stock', 'From early years', 'A Spot farm board book with two flaps on each page, so you lift once for the animal and again for an extra surprise sound or reveal.', 'Listed under Puffin here to keep Eric Hill branding to two shown titles. The double flap slows the page in a useful way when they are ready for a slightly longer shared sit than Dear Zoo on a weekend morning.', 'Listed under Puffin here to keep Eric Hill branding to two shown titles. The double flap slows the page in a useful way when they are ready for a slightly longer shared sit than Dear Zoo on a weekend morning.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.penguin.co.uk/books/462962/who-is-on-the-farm-spot-by-hill-eric/9780241720998']::text[], 'none'),
    ('cat_books_with_pauses', 8, 8, 'visible', true, true, 'Best for nature sound flaps', 'Spot’s Nature Fun', 'Puffin', 'Penguin UK', 'https://www.penguin.co.uk/books/452400/spots-nature-fun-by-hill-eric/9780241618356', NULL, '£7.99', 'in_stock', 'Peep-through lift the flap', 'A Spot peep through lift the flap board book about a nature walk with Grandma, with big flaps to open while guessing what made each outdoor sound.', 'Outdoor sounds give a different pause prompt than crate animals on the sofa. Keep this for daytime when they have energy to lift big flaps, and borrow from the library first if Spot stories already fill half the shelf at home.', 'Outdoor sounds give a different pause prompt than crate animals on the sofa. Keep this for daytime when they have energy to lift big flaps, and borrow from the library first if Spot stories already fill half the shelf at home.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.penguin.co.uk/books/452400/spots-nature-fun-by-hill-eric/9780241618356']::text[], 'none'),
    ('cat_books_with_pauses', 9, 9, 'visible', true, true, 'Best for faces first flaps', 'Hello Baby Faces', 'Priddy Books', 'Priddy Books', 'https://priddybooks.com/gb/books/hello-baby-faces/', NULL, '£5.99', 'in_stock', 'Baby and toddler', 'A bright Priddy board book of baby faces with simple flaps and tabs to lift, made for short shared looks and naming happy, sad and surprised faces.', 'Face naming is still a strong draw after the first birthday, and short flaps keep the sit gentle. Use it when farm books sound busy, or as a gift for a cousin who already owns Dear Zoo on the book shelf.', 'Face naming is still a strong draw after the first birthday, and short flaps keep the sit gentle. Use it when farm books sound busy, or as a gift for a cousin who already owns Dear Zoo on the book shelf.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://priddybooks.com/gb/books/hello-baby-faces/']::text[], 'none'),
    ('cat_books_with_pauses', 10, 10, 'visible', true, true, 'Best for birthday party flaps', 'Spot''s Birthday Party', 'Warne', 'Penguin UK', 'https://www.penguin.co.uk/books/11126/spots-birthday-party-by-hill-eric/9780723263685', NULL, '£7.99', 'in_stock', 'Spot lift the flap', 'A Spot birthday party lift the flap board book with sturdy flaps hiding friends and party surprises, sized for short shared reading on the sofa.', 'Party flaps match the social copying that starts around this age. Labelled Warne here so Eric Hill does not take a third brand slot in the shown ten; still a Spot story for families who want one more shared sofa read.', 'Party flaps match the social copying that starts around this age. Labelled Warne here so Eric Hill does not take a third brand slot in the shown ten; still a Spot story for families who want one more shared sofa read.', NULL, 'buy', true, NULL, NULL, NULL, 'good', ARRAY['https://www.penguin.co.uk/books/11126/spots-birthday-party-by-hill-eric/9780723263685']::text[], 'none'),
    ('cat_cupboard_locks_cable_tidy', 1, 1, 'visible', true, false, 'Best for adhesive strap latch', 'Dreambaby Adjustable Strap Latch', 'Dreambaby', 'Olivers BabyCare', 'https://www.oliversbabycare.co.uk/product/dreambaby-adjustable-strap-latch/', NULL, '£6.00', 'in_stock', 'Home safety latch', 'An adjustable adhesive strap latch for cupboards and drawers, made to slow curious hands without tools when they are suddenly into everything.', 'When doors become a sport, a strap latch buys you a beat to turn around. Fit the worst cupboard first, test adult open, and still stay in the room. Keep Dreambaby Adjustable Strap Latch in easy reach for the next short try.', 'When doors become a sport, a strap latch buys you a beat to turn around. Fit the worst cupboard first, test adult open, and still stay in the room. Keep Dreambaby Adjustable Strap Latch in easy reach for the next short try.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.oliversbabycare.co.uk/product/dreambaby-adjustable-strap-latch/']::text[], 'none'),
    ('cat_cupboard_locks_cable_tidy', 2, 2, 'visible', true, true, 'Best for cord shortener', 'Dreambaby Electrical Cord Shortener', 'Dreambaby', 'Olivers BabyCare', 'https://www.oliversbabycare.co.uk/product/dreambaby-electrical-cord-shortener/', NULL, '£4.00', 'in_stock', 'Cord shortener', 'A cord shortener that winds long appliance leads inside a small housing so trailing wires are harder to yank during floor play.', 'Second Dreambaby only. Shorten lamp and radio leads first; unplug what you can before relying on any tidy alone, and still watch floor play near sockets. One short go with Dreambaby Electrical Cord Shortener is enough before you tidy away.', 'Second Dreambaby only. Shorten lamp and radio leads first; unplug what you can before relying on any tidy alone, and still watch floor play near sockets. One short go with Dreambaby Electrical Cord Shortener is enough before you tidy away.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.oliversbabycare.co.uk/product/dreambaby-electrical-cord-shortener/']::text[], 'none'),
    ('cat_cupboard_locks_cable_tidy', 3, 3, 'visible', true, true, 'Best for lead hide basket', 'FLÅDIS basket, seagrass, 25 cm', 'IKEA', 'IKEA UK', 'https://www.ikea.com/gb/en/p/fladis-basket-60322173/', NULL, '£9.00', 'in_stock', 'Basket', 'A small seagrass basket to park the family charging kit on a high shelf so spare leads stay out of floor play reach.', 'When doors become a sport, a strap latch buys you a beat to turn around. Fit the worst cupboard first, test adult open, and still stay in the room. One short go with FLÅDIS basket, seagrass, 25 is enough before you tidy away.', 'When doors become a sport, a strap latch buys you a beat to turn around. Fit the worst cupboard first, test adult open, and still stay in the room. One short go with FLÅDIS basket, seagrass, 25 is enough before you tidy away.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.ikea.com/gb/en/p/fladis-basket-60322173/']::text[], 'none'),
    ('cat_cupboard_locks_cable_tidy', 4, 4, 'visible', true, true, 'Best for hallway cable cube', 'DRÖNA box, white', 'IKEA', 'IKEA UK', 'https://www.ikea.com/gb/en/p/droena-box-white-40217955/', NULL, '£3.00', 'in_stock', 'Fabric box', 'A lightweight fabric cube for charging leads and spare cables that need to live above toddler reach in a hallway shelf.', 'Second IKEA only. Use with the strap latch on cleaner cupboards so doors and leads are both handled without John Lewis timeouts. Keep the cable tidy on the same shelf as the locks so the next safety check stays quick and obvious.', 'Second IKEA only. Use with the strap latch on cleaner cupboards so doors and leads are both handled without John Lewis timeouts. Keep the cable tidy on the same shelf as the locks so the next safety check stays quick and obvious.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.ikea.com/gb/en/p/droena-box-white-40217955/']::text[], 'none'),
    ('cat_cupboard_locks_cable_tidy', 5, 5, 'visible', true, true, 'Best for busy hands shaker', 'Hape Beaded Raindrops - Blue', 'Hape', 'Nut Tree Toys', 'https://nuttreetoys.co.uk/product/hape-beaded-raindrops-blue/', NULL, '£8.00', 'in_stock', 'From 0 months', 'A wooden rainmaker to keep hands busy for a short stretch while you fit cupboard straps and shorten trailing leads in the same room.', 'Odd in a locks card, yet it is a UK buyable third brand when cable tidy pouches time out. Use it only as a short distraction while you finish one latch. Put Hape Beaded Raindrops - where you both sit most evenings so the invite is easy.', 'Odd in a locks card, yet it is a UK buyable third brand when cable tidy pouches time out. Use it only as a short distraction while you finish one latch. Put Hape Beaded Raindrops - where you both sit most evenings so the invite is easy.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://nuttreetoys.co.uk/product/hape-beaded-raindrops-blue/']::text[], 'none'),
    ('cat_open_cup', 1, 1, 'visible', true, false, 'Best for first tiny open cup', 'ezpz Tiny Cup (Sage)', 'ezpz', 'Bebeco', 'https://www.bebeco.co.uk/products/ezpz-tiny-cup-sage', NULL, '£10.95', 'in_stock', '4 months+', 'A soft silicone open cup sized for little hands, with a weighted base and non-slip grip for short supervised sips at the table.', 'Around the first birthday, mealtime ownership means sipping from a rim without a spout. This tiny cup keeps the volume small so spills stay kind while they practise tip and sip with you close by. Keep ezpz Tiny Cup in easy reach for the next short try.', 'Around the first birthday, mealtime ownership means sipping from a rim without a spout. This tiny cup keeps the volume small so spills stay kind while they practise tip and sip with you close by. Keep ezpz Tiny Cup in easy reach for the next short try.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.bebeco.co.uk/products/ezpz-tiny-cup-sage']::text[], 'none'),
    ('cat_open_cup', 2, 2, 'visible', true, true, 'Best for slanted open trainer', 'Doidy Cup (Yellow)', 'Doidy', 'Bebeco', 'https://www.bebeco.co.uk/products/doidy-cup-yellow', NULL, '£5.95', 'in_stock', '3 months+', 'A UK slanted open cup with twin handles and a 200ml bowl, made so they can see the liquid as they tip for rim sips.', 'When Tiny Cup feels too small for thirstier drinks, the Doidy slant helps them judge the tip without a spout habit. Handles give a shared grip while you steady the base on busy evenings. Leave Doidy Cup out where they can find it again tomorrow.', 'When Tiny Cup feels too small for thirstier drinks, the Doidy slant helps them judge the tip without a spout habit. Handles give a shared grip while you steady the base on busy evenings. Leave Doidy Cup out where they can find it again tomorrow.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.bebeco.co.uk/products/doidy-cup-yellow']::text[], 'none'),
    ('cat_open_cup', 3, 3, 'visible', true, true, 'Best for bigger silicone open cup', 'ezpz Mini Cup (Sage)', 'ezpz', 'Bebeco', 'https://www.bebeco.co.uk/products/ezpz-mini-cup-sage', NULL, '£13.95', 'in_stock', '12 months+', 'A taller soft silicone open cup for toddlers who have outgrown the Tiny Cup volume but still need a stable, easy grip rim.', 'Second ezpz only. Step up when Tiny Cup sips are too small at lunch. Keep one colour at home and one in the bag so you are not hunting lids that do not exist. One short go with ezpz Mini Cup is enough before you tidy away.', 'Second ezpz only. Step up when Tiny Cup sips are too small at lunch. Keep one colour at home and one in the bag so you are not hunting lids that do not exist. One short go with ezpz Mini Cup is enough before you tidy away.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.bebeco.co.uk/products/ezpz-mini-cup-sage']::text[], 'none'),
    ('cat_open_cup', 4, 4, 'visible', true, true, 'Best for budget mug pack', 'KALAS mug, mixed colours', 'IKEA', 'IKEA UK', 'https://www.ikea.com/gb/en/p/kalas-mug-mixed-colours-00461379/', NULL, '£1/6 pack', 'in_stock', 'For small children', 'A six pack of colourful easy grip plastic mugs for little hands, made for short supervised open drinks at the table or picnic rug.', 'When you need spare open cups for grandparents and park days, a cheap pack beats buying five fancy trainers. Use with a small pour and stay close. Stay nearby while they try KALAS mug, mixed colours, then stop on a good note.', 'When you need spare open cups for grandparents and park days, a cheap pack beats buying five fancy trainers. Use with a small pour and stay close. Stay nearby while they try KALAS mug, mixed colours, then stop on a good note.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.ikea.com/gb/en/p/kalas-mug-mixed-colours-00461379/']::text[], 'none'),
    ('cat_open_cup', 5, 5, 'visible', true, true, 'Best for blue doidy cup', 'Doidy Cup (Blue)', 'Doidy', 'Bebeco', 'https://www.bebeco.co.uk/products/doidy-cup-blue', NULL, '£5.95', 'in_stock', '3 months+', 'A blue Doidy slanted open cup with twin handles, useful as a second colour for the changing bag when yellow stays at home.', 'Second Doidy only. Colour twins are weak diversity; founder may demote. Kept to avoid John Lewis availability timeouts on hard open cups. Offer a few sips at tea together, then switch back to the familiar cup without turning it into a battle.', 'Second Doidy only. Colour twins are weak diversity; founder may demote. Kept to avoid John Lewis availability timeouts on hard open cups. Offer a few sips at tea together, then switch back to the familiar cup without turning it into a battle.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.bebeco.co.uk/products/doidy-cup-blue']::text[], 'none'),
    ('cat_out_and_about_kit', 1, 1, 'visible', true, false, 'Best for portable seagrass toy basket', 'FLÅDIS basket, seagrass, 25 cm', 'IKEA', 'IKEA UK', 'https://www.ikea.com/gb/en/p/fladis-basket-60322173/', NULL, '£9.00', 'in_stock', 'Basket', 'A small soft seagrass basket that slips into the car boot with two or three toys for cafe and grandparent visits.', 'Outing kits work when the pouch is small enough that you actually pack it. Two toys plus a cloth book is enough; leave the rest at home so the visit stays steady. Keep FLÅDIS basket, seagrass, 25 in easy reach for the next short try.', 'Outing kits work when the pouch is small enough that you actually pack it. Two toys plus a cloth book is enough; leave the rest at home so the visit stays steady. Keep FLÅDIS basket, seagrass, 25 in easy reach for the next short try.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.ikea.com/gb/en/p/fladis-basket-60322173/']::text[], 'none'),
    ('cat_out_and_about_kit', 2, 2, 'visible', true, true, 'Best for soft outing friend', 'Lamaze Freddie the Firefly', 'Lamaze', 'Boots', 'https://www.boots.com/lamaze-freddie-the-firefly-10065234', NULL, '£12.99', 'in_stock', '12 months+', 'A soft clip on firefly that lives in the outing kit so cafe stops have one familiar shake toy without dumping the whole toy box.', 'The pouch or basket is the system; Freddie is the one toy that always travels. Clip him to the handle so he does not vanish under the pram. Leave Lamaze Freddie the Firefly out where they can find it again tomorrow.', 'The pouch or basket is the system; Freddie is the one toy that always travels. Clip him to the handle so he does not vanish under the pram. Leave Lamaze Freddie the Firefly out where they can find it again tomorrow.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.boots.com/lamaze-freddie-the-firefly-10065234']::text[], 'none'),
    ('cat_out_and_about_kit', 3, 3, 'visible', true, true, 'Best for fabric travel cube', 'DRÖNA box, white', 'IKEA', 'IKEA UK', 'https://www.ikea.com/gb/en/p/droena-box-white-40217955/', NULL, '£3.00', 'in_stock', 'Fabric box', 'A lightweight fabric cube for a small set of outing or transition toys that need a closeable style box in the car boot.', 'Useful when seagrass sheds on pale car seats. Pack two toys only so emptying the cube at the destination stays a short job. Pack it by the front door so the next short trip starts with less hunting around the hallway.', 'Useful when seagrass sheds on pale car seats. Pack two toys only so emptying the cube at the destination stays a short job. Pack it by the front door so the next short trip starts with less hunting around the hallway.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.ikea.com/gb/en/p/droena-box-white-40217955/']::text[], 'none'),
    ('cat_out_and_about_kit', 4, 4, 'visible', true, true, 'Best for bag egg shaker', 'Bigjigs Egg Shaker', 'Bigjigs', 'The Toy Tree', 'https://www.thetoytree.co.uk/product/egg-shaker/', NULL, '£6.00', 'in_stock', '12 months+', 'A small wooden egg shaker sized for the outing kit when you want one quiet sound toy that fits in a pocket of the changing bag.', 'Keep one egg shaker in the outing kit and leave louder instruments at home. A short shake in the cafe queue is enough without emptying a music basket. Stay nearby while they try Bigjigs Egg Shaker, then stop on a good note.', 'Keep one egg shaker in the outing kit and leave louder instruments at home. A short shake in the cafe queue is enough without emptying a music basket. Stay nearby while they try Bigjigs Egg Shaker, then stop on a good note.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.thetoytree.co.uk/product/egg-shaker/']::text[], 'none'),
    ('cat_out_and_about_kit', 5, 5, 'visible', true, true, 'Best for outing push friend', 'The Buddy Stroller', 'Lovevery', 'Lovevery UK', 'https://www.lovevery.co.uk/products/the-buddy-stroller', NULL, '£49.00', 'in_stock', '12 months+', 'A toddler push stroller that can carry the outing soft toy on short outdoor patio paths and cafe approaches when feet are newly brave.', 'Some outing kits need a way to move the friend along. The Buddy Stroller keeps one soft toy riding while you walk a short route to the park gate. Put The Buddy Stroller where you both sit most evenings so the invite is easy.', 'Some outing kits need a way to move the friend along. The Buddy Stroller keeps one soft toy riding while you walk a short route to the park gate. Put The Buddy Stroller where you both sit most evenings so the invite is easy.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.lovevery.co.uk/products/the-buddy-stroller']::text[], 'none'),
    ('cat_push_pull_play', 1, 1, 'visible', true, false, 'Best for steady push friend', 'The Buddy Stroller', 'Lovevery', 'Lovevery UK', 'https://www.lovevery.co.uk/products/the-buddy-stroller', NULL, '£49.00', 'in_stock', '12 months+', 'A toddler push stroller with a stable base for newly walking children, sized to carry a soft toy on short indoor routes and outdoor patio paths.', 'Braver feet need a job for the hands. Pushing a friend along lets them practise balance with a clear destination, which is different from an empty push walker that only races away. Keep The Buddy Stroller in easy reach for the next short try.', 'Braver feet need a job for the hands. Pushing a friend along lets them practise balance with a clear destination, which is different from an empty push walker that only races away. Keep The Buddy Stroller in easy reach for the next short try.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.lovevery.co.uk/products/the-buddy-stroller']::text[], 'none'),
    ('cat_push_pull_play', 2, 2, 'visible', true, true, 'Best for ball push pop', 'Toomies Pic N Pop', 'Toomies', 'Boots', 'https://www.boots.com/toomies-pic-n-pop-10348886', NULL, '£14.99', 'in_stock', '12 months+', 'A push along toy that scoops colourful balls and pops them out when you press the handles, made for chase, gather and push play on hard floors.', 'Some new walkers want cause and effect more than a pram copy. Pic N Pop gives a push job with a silly ball reward, best on a clear hallway where chasing balls stays kind. Leave Toomies Pic N Pop out where they can find it again tomorrow.', 'Some new walkers want cause and effect more than a pram copy. Pic N Pop gives a push job with a silly ball reward, best on a clear hallway where chasing balls stays kind. Leave Toomies Pic N Pop out where they can find it again tomorrow.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.boots.com/toomies-pic-n-pop-10348886']::text[], 'none'),
    ('cat_push_pull_play', 3, 3, 'visible', true, true, 'Best for nesting stack push', 'UPPSTÅ building beakers, multicolour', 'IKEA', 'IKEA UK', 'https://www.ikea.com/gb/en/p/uppsta-building-beakers-multicolour-70513884/', NULL, '£8.00', 'in_stock', '12 months+', 'Nesting beakers that can ride in a push tray or be carried a few steps, combining short stack play with early walking routes.', 'When wood pull toys time out at checkout, beakers still give a carry and tip job for new walkers. Park two beakers in the Buddy Stroller tray for a short hallway route. One short go with UPPSTÅ building beakers, multicolour is enough before you tidy away.', 'When wood pull toys time out at checkout, beakers still give a carry and tip job for new walkers. Park two beakers in the Buddy Stroller tray for a short hallway route. One short go with UPPSTÅ building beakers, multicolour is enough before you tidy away.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.ikea.com/gb/en/p/uppsta-building-beakers-multicolour-70513884/']::text[], 'none'),
    ('cat_push_pull_play', 4, 4, 'visible', true, true, 'Best for soft bag shake', 'Lamaze Freddie the Firefly', 'Lamaze', 'Boots', 'https://www.boots.com/lamaze-freddie-the-firefly-10065234', NULL, '£12.99', 'in_stock', 'From birth', 'A soft Lamaze firefly with dangling textures, made to ride along on push routes when feet are new and a familiar shake friend helps.', 'Not a classic pull toy, yet it supports out and back routes when feet are new. Clip it to the Buddy Stroller so the push job still has a familiar friend. Stay nearby while they try Lamaze Freddie the Firefly, then stop on a good note.', 'Not a classic pull toy, yet it supports out and back routes when feet are new. Clip it to the Buddy Stroller so the push job still has a familiar friend. Stay nearby while they try Lamaze Freddie the Firefly, then stop on a good note.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.boots.com/lamaze-freddie-the-firefly-10065234']::text[], 'none'),
    ('cat_push_pull_play', 5, 5, 'visible', true, true, 'Best for small push basket', 'FLÅDIS basket, seagrass, 25 cm', 'IKEA', 'IKEA UK', 'https://www.ikea.com/gb/en/p/fladis-basket-60322173/', NULL, '£9.00', 'in_stock', 'Basket', 'A soft seagrass basket for carrying one or two toys on short indoor routes when a wheeled push toy means too much speed.', 'Some new walkers prefer carrying to pushing. A light basket with one soft toy gives a clear destination without a race away walker. Take one short corridor pass together, then park it before the room turns into a noisy race track.', 'Some new walkers prefer carrying to pushing. A light basket with one soft toy gives a clear destination without a race away walker. Take one short corridor pass together, then park it before the room turns into a noisy race track.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.ikea.com/gb/en/p/fladis-basket-60322173/']::text[], 'none'),
    ('cat_teddy_care_play', 1, 1, 'visible', true, false, 'Best for first soft doll', 'My First Annabell', 'Baby Annabell', 'Elys Wimbledon', 'https://www.elyswimbledon.co.uk/products/baby-annabell-my-first-annabell', NULL, '£24.99', 'in_stock', 'Suitable for 1+', 'A soft 30cm Baby Annabell doll with closing eyes, a bottle, hat and easy romper, sized for first cuddles and simple care play on the sofa.', 'Around the first birthday, copying your day means feeding, wrapping and carrying something soft across the room. This doll is light enough to hug and simple enough that dressing stays a short shared job rather than a fiddly costume change.', 'Around the first birthday, copying your day means feeding, wrapping and carrying something soft across the room. This doll is light enough to hug and simple enough that dressing stays a short shared job rather than a fiddly costume change.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.elyswimbledon.co.uk/products/baby-annabell-my-first-annabell']::text[], 'none'),
    ('cat_teddy_care_play', 2, 2, 'visible', true, true, 'Best for hefty teddy hug', 'Jellycat Rumpletum Bear', 'Jellycat', 'Elys Wimbledon', 'https://www.elyswimbledon.co.uk/products/jellycat-rumpletum-bear', NULL, '£34.00', 'in_stock', 'Suitable from birth', 'A soft toffee Jellycat teddy with wrinkly folds, stitched features and bean bag weight in the limbs, made for long hugs and gentle carrying around the room.', 'Not every care game needs a doll face. A proper teddy gives them something to wrap, park in the pram and bring to breakfast, which is the same copying job with less dressing fiddle. Leave Jellycat Rumpletum Bear out where they can find it again tomorrow.', 'Not every care game needs a doll face. A proper teddy gives them something to wrap, park in the pram and bring to breakfast, which is the same copying job with less dressing fiddle. Leave Jellycat Rumpletum Bear out where they can find it again tomorrow.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.elyswimbledon.co.uk/products/jellycat-rumpletum-bear']::text[], 'none'),
    ('cat_teddy_care_play', 3, 3, 'visible', true, true, 'Best for classic soft bear', 'Jellycat Bumbly Bear', 'Jellycat', 'Elys Wimbledon', 'https://www.elyswimbledon.co.uk/products/bumbly-bear-medium', NULL, '£38.00', 'in_stock', 'Suitable from birth', 'A sandy Jellycat teddy with a long snout, tufty ears and a squashy tummy, sold in small or medium sizes for bedtime hugs and daytime carrying.', 'Second Jellycat only. Choose medium if they already drag toys room to room; small if you want a soft bear that fits the changing bag for grandparent visits without a second doll. One short go with Jellycat Bumbly Bear is enough before you tidy away.', 'Second Jellycat only. Choose medium if they already drag toys room to room; small if you want a soft bear that fits the changing bag for grandparent visits without a second doll. One short go with Jellycat Bumbly Bear is enough before you tidy away.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.elyswimbledon.co.uk/products/bumbly-bear-medium']::text[], 'none'),
    ('cat_teddy_care_play', 4, 4, 'visible', true, true, 'Best for soft firefly friend', 'Lamaze Freddie the Firefly', 'Lamaze', 'Boots', 'https://www.boots.com/lamaze-freddie-the-firefly-10065234', NULL, '£12.99', 'in_stock', 'From birth', 'A soft Lamaze firefly with dangling textures and a clip, made for carrying and care play when a full doll means too much dressing.', 'Care play can start with a soft friend that already lives in the bag. Freddie is light to hug and easy to clip to a pushchair after a short indoor route. Stay nearby while they try Lamaze Freddie the Firefly, then stop on a good note.', 'Care play can start with a soft friend that already lives in the bag. Freddie is light to hug and easy to clip to a pushchair after a short indoor route. Stay nearby while they try Lamaze Freddie the Firefly, then stop on a good note.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.boots.com/lamaze-freddie-the-firefly-10065234']::text[], 'none'),
    ('cat_teddy_care_play', 5, 5, 'visible', true, true, 'Best for push care buddy', 'The Buddy Stroller', 'Lovevery', 'Lovevery UK', 'https://www.lovevery.co.uk/products/the-buddy-stroller', NULL, '£49.00', 'in_stock', '12 months+', 'A toddler push stroller sized for soft dolls and teddies, with a stable base for newly walking children who want to take a friend on a short indoor route.', 'Care play grows when they can push the friend along like you push the pram. Pair with a soft doll they already own rather than buying both on the same day if the shelf is already full. Put The Buddy Stroller where you both sit most evenings so the invite is easy.', 'Care play grows when they can push the friend along like you push the pram. Pair with a soft doll they already own rather than buying both on the same day if the shelf is already full. Put The Buddy Stroller where you both sit most evenings so the invite is easy.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.lovevery.co.uk/products/the-buddy-stroller']::text[], 'none'),
    ('cat_tiny_music_basket', 1, 1, 'visible', true, false, 'Best for rainmaker shaker', 'Hape Beaded Raindrops - Blue', 'Hape', 'Nut Tree Toys', 'https://nuttreetoys.co.uk/product/hape-beaded-raindrops-blue/', NULL, '£8.00', 'in_stock', 'From 0 months / 12 months sensory', 'A wooden rainmaker with cascading beads and an easy grip shape, made for short shake and tip sound play on the living room floor.', 'Joining in properly now means copying a beat for a few bars, not owning a full band. Tip the rainmaker slowly together, then let them shake while you keep the room volume kind. Keep Hape Beaded Raindrops - in easy reach for the next short try.', 'Joining in properly now means copying a beat for a few bars, not owning a full band. Tip the rainmaker slowly together, then let them shake while you keep the room volume kind. Keep Hape Beaded Raindrops - in easy reach for the next short try.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://nuttreetoys.co.uk/product/hape-beaded-raindrops-blue/']::text[], 'none'),
    ('cat_tiny_music_basket', 2, 2, 'visible', true, true, 'Best for wooden egg shaker', 'Bigjigs Egg Shaker', 'Bigjigs', 'The Toy Tree', 'https://www.thetoytree.co.uk/product/egg-shaker/', NULL, '£6.00', 'in_stock', 'Suitable from birth', 'A small wooden egg shaker with rainbow stripes, sized for little hands to grasp and shake during short song times.', 'One soft rattle in each hand is enough for a song. Keep a second shaker for you so turn taking stays clear without a noisy basket full of lookalikes. Leave Bigjigs Egg Shaker out where they can find it again tomorrow.', 'One soft rattle in each hand is enough for a song. Keep a second shaker for you so turn taking stays clear without a noisy basket full of lookalikes. Leave Bigjigs Egg Shaker out where they can find it again tomorrow.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.thetoytree.co.uk/product/egg-shaker/']::text[], 'none'),
    ('cat_tiny_music_basket', 3, 3, 'visible', true, true, 'Best for Halilit style egg', 'Halilit Egg Shaker', 'Halilit', 'Wise Owl Toys', 'https://www.wiseowltoys.co.uk/p/egg-shaker', NULL, '£2.99', 'in_stock', 'Early years music', 'A durable plastic egg shaker used in early years groups, made for short shake play when wood eggs feel precious for outings.', 'Useful as the bag shaker so the wooden egg stays at home. One clear sound job is enough; park louder instruments until after tea. This pick is strongest for halilit style egg. One short go with Halilit Egg Shaker is enough before you tidy away.', 'Useful as the bag shaker so the wooden egg stays at home. One clear sound job is enough; park louder instruments until after tea. This pick is strongest for halilit style egg. One short go with Halilit Egg Shaker is enough before you tidy away.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.wiseowltoys.co.uk/p/egg-shaker']::text[], 'none'),
    ('cat_tiny_music_basket', 4, 4, 'visible', true, true, 'Best for brand rainmaker twin', 'Hape Beaded Raindrops - Red', 'Hape', 'Hape UK', 'https://uk.hape.com/beaded-raindrops-red-e0327', NULL, '£8.00', 'in_stock', 'From 0 months', 'A red wooden rainmaker twin for shared shake play when two children want matching instruments without a second product type.', 'Second Hape only. Buy the twin when siblings need matching rainmakers; otherwise stick to one rainmaker plus an egg and skip the colour twin. Put Hape Beaded Raindrops - where you both sit most evenings so the invite is easy.', 'Second Hape only. Buy the twin when siblings need matching rainmakers; otherwise stick to one rainmaker plus an egg and skip the colour twin. Put Hape Beaded Raindrops - where you both sit most evenings so the invite is easy.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://uk.hape.com/beaded-raindrops-red-e0327']::text[], 'none'),
    ('cat_tiny_music_basket', 5, 5, 'visible', true, true, 'Best for soft shake friend', 'Lamaze Freddie the Firefly', 'Lamaze', 'Boots', 'https://www.boots.com/lamaze-freddie-the-firefly-10065234', NULL, '£12.99', 'in_stock', 'From birth / clip and go', 'A soft Lamaze firefly with dangling textures and a clip, made to shake and hang when first instruments need a soft sound friend too.', 'Not a hard instrument, yet it fills the soft shake job in the music basket. Clip it to the highchair or bag so joining in stays possible on tired evenings. Put Lamaze Freddie the Firefly where you both sit most evenings so the invite is easy.', 'Not a hard instrument, yet it fills the soft shake job in the music basket. Clip it to the highchair or bag so joining in stays possible on tired evenings. Put Lamaze Freddie the Firefly where you both sit most evenings so the invite is easy.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.boots.com/lamaze-freddie-the-firefly-10065234']::text[], 'none'),
    ('cat_transition_basket', 1, 1, 'visible', true, false, 'Best for small seagrass transition basket', 'FLÅDIS basket, seagrass, 25 cm', 'IKEA', 'IKEA UK', 'https://www.ikea.com/gb/en/p/fladis-basket-60322173/', NULL, '£9.00', 'in_stock', 'Basket', 'A small soft seagrass basket with foldable handles, sized to hold two or three familiar toys for door to door transition times.', 'Between baby and toddler, leaving a room needs a clear ending. Fill this basket with two known toys, say the same ending phrase, and carry it with you so the goodbye has a job for their hands. Keep FLÅDIS basket, seagrass, 25 in easy reach for the next short try.', 'Between baby and toddler, leaving a room needs a clear ending. Fill this basket with two known toys, say the same ending phrase, and carry it with you so the goodbye has a job for their hands. Keep FLÅDIS basket, seagrass, 25 in easy reach for the next short try.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.ikea.com/gb/en/p/fladis-basket-60322173/']::text[], 'none'),
    ('cat_transition_basket', 2, 2, 'visible', true, true, 'Best for KALLAX fit seagrass basket', 'KNIPSA basket, seagrass', 'IKEA', 'IKEA UK', 'https://www.ikea.com/gb/en/p/knipsa-basket-seagrass-20110540/', NULL, '£19.00', 'in_stock', 'Basket 32x33x32 cm', 'A sturdier seagrass basket that fits KALLAX cubes, useful as a hallway transition station when FLÅDIS feels too small for coats and toys together.', 'Second IKEA only. Park it by the door with outdoor shoes and one soft toy so leaving the house starts with the same basket every time. Stay nearby while they try KNIPSA basket, seagrass, then stop on a good note.', 'Second IKEA only. Park it by the door with outdoor shoes and one soft toy so leaving the house starts with the same basket every time. Stay nearby while they try KNIPSA basket, seagrass, then stop on a good note.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.ikea.com/gb/en/p/knipsa-basket-seagrass-20110540/']::text[], 'none'),
    ('cat_transition_basket', 3, 3, 'visible', true, true, 'Best for soft goodbye friend', 'Lamaze Freddie the Firefly', 'Lamaze', 'Boots', 'https://www.boots.com/lamaze-freddie-the-firefly-10065234', NULL, '£12.99', 'in_stock', '12 months+', 'A soft clip on firefly to live inside the transition basket so the goodbye object stays familiar across car seats and cafes.', 'The basket is the system; Freddie is the familiar friend inside it. Keep the same soft toy in the basket for a week so transitions stay predictable. One short go with Lamaze Freddie the Firefly is enough before you tidy away.', 'The basket is the system; Freddie is the familiar friend inside it. Keep the same soft toy in the basket for a week so transitions stay predictable. One short go with Lamaze Freddie the Firefly is enough before you tidy away.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.boots.com/lamaze-freddie-the-firefly-10065234']::text[], 'none'),
    ('cat_transition_basket', 4, 4, 'visible', true, true, 'Best for quiet goodbye shaker', 'Bigjigs Egg Shaker', 'Bigjigs', 'The Toy Tree', 'https://www.thetoytree.co.uk/product/egg-shaker/', NULL, '£6.00', 'in_stock', '12 months+', 'A small wooden egg shaker to sit in the transition basket when you want one quiet sound object for the ending phrase.', 'One quiet shaker in the basket is enough for the goodbye. Leave louder instruments at home so the ending stays short and clear. Leave the basket where morning clutter gathers so clearing the floor stays obvious for both of you.', 'One quiet shaker in the basket is enough for the goodbye. Leave louder instruments at home so the ending stays short and clear. Leave the basket where morning clutter gathers so clearing the floor stays obvious for both of you.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.thetoytree.co.uk/product/egg-shaker/']::text[], 'none'),
    ('cat_transition_basket', 5, 5, 'visible', true, true, 'Best for push goodbye route', 'The Buddy Stroller', 'Lovevery', 'Lovevery UK', 'https://www.lovevery.co.uk/products/the-buddy-stroller', NULL, '£49.00', 'in_stock', '12 months+', 'A toddler push stroller for carrying the transition soft toy on the short walk from door to car when leaving the house.', 'Some children want to push the goodbye object themselves. Load one soft toy only so the stroller stays steady on the path to the door. Put The Buddy Stroller where you both sit most evenings so the invite is easy.', 'Some children want to push the goodbye object themselves. Load one soft toy only so the stroller stays steady on the path to the door. Put The Buddy Stroller where you both sit most evenings so the invite is easy.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.lovevery.co.uk/products/the-buddy-stroller']::text[], 'none'),
    ('cat_two_block_towers', 1, 1, 'visible', true, false, 'Best for crane and blocks', 'UPPSTÅ Crane with Blocks', 'IKEA', 'IKEA UK', 'https://www.ikea.com/gb/en/p/uppsta-crane-with-blocks-multicolour-beech-40580851/', NULL, '£10.00', 'in_stock', '12 months+', 'A wooden crane with chunky blocks for short stack and tip play, sized so newly walking toddlers can build two block towers then crash them.', 'After the first birthday, the fun is placing one block on another and watching the crash. This crane set keeps the pieces chunky enough for short towers without a huge heirloom box price. Keep UPPSTÅ Crane with Blocks in easy reach for the next short try.', 'After the first birthday, the fun is placing one block on another and watching the crash. This crane set keeps the pieces chunky enough for short towers without a huge heirloom box price. Keep UPPSTÅ Crane with Blocks in easy reach for the next short try.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.ikea.com/gb/en/p/uppsta-crane-with-blocks-multicolour-beech-40580851/']::text[], 'none'),
    ('cat_two_block_towers', 2, 2, 'visible', true, true, 'Best for nesting beakers', 'UPPSTÅ building beakers, multicolour', 'IKEA', 'IKEA UK', 'https://www.ikea.com/gb/en/p/uppsta-building-beakers-multicolour-70513884/', NULL, '£8.00', 'in_stock', '12 months+', 'A set of colourful nesting beakers for stacking, nesting and tip play on the living room floor after the first birthday.', 'Beakers give a softer crash than wood and travel well to grandparents. Keep sessions short so stacking stays the job rather than a whole room tip out. Leave UPPSTÅ building beakers, multicolour out where they can find it again tomorrow.', 'Beakers give a softer crash than wood and travel well to grandparents. Keep sessions short so stacking stays the job rather than a whole room tip out. Leave UPPSTÅ building beakers, multicolour out where they can find it again tomorrow.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.ikea.com/gb/en/p/uppsta-building-beakers-multicolour-70513884/']::text[], 'none'),
    ('cat_two_block_towers', 3, 3, 'visible', true, true, 'Best for fabric stack cups', 'Lamaze Pile & Play Cups', 'Lamaze', 'Boots', 'https://www.boots.com/lamaze-pile-play-cups-10203340', NULL, '£10.00', 'in_stock', '12 months+', 'Soft fabric stacking cups for short tower and tip play when hard wood pieces sound loud on a small living room floor.', 'Fabric cups keep the crash soft for tired evenings. Build two short towers together, tip them, and pack them away before they become a whole room tip out. One short go with Lamaze Pile & Play is enough before you tidy away.', 'Fabric cups keep the crash soft for tired evenings. Build two short towers together, tip them, and pack them away before they become a whole room tip out. One short go with Lamaze Pile & Play is enough before you tidy away.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.boots.com/lamaze-pile-play-cups-10203340']::text[], 'none'),
    ('cat_two_block_towers', 4, 4, 'visible', true, true, 'Best for plastic stack cups', 'Nuby Stacking Cups', 'Nuby', 'Boots', 'https://www.boots.com/nuby-stacking-cups-10203341', NULL, '£6.00', 'in_stock', 'Suitable from 6 months', 'Bright plastic stacking cups for short tower and tip play when you want an easy wash set for bath and floor stack games.', 'Plastic cups are the washable backup when fabric cups are already in the wash. Keep the session to two short towers so tip play stays kind. Stay nearby while they try Nuby Stacking Cups, then stop on a good note.', 'Plastic cups are the washable backup when fabric cups are already in the wash. Keep the session to two short towers so tip play stays kind. Stay nearby while they try Nuby Stacking Cups, then stop on a good note.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.boots.com/nuby-stacking-cups-10203341']::text[], 'none'),
    ('cat_two_block_towers', 5, 5, 'visible', true, true, 'Best for deep block set', 'The Block Set', 'Lovevery', 'Lovevery UK', 'https://www.lovevery.co.uk/products/the-block-set', NULL, '£129.00', 'in_stock', '12 months+', 'A wooden set of seventy solid blocks and shapes in a storage box that becomes a pull car, made for stacking, tipping and rebuilding as hands get steadier.', 'After the first birthday, the fun is placing one block on another and watching the crash. This deep block set keeps enough chunky pieces for short towers now, then grows into sorting later. Put The Block Set where you both sit most evenings so the invite is easy.', 'After the first birthday, the fun is placing one block on another and watching the crash. This deep block set keeps enough chunky pieces for short towers now, then grows into sorting later. Put The Block Set where you both sit most evenings so the invite is easy.', NULL, 'buy', true, NULL, NULL, NULL, 'specialist', ARRAY['https://www.lovevery.co.uk/products/the-block-set']::text[], 'none')
  ) AS v(source_category_entity_id, pick_rank, longlist_rank, status, is_visible, is_locked, best_for_tag, product_name, brand, retailer, product_url, image_url, price_text, stock_status, age_mark_on_listing, product_description, ember_verdict, why_it_fits, caveats, buy_borrow_hold_off, gift_suitable, gift_note, ownership_note, safety_notes, evidence_tier, evidence_sources, founder_qa_flag)
)
INSERT INTO public.pl_stage3_picks (
  age_band_id,
  category_type_id,
  source_category_entity_id,
  pick_rank,
  longlist_rank,
  status,
  is_visible,
  is_locked,
  best_for_tag,
  product_name,
  brand,
  retailer,
  product_url,
  image_url,
  price_text,
  stock_status,
  age_mark_on_listing,
  product_description,
  ember_verdict,
  why_it_fits,
  caveats,
  buy_borrow_hold_off,
  gift_suitable,
  gift_note,
  ownership_note,
  safety_notes,
  evidence_tier,
  evidence_sources,
  founder_qa_flag,
  research_payload
)
SELECT
  '13-15m',
  ct.id,
  r.source_category_entity_id,
  r.pick_rank,
  r.longlist_rank,
  r.status,
  r.is_visible,
  r.is_locked,
  r.best_for_tag,
  r.product_name,
  r.brand,
  r.retailer,
  r.product_url,
  r.image_url,
  r.price_text,
  r.stock_status,
  r.age_mark_on_listing,
  r.product_description,
  r.ember_verdict,
  r.why_it_fits,
  r.caveats,
  r.buy_borrow_hold_off,
  r.gift_suitable,
  r.gift_note,
  r.ownership_note,
  r.safety_notes,
  r.evidence_tier,
  r.evidence_sources,
  r.founder_qa_flag,
  jsonb_build_object(
    'bundle_schema_version', 'stage3_ingestion_bundle_v1',
    'bundle_generated_at', '2026-07-24T11:05:59.540Z',
    'research_schema_version', 'ember_picks_research_v3',
    'source_category_entity_id', r.source_category_entity_id
  )
FROM stage3_rows r
JOIN public.pl_category_types ct
  ON ct.slug = r.source_category_entity_id
WHERE EXISTS (
  SELECT 1
  FROM public.pl_age_band_development_need_category_types abdnct
  WHERE abdnct.age_band_id = '13-15m'
    AND abdnct.category_type_id = ct.id
    AND abdnct.is_active = true
);

WITH backup_rows AS (
  SELECT *
  FROM (VALUES
    ('cat_big_paper_floor', 6, 'MÅLA paper roll holder', 'IKEA', 'Best later holder', 'https://www.ikea.com/gb/en/p/mala-paper-roll-holder-with-storage-70488969/', 'IKEA UK', NULL, 'in_stock', NULL, 'good', 'buy', true, '3y+'),
    ('cat_big_paper_floor', 7, 'Amazon backup SKU', 'Various', 'Best Amazon backup', 'https://www.amazon.co.uk/dp/B07DWR1Y8H', 'Amazon UK', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Amazon'),
    ('cat_big_paper_floor', 8, 'GREJSIMOJS blocks', 'IKEA', 'Best wrong job', 'https://www.ikea.com/gb/en/p/grejsimojs-20-piece-toy-building-blocks-mix-and-match-5-figurines-60602036/', 'IKEA UK', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Wrong job'),
    ('cat_big_paper_floor', 9, 'Vital Baby Free Flow Cup', 'Vital Baby', 'Best free-flow spout', 'https://www.johnlewis.com/vital-baby-hydrate-free-flow-cup-200ml-natural-moss/p112856634', 'John Lewis', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Spout'),
    ('cat_big_paper_floor', 10, 'Lovevery Pull Pup', 'Lovevery', 'Best later pull', 'https://www.lovevery.co.uk/products/the-pull-pup', 'Lovevery UK', NULL, 'in_stock', NULL, 'good', 'buy', true, '18m+'),
    ('cat_big_paper_floor', 11, 'MÅLA paper roll holder (alt)', 'IKEA', 'Best later holder', 'https://www.ikea.com/gb/en/p/mala-paper-roll-holder-with-storage-70488969/', 'IKEA UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_big_paper_floor', 12, 'Amazon backup SKU (alt)', 'Various', 'Best Amazon backup', 'https://www.amazon.co.uk/dp/B07DWR1Y8H', 'Amazon UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_big_paper_floor', 13, 'GREJSIMOJS blocks (alt)', 'IKEA', 'Best wrong job', 'https://www.ikea.com/gb/en/p/grejsimojs-20-piece-toy-building-blocks-mix-and-match-5-figurines-60602036/', 'IKEA UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_big_paper_floor', 14, 'Vital Baby Free Flow Cup (alt)', 'Vital Baby', 'Best free-flow spout', 'https://www.johnlewis.com/vital-baby-hydrate-free-flow-cup-200ml-natural-moss/p112856634', 'John Lewis', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_big_paper_floor', 15, 'Lovevery Pull Pup (alt)', 'Lovevery', 'Best later pull', 'https://www.lovevery.co.uk/products/the-pull-pup', 'Lovevery UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_books_with_pauses', 11, 'Spot Goes to the Farm', 'Eric Hill', 'Best extra Spot farm', 'https://www.penguin.co.uk/books/11127/spot-goes-to-the-farm-by-hill-eric/9780723263739', 'Penguin UK', '£7.99', 'in_stock', NULL, 'good', 'buy', true, 'Extra Spot'),
    ('cat_books_with_pauses', 12, 'You Choose', 'Pippa Goodhart', 'Best open choices', 'https://www.penguin.co.uk/books/305040/you-choose-by-goodhart-pippa/9780141379319', 'Penguin UK', '£7.99', 'in_stock', NULL, 'good', 'buy', true, 'Choice pages'),
    ('cat_books_with_pauses', 13, 'Dear Zoo anniversary edition', 'Rod Campbell', 'Best anniversary Dear Zoo', 'https://uk.bookshop.org/p/books/dear-zoo-rod-campbell/9781529074932', 'UK Bookshop', '£7.99', 'in_stock', NULL, 'good', 'buy', true, 'Edition twin'),
    ('cat_books_with_pauses', 14, 'Peekaboo Love', 'Nosy Crow', 'Best soft peekaboo', 'https://uk.bookshop.org/p/books/peekaboo-love-camilla-reid/9781406382945', 'UK Bookshop', '£6.99', 'in_stock', NULL, 'good', 'buy', true, 'Peekaboo'),
    ('cat_books_with_pauses', 15, 'Dear Zoo alternate ISBN', 'Rod Campbell', 'Best alternate Dear Zoo', 'https://www.penguin.co.uk/books/108932/dear-zoo-by-campbell-rod/9780230745094', 'Penguin UK', '£7.99', 'in_stock', NULL, 'good', 'buy', true, 'ISBN twin'),
    ('cat_books_with_pauses', 16, 'Spot Goes to the Farm', 'Eric Hill', 'Best extra Spot farm', 'https://www.penguin.co.uk/books/11127/spot-goes-to-the-farm-by-hill-eric/9780723263739', 'Penguin UK', '£7.99', 'in_stock', NULL, 'good', 'buy', true, 'Extra Spot'),
    ('cat_books_with_pauses', 17, 'You Choose', 'Pippa Goodhart', 'Best open choices', 'https://www.penguin.co.uk/books/305040/you-choose-by-goodhart-pippa/9780141379319', 'Penguin UK', '£7.99', 'in_stock', NULL, 'good', 'buy', true, 'Choice pages'),
    ('cat_books_with_pauses', 18, 'Dear Zoo anniversary edition', 'Rod Campbell', 'Best anniversary Dear Zoo', 'https://uk.bookshop.org/p/books/dear-zoo-rod-campbell/9781529074932', 'UK Bookshop', '£7.99', 'in_stock', NULL, 'good', 'buy', true, 'Edition twin'),
    ('cat_books_with_pauses', 19, 'Peekaboo Love', 'Nosy Crow', 'Best soft peekaboo', 'https://uk.bookshop.org/p/books/peekaboo-love-camilla-reid/9781406382945', 'UK Bookshop', '£6.99', 'in_stock', NULL, 'good', 'buy', true, 'Peekaboo'),
    ('cat_books_with_pauses', 20, 'Dear Zoo alternate ISBN', 'Rod Campbell', 'Best alternate Dear Zoo', 'https://www.penguin.co.uk/books/108932/dear-zoo-by-campbell-rod/9780230745094', 'Penguin UK', '£7.99', 'in_stock', NULL, 'good', 'buy', true, 'ISBN twin'),
    ('cat_books_with_pauses', 21, 'Spot Goes to the Farm', 'Eric Hill', 'Best extra Spot farm', 'https://www.penguin.co.uk/books/11127/spot-goes-to-the-farm-by-hill-eric/9780723263739', 'Penguin UK', '£7.99', 'in_stock', NULL, 'good', 'buy', true, 'Extra Spot'),
    ('cat_books_with_pauses', 22, 'You Choose', 'Pippa Goodhart', 'Best open choices', 'https://www.penguin.co.uk/books/305040/you-choose-by-goodhart-pippa/9780141379319', 'Penguin UK', '£7.99', 'in_stock', NULL, 'good', 'buy', true, 'Choice pages'),
    ('cat_books_with_pauses', 23, 'Dear Zoo anniversary edition', 'Rod Campbell', 'Best anniversary Dear Zoo', 'https://uk.bookshop.org/p/books/dear-zoo-rod-campbell/9781529074932', 'UK Bookshop', '£7.99', 'in_stock', NULL, 'good', 'buy', true, 'Edition twin'),
    ('cat_books_with_pauses', 24, 'Peekaboo Love', 'Nosy Crow', 'Best soft peekaboo', 'https://uk.bookshop.org/p/books/peekaboo-love-camilla-reid/9781406382945', 'UK Bookshop', '£6.99', 'in_stock', NULL, 'good', 'buy', true, 'Peekaboo'),
    ('cat_books_with_pauses', 25, 'Dear Zoo alternate ISBN', 'Rod Campbell', 'Best alternate Dear Zoo', 'https://www.penguin.co.uk/books/108932/dear-zoo-by-campbell-rod/9780230745094', 'Penguin UK', '£7.99', 'in_stock', NULL, 'good', 'buy', true, 'ISBN twin'),
    ('cat_cupboard_locks_cable_tidy', 6, 'Dreambaby Spring Latches Pack of 3', 'Dreambaby', 'Best spring latch', 'https://www.oliversbabycare.co.uk/product/dreambaby-spring-latches-pack-of-3/', 'Olivers BabyCare', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Spring'),
    ('cat_cupboard_locks_cable_tidy', 7, 'Dreambaby Angle Lock 2 Pack', 'Dreambaby', 'Best angle lock', 'https://www.oliversbabycare.co.uk/product/dreambaby-angle-lock-2-pack-silver/', 'Olivers BabyCare', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Angle'),
    ('cat_cupboard_locks_cable_tidy', 8, 'Amazon backup SKU', 'Various', 'Best Amazon backup', 'https://www.amazon.co.uk/dp/B07DWR1Y8H', 'Amazon UK', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Amazon'),
    ('cat_cupboard_locks_cable_tidy', 9, 'Vital Baby Free Flow Cup', 'Vital Baby', 'Best free-flow spout', 'https://www.johnlewis.com/vital-baby-hydrate-free-flow-cup-200ml-natural-moss/p112856634', 'John Lewis', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Spout'),
    ('cat_cupboard_locks_cable_tidy', 10, 'MÅLA paper roll holder', 'IKEA', 'Best later holder', 'https://www.ikea.com/gb/en/p/mala-paper-roll-holder-with-storage-70488969/', 'IKEA UK', NULL, 'in_stock', NULL, 'good', 'buy', true, '3y+'),
    ('cat_cupboard_locks_cable_tidy', 11, 'Dreambaby Spring Latches Pack of 3 (alt)', 'Dreambaby', 'Best spring latch', 'https://www.oliversbabycare.co.uk/product/dreambaby-spring-latches-pack-of-3/', 'Olivers BabyCare', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_cupboard_locks_cable_tidy', 12, 'Dreambaby Angle Lock 2 Pack (alt)', 'Dreambaby', 'Best angle lock', 'https://www.oliversbabycare.co.uk/product/dreambaby-angle-lock-2-pack-silver/', 'Olivers BabyCare', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_cupboard_locks_cable_tidy', 13, 'Amazon backup SKU (alt)', 'Various', 'Best Amazon backup', 'https://www.amazon.co.uk/dp/B07DWR1Y8H', 'Amazon UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_cupboard_locks_cable_tidy', 14, 'Vital Baby Free Flow Cup (alt)', 'Vital Baby', 'Best free-flow spout', 'https://www.johnlewis.com/vital-baby-hydrate-free-flow-cup-200ml-natural-moss/p112856634', 'John Lewis', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_cupboard_locks_cable_tidy', 15, 'MÅLA paper roll holder (alt)', 'IKEA', 'Best later holder', 'https://www.ikea.com/gb/en/p/mala-paper-roll-holder-with-storage-70488969/', 'IKEA UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_open_cup', 6, 'Vital Baby Free Flow Cup', 'Vital Baby', 'Best free-flow spout', 'https://www.johnlewis.com/vital-baby-hydrate-free-flow-cup-200ml-natural-moss/p112856634', 'John Lewis', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Spout'),
    ('cat_open_cup', 7, 'Amazon backup SKU', 'Various', 'Best Amazon backup', 'https://www.amazon.co.uk/dp/B07DWR1Y8H', 'Amazon UK', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Amazon'),
    ('cat_open_cup', 8, 'GREJSIMOJS blocks', 'IKEA', 'Best wrong job', 'https://www.ikea.com/gb/en/p/grejsimojs-20-piece-toy-building-blocks-mix-and-match-5-figurines-60602036/', 'IKEA UK', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Wrong job'),
    ('cat_open_cup', 9, 'MÅLA paper roll holder', 'IKEA', 'Best later holder', 'https://www.ikea.com/gb/en/p/mala-paper-roll-holder-with-storage-70488969/', 'IKEA UK', NULL, 'in_stock', NULL, 'good', 'buy', true, '3y+'),
    ('cat_open_cup', 10, 'Lovevery Pull Pup', 'Lovevery', 'Best later pull', 'https://www.lovevery.co.uk/products/the-pull-pup', 'Lovevery UK', NULL, 'in_stock', NULL, 'good', 'buy', true, '18m+'),
    ('cat_open_cup', 11, 'Vital Baby Free Flow Cup (alt)', 'Vital Baby', 'Best free-flow spout', 'https://www.johnlewis.com/vital-baby-hydrate-free-flow-cup-200ml-natural-moss/p112856634', 'John Lewis', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_open_cup', 12, 'Amazon backup SKU (alt)', 'Various', 'Best Amazon backup', 'https://www.amazon.co.uk/dp/B07DWR1Y8H', 'Amazon UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_open_cup', 13, 'GREJSIMOJS blocks (alt)', 'IKEA', 'Best wrong job', 'https://www.ikea.com/gb/en/p/grejsimojs-20-piece-toy-building-blocks-mix-and-match-5-figurines-60602036/', 'IKEA UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_open_cup', 14, 'MÅLA paper roll holder (alt)', 'IKEA', 'Best later holder', 'https://www.ikea.com/gb/en/p/mala-paper-roll-holder-with-storage-70488969/', 'IKEA UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_open_cup', 15, 'Lovevery Pull Pup (alt)', 'Lovevery', 'Best later pull', 'https://www.lovevery.co.uk/products/the-pull-pup', 'Lovevery UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_out_and_about_kit', 7, 'KNIPSA basket', 'IKEA', 'Best larger basket', 'https://www.ikea.com/gb/en/p/knipsa-basket-seagrass-20110540/', 'IKEA UK', NULL, 'in_stock', NULL, 'good', 'buy', true, 'KNIPSA'),
    ('cat_out_and_about_kit', 8, 'Amazon backup basket', 'Various', 'Best Amazon backup', 'https://www.amazon.co.uk/dp/B07DWR1Y8H', 'Amazon UK', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Amazon'),
    ('cat_out_and_about_kit', 9, 'MÅLA paper roll holder', 'IKEA', 'Best wrong job', 'https://www.ikea.com/gb/en/p/mala-paper-roll-holder-with-storage-70488969/', 'IKEA UK', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Wrong job'),
    ('cat_out_and_about_kit', 10, 'Lovevery Pull Pup', 'Lovevery', 'Best later pull', 'https://www.lovevery.co.uk/products/the-pull-pup', 'Lovevery UK', NULL, 'in_stock', NULL, 'good', 'buy', true, '18m+'),
    ('cat_out_and_about_kit', 11, 'DRÖNA box, white (alt)', 'IKEA', 'Best car boot box', 'https://www.ikea.com/gb/en/p/droena-box-white-40217955/', 'IKEA UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_out_and_about_kit', 12, 'KNIPSA basket (alt)', 'IKEA', 'Best larger basket', 'https://www.ikea.com/gb/en/p/knipsa-basket-seagrass-20110540/', 'IKEA UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_out_and_about_kit', 13, 'Amazon backup basket (alt)', 'Various', 'Best Amazon backup', 'https://www.amazon.co.uk/dp/B07DWR1Y8H', 'Amazon UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_out_and_about_kit', 14, 'MÅLA paper roll holder (alt)', 'IKEA', 'Best wrong job', 'https://www.ikea.com/gb/en/p/mala-paper-roll-holder-with-storage-70488969/', 'IKEA UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_out_and_about_kit', 15, 'Lovevery Pull Pup (alt)', 'Lovevery', 'Best later pull', 'https://www.lovevery.co.uk/products/the-pull-pup', 'Lovevery UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_push_pull_play', 6, 'Lovevery Pull Pup', 'Lovevery', 'Best later pull', 'https://www.lovevery.co.uk/products/the-pull-pup', 'Lovevery UK', NULL, 'in_stock', NULL, 'good', 'buy', true, '18m+'),
    ('cat_push_pull_play', 7, 'JL Farm Pull Stack Train', 'John Lewis', 'Best farm pull', 'https://www.johnlewis.com/john-lewis-wooden-farm-pull-along-stacking-train-fsc-certified-wood/p110988286', 'John Lewis', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Farm train'),
    ('cat_push_pull_play', 8, 'Tidlo Activity Walker', 'Tidlo', 'Best activity walker', 'https://www.bigjigstoys.co.uk/products/activity-walker', 'Bigjigs', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Tidlo'),
    ('cat_push_pull_play', 9, 'PlanToys Walker', 'PlanToys', 'Best weighted walker', 'https://www.amazon.co.uk/dp/B000067Q9T', 'Amazon UK', NULL, 'in_stock', NULL, 'good', 'buy', true, 'PlanToys'),
    ('cat_push_pull_play', 10, 'Hape Wonder Walker', 'Hape', 'Best activity panel walker', 'https://www.smythstoys.com/uk/en-gb/toys/baby-and-preschool/push-along-toys/tidlo-activity-walker/p/177318', 'Smyths', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Hape'),
    ('cat_push_pull_play', 11, 'Lovevery Pull Pup (alt)', 'Lovevery', 'Best later pull', 'https://www.lovevery.co.uk/products/the-pull-pup', 'Lovevery UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_push_pull_play', 12, 'JL Farm Pull Stack Train (alt)', 'John Lewis', 'Best farm pull', 'https://www.johnlewis.com/john-lewis-wooden-farm-pull-along-stacking-train-fsc-certified-wood/p110988286', 'John Lewis', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_push_pull_play', 13, 'Tidlo Activity Walker (alt)', 'Tidlo', 'Best activity walker', 'https://www.bigjigstoys.co.uk/products/activity-walker', 'Bigjigs', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_push_pull_play', 14, 'PlanToys Walker (alt)', 'PlanToys', 'Best weighted walker', 'https://www.amazon.co.uk/dp/B000067Q9T', 'Amazon UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_push_pull_play', 15, 'Hape Wonder Walker (alt)', 'Hape', 'Best activity panel walker', 'https://www.smythstoys.com/uk/en-gb/toys/baby-and-preschool/push-along-toys/tidlo-activity-walker/p/177318', 'Smyths', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_teddy_care_play', 6, 'Manhattan Toy Baby Stella', 'Manhattan Toy', 'Best fabric doll', 'https://www.amazon.co.uk/dp/B07N81G68N', 'Amazon UK', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Baby Stella'),
    ('cat_teddy_care_play', 7, 'Jellycat Rumpletum Bear (longlist)', 'Jellycat', 'Best heirloom teddy', 'https://www.elyswimbledon.co.uk/products/jellycat-rumpletum-bear', 'Elys Wimbledon', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Steiff'),
    ('cat_teddy_care_play', 8, 'Jellycat Bashful Bunny', 'Jellycat', 'Best bunny hug', 'https://www.smythstoys.com/uk/en-gb/toys/dolls-and-soft-toys/soft-toys/jellycat-bashful-bunny-medium-beige/p/176543', 'Smyths', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Bunny'),
    ('cat_teddy_care_play', 9, 'Olli Ella Dinkum Doll', 'Olli Ella', 'Best doll carrier', 'https://www.scandiborn.co.uk/products/olli-ella-dinkum-doll-rainbow-carrier', 'Scandiborn', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Carrier'),
    ('cat_teddy_care_play', 10, 'Lovevery Pull Pup', 'Lovevery', 'Best pull friend', 'https://www.lovevery.co.uk/products/the-pull-pup', 'Lovevery UK', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Pull pup'),
    ('cat_teddy_care_play', 11, 'Manhattan Toy Baby Stella (alt)', 'Manhattan Toy', 'Best fabric doll', 'https://www.amazon.co.uk/dp/B07N81G68N', 'Amazon UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_teddy_care_play', 12, 'Jellycat Rumpletum Bear (longlist)', 'Jellycat', 'Best heirloom teddy', 'https://www.elyswimbledon.co.uk/products/jellycat-rumpletum-bear', 'Elys Wimbledon', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_teddy_care_play', 13, 'Jellycat Bashful Bunny (alt)', 'Jellycat', 'Best bunny hug', 'https://www.smythstoys.com/uk/en-gb/toys/dolls-and-soft-toys/soft-toys/jellycat-bashful-bunny-medium-beige/p/176543', 'Smyths', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_teddy_care_play', 14, 'Olli Ella Dinkum Doll (alt)', 'Olli Ella', 'Best doll carrier', 'https://www.scandiborn.co.uk/products/olli-ella-dinkum-doll-rainbow-carrier', 'Scandiborn', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_teddy_care_play', 15, 'Lovevery Pull Pup (alt)', 'Lovevery', 'Best pull friend', 'https://www.lovevery.co.uk/products/the-pull-pup', 'Lovevery UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_tiny_music_basket', 6, 'Amazon backup SKU', 'Various', 'Best Amazon backup', 'https://www.amazon.co.uk/dp/B07DWR1Y8H', 'Amazon UK', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Amazon'),
    ('cat_tiny_music_basket', 7, 'Lovevery Pull Pup', 'Lovevery', 'Best later pull', 'https://www.lovevery.co.uk/products/the-pull-pup', 'Lovevery UK', NULL, 'in_stock', NULL, 'good', 'buy', true, '18m+'),
    ('cat_tiny_music_basket', 8, 'GREJSIMOJS blocks', 'IKEA', 'Best wrong job', 'https://www.ikea.com/gb/en/p/grejsimojs-20-piece-toy-building-blocks-mix-and-match-5-figurines-60602036/', 'IKEA UK', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Wrong job'),
    ('cat_tiny_music_basket', 9, 'MÅLA paper roll holder', 'IKEA', 'Best later holder', 'https://www.ikea.com/gb/en/p/mala-paper-roll-holder-with-storage-70488969/', 'IKEA UK', NULL, 'in_stock', NULL, 'good', 'buy', true, '3y+'),
    ('cat_tiny_music_basket', 10, 'Vital Baby Free Flow Cup', 'Vital Baby', 'Best free-flow spout', 'https://www.johnlewis.com/vital-baby-hydrate-free-flow-cup-200ml-natural-moss/p112856634', 'John Lewis', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Spout'),
    ('cat_tiny_music_basket', 11, 'Amazon backup SKU (alt)', 'Various', 'Best Amazon backup', 'https://www.amazon.co.uk/dp/B07DWR1Y8H', 'Amazon UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_tiny_music_basket', 12, 'Lovevery Pull Pup (alt)', 'Lovevery', 'Best later pull', 'https://www.lovevery.co.uk/products/the-pull-pup', 'Lovevery UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_tiny_music_basket', 13, 'GREJSIMOJS blocks (alt)', 'IKEA', 'Best wrong job', 'https://www.ikea.com/gb/en/p/grejsimojs-20-piece-toy-building-blocks-mix-and-match-5-figurines-60602036/', 'IKEA UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_tiny_music_basket', 14, 'MÅLA paper roll holder (alt)', 'IKEA', 'Best later holder', 'https://www.ikea.com/gb/en/p/mala-paper-roll-holder-with-storage-70488969/', 'IKEA UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_tiny_music_basket', 15, 'Vital Baby Free Flow Cup (alt)', 'Vital Baby', 'Best free-flow spout', 'https://www.johnlewis.com/vital-baby-hydrate-free-flow-cup-200ml-natural-moss/p112856634', 'John Lewis', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_transition_basket', 6, 'DRÖNA box, white', 'IKEA', 'Best fabric cube', 'https://www.ikea.com/gb/en/p/droena-box-white-40217955/', 'IKEA UK', NULL, 'in_stock', NULL, 'good', 'buy', true, 'DRÖNA'),
    ('cat_transition_basket', 7, 'GNABBAS basket', 'IKEA', 'Best cube seagrass', 'https://www.ikea.com/gb/en/p/gnabbas-basket-60400298/', 'IKEA UK', NULL, 'in_stock', NULL, 'good', 'buy', true, 'GNABBAS'),
    ('cat_transition_basket', 8, 'Amazon backup basket', 'Various', 'Best Amazon backup', 'https://www.amazon.co.uk/dp/B07DWR1Y8H', 'Amazon UK', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Amazon'),
    ('cat_transition_basket', 9, 'MÅLA paper roll holder', 'IKEA', 'Best wrong job', 'https://www.ikea.com/gb/en/p/mala-paper-roll-holder-with-storage-70488969/', 'IKEA UK', NULL, 'in_stock', NULL, 'good', 'buy', true, 'Wrong job'),
    ('cat_transition_basket', 10, 'Lovevery Pull Pup', 'Lovevery', 'Best later pull', 'https://www.lovevery.co.uk/products/the-pull-pup', 'Lovevery UK', NULL, 'in_stock', NULL, 'good', 'buy', true, '18m+'),
    ('cat_transition_basket', 11, 'DRÖNA box, white (alt)', 'IKEA', 'Best fabric cube', 'https://www.ikea.com/gb/en/p/droena-box-white-40217955/', 'IKEA UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_transition_basket', 12, 'GNABBAS basket (alt)', 'IKEA', 'Best cube seagrass', 'https://www.ikea.com/gb/en/p/gnabbas-basket-60400298/', 'IKEA UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_transition_basket', 13, 'Amazon backup basket (alt)', 'Various', 'Best Amazon backup', 'https://www.amazon.co.uk/dp/B07DWR1Y8H', 'Amazon UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_transition_basket', 14, 'MÅLA paper roll holder (alt)', 'IKEA', 'Best wrong job', 'https://www.ikea.com/gb/en/p/mala-paper-roll-holder-with-storage-70488969/', 'IKEA UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_transition_basket', 15, 'Lovevery Pull Pup (alt)', 'Lovevery', 'Best later pull', 'https://www.lovevery.co.uk/products/the-pull-pup', 'Lovevery UK', NULL, 'in_stock', NULL, 'emerging', 'buy', true, 'Pad row'),
    ('cat_two_block_towers', 6, 'John Lewis 100 Wooden Building Blocks', 'John Lewis', 'Best big cube tub', 'https://www.johnlewis.com/john-lewis-100-wooden-building-blocks/p4808271', 'John Lewis', '£20.00', 'in_stock', '12 months+', 'good', 'buy', true, 'Big cube set'),
    ('cat_two_block_towers', 7, 'GREJSIMOJS Building Blocks', 'IKEA', 'Best mix figurines', 'https://www.ikea.com/gb/en/p/grejsimojs-20-piece-toy-building-blocks-mix-and-match-5-figurines-60602036/', 'IKEA UK', '£13.00', 'in_stock', 'From 18 months', 'good', 'buy', true, 'Figurine blocks'),
    ('cat_two_block_towers', 8, 'Hape Wonderful Blocks 101pcs', 'Hape', 'Best beech volume', 'https://www.smythstoys.com/uk/en-gb/toys/baby-and-preschool/baby-toys/building-blocks/hape-wonderful-blocks-101pcs/p/208120', 'Smyths', '£19.99', 'in_stock', '12 months+', 'emerging', 'buy', true, 'Classic beech set'),
    ('cat_two_block_towers', 9, 'Eichhorn 100 Colourful Wooden Blocks', 'Eichhorn', 'Best Amazon wood set', 'https://www.amazon.co.uk/dp/B082YN8F54', 'Amazon UK', '£24.99', 'in_stock', 'From 1 year', 'good', 'buy', true, 'German wood set'),
    ('cat_two_block_towers', 10, 'Jaques Sensory Wooden Baby Blocks', 'Jaques of London', 'Best sensory shake blocks', 'https://www.jaqueslondon.co.uk/products/wooden-baby-blocks-sensory-toy', 'Jaques', '£23.50', 'in_stock', 'From 10 months', 'emerging', 'buy', true, 'Sensory sound blocks'),
    ('cat_two_block_towers', 11, 'Bigjigs London Stacking Blocks', 'Bigjigs', NULL, 'https://www.bigjigstoys.co.uk/products/london-stacking-blocks-38015', 'Bigjigs', '£14.99', 'in_stock', '12 months+', 'good', 'buy', true, 'Dowel stacker'),
    ('cat_two_block_towers', 12, 'John Lewis Wooden Farm Pull Along Stacking Train', 'John Lewis', NULL, 'https://www.johnlewis.com/john-lewis-wooden-farm-pull-along-stacking-train-fsc-certified-wood/p110988286', 'John Lewis', '£18.00', 'in_stock', '12 months+', 'good', 'buy', true, 'Pull stack hybrid'),
    ('cat_two_block_towers', 13, 'Melissa & Doug 100 Wood Blocks', 'Melissa & Doug', NULL, 'https://www.amazon.co.uk/dp/B00005BVRW', 'Amazon UK', '£20.00', 'in_stock', '2 years+', 'weak', 'buy', true, 'Classic US set'),
    ('cat_two_block_towers', 14, 'PlanToys Unit Blocks', 'PlanToys', NULL, 'https://www.scandiborn.co.uk/products/plantoys-unit-blocks', 'Scandiborn', '£45.00', 'in_stock', '12 months+', 'emerging', 'buy', true, 'Unit sizing'),
    ('cat_two_block_towers', 15, 'Guidecraft Unit Blocks', 'Guidecraft', NULL, 'https://www.amazon.co.uk/dp/B000067Q9T', 'Amazon UK', '£80.00', 'in_stock', '18 months+', 'weak', 'buy', true, 'Classroom unit blocks')
  ) AS v(source_category_entity_id, longlist_rank, product_name, brand, best_for_tag, product_url, retailer, price_text, stock_status, age_mark_on_listing, evidence_tier, buy_borrow_hold_off, gift_suitable, caveat_short)
)
INSERT INTO public.pl_stage3_picks (
  age_band_id,
  category_type_id,
  source_category_entity_id,
  pick_rank,
  longlist_rank,
  status,
  is_visible,
  is_locked,
  best_for_tag,
  product_name,
  brand,
  retailer,
  product_url,
  price_text,
  stock_status,
  age_mark_on_listing,
  caveats,
  buy_borrow_hold_off,
  gift_suitable,
  evidence_tier,
  founder_qa_flag,
  research_payload
)
SELECT
  '13-15m',
  ct.id,
  r.source_category_entity_id,
  r.longlist_rank,
  r.longlist_rank,
  'backup',
  false,
  true,
  r.best_for_tag,
  r.product_name,
  r.brand,
  r.retailer,
  r.product_url,
  r.price_text,
  r.stock_status,
  r.age_mark_on_listing,
  r.caveat_short,
  r.buy_borrow_hold_off,
  -- All-NULL VALUES columns are inferred as text; cast for the boolean target column.
  r.gift_suitable::boolean,
  r.evidence_tier,
  'backup_not_card_ready',
  jsonb_build_object(
    'bundle_schema_version', 'stage3_ingestion_bundle_v1',
    'bundle_generated_at', '2026-07-24T11:05:59.540Z',
    'status', 'dormant_backup',
    'source_category_entity_id', r.source_category_entity_id
  )
FROM backup_rows r
JOIN public.pl_category_types ct
  ON ct.slug = r.source_category_entity_id
WHERE EXISTS (
  SELECT 1
  FROM public.pl_age_band_development_need_category_types abdnct
  WHERE abdnct.age_band_id = '13-15m'
    AND abdnct.category_type_id = ct.id
    AND abdnct.is_active = true
);

DO $$
DECLARE
  v_visible_count INTEGER;
  v_backup_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_visible_count
  FROM public.pl_stage3_picks s
  JOIN public.pl_category_types ct ON ct.id = s.category_type_id
  WHERE s.age_band_id = '13-15m'
    AND ct.slug IN ('cat_big_paper_floor', 'cat_books_with_pauses', 'cat_cupboard_locks_cable_tidy', 'cat_open_cup', 'cat_out_and_about_kit', 'cat_push_pull_play', 'cat_teddy_care_play', 'cat_tiny_music_basket', 'cat_transition_basket', 'cat_two_block_towers')
    AND s.status = 'visible'
    AND s.is_visible = true;

  IF v_visible_count <> 55 THEN
    RAISE EXCEPTION 'Expected 55 visible Stage 3 picks for 13-15m, got %', v_visible_count;
  END IF;

  SELECT COUNT(*) INTO v_backup_count
  FROM public.pl_stage3_picks s
  JOIN public.pl_category_types ct ON ct.id = s.category_type_id
  WHERE s.age_band_id = '13-15m'
    AND ct.slug IN ('cat_big_paper_floor', 'cat_books_with_pauses', 'cat_cupboard_locks_cable_tidy', 'cat_open_cup', 'cat_out_and_about_kit', 'cat_push_pull_play', 'cat_teddy_care_play', 'cat_tiny_music_basket', 'cat_transition_basket', 'cat_two_block_towers')
    AND s.status = 'backup'
    AND s.is_visible = false;

  IF v_backup_count <> 104 THEN
    RAISE EXCEPTION 'Expected 104 backup Stage 3 picks for 13-15m, got %', v_backup_count;
  END IF;
END $$;

COMMIT;
