-- PR4: structured listing draft details on private marketplace_listing_drafts.

ALTER TABLE public.marketplace_listing_drafts
  ADD COLUMN IF NOT EXISTS listing_draft_details_json JSONB NULL,
  ADD COLUMN IF NOT EXISTS listing_details_generated_at TIMESTAMPTZ NULL;

COMMENT ON COLUMN public.marketplace_listing_drafts.listing_draft_details_json IS
  'Structured editable listing draft details (checklists, safety notes, photo tips) from PR4 generation.';

COMMENT ON COLUMN public.marketplace_listing_drafts.listing_details_generated_at IS
  'When listing draft details were last generated by Gemini (PR4).';
