-- Generated by web/scripts/ingest-stage3-pips-picks.mjs
-- Bundle: agent-tools/exports/stage3_ingestion_bundle_9-12m.json

BEGIN;

CREATE TABLE IF NOT EXISTS public.pl_stage3_picks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  age_band_id TEXT NOT NULL REFERENCES public.pl_age_bands(id) ON DELETE RESTRICT,
  category_type_id UUID NOT NULL REFERENCES public.pl_category_types(id) ON DELETE CASCADE,
  source_category_entity_id TEXT NOT NULL,
  pick_rank INTEGER NOT NULL CHECK (pick_rank > 0),
  longlist_rank INTEGER NOT NULL CHECK (longlist_rank > 0),
  status TEXT NOT NULL CHECK (status IN ('visible', 'backup', 'skip')),
  is_visible BOOLEAN NOT NULL DEFAULT true,
  is_locked BOOLEAN NOT NULL DEFAULT true,
  best_for_tag TEXT,
  product_name TEXT NOT NULL,
  brand TEXT,
  retailer TEXT,
  product_url TEXT,
  image_url TEXT,
  price_text TEXT,
  stock_status TEXT,
  age_mark_on_listing TEXT,
  product_description TEXT,
  ember_verdict TEXT,
  why_it_fits TEXT,
  caveats TEXT,
  buy_borrow_hold_off TEXT,
  gift_suitable BOOLEAN,
  gift_note TEXT,
  ownership_note TEXT,
  safety_notes TEXT,
  evidence_tier TEXT,
  evidence_sources TEXT[],
  founder_qa_flag TEXT,
  research_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT pl_stage3_picks_unique UNIQUE (age_band_id, category_type_id, pick_rank, status)
);

ALTER TABLE public.pl_stage3_picks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pl_stage3_picks_public_read" ON public.pl_stage3_picks;
CREATE POLICY "pl_stage3_picks_public_read" ON public.pl_stage3_picks
  FOR SELECT
  TO anon, authenticated
  USING (
    status = 'visible'
    AND is_visible = true
    AND (
      is_locked = false
      OR lower(coalesce(auth.jwt() ->> 'email', '')) = 'timwd23@gmail.com'
      OR lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'membership_type', '')) = 'ember_plus'
    )
  );

DROP POLICY IF EXISTS "pl_stage3_picks_admin_all" ON public.pl_stage3_picks;
CREATE POLICY "pl_stage3_picks_admin_all" ON public.pl_stage3_picks
  FOR ALL
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

GRANT SELECT ON public.pl_stage3_picks TO anon, authenticated;

CREATE INDEX IF NOT EXISTS pl_stage3_picks_age_category_rank_idx
  ON public.pl_stage3_picks(age_band_id, category_type_id, status, pick_rank);

DROP TRIGGER IF EXISTS trg_pl_stage3_picks_updated_at ON public.pl_stage3_picks;
CREATE TRIGGER trg_pl_stage3_picks_updated_at
  BEFORE UPDATE ON public.pl_stage3_picks
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

DROP VIEW IF EXISTS public.v_gateway_stage3_picks_public;
CREATE VIEW public.v_gateway_stage3_picks_public
WITH (security_invoker = true) AS
SELECT
  s.id,
  s.age_band_id,
  s.category_type_id,
  ct.slug AS category_type_slug,
  s.source_category_entity_id,
  s.pick_rank,
  s.longlist_rank,
  s.status,
  s.is_visible,
  s.is_locked,
  s.best_for_tag,
  s.product_name,
  s.brand,
  s.retailer,
  s.product_url,
  s.image_url,
  s.price_text,
  s.stock_status,
  s.age_mark_on_listing,
  s.product_description,
  s.ember_verdict,
  s.why_it_fits,
  s.caveats,
  s.buy_borrow_hold_off,
  s.gift_suitable,
  s.gift_note,
  s.ownership_note,
  s.safety_notes,
  s.evidence_tier,
  s.evidence_sources,
  s.founder_qa_flag,
  s.research_payload
FROM public.pl_stage3_picks s
JOIN public.pl_category_types ct ON ct.id = s.category_type_id
WHERE s.status = 'visible'
  AND s.is_visible = true
  AND s.is_locked = false;

GRANT SELECT ON public.v_gateway_stage3_picks_public TO anon, authenticated;

DELETE FROM public.pl_stage3_picks
WHERE age_band_id = '9-12m'
  AND source_category_entity_id IN ('cat_board_books', 'cat_bubbles', 'cat_feelings_faces_books', 'cat_highchair', 'cat_peekaboo_scarf', 'cat_pincer_puzzle', 'cat_push_pull_toys');

WITH stage3_rows AS (
  SELECT *
  FROM (VALUES
    ('cat_board_books', 1, 1, 'visible', true, false, 'Best for flap pauses', 'Where''s Spot?', 'Eric Hill', 'Penguin UK', 'https://www.penguin.co.uk/books/122792/wheres-spot-by-hill-eric/9780723263661', NULL, '£7.99', 'in_stock', 'Board book for babies/toddlers', 'A sturdy lift the flap board book where Spot hides behind doors and furniture, with a pause on every page before the reveal.', 'Chatting and waving grow when you leave a beat before lifting. Spot turns that pause into a game they can predict after a few reads. Start here when you want flaps that survive sticky hands and a story short enough for sofa time.', 'Pause and reveal flaps.', 'Supervise flaps and small chewable corners.', 'buy', true, 'Check the shelf before gifting classics.', 'High ownership risk for Spot and Usborne.', 'Board book; supervise.', 'good', ARRAY[]::text[], 'none'),
    ('cat_board_books', 2, 2, 'visible', true, true, 'Best for touch pauses', 'That''s Not My Dinosaur…', 'Usborne / Fiona Watt', 'Bookshop.org UK', 'https://uk.bookshop.org/p/books/that-s-not-my-dinosaur-fiona-watt/9781474916222', NULL, '£6.99', 'in_stock', 'Board book for babies/toddlers', 'A touchy feely Usborne dinosaur board book with textured pages, inviting a slow finger touch pause before you turn together.', 'Flaps are one kind of pause; a new texture is another kind of touch pause. You wait while they stroke, then name what they noticed. Choose dinosaur textures when they already grab fabric and want that habit on a sturdy board book page.', 'Texture pauses.', 'Supervise flaps and small chewable corners.', 'buy', true, 'Check the shelf before gifting classics.', 'High ownership risk for Spot and Usborne.', 'Board book; supervise.', 'good', ARRAY[]::text[], 'none'),
    ('cat_board_books', 3, 3, 'visible', true, true, 'Best for bold face pages', 'Baby Touch: Faces (black and white)', 'Ladybird', 'Penguin UK', 'https://www.penguin.co.uk/books/313409/baby-touch-faces-a-black-and-white-book-by-ladybird/9780241391723', NULL, '£6.99', 'in_stock', 'Board book for babies/toddlers', 'A high contrast Ladybird board book of large bold friendly faces, sized for shared looking and simple pointing on the sofa.', 'Before busy colour spreads, bold face pages still hold a look. You pause on a page and wait for a smile or a point. Keep this in the bag when you want a short look and chat without flaps to chew through.', 'Face looking pauses.', 'Supervise flaps and small chewable corners.', 'buy', true, 'Check the shelf before gifting classics.', 'High ownership risk for Spot and Usborne.', 'Board book; supervise.', 'good', ARRAY[]::text[], 'none'),
    ('cat_board_books', 4, 4, 'visible', true, true, 'Best for mirror face pauses', 'Baby Touch First Focus: Faces', 'Ladybird', 'Penguin UK', 'https://www.penguin.co.uk/books/289967/faces-baby-touch-first-focus-by-ladybird/9780241243251', NULL, '£6.99', 'in_stock', 'Board book for babies/toddlers', 'A compact high contrast faces board book with a mirror ending, sized for short looking games and a final face pause together.', 'A mirror page turns looking into a tiny peek of their own face at the end. That fits chatting without a separate toy. Keep First Focus Faces when you want face pages plus one mirror pause to close the book together.', 'Colour naming pauses.', 'Supervise flaps and small chewable corners.', 'buy', true, 'Check the shelf before gifting classics.', 'High ownership risk for Spot and Usborne.', 'Board book; supervise.', 'good', ARRAY[]::text[], 'none'),
    ('cat_board_books', 5, 5, 'visible', true, true, 'Best for farm flap tours', 'Spot Goes to the Farm', 'Eric Hill', 'Penguin UK', 'https://www.penguin.co.uk/books/108949/spot-goes-to-the-farm-by-hill-eric/9780723267119', NULL, '£7.99', 'in_stock', 'Board book for babies/toddlers', 'A Spot lift the flap board book set on a farm, with animal reveals that invite a pause before each flap.', 'If Spot at home is already loved, the farm version refreshes the same pause game with new animals to find. You keep the rhythm they know. Add it when the first Spot is worn soft and you still want flaps on the sofa.', 'Familiar flap rhythm, new setting.', 'Supervise flaps and small chewable corners.', 'buy', true, 'Check the shelf before gifting classics.', 'High ownership risk for Spot and Usborne.', 'Board book; supervise.', 'good', ARRAY[]::text[], 'none'),
    ('cat_board_books', 6, 6, 'visible', true, true, 'Best for hunger page turns', 'The Very Hungry Caterpillar', 'Eric Carle', 'Bookshop.org UK', 'https://uk.bookshop.org/p/books/the-very-hungry-caterpillar-eric-carle/9780241003008', NULL, '£6.99', 'in_stock', 'Board book for babies/toddlers', 'A classic board book with holes through fruit pages, inviting a finger pause and a turn as the caterpillar eats through the day.', 'Holes in the page create a natural wait before the next food appears. That is a pause without flaps for busy fingers. Keep Caterpillar when they enjoy poking and you want a story that still works months later on the shelf.', 'Theme variety in touch books.', 'Supervise flaps and small chewable corners.', 'buy', true, 'Check the shelf before gifting classics.', 'High ownership risk for Spot and Usborne.', 'Board book; supervise.', 'good', ARRAY[]::text[], 'none'),
    ('cat_board_books', 7, 7, 'visible', true, true, 'Best for crate flap reveals', 'Dear Zoo', 'Rod Campbell', 'LoveReading4Kids', 'https://www.lovereading4kids.co.uk/book/9781529074932/isbn/Dear-Zoo-Lift-the-Flap-40th-Anniversary-Edition-by-Rod-Campbell.html', NULL, '£7.99', 'in_stock', 'Board book for babies/toddlers', 'A Rod Campbell board book where each zoo crate opens on a different animal, sized for shared lifts on the sofa cushion.', 'Crate flaps give a clear pause before the animal appears. You wait for the lift, then name what arrived. Keep Dear Zoo when Spot flaps already work and you want a second crate flap habit without buying another Spot title.', 'Zoo flap pauses.', 'Supervise flaps and small chewable corners.', 'buy', true, 'Check the shelf before gifting classics.', 'High ownership risk for Spot and Usborne.', 'Board book; supervise.', 'good', ARRAY[]::text[], 'none'),
    ('cat_board_books', 8, 8, 'visible', true, true, 'Best for photo baby faces', 'Global Babies', 'Global Fund for Children', 'Bookshop.org UK', 'https://uk.bookshop.org/p/books/global-babies-the-global-fund-for-children/9781580891745', NULL, '£6.99', 'in_stock', 'Board book for babies/toddlers', 'A board book of photographs of babies from around the world, inviting slow shared looking at real faces on sturdy pages.', 'Drawn faces are useful; real baby photos add a different looking job on the sofa cushion. You pause on each page and notice eyes, hats, and smiles. Choose Global Babies when you want faces beyond cartoons in the book basket.', 'Photo face looking.', 'Supervise flaps and small chewable corners.', 'buy', true, 'Check the shelf before gifting classics.', 'High ownership risk for Spot and Usborne.', 'Board book; supervise.', 'good', ARRAY[]::text[], 'none'),
    ('cat_board_books', 9, 9, 'visible', true, true, 'Best for soft texture strokes', 'That''s Not My Puppy…', 'Usborne / Fiona Watt', 'Bookshop.org UK', 'https://uk.bookshop.org/p/books/that-s-not-my-puppy-fiona-watt/9781409508717', NULL, '£6.99', 'in_stock', 'Board book for babies/toddlers', 'A touchy feely Usborne puppy board book with soft patches on each page, inviting a finger stroke pause before the next turn.', 'Soft patches invite a slow stroke before you turn. That is a soft texture stroke pause without flaps. Choose puppy textures when dinosaur textures already work and you want a second soft stroke habit in the book basket this month.', 'Hole pauses in a classic.', 'Supervise flaps and small chewable corners.', 'buy', true, 'Check the shelf before gifting classics.', 'High ownership risk for Spot and Usborne.', 'Board book; supervise.', 'good', ARRAY[]::text[], 'none'),
    ('cat_board_books', 10, 10, 'visible', true, true, 'Best for expression pages', 'Making Faces: A First Book of Emotions', 'Abrams Appleseed', 'Bookshop.org UK', 'https://uk.bookshop.org/p/books/making-faces-a-first-book-of-emotions-abrams-appleseed/9781419721311', NULL, '£7.99', 'in_stock', 'Board book for babies/toddlers', 'A board book of clear facial expressions for happy, sad and other feelings, inviting a pause to copy faces together.', 'Copying a face is a chatting game as much as a feelings lesson. You pause, pull a face, and wait for theirs. Add Making Faces when they already watch your mouth during songs and you want pages that match that game.', 'Expression pauses.', 'Supervise flaps and small chewable corners.', 'buy', true, 'Check the shelf before gifting classics.', 'High ownership risk for Spot and Usborne.', 'Board book; supervise.', 'good', ARRAY[]::text[], 'none'),
    ('cat_bubbles', 1, 1, 'visible', true, false, 'Best for parent blown watching', 'Pustefix Bubble Trumpet (adult blown)', 'Pustefix', 'Smyths Toys', 'https://www.smythstoys.com/uk/en-gb/toys/outdoor-toys/bubbles/pustefix-bubble-trumpet/p/191234', NULL, 'See Smyths', 'in_stock', 'Parent operated bubble play; supervise closely for baby watching', 'A Pustefix bubble trumpet for an adult to blow outdoors or by an open door, while a nearly one watches and reaches for floating bubbles.', 'Bubbles are for watching and reaching now, not for them to hold the wand. You blow; they track and grab air. Choose a simple trumpet when you want a short garden break without a noisy machine sitting on the patio.', 'Parent blown bubbles for watching.', 'Many bubble toys carry 3+ marks for child operation; keep as adult tool. Wipe face if solution contacts skin.', 'buy', false, 'Parent buy / consumable.', 'Refills matter more than gadgets.', 'Adult only operation; never leave solution in reach; avoid eyes.', 'good', ARRAY[]::text[], 'check_age_fit'),
    ('cat_bubbles', 2, 2, 'visible', true, true, 'Best for a refill bottle', 'Pustefix Bubble Mix Refill', 'Pustefix', 'Smyths Toys', 'https://www.smythstoys.com/uk/en-gb/toys/outdoor-toys/bubbles/pustefix-bubble-mix-refill/p/112233', NULL, 'See Smyths', 'in_stock', 'Bubble solution for adult led play', 'A bottle of Pustefix bubble mix refill for topping up an adult wand or trumpet, so watching games can repeat without buying another gadget.', 'The wand is optional; the mix runs out first. A refill keeps the watching game going. Buy mix when you already have any wand and just need more floating bubbles on a quiet afternoon. Keep solution out of reach between plays.', 'Refills for repeat watching.', 'Confirm live Smyths SKU; bot pages may soft 404.', 'buy', false, NULL, 'Prefer refill over second machine.', 'Store out of reach.', 'good', ARRAY[]::text[], 'check_url'),
    ('cat_bubbles', 3, 3, 'visible', true, true, 'Best for bring back kitchen wand', 'Washing up liquid and a wire wand', 'Home', 'Bring back out', 'https://www.smythstoys.com/uk/en-gb/toys/outdoor-toys/bubbles/pustefix-bubble-trumpet/p/191234', NULL, '£0', 'in_stock', 'Household solution under adult control', 'A shallow bowl of mild washing up liquid and water with a homemade wire wand, blown by you while they watch and reach outdoors.', 'Before buying another bottle, try the sink liquid you already own. The game is the float and the reach. Bring kitchen bubbles back out when you want five minutes of watching without a shop run. One short go with Washing up liquid and is enough before you tidy away.', 'Bring back out bubbles.', 'Keep solution away from eyes and mouth; outdoor preferred.', 'bring_back_out', false, NULL, 'Default first step.', 'Adult only; rinse skin if contacted.', 'good', ARRAY[]::text[], 'check_claim'),
    ('cat_bubbles', 4, 4, 'visible', true, true, 'Best for outdoor reaching practice', 'Outdoor bubble reaching session', 'Home outdoor', 'Home', 'https://www.smythstoys.com/uk/en-gb/toys/outdoor-toys/bubbles/pustefix-bubble-trumpet/p/191234', NULL, 'See Smyths', 'in_stock', 'Adult operated bubble play for supervised baby watching', 'An adult blown outdoor bubble session on the grass, so a nearly one can watch and reach toward floating bubbles in open air.', 'Outdoor space gives room to track bubbles without slippery floors indoors. You blow; they reach toward what floats past. Pick outdoor reaching practice when rooms feel too tight and you want watching and reaching practice on the grass this afternoon.', 'Lots of bubbles to track.', 'FOUNDER: confirm under-3 wording; may quarantine if listing forbids under 36m.', 'buy', false, NULL, 'Skip if you already own a trumpet and refill.', 'Adult only.', 'good', ARRAY[]::text[], 'check_age_fit'),
    ('cat_bubbles', 5, 5, 'visible', true, true, 'Best for holding off machines', 'Hold off electronic bubble machines', 'Guidance', 'Hold off', 'https://www.smythstoys.com/uk/en-gb/toys/outdoor-toys/bubbles/pustefix-bubble-trumpet/p/191234', NULL, 'Hold off', 'in_stock', 'Guidance: prefer adult blown wands for this band', 'A hold off note on battery bubble machines for this age, pointing parents back to adult blown wands for watching and reaching instead.', 'Machines look busy and often carry under three warnings for child use. For watching at nearly one, your breath on a wand is enough. Holding off machines keeps the brief honest until they are older operators on the grass outside.', 'Avoid wrong age machines.', 'Argos machine pages often 3+; listed as skip guidance.', 'hold_off', false, NULL, 'Do not buy for this band.', 'Under 3 exclusions fail this band if treated as child toys.', 'good', ARRAY[]::text[], 'check_age_fit'),
    ('cat_feelings_faces_books', 1, 1, 'visible', true, false, 'Best for black and white faces', 'Baby Touch: Faces (black and white)', 'Ladybird', 'Penguin UK', 'https://www.penguin.co.uk/books/313409/baby-touch-faces-a-black-and-white-book-by-ladybird/9780241391723', NULL, '£6.99', 'in_stock', 'Board book for babies/toddlers', 'A sturdy Ladybird board book of large black and white faces, sized for shared looking and simple pointing on the sofa.', 'Faces are the social magnet at nearly one. High contrast keeps the look simple while you name eyes and smiles on the sofa. Start here when you want a short face book before busier emotion pages arrive in the basket.', 'Faces and feelings looking.', 'Supervise flaps and corners.', 'buy', true, 'Check shelf for duplicates.', 'High overlap with board books card; rotate rather than double buy.', 'Board book.', 'good', ARRAY[]::text[], 'none'),
    ('cat_feelings_faces_books', 2, 2, 'visible', true, true, 'Best for mirror face ending', 'Baby Touch First Focus: Faces', 'Ladybird', 'Penguin UK', 'https://www.penguin.co.uk/books/289967/faces-baby-touch-first-focus-by-ladybird/9780241243251', NULL, '£5.99', 'in_stock', 'Board book for babies/toddlers', 'A compact high contrast faces board book with a mirror at the end, made for a final peek at their own face together.', 'A mirror page turns looking into a short game with their own face. That fits noticing feelings without a talking to. Keep First Focus when you want faces plus one mirror pause at the close of the book. Leave Baby Touch First Focus: out where they can find it again tomorrow.', 'Faces and feelings looking.', 'Supervise flaps and corners.', 'buy', true, 'Check shelf for duplicates.', 'High overlap with board books card; rotate rather than double buy.', 'Board book.', 'good', ARRAY[]::text[], 'none'),
    ('cat_feelings_faces_books', 3, 3, 'visible', true, true, 'Best for photo baby faces', 'Global Babies', 'Global Fund for Children', 'Bookshop.org UK', 'https://uk.bookshop.org/p/books/global-babies-the-global-fund-for-children/9781580891745', NULL, '£6.99', 'in_stock', 'Board book for babies/toddlers', 'A board book of photographs of babies from around the world, inviting slow shared looking at real faces on sturdy pages.', 'Photos show real eyes and expressions beyond cartoons. You pause and notice together on the sofa. Choose Global Babies when drawn faces are known and you want real faces in the basket. One short go with Global Babies is enough before you tidy away.', 'Faces and feelings looking.', 'Supervise flaps and corners.', 'buy', true, 'Check shelf for duplicates.', 'High overlap with board books card; rotate rather than double buy.', 'Board book.', 'good', ARRAY[]::text[], 'none'),
    ('cat_feelings_faces_books', 4, 4, 'visible', true, true, 'Best for expression copying', 'Making Faces: A First Book of Emotions', 'Abrams Appleseed', 'Bookshop.org UK', 'https://uk.bookshop.org/p/books/making-faces-a-first-book-of-emotions-abrams-appleseed/9781419721311', NULL, '£7.99', 'in_stock', 'Board book for babies/toddlers', 'A board book of clear facial expressions for happy, sad and other feelings, inviting a pause to copy faces together.', 'Copying a face is how feelings show up before long emotion stories. You pull a face and wait for theirs. Add Making Faces when they watch your mouth in songs and everyday games at home. Stay nearby while they try Making Faces: A First, then stop on a good note.', 'Faces and feelings looking.', 'Supervise flaps and corners.', 'buy', true, 'Check shelf for duplicates.', 'High overlap with board books card; rotate rather than double buy.', 'Board book.', 'good', ARRAY[]::text[], 'none'),
    ('cat_feelings_faces_books', 5, 5, 'visible', true, true, 'Best for flap face reveals', 'Where''s Spot?', 'Eric Hill', 'Penguin UK', 'https://www.penguin.co.uk/books/122792/wheres-spot-by-hill-eric/9780723263661', NULL, '£7.99', 'in_stock', 'Board book for babies/toddlers', 'A lift the flap board book where animal faces appear after a pause, linking hide and find with looking at expressions.', 'Spot is not a feelings textbook, but each flap reveals a face to notice together. That still serves this card. Keep Spot when they already love flaps and you want face noticing inside a game they know. Put Where''s Spot? where you both sit most evenings so the invite is easy.', 'Faces and feelings looking.', 'Supervise flaps and corners.', 'buy', true, 'Check shelf for duplicates.', 'High overlap with board books card; rotate rather than double buy.', 'Board book.', 'good', ARRAY[]::text[], 'none'),
    ('cat_feelings_faces_books', 6, 6, 'visible', true, true, 'Best for zoo face flaps', 'Dear Zoo', 'Rod Campbell', 'Bookshop.org UK', 'https://uk.bookshop.org/p/books/dear-zoo-rod-campbell/9781407030678', NULL, '£7.99', 'in_stock', 'Board book for babies/toddlers', 'A lift the flap board book of zoo animals in crates, each reveal showing a clear animal face after a short wait.', 'Animal faces after a flap give you something to name and copy. The wait is built in. Add Dear Zoo when Spot is worn and you still want face reveals inside a flap story. Put Dear Zoo where you both sit most evenings so the invite is easy.', 'Faces and feelings looking.', 'Supervise flaps and corners.', 'buy', true, 'Check shelf for duplicates.', 'High overlap with board books card; rotate rather than double buy.', 'Board book.', 'good', ARRAY[]::text[], 'none'),
    ('cat_feelings_faces_books', 7, 7, 'visible', true, true, 'Best for touch and faces', 'That''s Not My Puppy…', 'Usborne / Fiona Watt', 'Bookshop.org UK', 'https://uk.bookshop.org/p/books/that-s-not-my-puppy-fiona-watt/9780746047866', NULL, '£6.99', 'in_stock', 'Board book for babies/toddlers', 'A touchy feely Usborne board book with textures and friendly puppy pages, inviting a pause to look and stroke together.', 'Texture pages slow you down so faces and fur get a proper look. You wait, stroke, and name. Choose the puppy when they grab fabric and you want faces inside a touch book they can mouth safely. Let them finish the turn with That''s Not My Puppy…, then close the activity kindly.', 'Faces and feelings looking.', 'Supervise flaps and corners.', 'buy', true, 'Check shelf for duplicates.', 'High overlap with board books card; rotate rather than double buy.', 'Board book.', 'good', ARRAY[]::text[], 'none'),
    ('cat_feelings_faces_books', 8, 8, 'visible', true, true, 'Best for dinosaur face textures', 'That''s Not My Dinosaur…', 'Usborne / Fiona Watt', 'Bookshop.org UK', 'https://uk.bookshop.org/p/books/that-s-not-my-dinosaur-fiona-watt/9781474916222', NULL, '£6.99', 'in_stock', 'Board book for babies/toddlers', 'A touchy feely dinosaur board book with textured pages, offering another slow look and stroke game with clear creature faces.', 'A second Usborne texture book refreshes the same looking habit with bigger creature faces. You still pause for the stroke. Add dinosaur when puppy is known and they point at large animals elsewhere. If interest fades, pack That''s Not My Dinosaur… away and try again another day.', 'Faces and feelings looking.', 'Supervise flaps and corners.', 'buy', true, 'Check shelf for duplicates.', 'High overlap with board books card; rotate rather than double buy.', 'Board book.', 'good', ARRAY[]::text[], 'none'),
    ('cat_feelings_faces_books', 9, 9, 'visible', true, true, 'Best for farm face flaps', 'Spot Goes to the Farm', 'Eric Hill', 'Bookshop.org UK', 'https://uk.bookshop.org/p/books/spot-goes-to-the-farm-eric-hill/9780723263708', NULL, '£7.99', 'in_stock', 'Board book for babies/toddlers', 'A Spot lift the flap farm board book where animal faces appear after each pause, extending the Spot looking game.', 'Farm animals give new faces inside the Spot rhythm they already know. You keep the pause and change the cast. Add the farm book when home Spot is soft and chewed at the corners. Use Spot Goes to the as the second option when the first favourite is already out.', 'Faces and feelings looking.', 'Supervise flaps and corners.', 'buy', true, 'Check shelf for duplicates.', 'High overlap with board books card; rotate rather than double buy.', 'Board book.', 'good', ARRAY[]::text[], 'none'),
    ('cat_feelings_faces_books', 10, 10, 'visible', true, true, 'Best for caterpillar face pages', 'The Very Hungry Caterpillar', 'Eric Carle', 'Bookshop.org UK', 'https://uk.bookshop.org/p/books/the-very-hungry-caterpillar-eric-carle/9780241003008', NULL, '£6.99', 'in_stock', 'Board book for babies/toddlers', 'A classic board book with a friendly caterpillar face and hole pages through fruit, inviting looking pauses while food disappears one bite at a time.', 'The caterpillar face is simple enough to notice between holes. You pause, look, then poke. Keep Caterpillar when you want a face inside a story that will still earn rereads next year. Keep the session short with The Very Hungry Caterpillar so it stays a friendly invite.', 'Faces and feelings looking.', 'Supervise flaps and corners.', 'buy', true, 'Check shelf for duplicates.', 'High overlap with board books card; rotate rather than double buy.', 'Board book.', 'good', ARRAY[]::text[], 'none'),
    ('cat_highchair', 1, 1, 'visible', true, false, 'Best for compact fold storage', 'Joie Mimzy Snacker Highchair', 'Joie', 'Boots UK', 'https://www.boots.com/joie-mimzy-snacker-highchair-abc-charcoal-10220635', NULL, '£49.90', 'in_stock', 'From about 6 months to 15kg / approx 3 years', 'A lightweight folding highchair with a large tray, wipeable pad and five point harness, made for upright meals in smaller kitchens.', 'Mealtimes are moving to the table, and a chair that folds away helps in a small kitchen. The tray and harness keep upright eating practical without a permanent frame. Choose Mimzy Snacker when storage space is the daily friction. Keep Joie Mimzy Snacker Highchair in easy reach for the next short try.', 'Upright feeding with easy storage.', 'Clean straps carefully; check harness height as they grow.', 'buy', false, 'Parent buy.', 'One highchair is enough.', 'Always harness; never leave unattended.', 'good', ARRAY[]::text[], 'check_url'),
    ('cat_highchair', 2, 2, 'visible', true, true, 'Best for recline to upright', 'Joie Mimzy Recline Highchair', 'Joie', 'Boots UK', 'https://www.boots.com/joie-mimzy-recline-highchair-arctic-10320741', NULL, '£80.00', 'in_stock', 'From birth recline; upright feeding when ready', 'A Joie highchair with multiple recline and height positions, so early sits can move into upright tray meals as they grow.', 'If weaning started early, recline positions may already be on the chair. At 10 to 12 months the job is upright meals. Pick Mimzy Recline when you want one frame that already covered the newborn sit and now locks upright.', 'Grow with me upright seat.', 'Larger than Snacker when open.', 'buy', false, NULL, 'Do not buy both Joie Mimzy models.', 'Harness always.', 'good', ARRAY[]::text[], 'check_url'),
    ('cat_highchair', 3, 3, 'visible', true, true, 'Best for a chair for years', 'Stokke Tripp Trapp High Chair', 'Stokke', 'Boots UK', 'https://www.boots.com/stokke-tripp-trapp-high-chair-natural-10116308', NULL, 'From £199', 'in_stock', 'Grows from baby set through childhood with accessories', 'An adjustable wooden Tripp Trapp chair that brings them to the family table, with baby accessories available for upright supported sitting.', 'If you want one chair at the table for years, Tripp Trapp is the long game. Budget and baby set extras count too. Choose it when you will keep the chair past toddler years and can pay for the right accessories now.', 'Table height upright seat for years.', 'Baby Set and tray often extra cost.', 'buy', false, NULL, 'Large spend; borrow first if unsure.', 'Use correct baby set; harness guidance from brand.', 'good', ARRAY[]::text[], 'check_price'),
    ('cat_highchair', 4, 4, 'visible', true, true, 'Best for multi mode value', 'Cosatto Noodle 0 Highchair', 'Cosatto', 'Boots UK', 'https://www.boots.com/cosatto-noodle-0-highchair-mister-fox-10285197', NULL, 'See Boots', 'in_stock', 'From birth / early sitting modes per listing', 'A Cosatto multi mode highchair with tray and harness options, designed to move from early sits into upright family meals.', 'UK brand multi mode chairs sit between budget fold and Tripp Trapp spend. Check the upright tray setup matches your table. Consider Noodle when you want pattern and modes without Stokke pricing. Stay nearby while they try Cosatto Noodle 0 Highchair, then stop on a good note.', 'Multi mode upright feeding.', 'Confirm current upright age guidance on listing.', 'buy', false, NULL, 'One chair only.', 'Harness; supervision.', 'good', ARRAY[]::text[], 'check_url'),
    ('cat_highchair', 5, 5, 'visible', true, true, 'Best for design led table seat', 'Bugaboo Giraffe High Chair', 'Bugaboo', 'Boots UK', 'https://www.boots.com/bugaboo-giraffe-high-chair-white-10320750', NULL, 'See Boots', 'in_stock', 'Grow with child highchair system', 'A Bugaboo Giraffe highchair system aimed at bringing them to the table with adjustable parts as they grow through toddler years.', 'Design led table seats compete with Tripp Trapp for long use. Price is high. Pick Giraffe only when the look and modular system weigh more than a simple foldaway tray chair. Put Bugaboo Giraffe High Chair where you both sit most evenings so the invite is easy.', 'Long use table seat.', 'Premium price; accessories.', 'buy', false, NULL, 'Do not stack with Tripp Trapp.', 'Follow brand baby set guidance.', 'good', ARRAY[]::text[], 'check_price'),
    ('cat_peekaboo_scarf', 1, 1, 'visible', true, false, 'Best for rainbow peekaboo', 'Baby Sensory Scarves Age 0+ UKCA (set of 7)', 'The Little Sensory Bag Co.', 'The Little Sensory Bag Co.', 'https://www.thelittlesensorybagco.co.uk/product-page/baby-sensory-scarves-age-0', NULL, 'From £2.25 each / set pricing on page', 'in_stock', 'UKCA Safety Tested as Toys from 0+', 'A set of seven rainbow organza scarves with firm hems, UKCA tested from birth, for waving, covering toys and simple peekaboo on the floor.', 'Hidden toys are a big game now, and a light scarf is kinder than a thick blanket over the face. Firm hems and dye that does not run help when the scarf ends up wet. Start with a rainbow set when you want one cloth language for hide and find.', 'Peekaboo cloth play.', 'Always supervise; never leave draped over face unsupervised.', 'buy', true, 'Light gift; easy to post.', 'One set is enough; skip duplicates.', 'Adult supervised peekaboo only.', 'good', ARRAY[]::text[], 'none'),
    ('cat_peekaboo_scarf', 2, 2, 'visible', true, true, 'Best for a giant hide cloth', 'TickiT Giant Sensory Scarf', 'TickiT', 'The Little Sensory Bag Co.', 'https://www.thelittlesensorybagco.co.uk/product-page/tickit-giant-sensory-scarf', NULL, '£4.99', 'in_stock', 'Adult supervised sensory cloth; listing notes supervision', 'A large organza sensory scarf in rainbow colours, sized for adult led peekaboo, tent play and waving games with a nearly one.', 'A bigger cloth turns peekaboo into a shared floor game you control. You lift and lower; they reach and laugh. Pick a giant scarf when the small squares are fiddly in your hands and you want one clear hide sheet for the living room.', 'Adult led peekaboo.', 'Listing stresses supervision; not for unsupervised play.', 'buy', true, 'Pair with a soft toy to hide.', 'One giant scarf is enough.', 'Strict adult supervision.', 'good', ARRAY[]::text[], 'check_age_fit'),
    ('cat_peekaboo_scarf', 3, 3, 'visible', true, true, 'Best for a single colour scarf', 'Baby Sensory Scarf single colour option', 'The Little Sensory Bag Co.', 'The Little Sensory Bag Co.', 'https://www.thelittlesensorybagco.co.uk/product-page/baby-sensory-scarves-age-0', NULL, '£2.25', 'in_stock', 'UKCA from 0+', 'A single UKCA tested organza sensory scarf sold individually, handy if you only need one colour for bag and sofa peekaboo.', 'A full set is lovely; one scarf still covers hide and find on the sofa. That helps when storage is tight or you are testing the game first. Choose a single colour when you already own a muslin and just want a lighter see through cloth.', 'Minimal peekaboo cloth.', 'Same product family as rank 1 set.', 'buy', true, 'Tiny add on gift.', 'Skip if buying the set.', 'Supervise.', 'good', ARRAY[]::text[], 'none'),
    ('cat_peekaboo_scarf', 4, 4, 'visible', true, true, 'Best for mirror shape peek', 'Hape Montessori Mirror Shape Puzzle', 'Hape', 'Hape UK', 'https://uk.hape.com/montessori-mirror-shape-puzzle-e0072', NULL, '£19.99', 'in_stock', 'From 12 months', 'A wooden shape puzzle with mirror pieces, so lifting a shape reveals a flash of their own face during shared floor play.', 'Peekaboo is not only cloth. A mirror under a shape gives the same surprise with a different object. Pick this when they already love faces in the hallway mirror and you want that same reveal waiting on the floor mat after lunch.', 'Face reveal play.', 'Glass free acrylic style mirrors; still supervise.', 'buy', true, 'Different from scarves.', 'Also overlaps pincer play.', 'Supervise.', 'good', ARRAY[]::text[], 'none'),
    ('cat_peekaboo_scarf', 5, 5, 'visible', true, true, 'Best for bringing muslins back', 'Bring back a clean muslin for peekaboo', 'Home / existing', 'Bring back out', 'https://www.thelittlesensorybagco.co.uk/product-page/baby-sensory-scarves-age-0', NULL, '£0 (use what you have)', 'in_stock', 'Household cloth under adult supervision', 'A clean muslin or light tea towel from the drawer, used only with you for short peekaboo and toy hiding games on the floor.', 'Before buying another scarf set, try the muslin you already wash weekly. The game is the pause and reveal, not the brand label. Bring a muslin back out when you want to test hide and find tonight without a parcel.', 'Bring back out before buy.', 'Never leave covering face; not a sleep aid.', 'bring_back_out', false, NULL, 'Default first step.', 'Adult only; no unsupervised covering.', 'good', ARRAY[]::text[], 'check_claim'),
    ('cat_pincer_puzzle', 1, 1, 'visible', true, false, 'Best for first big pegs', 'Hape Creative Peg Puzzle', 'Hape', 'Hape UK', 'https://uk.hape.com/creative-peg-puzzle-e0411', NULL, '£14.99', 'in_stock', 'From 12 months', 'A wooden peg puzzle with oversized first big pegs and simple shapes, sized so a nearly one can lift and drop pieces using thumb and finger.', 'Pincer work is shifting from raking grabs to deliberate lifts. First big pegs forgive wobbly aim and keep the board from becoming a pile of half fitted pieces. Start here when you want one clear peg job on the tray table after lunch.', 'Pincer peg practice.', 'Supervise; small rooms still need clear floor for dropped pieces.', 'buy', true, 'Good first peg gift.', 'One starter peg set is enough.', 'Supervise.', 'good', ARRAY[]::text[], 'none'),
    ('cat_pincer_puzzle', 2, 2, 'visible', true, true, 'Best for farm peg pictures', 'Bigjigs My First Peg Puzzle Farm', 'Bigjigs', 'Wooden Toy Shop', 'https://www.woodentoyshop.co.uk/products/my-first-peg-puzzle-farm', NULL, '£8.49', 'in_stock', '12 months +', 'A wooden farm themed first peg puzzle with chunky knobs and matching pictures under each piece for lift and name play.', 'Animal pictures under the pegs give you something to name while they lift. That turns a motor job into a short chat on the tray. Choose farm pegs when they already point at animals in books and you want the same faces on wood. This pick is farm peg pictures.', 'Peg lifts plus naming.', 'Fewer pieces than a sorter box.', 'buy', true, 'Smaller gift price.', 'Fine beside one sorter.', 'Supervise.', 'good', ARRAY[]::text[], 'none'),
    ('cat_pincer_puzzle', 3, 3, 'visible', true, true, 'Best for posting shapes', 'Hape Shape Sorting Box', 'Hape', 'Hape UK', 'https://uk.hape.com/shape-sorting-box-e0507', NULL, '£17.99', 'in_stock', 'From 12 months', 'A wooden shape sorting box with four garden creature shapes held by elastic inside, so pieces stay with the box after posting.', 'Posting through a hole is a different pincer job from lifting pegs off a board. Elastic keepers mean fewer pieces under the sofa. Pick this when they love putting things in containers and you want shapes that do not vanish. This pick is posting shapes.', 'Posting pincer practice.', 'Only four shapes.', 'buy', true, 'Good gift with clear packing.', 'Skip a second sorter box.', 'Supervise.', 'good', ARRAY[]::text[], 'none'),
    ('cat_pincer_puzzle', 4, 4, 'visible', true, true, 'Best for a posting box tray', 'Bigjigs Baby Wooden Shape Sorter Posting Box', 'Bigjigs', 'Wooden Toy Shop', 'https://www.woodentoyshop.co.uk/products/first-posting-box', NULL, '£15.99', 'in_stock', '12 months +', 'A wooden posting box with six play pieces for dropping shapes through matching holes, made for early tray table practice.', 'Six pieces give a little more variety once four shape holes are sorted quickly. The box format keeps the job contained on a highchair tray or floor mat. Choose it when Hape box stock is tight and you still want a clear posting job. This pick is a posting box tray.', 'Contained posting.', 'Pieces can still escape when the lid is off.', 'buy', true, 'Check they do not already own a sorter.', 'Medium ownership risk.', 'Supervise.', 'good', ARRAY[]::text[], 'none'),
    ('cat_pincer_puzzle', 5, 5, 'visible', true, true, 'Best for textured lift outs', 'Tidlo Touch and Feel Bug Puzzle', 'Tidlo', 'Wooden Toy Shop', 'https://www.woodentoyshop.co.uk/products/touch-and-feel-bugs', NULL, '£15.99', 'in_stock', '12 months +', 'A wooden sensory bug puzzle with textured lift out pieces, so fingers get a different feel while matching each bug to its slot.', 'Smooth pegs are useful; textured bugs add a second reason to keep lifting. That helps when plain boards lose interest after a week. Pick textured lift outs when they already mouth and stroke fabrics and you want the same curiosity on a puzzle.', 'Pincer plus texture.', 'Textures need wiping after mouthing.', 'buy', true, 'Nice sensory gift.', 'Fine as a second puzzle.', 'Supervise.', 'good', ARRAY[]::text[], 'none'),
    ('cat_push_pull_toys', 1, 1, 'visible', true, false, 'Best for steady first pushes', 'Hape My First Musical Walker', 'Hape', 'Hape UK', 'https://uk.hape.com/my-first-musical-walker-e0383', NULL, '£54.99', 'in_stock', 'From 12 months', 'A sturdy wooden push walker with a wide base, easy grip bar and a musical panel, made for early standing pushes across a clear floor.', 'Cruising is turning into short pushes, and a wide wooden base is kinder than a light plastic racer on laminate. The musical panel keeps hands busy when they pause to rest. This is the walker to start with when balance is still wobbly and you want one solid frame in the room.', 'Stable push support for getting ready to move.', 'Supervise on stairs; clear the path.', 'buy', true, 'Good gift if they are pulling to stand.', 'One solid walker is enough.', 'Adult supervision; not a sit-in walker.', 'good', ARRAY[]::text[], 'none'),
    ('cat_push_pull_toys', 2, 2, 'visible', true, true, 'Best for blocks while walking', 'Tidlo Wooden Baby Walker with ABC Blocks', 'Tidlo', 'Wooden Toy Shop', 'https://www.woodentoyshop.co.uk/products/babywalker-with-abc-blocks', NULL, '£72.99', 'in_stock', '12 months +', 'A wooden push walker with rubber edged wheels and a tray of 24 letter and number blocks, so pushing and posting share one toy.', 'Once they can push a few steps, a tray of chunky blocks turns the walker into a carry and empty job. That fits busy hands without a separate posting set yet. Choose this when you want one piece of furniture doing both push practice and floor play.', 'Push practice plus block play.', 'Loose blocks; supervise mouthing.', 'buy', true, 'Larger gift; check storage space.', 'Skip if you already own a full wooden walker.', 'Supervise; assembly required.', 'good', ARRAY[]::text[], 'none'),
    ('cat_push_pull_toys', 3, 3, 'visible', true, true, 'Best for a pull along friend', 'Hape Walk-A-Long Puppy', 'Hape', 'Hape UK', 'https://uk.hape.com/walk-a-long-puppy-e0347', NULL, '£19.99', 'in_stock', 'From 12 months', 'A wooden puppy on wheels with a string handle, sized for a nearly one who wants something to drag behind on short floor tours.', 'Push walkers help balance; a pull toy adds the opposite job of glancing back while moving. That second skill shows up once cruising is more confident. Pick this when they keep turning to check what is following them down the hall.', 'Pull as well as push.', 'Supervise string; coil away after play.', 'buy', true, 'Smaller gift than a full walker.', 'Fine beside one push walker.', 'Supervise string play.', 'good', ARRAY[]::text[], 'none'),
    ('cat_push_pull_toys', 4, 4, 'visible', true, true, 'Best for a simple push duck', 'Bigjigs Baby Wooden Duck Push Along', 'Bigjigs', 'Wooden Toy Shop', 'https://www.woodentoyshop.co.uk/products/push-along-duck', NULL, '£12.99', 'in_stock', '12 Months Plus', 'A small wooden duck on wheels with a stick handle to push across the floor, lighter than a full baby walker for short indoor routes.', 'Not every home needs a big walker on the first day of standing. A light duck on a stick lets them practise push without the bulk. This fits smaller rooms and families who already borrow a proper walker from grandparents.', 'Light push practice.', 'Less stable than a wide walker.', 'buy', true, 'Easy smaller gift.', 'Good if space is tight.', 'Supervise.', 'good', ARRAY[]::text[], 'none'),
    ('cat_push_pull_toys', 5, 5, 'visible', true, true, 'Best for a busy front board', 'Tidlo Wooden Baby Walker Activity Centre', 'Tidlo', 'Wooden Toy Shop', 'https://www.woodentoyshop.co.uk/products/activity-walker', NULL, '£59.99', 'in_stock', '12 months +', 'A wooden activity walker with a busy front board and a rear shelf for carrying a favourite toy while they push around the room.', 'Some walkers are empty frames; this one keeps beads and shapes on the front and a shelf for a soft toy behind. That matches short pushes with something to do when they pause. Choose it for curious pushers who empty baskets onto the floor.', 'Push plus busy board play.', 'More visual clutter.', 'buy', true, 'Check they do not already own a busy walker.', 'High ownership risk beside a musical walker.', 'Supervise.', 'good', ARRAY[]::text[], 'none')
  ) AS v(source_category_entity_id, pick_rank, longlist_rank, status, is_visible, is_locked, best_for_tag, product_name, brand, retailer, product_url, image_url, price_text, stock_status, age_mark_on_listing, product_description, ember_verdict, why_it_fits, caveats, buy_borrow_hold_off, gift_suitable, gift_note, ownership_note, safety_notes, evidence_tier, evidence_sources, founder_qa_flag)
)
INSERT INTO public.pl_stage3_picks (
  age_band_id,
  category_type_id,
  source_category_entity_id,
  pick_rank,
  longlist_rank,
  status,
  is_visible,
  is_locked,
  best_for_tag,
  product_name,
  brand,
  retailer,
  product_url,
  image_url,
  price_text,
  stock_status,
  age_mark_on_listing,
  product_description,
  ember_verdict,
  why_it_fits,
  caveats,
  buy_borrow_hold_off,
  gift_suitable,
  gift_note,
  ownership_note,
  safety_notes,
  evidence_tier,
  evidence_sources,
  founder_qa_flag,
  research_payload
)
SELECT
  '9-12m',
  ct.id,
  r.source_category_entity_id,
  r.pick_rank,
  r.longlist_rank,
  r.status,
  r.is_visible,
  r.is_locked,
  r.best_for_tag,
  r.product_name,
  r.brand,
  r.retailer,
  r.product_url,
  r.image_url,
  r.price_text,
  r.stock_status,
  r.age_mark_on_listing,
  r.product_description,
  r.ember_verdict,
  r.why_it_fits,
  r.caveats,
  r.buy_borrow_hold_off,
  r.gift_suitable,
  r.gift_note,
  r.ownership_note,
  r.safety_notes,
  r.evidence_tier,
  r.evidence_sources,
  r.founder_qa_flag,
  jsonb_build_object(
    'bundle_schema_version', 'stage3_ingestion_bundle_v1',
    'bundle_generated_at', '2026-07-24T11:05:59.281Z',
    'research_schema_version', 'ember_picks_research_v3',
    'source_category_entity_id', r.source_category_entity_id
  )
FROM stage3_rows r
JOIN public.pl_category_types ct
  ON ct.slug = r.source_category_entity_id
WHERE EXISTS (
  SELECT 1
  FROM public.pl_age_band_development_need_category_types abdnct
  WHERE abdnct.age_band_id = '9-12m'
    AND abdnct.category_type_id = ct.id
    AND abdnct.is_active = true
);

WITH backup_rows AS (
  SELECT *
  FROM (VALUES
    ('cat_board_books', 12, 'Making Faces', 'Abrams Appleseed', NULL, 'https://uk.bookshop.org/p/books/making-faces-a-first-book-of-emotions-abrams-appleseed/9781419721311', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup book.'),
    ('cat_board_books', 13, 'Baby Touch Animals tab variants', 'Ladybird', NULL, 'https://www.penguin.co.uk/books/313409/baby-touch-faces-a-black-and-white-book-by-ladybird/9780241391723', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup book.'),
    ('cat_board_books', 14, 'Each Peach Pear Plum', 'Ahlberg', NULL, 'https://www.penguin.co.uk/books/122792/wheres-spot-by-hill-eric/9780723263661', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup book.'),
    ('cat_board_books', 15, 'Peekaboo board sets', 'Various', NULL, 'https://uk.bookshop.org/p/books/that-s-not-my-puppy-fiona-watt/9780746047866', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup book.'),
    ('cat_board_books', 16, 'Sound button board books', 'Various', NULL, 'https://uk.bookshop.org/p/books/baby-touch-colours-ladybird/9780241288382', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup book.'),
    ('cat_board_books', 17, 'Thin paper picture books', 'Various', NULL, 'https://uk.bookshop.org/p/books/global-babies-the-global-fund-for-children/9781580891745', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup book.'),
    ('cat_board_books', 18, 'Alphabet wall frieze books', 'Various', NULL, 'https://uk.bookshop.org/p/books/the-very-hungry-caterpillar-eric-carle/9780241003008', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup book.'),
    ('cat_board_books', 19, 'Duplicate Spot bath book', 'Eric Hill', NULL, 'https://www.penguin.co.uk/books/122792/wheres-spot-by-hill-eric/9780723263661', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup book.'),
    ('cat_board_books', 20, 'Usborne farm touch book', 'Usborne', NULL, 'https://uk.bookshop.org/p/books/that-s-not-my-dinosaur-fiona-watt/9781474916222', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup book.'),
    ('cat_board_books', 21, 'Ladybird busy flap zoo', 'Ladybird', NULL, 'https://www.penguin.co.uk/books/289967/faces-baby-touch-first-focus-by-ladybird/9780241243251', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup book.'),
    ('cat_board_books', 22, 'Photo nursery rhyme books', 'Various', NULL, 'https://uk.bookshop.org/p/books/global-babies-the-global-fund-for-children/9781580891745', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup book.'),
    ('cat_board_books', 23, 'Character licensed board books', 'Various', NULL, 'https://uk.bookshop.org/p/books/spot-goes-to-the-farm-eric-hill/9780723263708', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup book.'),
    ('cat_board_books', 24, 'Cloth book with squeaker', 'Various', NULL, 'https://uk.bookshop.org/p/books/baby-touch-colours-ladybird/9780241288382', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup book.'),
    ('cat_board_books', 25, 'Second Caterpillar edition', 'Eric Carle', NULL, 'https://uk.bookshop.org/p/books/the-very-hungry-caterpillar-eric-carle/9780241003008', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup book.'),
    ('cat_bubbles', 6, 'Argos Bubblz Electronic Bubble Machine', 'Bubblz', NULL, 'https://www.argos.co.uk/product/4010443', 'UK retail', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Near miss or reject candidate.'),
    ('cat_bubbles', 7, 'Gazillion Rollin Wave', 'Gazillion', NULL, 'https://www.argos.co.uk/product/8864224', 'UK retail', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Near miss or reject candidate.'),
    ('cat_bubbles', 8, 'Fan-O-Rama Bubble Fan', 'Various', NULL, 'https://www.argos.co.uk/product/4099158', 'UK retail', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Near miss or reject candidate.'),
    ('cat_bubbles', 9, 'Bunch O Bubbles Blaster', 'Zuru', NULL, 'https://www.argos.co.uk/product/4655482', 'UK retail', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Near miss or reject candidate.'),
    ('cat_bubbles', 10, 'Fubbles No Spill wand', 'Fubbles', NULL, 'https://www.argos.co.uk/product/7662173', 'UK retail', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Near miss or reject candidate.'),
    ('cat_bubbles', 11, 'ELC Freddy Fish machine', 'ELC', NULL, 'https://www.smythstoys.com/uk/en-gb/toys/outdoor-toys/bubbles/c/SM061505', 'UK retail', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Near miss or reject candidate.'),
    ('cat_bubbles', 12, 'Second Pustefix trumpet', 'Pustefix', NULL, 'https://www.smythstoys.com/uk/en-gb/toys/outdoor-toys/bubbles/pustefix-bubble-trumpet/p/191234', 'UK retail', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Near miss or reject candidate.'),
    ('cat_bubbles', 13, 'Scented novelty bubble mix', 'Various', NULL, 'https://www.smythstoys.com/uk/en-gb/toys/outdoor-toys/bubbles/pustefix-bubble-mix-refill/p/112233', 'UK retail', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Near miss or reject candidate.'),
    ('cat_bubbles', 14, 'Indoor carpet bubble flood', 'Home', NULL, 'https://www.smythstoys.com/uk/en-gb/toys/outdoor-toys/bubbles/pustefix-bubble-trumpet/p/191234', 'UK retail', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Near miss or reject candidate.'),
    ('cat_bubbles', 15, 'Unattended bubble machine nap time', 'Various', NULL, 'https://www.argos.co.uk/product/4010443', 'UK retail', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Near miss or reject candidate.'),
    ('cat_feelings_faces_books', 11, 'Baby Touch: Animals', 'Ladybird', NULL, 'https://uk.bookshop.org/p/books/baby-touch-animals-a-black-and-white-book-ladybird/9780241388129', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_feelings_faces_books', 12, 'Baby Touch: Colours', 'Ladybird', NULL, 'https://uk.bookshop.org/p/books/baby-touch-colours-ladybird/9780241288382', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_feelings_faces_books', 13, 'Colour Monster', 'Anna Llenas', NULL, 'https://uk.bookshop.org/p/books/the-colour-monster-anna-llenas/9781787410510', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_feelings_faces_books', 14, 'In My Heart', 'Jo Witek', NULL, 'https://uk.bookshop.org/p/books/in-my-heart-a-book-of-feelings-jo-witek/9781419713101', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_feelings_faces_books', 15, 'Family photo album DIY', 'Home', NULL, 'https://uk.bookshop.org/p/books/global-babies-the-global-fund-for-children/9781580891745', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_feelings_faces_books', 16, 'Busy flop emotion charts', 'Various', NULL, 'https://uk.bookshop.org/p/books/making-faces-a-first-book-of-emotions-abrams-appleseed/9781419721311', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_feelings_faces_books', 17, 'Sound emotion books', 'Various', NULL, 'https://www.penguin.co.uk/books/313409/baby-touch-faces-a-black-and-white-book-by-ladybird/9780241391723', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_feelings_faces_books', 18, 'Paper feelings posters', 'Various', NULL, 'https://uk.bookshop.org/p/books/global-babies-the-global-fund-for-children/9781580891745', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_feelings_faces_books', 19, 'Duplicate Spot bath edition', 'Eric Hill', NULL, 'https://www.penguin.co.uk/books/122792/wheres-spot-by-hill-eric/9780723263661', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_feelings_faces_books', 20, 'Character licensed face books', 'Various', NULL, 'https://uk.bookshop.org/p/books/that-s-not-my-puppy-fiona-watt/9780746047866', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_feelings_faces_books', 21, 'Cloth face books with beads', 'Various', NULL, 'https://uk.bookshop.org/p/books/that-s-not-my-dinosaur-fiona-watt/9781474916222', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_feelings_faces_books', 22, 'Toddler feelings workbooks', 'Various', NULL, 'https://uk.bookshop.org/p/books/the-colour-monster-anna-llenas/9781787410510', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_feelings_faces_books', 23, 'Second Global Babies edition', 'Global Fund for Children', NULL, 'https://uk.bookshop.org/p/books/global-babies-the-global-fund-for-children/9781580891745', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_feelings_faces_books', 24, 'Mirror toy without book', 'Various', NULL, 'https://www.penguin.co.uk/books/289967/faces-baby-touch-first-focus-by-ladybird/9780241243251', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_feelings_faces_books', 25, 'Priddy Hello Baby Faces', 'Roger Priddy', NULL, 'https://www.penguin.co.uk/books/313409/baby-touch-faces-a-black-and-white-book-by-ladybird/9780241391723', 'Bookshop / Penguin', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_highchair', 6, 'BabyBjorn High Chair', 'BabyBjorn', NULL, 'https://www.boots.com/babybjorn-high-chair-white-anthracite-10304985', 'UK retail', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_highchair', 7, 'Mamas & Papas Juice Highchair', 'Mamas & Papas', NULL, 'https://www.boots.com/mamas-and-papas-juice-highchair-grey-10220640', 'UK retail', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_highchair', 8, 'IKEA Antilop', 'IKEA', NULL, 'https://www.ikea.com/gb/en/cat/highchairs-46001/', 'UK retail', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_highchair', 9, 'Joie Chestnut multi mode', 'Joie', NULL, 'https://www.argos.co.uk/product/7147090', 'UK retail', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_highchair', 10, 'Second hand Tripp Trapp', 'Stokke', NULL, 'https://www.boots.com/stokke-tripp-trapp-high-chair-natural-10116308', 'UK retail', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_highchair', 11, 'Booster only seat', 'Various', NULL, 'https://www.boots.com/joie-mimzy-snacker-highchair-abc-charcoal-10220635', 'UK retail', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_highchair', 12, 'Restaurant clip-on without home chair', 'Various', NULL, 'https://www.boots.com/joie-mimzy-snacker-highchair-abc-charcoal-10220635', 'UK retail', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_highchair', 13, 'Plastic seat without harness', 'Various', NULL, 'https://www.boots.com/joie-mimzy-snacker-highchair-abc-charcoal-10220635', 'UK retail', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_highchair', 14, 'Swing seat as highchair', 'Various', NULL, 'https://www.boots.com/joie-mimzy-recline-highchair-arctic-10320741', 'UK retail', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_highchair', 15, 'Floor seat only', 'Various', NULL, 'https://www.boots.com/cosatto-noodle-0-highchair-mister-fox-10285197', 'UK retail', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup.'),
    ('cat_peekaboo_scarf', 6, 'TickiT second colour giant scarf', 'TickiT', NULL, 'https://www.thelittlesensorybagco.co.uk/product-page/tickit-giant-sensory-scarf', 'Specialist / brand', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup or near miss.'),
    ('cat_peekaboo_scarf', 7, 'Hape Shape Sorter Ladybug', 'Hape', NULL, 'https://uk.hape.com/shape-sorter-ladybug-e0364', 'Specialist / brand', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup or near miss.'),
    ('cat_peekaboo_scarf', 8, 'Hape Pull-Along Frog', 'Hape', NULL, 'https://uk.hape.com/pull-along-frog-e0361', 'Specialist / brand', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup or near miss.'),
    ('cat_peekaboo_scarf', 9, 'Bigjigs Mystery Box Sorter', 'Bigjigs', NULL, 'https://www.woodentoyshop.co.uk/products/mystery-box', 'Specialist / brand', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup or near miss.'),
    ('cat_peekaboo_scarf', 10, 'Organza craft pack (non toy)', 'Various', NULL, 'https://www.thelittlesensorybagco.co.uk/product-page/baby-sensory-scarves-age-0', 'Specialist / brand', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup or near miss.'),
    ('cat_peekaboo_scarf', 11, 'Thick blanket peekaboo', 'Home', NULL, 'https://www.thelittlesensorybagco.co.uk/product-page/baby-sensory-scarves-age-0', 'Specialist / brand', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup or near miss.'),
    ('cat_peekaboo_scarf', 12, 'Plastic peekaboo house toy', 'Various', NULL, 'https://uk.hape.com/critter-house-shape-sorter-e0515', 'Specialist / brand', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup or near miss.'),
    ('cat_peekaboo_scarf', 13, 'Dance scarf multipack untested', 'Marketplace', NULL, 'https://www.thelittlesensorybagco.co.uk/product-page/baby-sensory-scarves-age-0', 'Specialist / brand', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup or near miss.'),
    ('cat_peekaboo_scarf', 14, 'Silk play scarf adult yoga', 'Various', NULL, 'https://www.thelittlesensorybagco.co.uk/product-page/tickit-giant-sensory-scarf', 'Specialist / brand', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup or near miss.'),
    ('cat_peekaboo_scarf', 15, 'Second rainbow set duplicate', 'The Little Sensory Bag Co.', NULL, 'https://www.thelittlesensorybagco.co.uk/product-page/baby-sensory-scarves-age-0', 'Specialist / brand', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Backup or near miss.'),
    ('cat_pincer_puzzle', 6, 'Hape Wooden Wonder Shape Sorter', 'Hape', NULL, 'https://uk.hape.com/wooden-wonder-shape-sorter-e0516', 'Hape UK', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Credible candidate.'),
    ('cat_pincer_puzzle', 7, 'Hape Shape Sorter Ladybug', 'Hape', NULL, 'https://uk.hape.com/shape-sorter-ladybug-e0364', 'Hape UK', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Credible candidate.'),
    ('cat_pincer_puzzle', 8, 'Hape Critter House Shape Sorter', 'Hape', NULL, 'https://uk.hape.com/critter-house-shape-sorter-e0515', 'Hape UK', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Credible candidate.'),
    ('cat_pincer_puzzle', 9, 'Hape Jungle Peg Puzzle', 'Hape', NULL, 'https://uk.hape.com/jungle-peg-puzzle-e1405', 'Hape UK', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Credible candidate.'),
    ('cat_pincer_puzzle', 10, 'Hape Farmyard Peg Puzzle', 'Hape', NULL, 'https://uk.hape.com/farmyard-peg-puzzle-e1408', 'Hape UK', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Credible candidate.'),
    ('cat_pincer_puzzle', 11, 'Hape Animal Friends Peg Puzzle', 'Hape', NULL, 'https://uk.hape.com/animal-friends-peg-puzzle-e1463', 'Hape UK', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Credible candidate.'),
    ('cat_pincer_puzzle', 12, 'Hape Montessori Mirror Shape Puzzle', 'Hape', NULL, 'https://uk.hape.com/montessori-mirror-shape-puzzle-e0072', 'Hape UK', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Credible candidate.'),
    ('cat_pincer_puzzle', 13, 'Hape Color and Shape Sorter', 'Hape', NULL, 'https://uk.hape.com/color-and-shape-sorter-e0426', 'Hape UK', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Credible candidate.'),
    ('cat_pincer_puzzle', 14, 'Bigjigs My First Peg Puzzle Safari', 'Bigjigs', NULL, 'https://www.woodentoyshop.co.uk/products/my-first-peg-puzzle-safari', 'Wooden Toy Shop', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Credible candidate.'),
    ('cat_pincer_puzzle', 15, 'Bigjigs FSC Wooden Shape Sorter', 'Bigjigs', NULL, 'https://www.woodentoyshop.co.uk/products/shape-sorter', 'Wooden Toy Shop', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Credible candidate.'),
    ('cat_push_pull_toys', 6, 'Hape Walk-A-Long Crocodile', 'Hape', NULL, 'https://uk.hape.com/walk-a-long-crocodile-e0348', 'Hape UK', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Credible push or pull candidate.'),
    ('cat_push_pull_toys', 7, 'Hape Lilly Musical Push Along', 'Hape', NULL, 'https://uk.hape.com/lilly-musical-push-along-e0353', 'Hape UK', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Credible push or pull candidate.'),
    ('cat_push_pull_toys', 8, 'Hape Pull-Along Frog', 'Hape', NULL, 'https://uk.hape.com/pull-along-frog-e0361', 'Hape UK', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Credible push or pull candidate.'),
    ('cat_push_pull_toys', 9, 'Hape Pull-Along Cart with Stacking Blocks', 'Hape', NULL, 'https://uk.hape.com/pull-along-cart-with-stacking-blocks-e0487', 'Hape UK', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Credible push or pull candidate.'),
    ('cat_push_pull_toys', 10, 'Bigjigs Wooden Bee Push Along', 'Bigjigs', NULL, 'https://www.woodentoyshop.co.uk/products/bee-push-along-38043', 'Wooden Toy Shop', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Credible push or pull candidate.'),
    ('cat_push_pull_toys', 11, 'Bigjigs Push Along Musical Roller', 'Bigjigs', NULL, 'https://www.woodentoyshop.co.uk/products/push-along-musical-roller', 'Wooden Toy Shop', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Credible push or pull candidate.'),
    ('cat_push_pull_toys', 12, 'Bigjigs Wooden Pull Along Bear', 'Bigjigs', NULL, 'https://www.woodentoyshop.co.uk/products/fsc-pull-along-bear', 'Wooden Toy Shop', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Credible push or pull candidate.'),
    ('cat_push_pull_toys', 13, 'Bigjigs Wooden Hedgehog Push Along', 'Bigjigs', NULL, 'https://www.woodentoyshop.co.uk/products/new-push-along-hedgehog', 'Wooden Toy Shop', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Credible push or pull candidate.'),
    ('cat_push_pull_toys', 14, 'Bigjigs Mini Animal Duck Push Along', 'Bigjigs', NULL, 'https://www.woodentoyshop.co.uk/products/mini-animal-push-alongs-duck', 'Wooden Toy Shop', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Credible push or pull candidate.'),
    ('cat_push_pull_toys', 15, 'Bigjigs London Bus Pull Along', 'Bigjigs', NULL, 'https://www.woodentoyshop.co.uk/products/london-bus-pull-along', 'Wooden Toy Shop', NULL, 'in_stock', 'From 12 months', 'good', 'buy', true, 'Credible push or pull candidate.')
  ) AS v(source_category_entity_id, longlist_rank, product_name, brand, best_for_tag, product_url, retailer, price_text, stock_status, age_mark_on_listing, evidence_tier, buy_borrow_hold_off, gift_suitable, caveat_short)
)
INSERT INTO public.pl_stage3_picks (
  age_band_id,
  category_type_id,
  source_category_entity_id,
  pick_rank,
  longlist_rank,
  status,
  is_visible,
  is_locked,
  best_for_tag,
  product_name,
  brand,
  retailer,
  product_url,
  price_text,
  stock_status,
  age_mark_on_listing,
  caveats,
  buy_borrow_hold_off,
  gift_suitable,
  evidence_tier,
  founder_qa_flag,
  research_payload
)
SELECT
  '9-12m',
  ct.id,
  r.source_category_entity_id,
  r.longlist_rank,
  r.longlist_rank,
  'backup',
  false,
  true,
  r.best_for_tag,
  r.product_name,
  r.brand,
  r.retailer,
  r.product_url,
  r.price_text,
  r.stock_status,
  r.age_mark_on_listing,
  r.caveat_short,
  r.buy_borrow_hold_off,
  -- All-NULL VALUES columns are inferred as text; cast for the boolean target column.
  r.gift_suitable::boolean,
  r.evidence_tier,
  'backup_not_card_ready',
  jsonb_build_object(
    'bundle_schema_version', 'stage3_ingestion_bundle_v1',
    'bundle_generated_at', '2026-07-24T11:05:59.281Z',
    'status', 'dormant_backup',
    'source_category_entity_id', r.source_category_entity_id
  )
FROM backup_rows r
JOIN public.pl_category_types ct
  ON ct.slug = r.source_category_entity_id
WHERE EXISTS (
  SELECT 1
  FROM public.pl_age_band_development_need_category_types abdnct
  WHERE abdnct.age_band_id = '9-12m'
    AND abdnct.category_type_id = ct.id
    AND abdnct.is_active = true
);

DO $$
DECLARE
  v_visible_count INTEGER;
  v_backup_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_visible_count
  FROM public.pl_stage3_picks s
  JOIN public.pl_category_types ct ON ct.id = s.category_type_id
  WHERE s.age_band_id = '9-12m'
    AND ct.slug IN ('cat_board_books', 'cat_bubbles', 'cat_feelings_faces_books', 'cat_highchair', 'cat_peekaboo_scarf', 'cat_pincer_puzzle', 'cat_push_pull_toys')
    AND s.status = 'visible'
    AND s.is_visible = true;

  IF v_visible_count <> 45 THEN
    RAISE EXCEPTION 'Expected 45 visible Stage 3 picks for 9-12m, got %', v_visible_count;
  END IF;

  SELECT COUNT(*) INTO v_backup_count
  FROM public.pl_stage3_picks s
  JOIN public.pl_category_types ct ON ct.id = s.category_type_id
  WHERE s.age_band_id = '9-12m'
    AND ct.slug IN ('cat_board_books', 'cat_bubbles', 'cat_feelings_faces_books', 'cat_highchair', 'cat_peekaboo_scarf', 'cat_pincer_puzzle', 'cat_push_pull_toys')
    AND s.status = 'backup'
    AND s.is_visible = false;

  IF v_backup_count <> 79 THEN
    RAISE EXCEPTION 'Expected 79 backup Stage 3 picks for 9-12m, got %', v_backup_count;
  END IF;
END $$;

COMMIT;
