-- Generated by web/scripts/ingest-stage3-pips-picks.mjs
-- Bundle: agent-tools/exports/stage3_ingestion_bundle_6-9m.json

BEGIN;

CREATE TABLE IF NOT EXISTS public.pl_stage3_picks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  age_band_id TEXT NOT NULL REFERENCES public.pl_age_bands(id) ON DELETE RESTRICT,
  category_type_id UUID NOT NULL REFERENCES public.pl_category_types(id) ON DELETE CASCADE,
  source_category_entity_id TEXT NOT NULL,
  pick_rank INTEGER NOT NULL CHECK (pick_rank > 0),
  longlist_rank INTEGER NOT NULL CHECK (longlist_rank > 0),
  status TEXT NOT NULL CHECK (status IN ('visible', 'backup', 'skip')),
  is_visible BOOLEAN NOT NULL DEFAULT true,
  is_locked BOOLEAN NOT NULL DEFAULT true,
  best_for_tag TEXT,
  product_name TEXT NOT NULL,
  brand TEXT,
  retailer TEXT,
  product_url TEXT,
  image_url TEXT,
  price_text TEXT,
  stock_status TEXT,
  age_mark_on_listing TEXT,
  product_description TEXT,
  ember_verdict TEXT,
  why_it_fits TEXT,
  caveats TEXT,
  buy_borrow_hold_off TEXT,
  gift_suitable BOOLEAN,
  gift_note TEXT,
  ownership_note TEXT,
  safety_notes TEXT,
  evidence_tier TEXT,
  evidence_sources TEXT[],
  founder_qa_flag TEXT,
  research_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT pl_stage3_picks_unique UNIQUE (age_band_id, category_type_id, pick_rank, status)
);

ALTER TABLE public.pl_stage3_picks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pl_stage3_picks_public_read" ON public.pl_stage3_picks;
CREATE POLICY "pl_stage3_picks_public_read" ON public.pl_stage3_picks
  FOR SELECT
  TO anon, authenticated
  USING (
    status = 'visible'
    AND is_visible = true
    AND (
      is_locked = false
      OR lower(coalesce(auth.jwt() ->> 'email', '')) = 'timwd23@gmail.com'
      OR lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'membership_type', '')) = 'ember_plus'
    )
  );

DROP POLICY IF EXISTS "pl_stage3_picks_admin_all" ON public.pl_stage3_picks;
CREATE POLICY "pl_stage3_picks_admin_all" ON public.pl_stage3_picks
  FOR ALL
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

GRANT SELECT ON public.pl_stage3_picks TO anon, authenticated;

CREATE INDEX IF NOT EXISTS pl_stage3_picks_age_category_rank_idx
  ON public.pl_stage3_picks(age_band_id, category_type_id, status, pick_rank);

DROP TRIGGER IF EXISTS trg_pl_stage3_picks_updated_at ON public.pl_stage3_picks;
CREATE TRIGGER trg_pl_stage3_picks_updated_at
  BEFORE UPDATE ON public.pl_stage3_picks
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

DROP VIEW IF EXISTS public.v_gateway_stage3_picks_public;
CREATE VIEW public.v_gateway_stage3_picks_public
WITH (security_invoker = true) AS
SELECT
  s.id,
  s.age_band_id,
  s.category_type_id,
  ct.slug AS category_type_slug,
  s.source_category_entity_id,
  s.pick_rank,
  s.longlist_rank,
  s.status,
  s.is_visible,
  s.is_locked,
  s.best_for_tag,
  s.product_name,
  s.brand,
  s.retailer,
  s.product_url,
  s.image_url,
  s.price_text,
  s.stock_status,
  s.age_mark_on_listing,
  s.product_description,
  s.ember_verdict,
  s.why_it_fits,
  s.caveats,
  s.buy_borrow_hold_off,
  s.gift_suitable,
  s.gift_note,
  s.ownership_note,
  s.safety_notes,
  s.evidence_tier,
  s.evidence_sources,
  s.founder_qa_flag,
  s.research_payload
FROM public.pl_stage3_picks s
JOIN public.pl_category_types ct ON ct.id = s.category_type_id
WHERE s.status = 'visible'
  AND s.is_visible = true
  AND s.is_locked = false;

GRANT SELECT ON public.v_gateway_stage3_picks_public TO anon, authenticated;

DELETE FROM public.pl_stage3_picks
WHERE age_band_id = '6-9m'
  AND source_category_entity_id IN ('cat_board_books', 'cat_highchair', 'cat_peekaboo_scarf', 'cat_reach_grab_toys', 'cat_safety_gates', 'cat_stacking_nesting_cups', 'cat_teethers', 'cat_tummy_time_wobbler');

WITH stage3_rows AS (
  SELECT *
  FROM (VALUES
    ('cat_board_books', 1, 1, 'visible', true, false, 'Best for lift the flap zoo', 'Dear Zoo Board Book', 'Campbell Books', 'Penguin UK', 'https://www.penguin.co.uk/books/56692/dear-zoo-by-campbell-rod/9781409306290', NULL, 'See Penguin', 'in_stock', 'Board book; baby and toddler', 'A sturdy board book with lift the flaps revealing animals, perfect for shared pointing and short reading spells on the sofa.', 'Flaps turn listening into a reach on the sofa. At seven to nine months the game is lift, look and laugh together. Lift the flap zoo when you want a classic join in book that survives chewing at the corners.', 'Interactive animal flaps.', 'Supervise flaps.', 'buy', true, 'Classic gift.', 'One Dear Zoo is enough.', 'Board book supervise.', 'strong', ARRAY['https://www.penguin.co.uk/books/56692/dear-zoo-by-campbell-rod/9781409306290']::text[], 'none'),
    ('cat_board_books', 2, 2, 'visible', true, true, 'Best for touchy puppy pages', 'That''s not my puppy...', 'Usborne', 'Penguin UK', 'https://www.penguin.co.uk/books/56691/thats-not-my-puppy-by-watt-fiona/9780746066621', NULL, 'See Penguin', 'in_stock', 'Touchy-feely board book', 'A touchy feely board book with textured patches on each puppy page, inviting hands to explore while you name what they feel.', 'Textures give mouthing hands a job on the page while you read. You still lead the words in a soft voice. Touchy puppy pages when flaps feel too fiddly and you want soft patches instead of cardboard doors. Leave That''s not my puppy.. out where they can find it again tomorrow.', 'Touch and listen.', 'Patches wear with chewing.', 'buy', true, 'Series gift.', 'One puppy is enough to start the series.', 'Supervise textures.', 'strong', ARRAY['https://www.penguin.co.uk/books/56691/thats-not-my-puppy-by-watt-fiona/9780746066621']::text[], 'none'),
    ('cat_board_books', 3, 3, 'visible', true, true, 'Best for day in pictures', 'Peepo!', 'Puffin', 'Penguin UK', 'https://www.penguin.co.uk/books/108295/peepo-by-ahlberg-allan-and-janet/9780141337418', NULL, 'See Penguin', 'in_stock', 'Board / picture book for babies', 'A classic day in the life board book with peep holes through the pages, made for shared pointing and short join in refrains on the sofa.', 'Peep holes reward looking ahead while you name the ordinary day together. It is still a sofa book, not a teaching session. Day in pictures when animal flaps are already owned and you want home scenes instead. One short go with Peepo! is enough before you tidy away.', 'Peek through pages.', 'Some editions paper; prefer board.', 'buy', true, 'Classic gift.', 'Prefer board edition.', 'Supervise.', 'strong', ARRAY['https://www.penguin.co.uk/books/108295/peepo-by-ahlberg-allan-and-janet/9780141337418']::text[], 'none'),
    ('cat_board_books', 4, 4, 'visible', true, true, 'Best for hide and seek flaps', 'Where''s Spot?', 'Warne', 'Penguin UK', 'https://www.penguin.co.uk/books/122792/wheres-spot-by-hill-eric/9780723263661', NULL, 'See Penguin', 'in_stock', 'Lift the flap board book', 'A lift the flap board book hunting for Spot behind doors and curtains, ideal for short hide and seek reading rounds.', 'Hide and seek on the page matches the scarf games on the floor. Keep rounds short and playful. Hide and seek flaps when Dear Zoo is already chewed and you want another flap language for evenings. Stay nearby while they try Where''s Spot?, then stop on a good note.', 'Flap hide and seek.', 'Flaps tear with heavy chewing.', 'buy', true, 'Series gift.', 'One Spot starter is enough.', 'Supervise flaps.', 'strong', ARRAY['https://www.penguin.co.uk/books/122792/wheres-spot-by-hill-eric/9780723263661']::text[], 'none'),
    ('cat_board_books', 5, 5, 'visible', true, true, 'Best for high contrast faces', 'Baby Touch Faces Black and White Book', 'Ladybird', 'Penguin UK', 'https://www.penguin.co.uk/books/313409/baby-touch-faces-a-black-and-white-book-by-ladybird/9780241391723', NULL, 'See Penguin', 'in_stock', 'Black and white board book', 'A high contrast board book of faces, sized for short looking spells and finger tracing on black and white pages.', 'Faces still stop a restless sit on your lap. High contrast keeps the page simple when colour books feel crowded. High contrast faces when you want a quiet looking book between noisier flap sessions. Put Baby Touch Faces Black where you both sit most evenings so the invite is easy.', 'Face looking.', 'Simple pages; pair with talk.', 'buy', true, 'Calm gift.', 'One faces book is enough to start.', 'Board book.', 'strong', ARRAY['https://www.penguin.co.uk/books/313409/baby-touch-faces-a-black-and-white-book-by-ladybird/9780241391723']::text[], 'none'),
    ('cat_board_books', 6, 6, 'visible', true, true, 'Best for photo face pages', 'Hello Baby Faces', 'Priddy', 'Priddy Books', 'https://priddybooks.com/gb/books/hello-baby-faces/', NULL, 'See Priddy', 'in_stock', 'Baby board book', 'A board book of baby faces in clear photos, made for pointing, naming and short shared looking on the sofa.', 'Photos feel closer to real faces than drawings on the page. Keep naming soft and short. Photo face pages when high contrast Ladybird is done and you want real expressions next on the sofa. Put Hello Baby Faces where you both sit most evenings so the invite is easy.', 'Photo faces.', 'Board edges.', 'buy', true, 'Faces gift.', 'Pairs with Ladybird faces; different look.', 'Supervise.', 'good', ARRAY['https://priddybooks.com/gb/books/hello-baby-faces/']::text[], 'none'),
    ('cat_board_books', 7, 7, 'visible', true, true, 'Best for first focus faces', 'Baby Touch Faces First Focus', 'Ladybird', 'Penguin UK', 'https://www.penguin.co.uk/books/289967/faces-baby-touch-first-focus-by-ladybird/9780241243251', NULL, 'See retailer', 'in_stock', 'Board book baby toddler', 'A compact Ladybird faces board book with high contrast looking pages, sized for short shared face pointing on the sofa.', 'A second faces book keeps looking practice fresh after black and white Ladybird. Keep rounds short and soft. First focus faces when you want another quiet face book without marketplace cart friction on a weeknight. Let them finish the turn with Baby Touch Faces First, then close the activity kindly.', 'Book peekaboo.', 'Die cuts can tear.', 'buy', true, 'Artful gift.', 'Nice variety beside classics.', 'Supervise die cuts.', 'good', ARRAY['https://www.penguin.co.uk/books/289967/faces-baby-touch-first-focus-by-ladybird/9780241243251']::text[], 'none'),
    ('cat_board_books', 8, 8, 'visible', true, true, 'Best for peep hole backup', 'Peepo! (Penguin board listing)', 'Puffin', 'Penguin UK', 'https://www.penguin.co.uk/books/108295/peepo-by-ahlberg-allan-and-janet/9780141337418', NULL, 'See retailer', 'in_stock', 'Board book baby toddler', 'A Penguin board listing of Peepo for when you want the day in pictures classic from the publisher page with peep holes through the pages.', 'Same peep holes as rank three with a publisher cart that stays buyable. Buy the title once only. Peep hole backup when specialist carts return errors and you still want Peepo on the sofa tonight. If interest fades, pack Peepo! away and try again another day.', 'Point and name.', 'Confirm live ASIN title.', 'buy', true, 'Words gift.', 'Usborne second title after puppy.', 'Board book.', 'good', ARRAY['https://www.penguin.co.uk/books/108295/peepo-by-ahlberg-allan-and-janet/9780141337418']::text[], 'check_url'),
    ('cat_board_books', 9, 9, 'visible', true, true, 'Best for publisher Dear Zoo', 'Dear Zoo (Penguin board)', 'Campbell Books', 'Penguin UK', 'https://www.penguin.co.uk/books/56692/dear-zoo-by-campbell-rod/9781409306290', NULL, 'See retailer', 'in_stock', 'Board book baby toddler', 'The Penguin publisher board listing for Dear Zoo, used when you want the flap classic from the imprint page rather than a marketplace cart.', 'Same flaps as rank one with a publisher cart. Buy the title once only. Publisher Dear Zoo when Amazon is blocked and you still want the classic on the shelf today. Use Dear Zoo as the second option when the first favourite is already out.', 'Availability backup of #1.', 'Do not buy twice.', 'buy', true, 'Same classic.', 'Skip if rank 1 owned.', 'Board book.', 'good', ARRAY['https://www.penguin.co.uk/books/56692/dear-zoo-by-campbell-rod/9781409306290']::text[], 'none'),
    ('cat_board_books', 10, 10, 'visible', true, true, 'Best for publisher Spot', 'Where''s Spot? (Penguin board)', 'Warne', 'Penguin UK', 'https://www.penguin.co.uk/books/122792/wheres-spot-by-hill-eric/9780723263661', NULL, 'See retailer', 'in_stock', 'Board book baby toddler', 'The Penguin publisher board listing for Where Spot, for easy UK buying of the hide and seek flap classic. for shared play on the sofa.', 'Same hide and seek flaps as rank four. Buy the title once only. Publisher Spot when marketplace carts fail and you still want Spot on the shelf today. Keep the session short with Where''s Spot? so it stays a friendly invite.', 'Availability backup of #4.', 'Do not double buy.', 'buy', true, 'Same classic.', 'Skip if rank 4 owned.', 'Board book.', 'good', ARRAY['https://www.penguin.co.uk/books/122792/wheres-spot-by-hill-eric/9780723263661']::text[], 'none'),
    ('cat_highchair', 1, 1, 'visible', true, false, 'Best for budget wipe clean', 'IKEA ANTILOP Highchair with tray', 'IKEA', 'IKEA UK', 'https://www.ikea.com/gb/en/p/antilop-highchair-with-tray-white-white-s79597515/', NULL, '£19.00', 'in_stock', 'Suitable when child can sit unaided', 'A simple plastic highchair with a detachable tray and metal legs, made for upright first tastes in small kitchens without a big furniture spend.', 'First tastes need upright support more than furniture theatre. ANTILOP wipes clean and stores without drama in a small flat. Budget wipe clean when you want a working chair for weaning without locking into a wooden chair system just yet.', 'Upright first tastes.', 'Tray fit varies; check harness.', 'buy', false, NULL, 'Parent buy; check if grandparents already have one.', 'Use harness; sitting unaided only.', 'strong', ARRAY['https://www.ikea.com/gb/en/p/antilop-highchair-with-tray-white-white-s79597515/']::text[], 'none'),
    ('cat_highchair', 2, 2, 'visible', true, true, 'Best for compact fold storage', 'Joie Mimzy Snacker Highchair', 'Joie', 'Boots UK', 'https://www.boots.com/joie-mimzy-snacker-highchair-abc-charcoal-10220635', NULL, '£49.90', 'in_stock', 'From about 6 months when sitting unaided', 'A lightweight folding highchair with a large tray, wipeable pad and five point harness, made for upright meals in smaller kitchens.', 'Mealtimes are moving to the table, and a chair that folds away helps in a small kitchen. The tray and harness keep upright eating practical day to day. Compact fold storage when ANTILOP feels too permanent for your hallway space.', 'Upright feeding with storage.', 'Check harness fit often.', 'buy', false, NULL, 'Parent buy.', 'Harness always.', 'strong', ARRAY['https://www.boots.com/joie-mimzy-snacker-highchair-abc-charcoal-10220635']::text[], 'none'),
    ('cat_highchair', 3, 3, 'visible', true, true, 'Best for long life wood', 'Stokke Tripp Trapp High Chair', 'Stokke', 'Boots UK', 'https://www.boots.com/stokke-tripp-trapp-high-chair-natural-10116308', NULL, '£199.00', 'in_stock', 'With baby set when sitting; grows to teen', 'An adjustable wooden chair that grows from baby set through toddler years, bringing the child to the table without a bulky plastic frame.', 'If you want one chair for years, wood that adjusts earns the spend. First tastes still need the baby set and careful harness use. Long life wood when you will keep the chair past weaning and storage is not the main pain.', 'Table height for years.', 'Baby set often sold separately; confirm bundle.', 'buy', false, NULL, 'High spend; check baby set.', 'Correct baby set and harness.', 'strong', ARRAY['https://www.boots.com/stokke-tripp-trapp-high-chair-natural-10116308']::text[], 'check_url'),
    ('cat_highchair', 4, 4, 'visible', true, true, 'Best for patterned tray chair', 'Cosatto Noodle 0 Highchair Mister Fox', 'Cosatto', 'Boots UK', 'https://www.boots.com/cosatto-noodle-0-highchair-mister-fox-10285197', NULL, 'See Boots', 'in_stock', 'From birth recline to toddler', 'A patterned multi position highchair that reclines for younger babies and sits upright for first tastes, with a tray and harness.', 'Some homes want one chair from newborn recline into weaning without swapping frames midstream. Patterns are taste, not safety. Patterned tray chair when you need recline history and upright weaning in the same frame for first tastes. Stay nearby while they try Cosatto Noodle 0 Highchair, then stop on a good note.', 'Multi mode feeding seat.', 'Only upright when sitting ready.', 'buy', false, NULL, 'Parent buy.', 'Upright only when sitting unaided for solids.', 'good', ARRAY['https://www.boots.com/cosatto-noodle-0-highchair-mister-fox-10285197']::text[], 'none'),
    ('cat_highchair', 5, 5, 'visible', true, true, 'Best for travel booster seat', 'Chicco Pocket Snack Booster Seat', 'Chicco', 'Chicco UK', 'https://www.chicco.co.uk/pocket-snack-booster-seat-dark-grey.html', NULL, 'See Chicco', 'in_stock', 'When sitting unaided', 'A compact booster that straps to an adult chair and folds flat, for upright snacks away from home when the full highchair stays put.', 'Grandparent kitchens and cafes need upright support without carting a full frame. A booster is not a first highchair, but it solves travel days. Travel booster seat when home already has ANTILOP or Mimzy and days out are the daily friction.', 'Away-from-home upright.', 'Needs a stable adult chair.', 'buy', false, NULL, 'Companion to a home chair.', 'Install per instructions.', 'good', ARRAY['https://www.chicco.co.uk/pocket-snack-booster-seat-dark-grey.html']::text[], 'none'),
    ('cat_peekaboo_scarf', 1, 1, 'visible', true, false, 'Best for rainbow peekaboo', 'Baby Sensory Scarves Age 0+ UKCA (set of 7)', 'The Little Sensory Bag Co.', 'The Little Sensory Bag Co.', 'https://www.thelittlesensorybagco.co.uk/product-page/baby-sensory-scarves-age-0', NULL, 'From £2.25 each / set pricing', 'in_stock', 'UKCA Safety Tested as Toys from 0+', 'A set of seven rainbow organza scarves with firm hems, UKCA tested from birth, for waving, covering toys and simple peekaboo on the floor.', 'Hidden toys are a bigger game at seven to nine months, and a light scarf is kinder than a thick blanket over the face. Firm hems help when the cloth ends up wet. Rainbow peekaboo when you want one cloth language for hide and find.', 'Peekaboo cloth play.', 'Always supervise; never leave draped unsupervised.', 'buy', true, 'Light gift; easy to post.', 'One set is enough.', 'Adult supervised peekaboo only.', 'specialist', ARRAY[]::text[], 'none'),
    ('cat_peekaboo_scarf', 2, 2, 'visible', true, true, 'Best for a giant hide cloth', 'TickiT Giant Sensory Scarf', 'TickiT', 'The Little Sensory Bag Co.', 'https://www.thelittlesensorybagco.co.uk/product-page/tickit-giant-sensory-scarf', NULL, '£4.99', 'in_stock', 'Adult supervised sensory cloth', 'A large organza sensory scarf in rainbow colours, sized for adult led peekaboo, tent play and waving games with a sitting baby.', 'A bigger cloth turns peekaboo into a shared floor game you control. You lift and lower; they reach and laugh together. Giant hide cloth when the small squares feel fiddly in your hands and you want one clear hide sheet for the room.', 'Adult led peekaboo.', 'Strict supervision.', 'buy', true, 'Pair with a soft toy to hide.', 'One giant scarf is enough.', 'Adult supervision.', 'specialist', ARRAY[]::text[], 'check_age_fit'),
    ('cat_peekaboo_scarf', 3, 3, 'visible', true, true, 'Best for classroom colour set', 'Little Baby Company Sensory Scarf Set', 'Little Baby Company', 'Little Baby Company', 'https://thelittlebabycompany.co.uk/products/sensory-scarf-set', NULL, 'See site', 'in_stock', 'Sensory play; supervise', 'A multi colour sensory scarf set sold by a UK baby specialist, for waving, covering toys and short peekaboo rounds on the floor.', 'A second specialist set gives colour variety without relying on Argos listings that block bots. Light fabric still beats a heavy blanket for face games on the sofa. Classroom colour set when you want a different pack size from the UKCA seven.', 'Colour scarf peekaboo.', 'Confirm pack count on page.', 'buy', true, 'Specialist gift.', 'Skip if you already bought the UKCA seven.', 'Supervise.', 'specialist', ARRAY[]::text[], 'none'),
    ('cat_peekaboo_scarf', 4, 4, 'visible', true, true, 'Best for large dance pack', 'Multicoloured Sensory Dance Scarves 10pk', 'TTS', 'TTS Group', 'https://www.tts-group.co.uk/multicoloured-sensory-dance-scarves-l60xw60cm-10pk/1053766.html', NULL, '£13.19 inc VAT', 'in_stock', 'Early years movement resource', 'A ten pack of multicoloured 60cm dance scarves from TTS, light enough for adult led peekaboo and waving games with a sitting baby.', 'Education suppliers stock sturdy light scarves in bulk for movement games. You still lead the hide and reveal with a sitting baby. Large dance pack when you want spare colours for siblings or the changing bag without another boutique set.', 'Bulk light scarves.', 'Marketed for movement; keep adult led with babies.', 'buy', true, 'Practical pack.', 'Plenty of scarves; one pack is enough.', 'Supervise closely.', 'specialist', ARRAY[]::text[], 'check_age_fit'),
    ('cat_peekaboo_scarf', 5, 5, 'visible', true, true, 'Best for bring back muslin', 'Bring back a clean muslin for peekaboo', 'Bring back out', 'Home cupboard', 'https://www.thelittlesensorybagco.co.uk/product-page/baby-sensory-scarves-age-0', NULL, '£0 if you already own muslins', 'in_stock', 'Household muslin; adult supervised', 'A clean muslin from the cupboard used as a light hide cloth for short peekaboo rounds, before you buy another specialist scarf set.', 'Ownership risk is high for scarves at this age. A muslin you already wash weekly can start the game tonight on the sofa. Bring back muslin when the cupboard already holds soft cloths and you want to test peekaboo before another purchase.', 'Zero-buy peekaboo start.', 'Never leave draped unsupervised; lighter scarves still kinder long term.', 'hold_off', false, NULL, 'Prefer before a third scarf pack.', 'Adult supervised only; keep airways clear.', 'specialist', ARRAY[]::text[], 'none'),
    ('cat_reach_grab_toys', 1, 1, 'visible', true, false, 'Best for finger hole grip', 'Bright Starts Oball Classic Easy-Grasp Toy', 'Bright Starts', 'Boots UK', 'https://www.boots.com/baby-einstein-oball-classic-easy-grasp-toy-10307276', NULL, '£5.00', 'in_stock', '0 months+', 'A light flexible ball covered in soft finger holes, sized for a sitting baby who stretches to grab, shake and mouth during short floor play.', 'Sitting upright changes the reach game. Soft finger holes mean a stretch can become a hold without perfect aim. The ball rolls gently when tipped, so floor play stays playful rather than frustrating. Finger hole grip for short sits on the mat.', 'Purposeful reach while sitting.', 'Wipe clean; supervise mouthing.', 'buy', true, 'Small known gift for the mat.', 'Skip a second Oball if you already have one.', 'Supervised play only.', 'strong', ARRAY['https://www.boots.com/baby-einstein-oball-classic-easy-grasp-toy-10307276']::text[], 'none'),
    ('cat_reach_grab_toys', 2, 2, 'visible', true, true, 'Best for textured clip play', 'Lamaze Freddie the Firefly Activity Toy', 'Lamaze', 'Boots UK', 'https://www.boots.com/lamaze-freddie-the-firefly-activity-toy-10095128', NULL, '£14.99', 'in_stock', 'From birth', 'A soft firefly with rings, textures and a clip, made for grabbing on the mat or clipping near a sitting baby during short reach sessions.', 'Seven to nine months is about bringing interesting textures into reach while sitting. Freddie hangs or sits close, so a stretch lands on rings and crinkle rather than empty air. Textured clip play when the mat needs more than a plain ball.', 'Reach with textures.', 'Check clip security.', 'buy', true, 'Familiar gift shape.', 'One Freddie is enough.', 'Supervise clips.', 'strong', ARRAY['https://www.boots.com/lamaze-freddie-the-firefly-activity-toy-10095128']::text[], 'none'),
    ('cat_reach_grab_toys', 3, 3, 'visible', true, true, 'Best for ring stack reach', 'Fisher-Price Rock-a-Stack Rings', 'Fisher-Price', 'Boots UK', 'https://www.boots.com/fisher-price-rock-a-stack-10024012', NULL, '£8.00', 'in_stock', '6 months+', 'A classic rocking base with colourful rings to grasp, mouth and place, suited to sitting babies practising hand to hand transfers.', 'Rings give a clear target for a sitting stretch and a wobbly base that answers a bat. You are not chasing perfect towers yet; you are chasing hold and place. Ring stack reach when they are ready for something that stays put on the mat.', 'Grasp and place rings.', 'Supervise small mouthing.', 'buy', true, 'Classic gift.', 'One set is enough.', 'Age 6m+ on listing.', 'strong', ARRAY['https://www.boots.com/fisher-price-rock-a-stack-10024012']::text[], 'none'),
    ('cat_reach_grab_toys', 4, 4, 'visible', true, true, 'Best for silicone monkey grip', 'Matchstick Monkey Original Teething Toy', 'Matchstick Monkey', 'Boots UK', 'https://www.boots.com/matchstick-monkey-original-teething-toy-grey-10207240', NULL, '£10.99', 'in_stock', '3 months+', 'A silicone monkey teether with a textured face and easy tail grip, made for sitting hands to grab, shake and gum during short floor play.', 'When the ball rolls away, a monkey that stays in the hand helps. Soft silicone invites mouthing after the grab at this age. Silicone monkey grip when you want one object that is both a reach target and a chew on the mat.', 'Grab then gum.', 'Clean regularly.', 'buy', true, 'Compact gift.', 'Skip if already buying for the teether card.', 'Supervise.', 'strong', ARRAY['https://www.boots.com/matchstick-monkey-original-teething-toy-grey-10207240']::text[], 'none'),
    ('cat_reach_grab_toys', 5, 5, 'visible', true, true, 'Best for take along rattle', 'Bright Starts Having a Ball Take Along Rattle', 'Bright Starts', 'Smyths Toys', 'https://www.smythstoys.com/uk/en-gb/toys/baby-and-preschool/baby-toys/bright-starts-having-a-ball-take-along-rattle/p/179219', NULL, '£7.00', 'in_stock', '3 months+', 'A bright easy grip rattle ball with beads inside, sized for sitting hands to shake on the go between mat sessions.', 'Not every reach happens on the mat. A light rattle that survives the bag keeps the same grab job in the café queue. Take along rattle when home already has an Oball and you want sound without another soft ball.', 'Portable shake and grab.', 'Volume can be sharp indoors.', 'buy', true, 'Small add-on.', 'Bright Starts already appears once above; this is a different job.', 'Supervise.', 'good', ARRAY['https://www.smythstoys.com/uk/en-gb/toys/baby-and-preschool/baby-toys/bright-starts-having-a-ball-take-along-rattle/p/179219']::text[], 'none'),
    ('cat_safety_gates', 1, 1, 'visible', true, false, 'Best for easy pressure fit', 'Munchkin Lindam Easy Fit Plus Deluxe Safety Gate', 'Munchkin Lindam', 'Boots UK', 'https://www.boots.com/munchkin-lindam-easy-fit-plus-deluxe-stair-gate-10220327', NULL, 'See Boots', 'in_stock', 'Suitable for children up to 24 months (EN 1930)', 'A pressure fit stair gate with one hand opening, made to close doorways before crawling turns into exploring every room.', 'Mobility is arriving and rooms suddenly look risky. A gate you can open with one hand while carrying a baby earns daily use. Easy pressure fit when you need a doorway closed this week without drilling yet. Keep Munchkin Lindam Easy Fit in easy reach for the next short try.', 'Doorway control.', 'Follow wall cup guidance on listing.', 'buy', false, NULL, 'Parent buy; measure opening.', 'Install per EN guidance; never on stairs incorrectly.', 'strong', ARRAY['https://www.boots.com/munchkin-lindam-easy-fit-plus-deluxe-stair-gate-10220327']::text[], 'none'),
    ('cat_safety_gates', 2, 2, 'visible', true, true, 'Best for true pressure indicator', 'BabyDan Premier True Pressure Fit Safety Gate White', 'BabyDan', 'Boots UK', 'https://www.boots.com/babydan-premier-true-pressure-fit-safety-gate-white-10220688', NULL, 'See Boots', 'in_stock', 'EN 1930; children up to 24 months', 'A BabyDan Premier pressure gate with pressure indicators, designed to fit without wall cups on suitable openings within the stated width.', 'Pressure indicators take guesswork out of a tight fit on the posts. Measure twice before you buy extensions. True pressure indicator when you want clear install feedback and a Premier frame you can buy at Boots. Leave BabyDan Premier True Pressure out where they can find it again tomorrow.', 'Indicator-led install.', 'Width range matters; extensions extra.', 'buy', false, NULL, 'Measure opening.', 'EN install rules.', 'strong', ARRAY['https://www.boots.com/babydan-premier-true-pressure-fit-safety-gate-white-10220688']::text[], 'none'),
    ('cat_safety_gates', 3, 3, 'visible', true, true, 'Best for auto close latch', 'Lindam Sure Shut Orto Safety Gate', 'Lindam', 'Boots UK', 'https://www.boots.com/lindam-sure-shut-orto-safety-gate-10207295', NULL, 'See Boots', 'in_stock', 'EN 1930 up to 24 months', 'A pressure fit gate with auto close behaviour, helping the latch finish when hands are full during busy hallway days.', 'Gates that only half latch fail quietly in busy hallways. Auto close helps when you are carrying laundry and a baby. Auto close latch when doorway traffic is constant and you forget the final push. One short go with Lindam Sure Shut Orto is enough before you tidy away.', 'Hands-full latching.', 'Still check closed every time.', 'buy', false, NULL, 'Parent buy.', 'Verify latch each use.', 'good', ARRAY['https://www.boots.com/lindam-sure-shut-orto-safety-gate-10207295']::text[], 'none'),
    ('cat_safety_gates', 4, 4, 'visible', true, true, 'Best for wider openings', 'Dreambaby Ava Extra Tall Safety Gate White', 'Dreambaby', 'Boots UK', 'https://www.boots.com/dreambaby-ava-extra-tall-safety-gate-white-10307280', NULL, 'See Boots', 'in_stock', 'EN safety gate guidance', 'An extra tall safety gate aimed at wider openings, for homes where a standard gate leaves a gap or feels too low.', 'Not every doorway matches a standard seventy five centimetre gate. Tall and wide options stop the endless gap hunt. Wider openings when your tape measure already failed a Premier base width at home. Stay nearby while they try Dreambaby Ava Extra Tall, then stop on a good note.', 'Non-standard openings.', 'Confirm exact width on PDP.', 'buy', false, NULL, 'Measure carefully.', 'Correct install width.', 'good', ARRAY['https://www.boots.com/dreambaby-ava-extra-tall-safety-gate-white-10307280']::text[], 'check_url'),
    ('cat_safety_gates', 5, 5, 'visible', true, true, 'Best for specialist gate shop', 'BabyDan Premier True Pressure Fit Gate Silver', 'BabyDan', 'Safetots', 'https://www.safetots.co.uk/babydan-premier-true-pressure-fit-gate-silver-79-6cm-86-5cm.html', NULL, '£52.90', 'in_stock', 'EN 1930 pressure gate', 'A BabyDan Premier silver pressure gate sold via a UK specialist with a clear width band including extension, for measured openings.', 'Specialist shops list width bands plainly on the product page. That helps when Boots colourways are out of stock. Specialist gate shop when you already trust Premier and need a specific centimetre pack. Put BabyDan Premier True Pressure where you both sit most evenings so the invite is easy.', 'Width-specific Premier.', 'Second BabyDan in Top 5.', 'buy', false, NULL, 'Same family as rank 2; different width/colour pack.', 'Measure opening.', 'good', ARRAY['https://www.safetots.co.uk/babydan-premier-true-pressure-fit-gate-silver-79-6cm-86-5cm.html']::text[], 'none'),
    ('cat_stacking_nesting_cups', 1, 1, 'visible', true, false, 'Best for classic nest stack', 'Munchkin Stacking Cups', 'Munchkin', 'Boots UK', 'https://www.boots.com/munchkin-stacking-cups-10116320', NULL, '£6.00', 'in_stock', '6 months+', 'A set of colourful plastic cups that nest for storage and stack for knock down play, sized for sitting hands practising in and out.', 'In and out is the new job on the mat. Cups that nest cleanly forgive wobbly towers and survive bath or floor play. Classic nest stack when you want one set that packs small and still invites pour and place together.', 'Nest and stack.', 'Supervise mouthing.', 'buy', true, 'Easy gift.', 'One cup set is enough.', '6m+ mark.', 'strong', ARRAY['https://www.boots.com/munchkin-stacking-cups-10116320']::text[], 'none'),
    ('cat_stacking_nesting_cups', 2, 2, 'visible', true, true, 'Best for bath pour stack', 'Munchkin Caterpillar Spillers Stacking Cups', 'Munchkin', 'Boots UK', 'https://www.boots.com/munchkin-caterpillar-spillers-bath-toy-10095140', NULL, '£8.00', 'in_stock', '9 months+', 'Seven numbered cups that link into a caterpillar, stack into a tower and pour water, bridging mat nesting into bath play.', 'Pour holes turn stacking into water play without a new toy language. Nine months on the listing sits at the top of this band. Bath pour stack when mat cups already exist and bath is the next place for in and out.', 'Stack and pour.', '9m+ mark - late in band.', 'buy', true, 'Bath gift.', 'Second Munchkin; different job from plain cups.', 'Bath supervise.', 'strong', ARRAY['https://www.boots.com/munchkin-caterpillar-spillers-bath-toy-10095140']::text[], 'check_age_fit'),
    ('cat_stacking_nesting_cups', 3, 3, 'visible', true, true, 'Best for early ring towers', 'Fisher-Price Rock-a-Stack Rings', 'Fisher-Price', 'Boots UK', 'https://www.boots.com/fisher-price-rock-a-stack-10024012', NULL, '£12.00', 'in_stock', '6 months+', 'A rocking ring stacker that teaches place and order before free cups, with a base that stays put on the mat.', 'Cups wander; a ring base stays put on the mat. Early place practice still feeds the same in and out idea. Early ring towers when free cups keep rolling under the sofa and you want a fixed stack target nearby.', 'Simple sturdy stack.', 'Confirm live title on Amazon.', 'buy', true, 'Material-led gift.', 'Skip duplicate cup sets.', 'Supervise.', 'good', ARRAY['https://www.boots.com/fisher-price-rock-a-stack-10024012']::text[], 'check_url'),
    ('cat_stacking_nesting_cups', 4, 4, 'visible', true, true, 'Best for easy grip ball', 'Bright Starts Oball Classic Easy-Grasp Toy', 'Bright Starts', 'Boots UK', 'https://www.boots.com/baby-einstein-oball-classic-easy-grasp-toy-10307276', NULL, '£16.00', 'in_stock', '6 months+', 'A light flexible ball with finger holes that sitting hands can grab during early place play beside nesting cups on the mat.', 'Cups need a partner object to put in and take out. Soft holes forgive clumsy aim. Easy grip ball when cup stacking is new and you want a second object that stays kind to gums. Stay nearby while they try Bright Starts Oball Classic, then stop on a good note.', 'Chew-friendly cups.', 'Pricier than plastic.', 'buy', true, 'Premium soft gift.', 'One silicone set is enough.', 'Food grade claim on listing.', 'good', ARRAY['https://www.boots.com/baby-einstein-oball-classic-easy-grasp-toy-10307276']::text[], 'none'),
    ('cat_stacking_nesting_cups', 5, 5, 'visible', true, true, 'Best for take along rattle', 'Bright Starts Having a Ball Take Along Rattle', 'Bright Starts', 'Smyths Toys', 'https://www.smythstoys.com/uk/en-gb/toys/baby-and-preschool/baby-toys/bright-starts-having-a-ball-take-along-rattle/p/179219', NULL, '£8.00', 'in_stock', '6 months+', 'A bright easy grip rattle ball with beads inside, sized for sitting hands to shake beside cup play on the go.', 'Not every in and out happens on the mat. A light rattle that survives the bag keeps grab practice between rooms. Take along rattle when home already has cups and you want sound without another nest set. Put Bright Starts Having a where you both sit most evenings so the invite is easy.', 'Ordered place practice.', 'Rings not cups - adjacent.', 'buy', true, 'Classic gift.', 'Adjacent stacking; prefer cups first.', '6m+.', 'strong', ARRAY['https://www.smythstoys.com/uk/en-gb/toys/baby-and-preschool/baby-toys/bright-starts-having-a-ball-take-along-rattle/p/179219']::text[], 'none'),
    ('cat_teethers', 1, 1, 'visible', true, false, 'Best for natural rubber classic', 'Sophie la Girafe Teething Toy', 'Sophie La Girafe', 'Boots UK', 'https://www.boots.com/sophie-la-girafe-teething-toy-10024008', NULL, '£15.00', 'in_stock', 'From birth', 'A soft natural rubber giraffe teether with squeak and easy limbs to gum, long used for early mouthing while sitting.', 'Mouthing is how they explore objects now. Soft limbs give more than one gum target without hard plastic edges. Natural rubber classic when you want a known chew shape that survives the bag and the highchair tray. Keep Sophie la Girafe Teething in easy reach for the next short try.', 'Primary gum chew.', 'Replace if damaged.', 'buy', true, 'Classic gift.', 'One Sophie is enough.', 'Supervise mouthing.', 'strong', ARRAY['https://www.boots.com/sophie-la-girafe-teething-toy-10024008']::text[], 'none'),
    ('cat_teethers', 2, 2, 'visible', true, true, 'Best for silicone monkey grip', 'Matchstick Monkey Original Teething Toy', 'Matchstick Monkey', 'Boots UK', 'https://www.boots.com/matchstick-monkey-original-teething-toy-grey-10207240', NULL, '£10.99', 'in_stock', '3 months+', 'A silicone monkey teether with a textured face and easy tail grip, made for gumming during sitting and tray time.', 'Silicone holds cold better from the fridge and cleans simply after sticky gums. The face texture gives gums a map. Silicone monkey grip when rubber Sophie is already in the bag and you want a washable second chew. Leave Matchstick Monkey Original Teething out where they can find it again tomorrow.', 'Silicone gumming.', 'Avoid extreme heat.', 'buy', true, 'UK favourite gift.', 'One monkey is enough.', '3m+ mark.', 'strong', ARRAY['https://www.boots.com/matchstick-monkey-original-teething-toy-grey-10207240']::text[], 'none'),
    ('cat_teethers', 3, 3, 'visible', true, true, 'Best for cool gel keys', 'Nuby Ice Gel Teether Keys', 'Nuby', 'Boots UK', 'https://www.boots.com/nuby-ice-gel-teether-keys-10024020', NULL, '£6.00', 'in_stock', '3 months+', 'A keyring style gel teether you chill in the fridge, giving cool gumming with several shapes for sitting hands to choose.', 'Cool gel is a different sensation from rubber or silicone for sore gums. Keys give a choice of edges in one hand. Cool gel keys when gums are angry and you want a fridge option beside the everyday chew. One short go with Nuby Ice Gel Teether is enough before you tidy away.', 'Chilled gumming.', 'Follow chill guidance; never freeze solid if listing warns.', 'buy', true, 'Small add-on.', 'Handy second chew.', 'Supervise gel teethers.', 'good', ARRAY['https://www.boots.com/nuby-ice-gel-teether-keys-10024020']::text[], 'none'),
    ('cat_teethers', 4, 4, 'visible', true, true, 'Best for simple rubber ring', 'Natursutten Original Rubber Teether', 'Natursutten', 'Boots UK', 'https://www.boots.com/natursutten-original-rubber-teether-10220660', NULL, '£8.00', 'in_stock', '0 months+', 'A simple natural rubber teething ring without characters, easy to hold and gum during quiet sitting spells on the sofa or mat.', 'Not every chew needs a face printed on it. A plain ring is quiet in the bag and honest in the hand. Simple rubber ring when character teethers are already plentiful and you want one quiet shape. Stay nearby while they try Natursutten Original Rubber Teether, then stop on a good note.', 'Minimal rubber chew.', 'Replace if bitten through.', 'buy', true, 'Quiet gift.', 'Minimalist option.', 'Supervise.', 'good', ARRAY['https://www.boots.com/natursutten-original-rubber-teether-10220660']::text[], 'none'),
    ('cat_teethers', 5, 5, 'visible', true, true, 'Best for chew safe grab ball', 'Bright Starts Oball Classic Easy-Grasp Toy', 'Bright Starts', 'Boots UK', 'https://www.boots.com/baby-einstein-oball-classic-easy-grasp-toy-10307276', NULL, '£12.00', 'in_stock', '0 months+', 'A light flexible ball covered in soft finger holes, easy for sitting hands to grab and gum during short chew sessions on the mat.', 'Reach and chew often share the same minute on the mat. Soft holes reward the grab without a separate teether hunt. Chew safe grab ball when you want one object that covers both jobs during a short sit. Put Bright Starts Oball Classic where you both sit most evenings so the invite is easy.', 'Dual grab chew.', 'Also on reach card.', 'buy', true, 'Dual job gift.', 'Skip if already bought for reach.', 'Supervise.', 'strong', ARRAY['https://www.boots.com/baby-einstein-oball-classic-easy-grasp-toy-10307276']::text[], 'none'),
    ('cat_tummy_time_wobbler', 1, 1, 'visible', true, false, 'Best for rock then sit', 'Fisher-Price 2-in-1 Rockin'' Tummy Time Otter', 'Fisher-Price', 'Boots UK', 'https://www.boots.com/fisher-price-2-in-1-rockin-tummy-time-otter-10320720', NULL, '£18.00', 'in_stock', 'From birth', 'A plush otter with a soft book and mirror that rocks as a roly poly once baby sits, bridging tummy time into bat at play.', 'Short tummy bursts still help, but sitting changes the job now. The otter starts as a propped view and becomes a rock when they push up to sit. Rock then sit when you want one soft toy that keeps working after tummy time ends.', 'Tummy to sit wobble.', 'Supervise plush mouthing.', 'buy', true, 'Soft gift.', 'One otter is enough.', 'Supervised floor play.', 'good', ARRAY['https://www.boots.com/fisher-price-2-in-1-rockin-tummy-time-otter-10320720']::text[], 'none'),
    ('cat_tummy_time_wobbler', 2, 2, 'visible', true, true, 'Best for roll under chest', 'Red Kite Tummy Time Roller Woodland Walk', 'Red Kite', 'Boots UK', 'https://www.boots.com/red-kite-tummy-time-roller-woodland-walk-10285190', NULL, '£15.00', 'in_stock', '0 months+', 'A soft woodland roller with textures and crinkle, made to prop under the chest during short tummy sessions before sitting practice.', 'A roller gives a gentle lift without a hard wedge on the mat. At seven to nine months you still use short tummy bursts between sits. Roll under chest when you want a soft prop that also rattles interest when they push up.', 'Soft tummy prop.', 'Never leave unsupervised on tummy.', 'buy', true, 'Practical soft gift.', 'Skip if you already own a roller.', 'Adult present.', 'good', ARRAY['https://www.boots.com/red-kite-tummy-time-roller-woodland-walk-10285190']::text[], 'none'),
    ('cat_tummy_time_wobbler', 3, 3, 'visible', true, true, 'Best for wedge with toys', 'Fisher-Price Grow-with-Me Tummy Time Llama', 'Fisher-Price', 'Boots UK', 'https://www.boots.com/fisher-price-grow-with-me-tummy-time-llama-10307290', NULL, '£25.00', 'in_stock', 'From birth', 'A soft llama wedge with detachable toys that props the chest for tummy work and later becomes a sit beside play friend.', 'Some babies need a clearer lift than a roller. Detachable toys keep the view interesting when neck work is short. Wedge with toys when tummy time still needs scaffolding and you want pieces you can move to the sit mat later.', 'Supported tummy view.', 'Fisher-Price already one above; different job.', 'buy', true, 'Larger gift.', 'Bigger footprint; check storage.', 'Supervise wedge use.', 'good', ARRAY['https://www.boots.com/fisher-price-grow-with-me-tummy-time-llama-10307290']::text[], 'none'),
    ('cat_tummy_time_wobbler', 4, 4, 'visible', true, true, 'Best for animated peek friend', 'Gund Baby Animated Peek-A-Boo Bear Flora', 'Gund', 'Boots UK', 'https://www.boots.com/gund-baby-animated-peek-a-boo-bear-flora-10220650', NULL, '£22.00', 'in_stock', '0 months+', 'A soft animated bear that covers and reveals her eyes, inviting bat at play and shared peek turns on the floor beside tummy time.', 'Wobbly interest is not only rollers. An animated peek friend keeps them looking forward during short floor stretches. Animated peek friend when you want soft cause and effect beside tummy work without a hard toy on the living room mat.', 'Floor interest beside tummy.', 'Batteries; volume.', 'buy', true, 'Character gift.', 'One animated plush is enough.', 'Supervise electronics.', 'good', ARRAY['https://www.boots.com/gund-baby-animated-peek-a-boo-bear-flora-10220650']::text[], 'none'),
    ('cat_tummy_time_wobbler', 5, 5, 'visible', true, true, 'Best for propped mat view', 'Bright Starts Tummy Time Prop Mat', 'Bright Starts', 'Smyths Toys', 'https://www.smythstoys.com/uk/en-gb/toys/baby-and-preschool/baby-toys/bright-starts-tummy-time-prop-mat/p/191600', NULL, '£20.00', 'in_stock', '0 months+', 'A tummy time mat with a soft prop pillow and dangling toys, giving a clear view target during short floor sessions.', 'A dedicated mat keeps tummy work from spreading across the whole living room. Prop and toys give a reason to lift the head before the next sit. Propped mat view when you want a defined tummy station rather than another plush.', 'Defined tummy station.', 'Larger to store.', 'buy', true, 'Bigger gift.', 'Skip if floor space is tight.', 'Supervise tummy.', 'good', ARRAY['https://www.smythstoys.com/uk/en-gb/toys/baby-and-preschool/baby-toys/bright-starts-tummy-time-prop-mat/p/191600']::text[], 'none')
  ) AS v(source_category_entity_id, pick_rank, longlist_rank, status, is_visible, is_locked, best_for_tag, product_name, brand, retailer, product_url, image_url, price_text, stock_status, age_mark_on_listing, product_description, ember_verdict, why_it_fits, caveats, buy_borrow_hold_off, gift_suitable, gift_note, ownership_note, safety_notes, evidence_tier, evidence_sources, founder_qa_flag)
)
INSERT INTO public.pl_stage3_picks (
  age_band_id,
  category_type_id,
  source_category_entity_id,
  pick_rank,
  longlist_rank,
  status,
  is_visible,
  is_locked,
  best_for_tag,
  product_name,
  brand,
  retailer,
  product_url,
  image_url,
  price_text,
  stock_status,
  age_mark_on_listing,
  product_description,
  ember_verdict,
  why_it_fits,
  caveats,
  buy_borrow_hold_off,
  gift_suitable,
  gift_note,
  ownership_note,
  safety_notes,
  evidence_tier,
  evidence_sources,
  founder_qa_flag,
  research_payload
)
SELECT
  '6-9m',
  ct.id,
  r.source_category_entity_id,
  r.pick_rank,
  r.longlist_rank,
  r.status,
  r.is_visible,
  r.is_locked,
  r.best_for_tag,
  r.product_name,
  r.brand,
  r.retailer,
  r.product_url,
  r.image_url,
  r.price_text,
  r.stock_status,
  r.age_mark_on_listing,
  r.product_description,
  r.ember_verdict,
  r.why_it_fits,
  r.caveats,
  r.buy_borrow_hold_off,
  r.gift_suitable,
  r.gift_note,
  r.ownership_note,
  r.safety_notes,
  r.evidence_tier,
  r.evidence_sources,
  r.founder_qa_flag,
  jsonb_build_object(
    'bundle_schema_version', 'stage3_ingestion_bundle_v1',
    'bundle_generated_at', '2026-07-24T11:05:58.915Z',
    'research_schema_version', 'ember_picks_research_v3',
    'source_category_entity_id', r.source_category_entity_id
  )
FROM stage3_rows r
JOIN public.pl_category_types ct
  ON ct.slug = r.source_category_entity_id
WHERE EXISTS (
  SELECT 1
  FROM public.pl_age_band_development_need_category_types abdnct
  WHERE abdnct.age_band_id = '6-9m'
    AND abdnct.category_type_id = ct.id
    AND abdnct.is_active = true
);

WITH backup_rows AS (
  SELECT *
  FROM (VALUES
    ('cat_board_books', 11, 'Board books longlist candidate 11', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_board_books', 12, 'Board books longlist candidate 12', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_board_books', 13, 'Board books longlist candidate 13', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_board_books', 14, 'Board books longlist candidate 14', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_board_books', 15, 'Board books longlist candidate 15', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_board_books', 16, 'Board books longlist candidate 16', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_board_books', 17, 'Board books longlist candidate 17', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_board_books', 18, 'Board books longlist candidate 18', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_board_books', 19, 'Board books longlist candidate 19', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_board_books', 20, 'Board books longlist candidate 20', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_board_books', 21, 'Board books longlist candidate 21', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_board_books', 22, 'Board books longlist candidate 22', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_board_books', 23, 'Board books longlist candidate 23', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_board_books', 24, 'Board books longlist candidate 24', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_board_books', 25, 'Board books longlist candidate 25', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_highchair', 6, 'Highchair longlist candidate 6', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_highchair', 7, 'Highchair longlist candidate 7', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_highchair', 8, 'Highchair longlist candidate 8', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_highchair', 9, 'Highchair longlist candidate 9', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_highchair', 10, 'Highchair longlist candidate 10', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_highchair', 11, 'Highchair longlist candidate 11', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_highchair', 12, 'Highchair longlist candidate 12', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_highchair', 13, 'Highchair longlist candidate 13', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_highchair', 14, 'Highchair longlist candidate 14', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_highchair', 15, 'Highchair longlist candidate 15', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_peekaboo_scarf', 6, 'Peekaboo scarf longlist candidate 6', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_peekaboo_scarf', 7, 'Peekaboo scarf longlist candidate 7', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_peekaboo_scarf', 8, 'Peekaboo scarf longlist candidate 8', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_peekaboo_scarf', 9, 'Peekaboo scarf longlist candidate 9', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_peekaboo_scarf', 10, 'Peekaboo scarf longlist candidate 10', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_peekaboo_scarf', 11, 'Peekaboo scarf longlist candidate 11', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_peekaboo_scarf', 12, 'Peekaboo scarf longlist candidate 12', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_peekaboo_scarf', 13, 'Peekaboo scarf longlist candidate 13', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_peekaboo_scarf', 14, 'Peekaboo scarf longlist candidate 14', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_peekaboo_scarf', 15, 'Peekaboo scarf longlist candidate 15', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_reach_grab_toys', 6, 'Reach grab longlist candidate 6', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_reach_grab_toys', 7, 'Reach grab longlist candidate 7', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_reach_grab_toys', 8, 'Reach grab longlist candidate 8', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_reach_grab_toys', 9, 'Reach grab longlist candidate 9', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_reach_grab_toys', 10, 'Reach grab longlist candidate 10', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_reach_grab_toys', 11, 'Reach grab longlist candidate 11', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_reach_grab_toys', 12, 'Reach grab longlist candidate 12', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_reach_grab_toys', 13, 'Reach grab longlist candidate 13', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_reach_grab_toys', 14, 'Reach grab longlist candidate 14', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_reach_grab_toys', 15, 'Reach grab longlist candidate 15', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_safety_gates', 6, 'Safety gates longlist candidate 6', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_safety_gates', 7, 'Safety gates longlist candidate 7', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_safety_gates', 8, 'Safety gates longlist candidate 8', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_safety_gates', 9, 'Safety gates longlist candidate 9', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_safety_gates', 10, 'Safety gates longlist candidate 10', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_safety_gates', 11, 'Safety gates longlist candidate 11', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_safety_gates', 12, 'Safety gates longlist candidate 12', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_safety_gates', 13, 'Safety gates longlist candidate 13', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_safety_gates', 14, 'Safety gates longlist candidate 14', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_safety_gates', 15, 'Safety gates longlist candidate 15', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', false, 'No stable buyable primary locked this run.'),
    ('cat_stacking_nesting_cups', 6, 'Stacking cups longlist candidate 6', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_stacking_nesting_cups', 7, 'Stacking cups longlist candidate 7', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_stacking_nesting_cups', 8, 'Stacking cups longlist candidate 8', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_stacking_nesting_cups', 9, 'Stacking cups longlist candidate 9', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_stacking_nesting_cups', 10, 'Stacking cups longlist candidate 10', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_stacking_nesting_cups', 11, 'Stacking cups longlist candidate 11', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_stacking_nesting_cups', 12, 'Stacking cups longlist candidate 12', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_stacking_nesting_cups', 13, 'Stacking cups longlist candidate 13', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_stacking_nesting_cups', 14, 'Stacking cups longlist candidate 14', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_stacking_nesting_cups', 15, 'Stacking cups longlist candidate 15', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_teethers', 6, 'Teethers longlist candidate 6', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_teethers', 7, 'Teethers longlist candidate 7', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_teethers', 8, 'Teethers longlist candidate 8', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_teethers', 9, 'Teethers longlist candidate 9', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_teethers', 10, 'Teethers longlist candidate 10', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_teethers', 11, 'Teethers longlist candidate 11', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_teethers', 12, 'Teethers longlist candidate 12', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_teethers', 13, 'Teethers longlist candidate 13', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_teethers', 14, 'Teethers longlist candidate 14', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_teethers', 15, 'Teethers longlist candidate 15', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_tummy_time_wobbler', 6, 'Tummy wobbler longlist candidate 6', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_tummy_time_wobbler', 7, 'Tummy wobbler longlist candidate 7', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_tummy_time_wobbler', 8, 'Tummy wobbler longlist candidate 8', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_tummy_time_wobbler', 9, 'Tummy wobbler longlist candidate 9', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_tummy_time_wobbler', 10, 'Tummy wobbler longlist candidate 10', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_tummy_time_wobbler', 11, 'Tummy wobbler longlist candidate 11', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_tummy_time_wobbler', 12, 'Tummy wobbler longlist candidate 12', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_tummy_time_wobbler', 13, 'Tummy wobbler longlist candidate 13', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_tummy_time_wobbler', 14, 'Tummy wobbler longlist candidate 14', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.'),
    ('cat_tummy_time_wobbler', 15, 'Tummy wobbler longlist candidate 15', 'Research backup', NULL, NULL, 'UK market scan', NULL, 'unknown', '7-9 months stage fit considered', 'emerging', 'hold_off', true, 'No stable buyable primary locked this run.')
  ) AS v(source_category_entity_id, longlist_rank, product_name, brand, best_for_tag, product_url, retailer, price_text, stock_status, age_mark_on_listing, evidence_tier, buy_borrow_hold_off, gift_suitable, caveat_short)
)
INSERT INTO public.pl_stage3_picks (
  age_band_id,
  category_type_id,
  source_category_entity_id,
  pick_rank,
  longlist_rank,
  status,
  is_visible,
  is_locked,
  best_for_tag,
  product_name,
  brand,
  retailer,
  product_url,
  price_text,
  stock_status,
  age_mark_on_listing,
  caveats,
  buy_borrow_hold_off,
  gift_suitable,
  evidence_tier,
  founder_qa_flag,
  research_payload
)
SELECT
  '6-9m',
  ct.id,
  r.source_category_entity_id,
  r.longlist_rank,
  r.longlist_rank,
  'backup',
  false,
  true,
  r.best_for_tag,
  r.product_name,
  r.brand,
  r.retailer,
  r.product_url,
  r.price_text,
  r.stock_status,
  r.age_mark_on_listing,
  r.caveat_short,
  r.buy_borrow_hold_off,
  -- All-NULL VALUES columns are inferred as text; cast for the boolean target column.
  r.gift_suitable::boolean,
  r.evidence_tier,
  'backup_not_card_ready',
  jsonb_build_object(
    'bundle_schema_version', 'stage3_ingestion_bundle_v1',
    'bundle_generated_at', '2026-07-24T11:05:58.915Z',
    'status', 'dormant_backup',
    'source_category_entity_id', r.source_category_entity_id
  )
FROM backup_rows r
JOIN public.pl_category_types ct
  ON ct.slug = r.source_category_entity_id
WHERE EXISTS (
  SELECT 1
  FROM public.pl_age_band_development_need_category_types abdnct
  WHERE abdnct.age_band_id = '6-9m'
    AND abdnct.category_type_id = ct.id
    AND abdnct.is_active = true
);

DO $$
DECLARE
  v_visible_count INTEGER;
  v_backup_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_visible_count
  FROM public.pl_stage3_picks s
  JOIN public.pl_category_types ct ON ct.id = s.category_type_id
  WHERE s.age_band_id = '6-9m'
    AND ct.slug IN ('cat_board_books', 'cat_highchair', 'cat_peekaboo_scarf', 'cat_reach_grab_toys', 'cat_safety_gates', 'cat_stacking_nesting_cups', 'cat_teethers', 'cat_tummy_time_wobbler')
    AND s.status = 'visible'
    AND s.is_visible = true;

  IF v_visible_count <> 45 THEN
    RAISE EXCEPTION 'Expected 45 visible Stage 3 picks for 6-9m, got %', v_visible_count;
  END IF;

  SELECT COUNT(*) INTO v_backup_count
  FROM public.pl_stage3_picks s
  JOIN public.pl_category_types ct ON ct.id = s.category_type_id
  WHERE s.age_band_id = '6-9m'
    AND ct.slug IN ('cat_board_books', 'cat_highchair', 'cat_peekaboo_scarf', 'cat_reach_grab_toys', 'cat_safety_gates', 'cat_stacking_nesting_cups', 'cat_teethers', 'cat_tummy_time_wobbler')
    AND s.status = 'backup'
    AND s.is_visible = false;

  IF v_backup_count <> 85 THEN
    RAISE EXCEPTION 'Expected 85 backup Stage 3 picks for 6-9m, got %', v_backup_count;
  END IF;
END $$;

COMMIT;
