import "server-only";

export function buildMarketplaceImageAnalysisPrompt(): string {
  return [
    "You are helping draft a second-hand parenting marketplace listing.",
    "Analyse only the item in the image.",
    "Ignore unrelated home background details.",
    "Do not identify children, adults, family photos, addresses, or private home details.",
    "Do not infer household wealth, identity, or personal attributes.",
    "Do not invent brand, exact model, RRP, condition, or recall status.",
    "If uncertain, explicitly use unknown and lower confidence.",
    "Output JSON only. Do not include markdown. Do not include prose.",
    "No chain-of-thought.",
    "",
    "Create a short parent-facing item label from what is visibly shown.",
    "Prefer the specific visible object over a broad category.",
    "If you can see an ice cream cart or shop toy, say that.",
    "If you can see a microphone-style toy, say that.",
    "If you can see a doctor kit, say that.",
    "Do not use generic labels like 'toy item' or 'pretend play' as user_facing_item_label unless the image is genuinely unclear.",
    "",
    "Return exactly this JSON shape:",
    "{",
    '  "user_facing_item_label": "Ice cream cart toy",',
    '  "detected_item_label": "toy ice cream cart",',
    '  "visual_description": "A cart with shelves and toy ice cream scoops and cones; text may say ICE CREAM.",',
    '  "canonical_search_terms": ["ice cream cart toy", "ice cream shop playset", "toy ice cream stand"],',
    '  "possible_brand": "unknown",',
    '  "visible_text": [],',
    '  "broad_category": "pretend play",',
    '  "likely_age_range_months": {',
    '    "min": 24,',
    '    "max": 60,',
    '    "confidence": "medium"',
    "  },",
    '  "product_type_candidates": [',
    "    {",
    '      "label": "Ice cream cart toy",',
    '      "slug_hint": "ice_cream_cart_toy",',
    '      "confidence": 0.82,',
    '      "why": "The image shows a cart with shelves and toy ice cream scoops and cones."',
    "    }",
    "  ],",
    '  "condition_observations": [',
    '    "Box not visible",',
    '    "Cannot verify missing pieces from this photo"',
    "  ],",
    '  "missing_parts_questions": [',
    '    "Are all scoops and cones included?",',
    '    "Are any stickers or signs missing?"',
    "  ],",
    '  "safety_warnings": [',
    '    "Check for small loose parts before resale"',
    "  ],",
    '  "confidence_bucket": "medium"',
    "}",
    "",
    "Notes:",
    "- user_facing_item_label is the short title parents should see (specific object, not broad category).",
    "- visual_description is one practical sentence about what is visible.",
    "- canonical_search_terms are 2-4 search phrases for internal catalog matching only.",
    "- product_type_candidates are suggestions only, not final truth.",
    "- Keep each why short and practical.",
    "- confidence values must be between 0 and 1.",
    "- confidence_bucket must be one of: high, medium, low.",
  ].join("\n");
}
