import "server-only";

export function buildMarketplaceImageAnalysisPrompt(): string {
  return [
    "You are helping draft a second-hand parenting marketplace listing.",
    "Analyse only the item in the image.",
    "Ignore unrelated home background details.",
    "Do not identify children, adults, family photos, addresses, or private home details.",
    "Do not infer household wealth, identity, or personal attributes.",
    "Do not invent brand, exact model, RRP, condition, or recall status.",
    "If uncertain, explicitly use unknown and lower confidence.",
    "Output JSON only. Do not include markdown. Do not include prose.",
    "No chain-of-thought.",
    "",
    "Return exactly this JSON shape:",
    "{",
    '  "detected_item_label": "toy doctor kit",',
    '  "possible_brand": "unknown",',
    '  "visible_text": [],',
    '  "broad_category": "pretend play",',
    '  "likely_age_range_months": {',
    '    "min": 24,',
    '    "max": 60,',
    '    "confidence": "medium"',
    "  },",
    '  "product_type_candidates": [',
    "    {",
    '      "label": "Toy doctor kit",',
    '      "slug_hint": "toy_doctor_kit",',
    '      "confidence": 0.82,',
    '      "why": "The image appears to show toy medical tools such as a stethoscope and syringe."',
    "    }",
    "  ],",
    '  "condition_observations": [',
    '    "Box not visible",',
    '    "Cannot verify missing pieces from this photo"',
    "  ],",
    '  "missing_parts_questions": [',
    '    "Are all small accessories included?",',
    '    "Is the case or storage bag included?"',
    "  ],",
    '  "safety_warnings": [',
    '    "Check for small loose parts before resale"',
    "  ],",
    '  "confidence_bucket": "medium"',
    "}",
    "",
    "Notes:",
    "- product_type_candidates are suggestions only, not final truth.",
    "- Keep each why short and practical.",
    "- confidence values must be between 0 and 1.",
    "- confidence_bucket must be one of: high, medium, low.",
  ].join("\n");
}
