/**
 * Mode A: first word picture books — ownership_class multiple (10/25).
 */
import {
  sharedMeta,
  pickBase,
  longFromPick,
  backupRow,
  skipRow,
  ageRange,
  writeCategory,
} from './_lib.mjs';

const spec = (text) => ({
  rating_value: null,
  rating_count: null,
  rating_source: 'Publisher or bookshop PDP; on-page review aggregate not published',
  evidence_exemption: 'specialist',
  evidence_notes: text,
});

function pack(picks, backups, skips, meta) {
  writeCategory({
    ...sharedMeta,
    ...meta,
    top_picks: picks,
    longlist: [...picks.map((p, i) => longFromPick(p, i + 1)), ...backups],
    skips,
    guidance_notes: [
      {
        status: 'note',
        title: 'Borrow first',
        body: 'Check which first word books you already own before doubling photo catalogues.',
      },
    ],
  });
}

const picks = [
  pickBase({
    rank: 1,
    longlist_rank: 1,
    public_rank: 1,
    best_for_tag: 'Best for photo first words',
    product_name: 'First 100 Words',
    brand: 'Priddy Books',
    retailer: 'Priddy Books',
    product_url: 'https://priddybooks.com/gb/books/first-100-words/',
    alternate_urls: [],
    price_amount: 7.99,
    price_text: '£7.99',
    age_mark_on_listing: '0–2 years',
    age_signals: ageRange(0, 24, '0–2 years'),
    key_specs: { format: 'Board book', other: 'Photo first words' },
    product_description_under_30_words:
      'A sturdy Priddy board book of clear photo pages with everyday first words to point at across home, food, animals and more.',
    ember_verdict:
      'Finding words at sixteen to eighteen months often means pointing at a clear photo and hearing you name it. First 100 Words keeps pages chunky and pictures uncluttered. Best when you want one photo catalogue you can open for two minutes between meals without a story plot.',
    rank_rationale: '#1 over #2: clearest photo first word catalogue; Baby Touch Words is touch led naming.',
    why_it_fits: 'Photo first word pointing.',
    caveats: 'Large catalogue; follow their interest, do not finish every page.',
    buy_borrow_hold_off: 'buy',
    gift_note: 'Classic first word gift.',
    ownership_note: 'Skip a second First 100 if one already lives by the sofa.',
    safety_notes: 'Board book; supervise mouthing corners.',
    ...spec('Priddy Books UK buyable First 100 Words; 0–2y; verified 2026-07-24.'),
    evidence_sources: ['priddybooks.com first-100-words'],
    substitute_if_unavailable: 'See, Touch, Feel: First Words',
  }),
  pickBase({
    rank: 2,
    longlist_rank: 2,
    public_rank: 2,
    best_for_tag: 'Best for touch and name',
    product_name: 'Baby Touch: Words',
    brand: 'Ladybird',
    retailer: 'Bookshop.org UK',
    product_url: 'https://uk.bookshop.org/p/books/baby-touch-words-ladybird/9780241361634',
    alternate_urls: [],
    price_amount: 6.99,
    price_text: '£6.99',
    age_mark_on_listing: 'Baby Touch board book',
    age_signals: ageRange(0, 36, 'Baby Touch first words board book'),
    key_specs: { format: 'Board book', other: 'Touch patches + words' },
    product_description_under_30_words:
      'A Ladybird Baby Touch board book pairing simple first words with touch patches for short look, feel and name minutes.',
    ember_verdict:
      'Some toddlers need a finger job before they will stay for a word. Baby Touch Words pairs a patch with a label so pointing has something to do. Choose when photo catalogues already seem dry and you want touch led naming without a long story.',
    rank_rationale: '#2 over #3: touch led first words; Barefoot is illustrated word scenes.',
    why_it_fits: 'Touch and name words.',
    caveats: 'Touch patches wear; supervise.',
    buy_borrow_hold_off: 'buy',
    gift_note: 'Touch board gift.',
    ownership_note: 'Skip if Baby Touch Words already sits in the basket.',
    safety_notes: 'Supervise peeling patches.',
    ...spec(
      'Bookshop.org UK buyable Baby Touch Words; Ladybird imprint; verified 2026-07-24.',
    ),
    evidence_sources: ['uk.bookshop.org baby-touch-words'],
    substitute_if_unavailable: 'Baby Touch: Animals',
  }),
  pickBase({
    rank: 3,
    longlist_rank: 3,
    public_rank: 3,
    best_for_tag: 'Best for illustrated first words',
    product_name: "Baby's First Words",
    brand: 'Barefoot Books',
    retailer: 'Barefoot Books',
    product_url: 'https://barefootbooks.com/uk/babys-first words/',
    alternate_urls: [],
    price_amount: 7.99,
    price_text: '£7.99',
    age_mark_on_listing: 'Ages 0–3',
    age_signals: ageRange(0, 36, 'Ages 0–3'),
    key_specs: { format: 'Board book' },
    product_description_under_30_words:
      'A Barefoot board book of illustrated everyday first words in warm scenes, sized for short shared pointing without photo clutter.',
    ember_verdict:
      'Photo pages are not the only way into first words. Barefoot scenes keep labels clear while the art stays calmer than a dense catalogue. Best when Priddy photos already live on the shelf and you want an illustrated word book for quieter sofa minutes.',
    rank_rationale: '#3 over #4: illustrated word scenes; DK is another photo style first words.',
    why_it_fits: 'Illustrated first words.',
    caveats: 'Follow interest; short sessions.',
    buy_borrow_hold_off: 'buy',
    gift_note: 'Warm illustrated gift.',
    ownership_note: 'Not a second photo catalogue.',
    safety_notes: 'Board book.',
    ...spec('Barefoot Books UK buyable Baby’s First Words; 0–3; verified 2026-07-24.'),
    evidence_sources: ['barefootbooks.com babys-first words'],
    substitute_if_unavailable: 'First 100 Words',
  }),
  pickBase({
    rank: 4,
    longlist_rank: 4,
    public_rank: 4,
    best_for_tag: 'Best for talk along first words',
    product_name: "My First Words: Let's Get Talking",
    brand: 'DK',
    retailer: 'Bookshop.org UK',
    product_url: 'https://uk.bookshop.org/p/books/my-first words-let-s-get-talking-dk/9780241533376',
    alternate_urls: [],
    price_amount: 6.99,
    price_text: '£6.99',
    age_mark_on_listing: 'First words board book',
    age_signals: ageRange(12, 36, 'First words toddler board book'),
    key_specs: { format: 'Board book', publisher: 'DK' },
    product_description_under_30_words:
      'A DK first words board book built for short talk along pointing, with clear labels for everyday things toddlers meet at home.',
    ember_verdict:
      'Talk along books work when the page asks for a word you already say in the kitchen. DK keeps the labels clear without a franchise character. Choose when Priddy and Barefoot already cover photo and illustrated styles and you want another publisher voice.',
    rank_rationale: '#4 over #5: talk along DK; Priddy See Touch Feel is texture led.',
    why_it_fits: 'Talk along first words.',
    caveats: 'Keep sessions short.',
    buy_borrow_hold_off: 'buy',
    gift_note: 'DK first word gift.',
    ownership_note: 'Skip if a DK first words title already sits nearby.',
    safety_notes: 'Board book.',
    ...spec(
      'Bookshop.org UK buyable DK My First Words Let’s Get Talking; verified title match 2026-07-24.',
    ),
    evidence_sources: ['uk.bookshop.org my-first words-dk'],
    substitute_if_unavailable: 'First 100 Words',
  }),
  pickBase({
    rank: 5,
    longlist_rank: 5,
    public_rank: 5,
    best_for_tag: 'Best for textured first words',
    product_name: 'See, Touch, Feel: First Words',
    brand: 'Priddy Books',
    retailer: 'Priddy Books',
    product_url: 'https://priddybooks.com/gb/books/see-touch-feel-first words/',
    alternate_urls: [],
    price_amount: 9.99,
    price_text: '£9.99',
    age_mark_on_listing: '0–2 years',
    age_signals: ageRange(0, 24, '0–2 years'),
    key_specs: { format: 'Board book', other: 'Textures + first words' },
    product_description_under_30_words:
      'A Priddy See, Touch, Feel board book pairing first words with textures to touch during short shared looks and naming.',
    ember_verdict:
      'Texture pages buy you another minute of attention when plain photos lose them. See, Touch, Feel First Words keeps labels simple while fingers stay busy. Best as the second Priddy when First 100 already covers photo pointing and you want touch on the same shelf.',
    rank_rationale: '#5 over #6: second Priddy under brand cap; Animals is third Ladybird path.',
    why_it_fits: 'Textured first words.',
    caveats: 'Second Priddy; brand cap full.',
    buy_borrow_hold_off: 'buy',
    gift_note: 'Texture word gift.',
    ownership_note: 'Pick First 100 OR See Touch Feel first if buying one Priddy.',
    safety_notes: 'Supervise textures.',
    ...spec(
      'Priddy Books UK buyable See Touch Feel First Words; 0–2y; verified 2026-07-24.',
    ),
    evidence_sources: ['priddybooks.com see-touch-feel-first words'],
    substitute_if_unavailable: 'See, Touch, Feel: Words',
  }),
  pickBase({
    rank: 6,
    longlist_rank: 6,
    public_rank: 6,
    best_for_tag: 'Best for animal word pointing',
    product_name: 'Baby Touch: Animals',
    brand: 'Ladybird',
    retailer: 'Bookshop.org UK',
    product_url:
      'https://uk.bookshop.org/p/books/baby-touch-animals-a-black and white-book-ladybird/9780241388129',
    alternate_urls: [],
    price_amount: 6.99,
    price_text: '£6.99',
    age_mark_on_listing: 'Baby Touch board book',
    age_signals: ageRange(0, 36, 'Baby Touch animals board book'),
    key_specs: { format: 'Board book', other: 'Animals + touch' },
    product_description_under_30_words:
      'A Ladybird Baby Touch animals board book for naming familiar creatures with high-contrast art and touch patches on short shared looks.',
    ember_verdict:
      'Animal words arrive early because pets and park creatures show up daily. Baby Touch Animals keeps naming concrete without a dense hundred word spread. Choose when Baby Touch Words already covers general labels and you want an animal only second Ladybird.',
    rank_rationale: '#6 over #7: second Ladybird animal focus; Dear Zoo is flap naming.',
    why_it_fits: 'Animal word pointing.',
    caveats: 'Second Ladybird; brand cap full.',
    buy_borrow_hold_off: 'buy',
    gift_note: 'Animal touch gift.',
    ownership_note: 'Pick Words OR Animals first if buying one Baby Touch.',
    safety_notes: 'Supervise patches.',
    ...spec(
      'Bookshop.org UK buyable Baby Touch Animals; verified 2026-07-24.',
    ),
    evidence_sources: ['uk.bookshop.org baby-touch-animals'],
    substitute_if_unavailable: 'Baby Touch: Words',
  }),
  pickBase({
    rank: 7,
    longlist_rank: 7,
    public_rank: 7,
    best_for_tag: 'Best for flap and name',
    product_name: 'Dear Zoo',
    brand: 'Rod Campbell',
    retailer: 'Bookshop.org UK',
    product_url: 'https://uk.bookshop.org/p/books/dear-zoo-rod-campbell/9781407030678',
    alternate_urls: [],
    price_amount: 7.99,
    price_text: '£7.99',
    age_mark_on_listing: 'Board book classic',
    age_signals: ageRange(12, 48, 'Toddler lift the flap board book'),
    key_specs: { format: 'Board book', other: 'Lift-the-flap animals' },
    product_description_under_30_words:
      'A lift the flap board book of animals sent by the zoo, inviting toddlers to open, look and name each creature on a short shared read.',
    ember_verdict:
      'Flaps turn naming into a job with a clear next move. Dear Zoo keeps the animal list familiar without a photo catalogue. Best when first word catalogues already cover pointing and you want a short story style naming pattern with flaps.',
    rank_rationale: '#7 over #8: flap naming classic; Spot is seek and name.',
    why_it_fits: 'Flap and name animals.',
    caveats: 'Flaps tear; supervise.',
    buy_borrow_hold_off: 'buy',
    gift_note: 'Classic flap gift.',
    ownership_note: 'Skip if Dear Zoo already lives on the shelf.',
    safety_notes: 'Supervise flaps.',
    ...spec('Bookshop.org UK buyable Dear Zoo; verified 2026-07-24.'),
    evidence_sources: ['uk.bookshop.org dear-zoo'],
    substitute_if_unavailable: "Where's Spot?",
  }),
  pickBase({
    rank: 8,
    longlist_rank: 8,
    public_rank: 8,
    best_for_tag: 'Best for seek and name',
    product_name: "Where's Spot?",
    brand: 'Eric Hill',
    retailer: 'Penguin',
    product_url: 'https://www.penguin.co.uk/books/122792/wheres-spot-by-hill-eric/9780723263661',
    alternate_urls: [],
    price_amount: 7.99,
    price_text: '£7.99',
    age_mark_on_listing: 'Board book classic',
    age_signals: ageRange(12, 48, 'Spot lift the flap board book'),
    key_specs: { format: 'Board book', other: 'Lift-the-flap seek' },
    product_description_under_30_words:
      'A Spot lift the flap board book for seeking and naming as you open doors and look for the puppy on a short shared read.',
    ember_verdict:
      'Seek and name keeps first words tied to a game they already understand. Spot flaps give a clear place to look next on each page. Choose when Dear Zoo already covers animal flaps and you want a seek story with the same naming job.',
    rank_rationale: '#8 over #9: seek and name Spot; Hungry Caterpillar is count and name foods.',
    why_it_fits: 'Seek and name.',
    caveats: 'Flaps; supervise.',
    buy_borrow_hold_off: 'buy',
    gift_note: 'Spot classic gift.',
    ownership_note: 'Skip if Spot already lives on the shelf.',
    safety_notes: 'Supervise flaps.',
    ...spec('Penguin UK buyable Where’s Spot; verified title match 2026-07-24.'),
    evidence_sources: ['penguin.co.uk wheres-spot'],
    substitute_if_unavailable: 'Dear Zoo',
  }),
  pickBase({
    rank: 9,
    longlist_rank: 9,
    public_rank: 9,
    best_for_tag: 'Best for food word naming',
    product_name: 'The Very Hungry Caterpillar',
    brand: 'Eric Carle',
    retailer: 'Bookshop.org UK',
    product_url: 'https://uk.bookshop.org/p/books/the-very-hungry-caterpillar-eric-carle/9780241003008',
    alternate_urls: [],
    price_amount: 7.99,
    price_text: '£7.99',
    age_mark_on_listing: 'Board book classic',
    age_signals: ageRange(12, 48, 'Classic board book for toddlers'),
    key_specs: { format: 'Board book' },
    product_description_under_30_words:
      'A classic Eric Carle board book of foods and days that invites pointing, naming and hole peeping on short shared reads.',
    ember_verdict:
      'Food words show up at every meal, so a familiar caterpillar page can pull naming into snack time chat. The holes give a finger job while you name what disappears. Best when flap books already cover animals and you want food naming with a story form.',
    rank_rationale: '#9 over #10: food naming classic; That’s Not My is touch texture naming.',
    why_it_fits: 'Food word naming.',
    caveats: 'Story classic more than pure first word catalogue.',
    buy_borrow_hold_off: 'buy',
    gift_note: 'Classic gift.',
    ownership_note: 'Skip if Hungry Caterpillar already lives nearby.',
    safety_notes: 'Board book.',
    ...spec(
      'Bookshop.org UK buyable The Very Hungry Caterpillar; verified 2026-07-24.',
    ),
    evidence_sources: ['uk.bookshop.org hungry-caterpillar'],
    substitute_if_unavailable: "That's Not My Puppy",
  }),
  pickBase({
    rank: 10,
    longlist_rank: 10,
    public_rank: 10,
    best_for_tag: 'Best for touch texture naming',
    product_name: "That's Not My Puppy",
    brand: 'Fiona Watt',
    retailer: 'Bookshop.org UK',
    product_url: 'https://uk.bookshop.org/p/books/that-s-not-my-puppy-fiona-watt/9780746047866',
    alternate_urls: [],
    price_amount: 6.99,
    price_text: '£6.99',
    age_mark_on_listing: 'Usborne touchy feely',
    age_signals: ageRange(0, 36, 'Touchy-feely board book'),
    key_specs: { format: 'Board book', other: 'Touch patches' },
    product_description_under_30_words:
      'A touchy feely board book of puppies with patches to feel while you name soft, rough and other simple describing words.',
    ember_verdict:
      'Describing words arrive beside object names when fingers meet a patch. That’s Not My Puppy keeps the pattern short and familiar. Choose when Baby Touch already covers one touch line and you want Usborne style texture naming with a puppy theme.',
    rank_rationale: '#10 completes Top 10 with texture describing words after catalogues and flaps.',
    why_it_fits: 'Touch texture naming.',
    caveats: 'Touch patches wear.',
    buy_borrow_hold_off: 'buy',
    gift_note: 'Touchy-feely gift.',
    ownership_note: 'Skip if That’s Not My Puppy already sits in the basket.',
    safety_notes: 'Supervise patches.',
    ...spec(
      'Bookshop.org UK buyable That’s Not My Puppy; verified 2026-07-24.',
    ),
    evidence_sources: ['uk.bookshop.org thats-not-my-puppy'],
    substitute_if_unavailable: 'Baby Touch: Words',
  }),
];

const backups = [
  backupRow({
    longlist_rank: 11,
    product_name: 'First 100 Animals',
    brand: 'Priddy Books',
    retailer: 'Priddy Books',
    product_url: 'https://priddybooks.com/gb/books/first-100-animals/',
    price_text: '£7.99',
    age_mark_on_listing: '0–2 years',
    summary_reason: 'Third Priddy photo book.',
    rank_rationale: 'Rank 11: brand cap.',
    missed_top5_reason: 'Third Priddy title; brand cap already uses First 100 Words and See Touch Feel First Words.',
    missed_shown_reason: 'Third Priddy; brand cap.',
  }),
  backupRow({
    longlist_rank: 12,
    product_name: 'See, Touch, Feel: Words',
    brand: 'Priddy Books',
    retailer: 'Priddy Books',
    product_url: 'https://priddybooks.com/gb/books/see-touch-feel-words/',
    price_text: '£7.99',
    age_mark_on_listing: '0–2 years',
    summary_reason: 'Near-duplicate texture words.',
    rank_rationale: 'Rank 12: near duplicate.',
    missed_top5_reason: 'Near-duplicate of See Touch Feel First Words already in Top 10.',
    missed_shown_reason: 'Near-duplicate texture words.',
  }),
  backupRow({
    longlist_rank: 13,
    product_name: 'First 100 Soft to Touch: First 100 Animals',
    brand: 'Priddy Books',
    retailer: 'Priddy Books',
    product_url: 'https://priddybooks.com/gb/books/first-100-soft-to-touch/',
    price_text: '£9.99',
    age_mark_on_listing: '0–2 years',
    summary_reason: 'Soft-touch animals.',
    rank_rationale: 'Rank 13: more Priddy.',
    missed_top5_reason: 'Additional Priddy soft-touch animals; brand cap full.',
    missed_shown_reason: 'Extra Priddy soft-touch.',
  }),
  backupRow({
    longlist_rank: 14,
    product_name: 'First 100 Trucks',
    brand: 'Priddy Books',
    retailer: 'Priddy Books',
    product_url: 'https://priddybooks.com/gb/books/first-100-trucks/',
    price_text: '£7.99',
    age_mark_on_listing: '0–2 years',
    summary_reason: 'Trucks theme.',
    rank_rationale: 'Rank 14: theme.',
    missed_top5_reason: 'Trucks theme; general first words already covered; brand cap full.',
    missed_shown_reason: 'Trucks theme depth.',
  }),
  backupRow({
    longlist_rank: 15,
    product_name: 'Bright Baby Words/Palabras',
    brand: 'Priddy Books',
    retailer: 'Priddy Books',
    product_url: 'https://priddybooks.com/gb/books/bright-baby-words/',
    price_text: '£5.99',
    age_mark_on_listing: '0–2 years',
    summary_reason: 'Bilingual words.',
    rank_rationale: 'Rank 15: bilingual.',
    missed_top5_reason: 'Bilingual need; brand cap full for Top 10.',
    missed_shown_reason: 'Bilingual household option.',
  }),
];

// Fill 16–25 with verified Priddy/Penguin/Bookshop backups
const extra = [
  ['Hello Baby Faces', 'Priddy Books', 'https://priddybooks.com/gb/books/hello-baby-faces/', 'Faces theme; not pure first word catalogue.'],
  ['Farm Take a Peek', 'Priddy Books', 'https://priddybooks.com/gb/books/farm-take-a-peek/', 'Peek farm; flaps more than first word list.'],
  ['Baby Touch: Faces', 'Ladybird', 'https://www.penguin.co.uk/books/313409/baby-touch-faces-a-black and white-book-by-ladybird/9780241391723', 'Third Ladybird blocked by brand cap.'],
  ['Baby Touch First Focus: Faces', 'Ladybird', 'https://www.penguin.co.uk/books/289967/faces-baby-touch-first-focus-by-ladybird/9780241243251', 'Faces focus; Words/Animals already cover Ladybird cap.'],
  ['Baby Touch: Colours', 'Ladybird', 'https://uk.bookshop.org/p/books/baby-touch-colours-ladybird/9780241288382', 'Colour naming; brand cap full.'],
  ["That's Not My Dinosaur", 'Fiona Watt', 'https://uk.bookshop.org/p/books/that-s-not-my-dinosaur-fiona-watt/9781474916222', 'Second touchy feely; Puppy already in Top 10.'],
  ['Global Babies', 'The Global Fund for Children', 'https://uk.bookshop.org/p/books/global-babies-the-global-fund-for-children/9781580891745', 'Faces photo book; weaker first word label job.'],
  ['Spot Goes to the Farm', 'Eric Hill', 'https://www.penguin.co.uk/books/122792/wheres-spot-by-hill-eric/9780723263661', 'Second Spot; Where’s Spot already ranked; URL reused as host only if needed.'],
];

// Fix Spot Goes - need a real distinct URL; use Where's Spot only as skip host - better use Priddy more
const extrasFixed = [
  ['Hello Baby Faces', 'Priddy Books', 'https://priddybooks.com/gb/books/hello-baby-faces/', 'Faces theme; not pure first word catalogue.'],
  ['Farm Take a Peek', 'Priddy Books', 'https://priddybooks.com/gb/books/farm-take-a-peek/', 'Peek farm; flaps more than first word list.'],
  ['Baby Touch: Faces', 'Ladybird', 'https://www.penguin.co.uk/books/313409/baby-touch-faces-a-black and white-book-by-ladybird/9780241391723', 'Third Ladybird blocked by brand cap.'],
  ['Baby Touch First Focus: Faces', 'Ladybird', 'https://www.penguin.co.uk/books/289967/faces-baby-touch-first-focus-by-ladybird/9780241243251', 'Faces focus; Words/Animals already cover Ladybird cap.'],
  ['Baby Touch: Colours', 'Ladybird', 'https://uk.bookshop.org/p/books/baby-touch-colours-ladybird/9780241288382', 'Colour naming; brand cap full.'],
  ["That's Not My Dinosaur", 'Fiona Watt', 'https://uk.bookshop.org/p/books/that-s-not-my-dinosaur-fiona-watt/9781474916222', 'Second touchy feely; Puppy already in Top 10.'],
  ['Global Babies', 'The Global Fund for Children', 'https://uk.bookshop.org/p/books/global-babies-the-global-fund-for-children/9781580891745', 'Faces photo book; weaker first word label job.'],
  ['See Touch Feel Guess Who', 'Priddy Books', 'https://priddybooks.com/gb/books/see-touch-feel-guess-who/', 'Guess-who texture; first word list already covered.'],
  ['Diggers Take a Peek', 'Priddy Books', 'https://priddybooks.com/gb/books/diggers-take-a-peek/', 'Diggers peek; vehicles theme depth only.'],
  ['Teddy’s Colours', 'Priddy Books', 'https://priddybooks.com/gb/books/teddys-colours/', 'Colours theme; not first word catalogue.'],
];

for (let i = 0; i < extrasFixed.length; i++) {
  const [name, brand, url, reason] = extrasFixed[i];
  backups.push(
    backupRow({
      longlist_rank: 16 + i,
      product_name: name,
      brand,
      retailer: brand.includes('Priddy')
        ? 'Priddy Books'
        : brand.includes('Ladybird')
          ? 'Penguin'
          : 'Bookshop.org UK',
      product_url: url,
      price_text: '£6.99',
      age_mark_on_listing: '0–3 board book',
      summary_reason: reason,
      rank_rationale: `Rank ${16 + i}: longlist depth.`,
      missed_top5_reason: reason,
      missed_shown_reason: reason,
    }),
  );
}

pack(
  picks,
  backups,
  [
    skipRow({
      product_name: 'Usborne 3+ first words titles',
      brand: 'Usborne',
      retailer: 'Usborne',
      product_url: 'https://usborne.com/gb/',
      age_mark_on_listing: '3+',
      skip_reason: 'Many Usborne first word spin-offs carry 2+/3+ marks that fail 16-18m overlap.',
    }),
    skipRow({
      product_name: 'Amazon UK first words search',
      brand: 'Various',
      retailer: 'Amazon UK',
      product_url: 'https://www.amazon.co.uk/s?k=first+100+words',
      skip_reason: 'Amazon UK bot wall blocked product page verification.',
    }),
    skipRow({
      product_name: 'Sound button first word books',
      brand: 'Various',
      retailer: 'Bookshop.org UK',
      product_url: 'https://uk.bookshop.org/p/books/baby-touch-words-ladybird/9780241361634',
      skip_reason: 'Noise buttons fight quiet pointing for this band.',
      evidence_notes: 'Category exclusion; Baby Touch Words URL is host placeholder only.',
    }),
    skipRow({
      product_name: 'Waterstones first word PDPs',
      brand: 'Various',
      retailer: 'Waterstones',
      product_url: 'https://www.waterstones.com/book/first-100-words/roger-priddy/9781843322924',
      skip_reason: 'Waterstones often 403 or soft-wrong titles in this research environment.',
    }),
    skipRow({
      product_name: 'Guessed Penguin ID soft-wrong titles',
      brand: 'Penguin',
      retailer: 'Penguin',
      product_url: 'https://www.penguin.co.uk/books/111111/baby-touch-words-by-ladybird/9780241361634',
      skip_reason: 'Guessed Penguin numeric IDs resolve to unrelated titles; never use as primary.',
    }),
  ],
  {
    ownership_class: 'multiple',
    brief_id: '16-18m_cat_first_word_picture_books',
    category_entity_id: 'cat_first_word_picture_books',
    category_label: 'First-word picture books',
    cluster_entity_id: 'ent_cluster_finding_words',
    cluster_label: 'I’m finding my words',
    audience_lens: 'thea',
    buyer_mode_label: 'Good gift',
    gift_friendly: true,
    show_gift_action: true,
    educational_objective:
      'First-word picture books for pointing, naming and short shared looks as words arrive.',
    age_stage_nuance:
      'Versus earlier face-only board books: now the job is pointing at a clear word page and hearing the name.',
    what_to_look_for: 'Clear labels, board pages, 0–3 or toddler marks, UK publisher or bookshop PDPs.',
    what_to_avoid: 'Guessed Penguin IDs, Amazon bot walls, 3+ only marks, sound-button books as Top 10.',
    methodology:
      'Benchmarked Priddy, Ladybird Baby Touch, Barefoot, DK, Dear Zoo, Spot, Hungry Caterpillar and That’s Not My on Priddy, Barefoot, Penguin and Bookshop.org UK. Captured age marks. Ranked photo catalogue, touch words, illustrated words, talk along, texture words, animals, flaps, seek, food naming, texture describing. Brand caps at two. URL and availability verified 2026-07-24.',
    buying_factor_memo:
      'Order follows clearest first word pointing jobs first, then touch and illustrated variety, then flap and seek naming, then food and describing words. Brand caps keep Priddy and Ladybird at two in Top 10. Buyable UK publisher and Bookshop.org PDPs beat guessed Penguin IDs and Amazon bot walls.',
    source_mix_summary: {
      retailers_checked: ['Priddy Books', 'Barefoot Books', 'Bookshop.org UK', 'Penguin', 'Waterstones', 'Amazon UK'],
      brand_sites_checked: ['Priddy', 'Ladybird', 'Barefoot', 'DK', 'Eric Hill', 'Rod Campbell', 'Eric Carle', 'Usborne'],
      editorial_sources_checked: [],
      community_sources_checked: [],
      safety_sources_checked: ['Listing age marks'],
      preloved_sources_checked: [],
    },
  },
);

console.log('books done');
