/**
 * Mode A: doll care, crayons, open cups — 16-18m.
 */
import {
  sharedMeta,
  pickBase,
  longFromPick,
  backupRow,
  skipRow,
  ageRange,
  writeCategory,
} from './_lib.mjs';

const spec = (text) => ({
  rating_value: null,
  rating_count: null,
  rating_source: 'Specialist or brand PDP; on-page review aggregate not published',
  evidence_exemption: 'specialist',
  evidence_notes: text,
});

function pack(picks, backups, skips, meta) {
  writeCategory({
    ...sharedMeta,
    ...meta,
    top_picks: picks,
    longlist: [...picks.map((p, i) => longFromPick(p, i + 1)), ...backups],
    skips,
    guidance_notes: [
      {
        status: 'note',
        title: 'Borrow first',
        body: 'Check what you already own in this format before adding a near duplicate.',
      },
    ],
  });
}

// ——— dolls ———
{
  const picks = [
    pickBase({
      rank: 1,
      longlist_rank: 1,
      public_rank: 1,
      best_for_tag: 'Best for soft bedtime care',
      product_name: 'Corolle Miss Floral Sweet Dreams Soft Doll',
      brand: 'Corolle',
      retailer: 'Adventure Toys',
      product_url: 'https://www.adventuretoys.co.uk/corolle-miss-floral-sweet-dreams-soft-doll/',
      alternate_urls: [],
      price_amount: 19.99,
      price_text: '£19.99',
      age_mark_on_listing: 'Birth +',
      age_signals: ageRange(0, 36, 'Birth +'),
      key_specs: { materials: 'Soft fabric', other: 'Pyjama doll' },
      product_description_under_30_words:
        'A soft fabric doll in pyjamas, sized for toddler cuddles, carry and simple tuck in care play without stiff plastic joints.',
      ember_verdict:
        'Copying real life at this age often starts with a soft body they can hug, carry and put to bed. Miss Floral keeps the doll light for sofa care games. Best when you want one soft doll that invites tuck in without a full bedroom set yet.',
      rank_rationale: '#1 over #2: clearest soft care doll; Blandine is rag-doll carry twin.',
      why_it_fits: 'Soft doll for care copy play.',
      caveats: 'Supervise tags.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Soft gift.',
      ownership_note: 'Skip a second soft doll if one already gets daily carry.',
      safety_notes: 'Check seams.',
      ...spec(
        'Adventure Toys UK buyable Corolle Miss Floral Sweet Dreams; birth+ mark; verified 2026-07-24.',
      ),
      evidence_sources: ['adventuretoys.co.uk corolle-miss-floral'],
      substitute_if_unavailable: 'Corolle Rag Doll Blandine Sweet Dreams',
    }),
    pickBase({
      rank: 2,
      longlist_rank: 2,
      public_rank: 2,
      best_for_tag: 'Best for rag-doll carry',
      product_name: 'Corolle Rag Doll Blandine Sweet Dreams',
      brand: 'Corolle',
      retailer: 'Adventure Toys',
      product_url: 'https://www.adventuretoys.co.uk/corolle-rag-doll-blandine-sweet-dreams/',
      alternate_urls: [],
      price_amount: 24.99,
      price_text: '£24.99',
      age_mark_on_listing: 'Birth +',
      age_signals: ageRange(0, 36, 'Birth +'),
      key_specs: { materials: 'Soft fabric rag doll' },
      product_description_under_30_words:
        'A soft rag style Corolle doll for cuddle, carry and simple care, with a floppy body that fits under a toddler arm indoors.',
      ember_verdict:
        'Some toddlers prefer a rag flop for dragging from room to room. Blandine keeps Corolle quality while limp limbs make carry simpler on short indoor trips. Choose when Miss Floral already sits on the shelf and you want a different soft care friend.',
      rank_rationale: '#2 over #3: second Corolle soft body; bed props come next.',
      why_it_fits: 'Rag doll carry care.',
      caveats: 'Second Corolle; brand cap full.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Soft character gift.',
      ownership_note: 'Pick floral OR Blandine, not both unless gifting elsewhere.',
      safety_notes: 'Supervise.',
      ...spec(
        'Adventure Toys UK buyable Corolle Blandine Sweet Dreams; birth+; verified 2026-07-24.',
      ),
      evidence_sources: ['adventuretoys.co.uk corolle-rag-doll-blandine'],
      substitute_if_unavailable: 'Corolle Miss Floral Sweet Dreams Soft Doll',
    }),
    pickBase({
      rank: 3,
      longlist_rank: 3,
      public_rank: 3,
      best_for_tag: 'Best for tuck in bed prop',
      product_name: 'Goki Dolls Bed',
      brand: 'Goki',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/goki-dolls-bed/',
      alternate_urls: [],
      price_amount: 16.99,
      price_text: '£16.99',
      age_mark_on_listing: '1 year +',
      age_signals: ageRange(12, 36, '1 year +'),
      key_specs: { materials: 'Wood', other: 'Doll bed' },
      product_description_under_30_words:
        'A wooden dolls bed sized for soft toys and small dolls, inviting tuck in, lift out and bedtime copy play on the floor.',
      ember_verdict:
        'Care play deepens when there is a clear place to put the doll down. A simple wooden bed turns carry into tuck in without a full dolls house. Best once a soft doll already lives on the sofa and you want one prop that gives bedtime copy a clear finish.',
      rank_rationale: '#3 over #4: clearest tuck in prop; cradles add rock.',
      why_it_fits: 'Bed prop for care.',
      caveats: 'Needs a soft doll they already own or buy separately.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Pair with soft doll.',
      ownership_note: 'Skip if a dolls bed already sits in the room.',
      safety_notes: 'Supervise.',
      ...spec('Toytastic UK buyable Goki Dolls Bed; 1y+; verified 2026-07-24.'),
      evidence_sources: ['toytastic.co.uk goki-dolls-bed'],
      substitute_if_unavailable: 'BigJigs Doll Cradle Blue Wooden',
    }),
    pickBase({
      rank: 4,
      longlist_rank: 4,
      public_rank: 4,
      best_for_tag: 'Best for rock and settle',
      product_name: 'BigJigs Doll Cradle Blue Wooden',
      brand: 'Bigjigs',
      retailer: 'Adventure Toys',
      product_url: 'https://www.adventuretoys.co.uk/bigjigs-doll-cradle-blue-wooden/',
      alternate_urls: [],
      price_amount: 22.99,
      price_text: '£22.99',
      age_mark_on_listing: '12 months +',
      age_signals: ageRange(12, 36, '12 months +'),
      key_specs: { materials: 'Wood', other: 'Rocking cradle' },
      product_description_under_30_words:
        'A wooden dolls cradle that rocks gently, inviting toddlers to settle a soft doll and try a short rock and watch care pattern.',
      ember_verdict:
        'Rocking a cradle is a clear copy of real settle minutes. Bigjigs wood keeps the motion gentle enough for small hands. Choose when a flat dolls bed already seems done and you want rock and settle as the next care job.',
      rank_rationale: '#4 over #5: wood rock cradle; Tidlo is alternate rock form.',
      why_it_fits: 'Rocking cradle care.',
      caveats: 'Needs doll or soft toy.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Wooden prop gift.',
      ownership_note: 'Pick bed OR cradle first, not both at once.',
      safety_notes: 'Supervise rocking near edges.',
      ...spec(
        'Adventure Toys UK buyable Bigjigs doll cradle; 12m+; verified 2026-07-24.',
      ),
      evidence_sources: ['adventuretoys.co.uk bigjigs-doll-cradle'],
      substitute_if_unavailable: "Tidlo Doll's Rocking Cradle",
    }),
    pickBase({
      rank: 5,
      longlist_rank: 5,
      public_rank: 5,
      best_for_tag: 'Best for carry cradle naps',
      product_name: "Tidlo Doll's Rocking Cradle",
      brand: 'Tidlo',
      retailer: 'Adventure Toys',
      product_url: 'https://www.adventuretoys.co.uk/tidlo-dolls-rocking-cradle/',
      alternate_urls: [],
      price_amount: 29.99,
      price_text: '£29.99',
      age_mark_on_listing: '12 months +',
      age_signals: ageRange(12, 36, '12 months +'),
      key_specs: { materials: 'Wood', other: 'Rocking cradle' },
      product_description_under_30_words:
        'A wooden Tidlo rocking cradle for soft dolls, giving a clear settle place and a gentle rock for bedtime copy play.',
      ember_verdict:
        'If Bigjigs stock is thin, Tidlo still covers rock and settle with sturdy wood. The cradle keeps care play in one spot instead of endless carry. Useful as the fifth pick when soft dolls are sorted and you want a second wood cradle option with a different brand.',
      rank_rationale: '#5: alternate wood cradle brand after Bigjigs.',
      why_it_fits: 'Alternate rocking cradle.',
      caveats: 'Near job overlap with Bigjigs cradle.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Wooden gift.',
      ownership_note: 'Do not buy both Bigjigs and Tidlo cradles.',
      safety_notes: 'Supervise.',
      ...spec(
        'Adventure Toys UK buyable Tidlo dolls rocking cradle; 12m+; verified 2026-07-24.',
      ),
      evidence_sources: ['adventuretoys.co.uk tidlo-dolls-rocking-cradle'],
      substitute_if_unavailable: 'Goki Dolls Carry Cradle Mosses Basket with bedding',
    }),
  ];

  const backups = [
    backupRow({
      longlist_rank: 6,
      product_name: 'Corolle Bath Alyzee Baby Doll',
      brand: 'Corolle',
      retailer: 'Adventure Toys',
      product_url: 'https://www.adventuretoys.co.uk/corolle-bath-alyzee-baby-doll/',
      price_text: '£29.99',
      age_mark_on_listing: 'Birth +',
      summary_reason: 'Bath care doll.',
      rank_rationale: 'Rank 6: third Corolle.',
      missed_top5_reason: 'Brand cap already uses two Corolle soft dolls.',
    }),
    backupRow({
      longlist_rank: 7,
      product_name: 'Goki Dolls Carry Cradle Mosses Basket with bedding',
      brand: 'Goki',
      retailer: 'Adventure Toys',
      product_url:
        'https://www.adventuretoys.co.uk/goki-dolls-carry-cradle-mosses-basket-with-bedding/',
      price_text: '£24.99',
      age_mark_on_listing: '1 year +',
      summary_reason: 'Carry cradle.',
      rank_rationale: 'Rank 7: second Goki prop.',
      missed_top5_reason: 'Carry cradle overlaps bed/cradle jobs already in Top 5.',
    }),
    backupRow({
      longlist_rank: 8,
      product_name: 'Goki Dolls Cradle',
      brand: 'Goki',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/goki-dolls-cradle/',
      price_text: '£18.99',
      age_mark_on_listing: '3 years +',
      summary_reason: 'Age fail risk.',
      rank_rationale: 'Rank 8: check age.',
      missed_top5_reason: 'Listing age often 3+; fails safe overlap for this band.',
    }),
    backupRow({
      longlist_rank: 9,
      product_name: 'Corolle Mini Cotton Flower Doll',
      brand: 'Corolle',
      retailer: 'Adventure Toys',
      product_url: 'https://www.adventuretoys.co.uk/corolle-mini-cotton-flower-doll-age-0-years/',
      price_text: '£19.99',
      age_mark_on_listing: '0 years +',
      summary_reason: 'Unbuyable at research.',
      rank_rationale: 'Rank 9: stock fail.',
      missed_top5_reason: 'Unbuyable during research.',
    }),
    backupRow({
      longlist_rank: 10,
      product_name: 'Scrunch Ball',
      brand: 'Scrunch',
      retailer: 'Adventure Toys',
      product_url: 'https://www.adventuretoys.co.uk/scrunch-ball/',
      price_text: '£12.99',
      age_mark_on_listing: 'Toddler',
      summary_reason: 'Wrong category.',
      rank_rationale: 'Rank 10: ball.',
      missed_top5_reason: 'Soft ball, not doll care.',
    }),
    backupRow({
      longlist_rank: 11,
      product_name: 'Hape Stacking Jack',
      brand: 'Hape',
      retailer: 'Adventure Toys',
      product_url: 'https://www.adventuretoys.co.uk/hape-stacking-jack/',
      price_text: '£9.25',
      age_mark_on_listing: '12 months +',
      summary_reason: 'Stacker.',
      rank_rationale: 'Rank 11: wrong category.',
      missed_top5_reason: 'Stacking category.',
    }),
    backupRow({
      longlist_rank: 12,
      product_name: 'SES Creative My First Colourball',
      brand: 'SES Creative',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/ses-creative-my-first-colourball/',
      price_text: '£16.99',
      age_mark_on_listing: '1–4 years',
      summary_reason: 'Crayon.',
      rank_rationale: 'Rank 12: art.',
      missed_top5_reason: 'Mark-making category.',
    }),
    backupRow({
      longlist_rank: 13,
      product_name: 'Doidy Cup',
      brand: 'Doidy',
      retailer: 'Boots',
      product_url: 'https://www.boots.com/doidy-cup-10150006',
      price_text: '£4.50',
      age_mark_on_listing: '3 months +',
      summary_reason: 'Cup.',
      rank_rationale: 'Rank 13: meals.',
      missed_top5_reason: 'Open cup category.',
    }),
    backupRow({
      longlist_rank: 14,
      product_name: 'Priddy First 100 Words',
      brand: 'Priddy Books',
      retailer: 'Priddy Books',
      product_url: 'https://priddybooks.com/gb/books/first-100-words/',
      price_text: '£7.99',
      age_mark_on_listing: '0–2 years',
      summary_reason: 'Book.',
      rank_rationale: 'Rank 14: words.',
      missed_top5_reason: 'First-word books category.',
    }),
    backupRow({
      longlist_rank: 15,
      product_name: 'Quercetti FlipCar Racetrack',
      brand: 'Quercetti',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/quercetti-flipcar-racetrack/',
      price_text: '£28.99',
      age_mark_on_listing: '18 months +',
      summary_reason: 'Ramp.',
      rank_rationale: 'Rank 15: ramp.',
      missed_top5_reason: 'Ramp rolling category.',
    }),
  ];

  pack(
    picks,
    backups,
    [
      skipRow({
        product_name: 'Corolle Mini Cotton Flower Doll',
        brand: 'Corolle',
        retailer: 'Adventure Toys',
        product_url: 'https://www.adventuretoys.co.uk/corolle-mini-cotton-flower-doll-age-0-years/',
        skip_reason: 'Unbuyable / out of stock during research.',
      }),
      skipRow({
        product_name: 'Goki Dolls Cradle (3+ listing)',
        brand: 'Goki',
        retailer: 'Toytastic',
        product_url: 'https://toytastic.co.uk/product/goki-dolls-cradle/',
        age_mark_on_listing: '3 years +',
        skip_reason: '3+ age mark fails 16-18m overlap.',
      }),
      skipRow({
        product_name: 'Plastic fashion dolls with small parts',
        brand: 'Various',
        retailer: 'Toytastic',
        product_url: 'https://toytastic.co.uk/product/goki-dolls-bed/',
        skip_reason: 'Fashion dolls with small accessories fail care brief and age safety.',
        evidence_notes: 'Category exclusion; Goki bed URL is host placeholder only.',
      }),
      skipRow({
        product_name: 'Amazon UK baby doll listings',
        brand: 'Various',
        retailer: 'Amazon UK',
        product_url: 'https://www.amazon.co.uk/s?k=soft+baby+doll',
        skip_reason: 'Amazon UK bot wall blocked product page verification.',
      }),
      skipRow({
        product_name: 'Electronic crying dolls',
        brand: 'Various',
        retailer: 'Smyths',
        product_url: 'https://www.adventuretoys.co.uk/corolle-miss-floral-sweet-dreams-soft-doll/',
        skip_reason: 'Noise and batteries fight quiet care copy at this age.',
        evidence_notes: 'Category exclusion; Corolle URL is host placeholder only.',
      }),
    ],
    {
      ownership_class: 'single',
      brief_id: '16-18m_cat_doll_soft_toy_care',
      category_entity_id: 'cat_doll_soft_toy_care',
      category_label: 'Soft toy and doll care play',
      cluster_entity_id: 'ent_cluster_copying_real_life',
      cluster_label: 'I’m copying real life',
      audience_lens: 'both',
      buyer_mode_label: 'Good gift',
      gift_friendly: true,
      show_gift_action: true,
      educational_objective: 'Soft dolls and simple care props for tuck in, carry and settle copy play.',
      age_stage_nuance:
        'Versus earlier cuddle-only soft toys: now the job is carry, tuck in and settle as a short care pattern.',
      what_to_look_for: 'Soft bodies, wooden bed or cradle props, birth–18m or 1y+ marks, UK buyable.',
      what_to_avoid: '3+ fashion dolls, electronic crying dolls, OOS mini Corolle as Top 5.',
      methodology:
        'Benchmarked Corolle soft dolls and Goki/Bigjigs/Tidlo care props on Adventure Toys and Toytastic. Captured age marks. Ranked soft care doll, rag carry, bed, rock cradle, alternate cradle. URL and availability verified 2026-07-24.',
      buying_factor_memo:
        'Order follows soft doll first, then care props that make tuck in and rock clear. Brand cap keeps Corolle at two. Buyable UK specialist PDPs beat Amazon bot-wall listings. Bath Corolle stays longlist to respect brand cap.',
      source_mix_summary: {
        retailers_checked: ['Adventure Toys', 'Toytastic', 'Amazon UK'],
        brand_sites_checked: ['Corolle', 'Goki', 'Bigjigs', 'Tidlo'],
        editorial_sources_checked: [],
        community_sources_checked: [],
        safety_sources_checked: ['Listing age marks'],
        preloved_sources_checked: [],
      },
    },
  );
}

// ——— crayons ———
{
  const picks = [
    pickBase({
      rank: 1,
      longlist_rank: 1,
      public_rank: 1,
      best_for_tag: 'Best for fist grip colour ball',
      product_name: 'SES Creative My First Colourball',
      brand: 'SES Creative',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/ses-creative-my-first-colourball/',
      alternate_urls: [],
      price_amount: 16.99,
      price_text: '£16.99',
      age_mark_on_listing: '1–4 years',
      age_signals: ageRange(12, 48, '1–4 years'),
      key_specs: { other: '6 colours in one ball' },
      product_description_under_30_words:
        'A large ball shaped crayon with six colour tips built in, made for toddler fist grips and short first scribbles on paper.',
      ember_verdict:
        'First marks at sixteen to eighteen months are often whole hand scribbles, not neat pencil holds. The Colourball keeps six colours in one body so nothing rolls under the sofa. Best when you want one tool that invites colour changes without a fistful of separate sticks.',
      rank_rationale: '#1 over #2: single all in one grip tool; beads are separate colours on a cord.',
      why_it_fits: 'Fist-grip first crayon.',
      caveats: 'Supervise mouthing.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Easy first art gift.',
      ownership_note: 'Skip a second Colourball if one already gets table time.',
      safety_notes: 'Adult present for first marks.',
      ...spec(
        'Toytastic UK buyable SES My First Colourball; 1–4y mark overlaps 16-18m; verified 2026-07-24.',
      ),
      evidence_sources: ['toytastic.co.uk ses-creative-my-first-colourball'],
      substitute_if_unavailable: 'SES Creative My First Crayon Beads',
    }),
    pickBase({
      rank: 2,
      longlist_rank: 2,
      public_rank: 2,
      best_for_tag: 'Best for bead crayons on a cord',
      product_name: 'SES Creative My First Crayon Beads',
      brand: 'SES Creative',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/ses-creative-my-first-crayon-beads/',
      alternate_urls: [],
      price_amount: 9.99,
      price_text: '£9.99',
      age_mark_on_listing: '1–4 years',
      age_signals: ageRange(12, 48, '1–4 years'),
      key_specs: { piece_count: '6 beads on cord' },
      product_description_under_30_words:
        'Six ball shaped crayon beads on a cord, chunky enough for fist grips and hard to lose under the sofa during first scribbles.',
      ember_verdict:
        'When separate crayons vanish in seconds, a cord keeps the set together. Bead shapes still fit whole hand grips while colours stay pickable. Choose when the Colourball already covers one tool days and you want a second SES format for the bag.',
      rank_rationale: '#2 over #3: cord kept set; Crayola jumbo is classic stick form.',
      why_it_fits: 'Cord-kept fist crayons.',
      caveats: 'Second SES; brand cap full.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Small art gift.',
      ownership_note: 'Pick Colourball OR beads first if budget is tight.',
      safety_notes: 'Supervise cord.',
      ...spec(
        'Toytastic UK buyable SES My First Crayon Beads; 1–4y; verified 2026-07-24.',
      ),
      evidence_sources: ['toytastic.co.uk ses-creative-my-first-crayon-beads'],
      substitute_if_unavailable: 'SES Creative My First Crayons',
    }),
    pickBase({
      rank: 3,
      longlist_rank: 3,
      public_rank: 3,
      best_for_tag: 'Best for jumbo stick crayons',
      product_name: 'Crayola My First Jumbo Crayons 8 Pack',
      brand: 'Crayola',
      retailer: 'Smyths',
      product_url:
        'https://www.smythstoys.com/uk/en-gb/toys/arts-and-crafts/crayons-and-pastels/crayola-my-first-jumbo-crayons-8-pack/p/195185',
      alternate_urls: [
        'https://www.boots.com/crayola-my-first-washable-crayons-8-pack-10289001',
      ],
      price_amount: 5.99,
      price_text: '£5.99',
      age_mark_on_listing: '12 months +',
      age_signals: ageRange(12, 48, '12 months + / My First range'),
      key_specs: { piece_count: '8 jumbo crayons' },
      product_description_under_30_words:
        'Eight jumbo Crayola sticks made for small hands learning first scribbles, thicker than school crayons and easier to grip whole hand.',
      ember_verdict:
        'Classic jumbo sticks still help once fist balls seem limiting. Crayola My First keeps the sticks thick enough for sixteen to eighteen months without tiny school crayons. Best when SES ball tools already cover grip play and you want familiar stick colours on paper.',
      rank_rationale: '#3 over #4: jumbo stick set; washable twin is mess control.',
      why_it_fits: 'Jumbo stick crayons.',
      caveats: 'Smyths primary; confirm stock at purchase.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Easy stocking gift.',
      ownership_note: 'Skip if jumbo crayons already live in the kitchen drawer.',
      safety_notes: 'Supervise.',
      ...spec(
        'Smyths UK buyable Crayola My First Jumbo Crayons; My First toddler range; smoke+availability verified 2026-07-24.',
      ),
      evidence_sources: ['smythstoys.com crayola-my-first-jumbo'],
      substitute_if_unavailable: 'Crayola My First Washable Crayons',
    }),
    pickBase({
      rank: 4,
      longlist_rank: 4,
      public_rank: 4,
      best_for_tag: 'Best for washable first marks',
      product_name: 'Crayola My First Washable Crayons',
      brand: 'Crayola',
      retailer: 'Smyths',
      product_url:
        'https://www.smythstoys.com/uk/en-gb/toys/arts-and-crafts/crayons-and-pastels/crayola-my-first-washable-crayons/p/189012',
      alternate_urls: [
        'https://www.boots.com/crayola-my-first-washable-crayons-8-pack-10289001',
      ],
      price_amount: 6.99,
      price_text: '£6.99',
      age_mark_on_listing: '12 months +',
      age_signals: ageRange(12, 48, '12 months + / My First washable'),
      key_specs: { other: 'Washable formula' },
      product_description_under_30_words:
        'Washable Crayola My First crayons for early scribbles, thicker sticks with a formula that rinses more kindly from skin and many fabrics.',
      ember_verdict:
        'Mark making at this age lands on hands as much as paper. Washable My First sticks keep the same jumbo idea with easier clean up. Choose when jumbo non washable already exist and you want a second Crayola set for highchair art days.',
      rank_rationale: '#4 over #5: washable stick job; fingerpaint is different medium.',
      why_it_fits: 'Washable first crayons.',
      caveats: 'Second Crayola; brand cap full.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Practical art gift.',
      ownership_note: 'Pick jumbo OR washable first if buying one Crayola set.',
      safety_notes: 'Supervise.',
      ...spec(
        'Smyths UK buyable Crayola My First Washable; Boots alternate also buyable 2026-07-24.',
      ),
      evidence_sources: ['smythstoys.com crayola-my-first-washable'],
      substitute_if_unavailable: 'Crayola My First Jumbo Crayons 8 Pack',
    }),
    pickBase({
      rank: 5,
      longlist_rank: 5,
      public_rank: 5,
      best_for_tag: 'Best for character chunky wax',
      product_name: 'Cerda Bing Wax Crayons 5 Pack',
      brand: 'Cerda',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/cerda-bing-wax-crayons/',
      alternate_urls: [],
      price_amount: 14.99,
      price_text: '£14.99',
      age_mark_on_listing: 'Chunky wax crayons for little hands (toddler and preschool listing copy)',
      age_signals: ageRange(18, 60, 'Chunky crayons for toddlers and preschoolers'),
      key_specs: { piece_count: '5 wax crayons', other: 'Bing character sleeves' },
      product_description_under_30_words:
        'Five chunky Bing wax crayons with character sleeves, thick enough for small hands practising short first scribbles on paper at the table.',
      ember_verdict:
        'Character crayons can pull a reluctant scribbler to the table when plain sticks look dull. Cerda keeps the sticks chunky for little hands while Bing art adds a familiar face. Best near eighteen months when SES and Crayola tools already cover grip basics and you want a fifth brand for gift variety.',
      rank_rationale: '#5: third brand line for gift variety after SES and Crayola caps.',
      why_it_fits: 'Character chunky wax.',
      caveats: 'Age mark soft on PDP; overlaps band at 18m only.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Character gift.',
      ownership_note: 'Skip if Bing crayons already live in the drawer.',
      safety_notes: 'Supervise; check packaging age before gift wrap.',
      founder_qa_flag: 'check_age_fit',
      ...spec(
        'Toytastic UK buyable Cerda Bing Wax Crayons; chunky toddler crayon copy on PDP without hard 3+ mark; verified buyable 2026-07-24; founder age QA flagged.',
      ),
      evidence_sources: ['toytastic.co.uk cerda-bing-wax-crayons'],
      substitute_if_unavailable: 'SES Creative My First Crayons',
    }),
  ];

  const backups = [
    backupRow({
      longlist_rank: 6,
      product_name: 'SES Creative My First Crayons',
      brand: 'SES Creative',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/ses-my-first-crayons/',
      price_text: '£13.99',
      age_mark_on_listing: '1–4 years',
      summary_reason: 'Third SES stick set.',
      rank_rationale: 'Rank 6: brand cap.',
      missed_top5_reason: 'Third SES Creative SKU; brand cap already full.',
    }),
    backupRow({
      longlist_rank: 7,
      product_name: 'SES Creative My First Fingerpaint 4 Pack',
      brand: 'SES Creative',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/ses-creative-my-first-fingerpaint-4-pack/',
      price_text: '£9.99',
      age_mark_on_listing: '1–4 years',
      summary_reason: 'Fingerpaint medium.',
      rank_rationale: 'Rank 7: paint not crayon stick.',
      missed_top5_reason: 'Fingerpaint medium; brand cap also full.',
    }),
    backupRow({
      longlist_rank: 8,
      product_name: 'SES Creative My First Colouring with Water Dinos',
      brand: 'SES Creative',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/ses-creative-my-first-colouring-with-water-dinos/',
      price_text: '£9.99',
      age_mark_on_listing: '1–4 years',
      summary_reason: 'Water colouring.',
      rank_rationale: 'Rank 8: water pen.',
      missed_top5_reason: 'Water colouring cards; not chunky wax crayons.',
    }),
    backupRow({
      longlist_rank: 9,
      product_name: 'SES Creative My First Crayons with Animal Cards',
      brand: 'SES Creative',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/ses-creative-my-first-crayons-animal-cards/',
      price_text: '£12.99',
      age_mark_on_listing: '1–4 years',
      summary_reason: 'Card kit.',
      rank_rationale: 'Rank 9: kit.',
      missed_top5_reason: 'Extra SES kit; brand cap full.',
    }),
    backupRow({
      longlist_rank: 10,
      product_name: 'Crayola My First Tripod Grip Crayons',
      brand: 'Crayola',
      retailer: 'Smyths',
      product_url:
        'https://www.smythstoys.com/uk/en-gb/toys/arts-and-crafts/crayons-and-pastels/crayola-my-first-tripod-grip-crayons/p/203441',
      price_text: '£6.99',
      age_mark_on_listing: '12 months +',
      summary_reason: 'Third Crayola.',
      rank_rationale: 'Rank 10: brand cap.',
      missed_top5_reason: 'Third Crayola My First SKU; brand cap already full.',
    }),
    backupRow({
      longlist_rank: 11,
      product_name: 'IKEA MALA wax crayon mixed colours',
      brand: 'IKEA',
      retailer: 'IKEA',
      product_url: 'https://www.ikea.com/gb/en/p/mala-wax-crayon-mixed-colours-00455547/',
      price_text: '£1.50',
      age_mark_on_listing: 'Recommended from 3 years',
      summary_reason: 'Age fail.',
      rank_rationale: 'Rank 11: 3y.',
      missed_top5_reason: 'Recommended from 3 years; fails 16-18m overlap.',
    }),
    backupRow({
      longlist_rank: 12,
      product_name: 'Moxy Colouring Case 86 Piece',
      brand: 'Moxy',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/moxy-colouring-case-86-piece-fsc-wood/',
      price_text: '£19.99',
      age_mark_on_listing: 'School art case',
      summary_reason: 'Too advanced.',
      rank_rationale: 'Rank 12: case.',
      missed_top5_reason: 'Large school art case; not first scribbles.',
    }),
    backupRow({
      longlist_rank: 13,
      product_name: 'Corolle Miss Floral Sweet Dreams Soft Doll',
      brand: 'Corolle',
      retailer: 'Adventure Toys',
      product_url: 'https://www.adventuretoys.co.uk/corolle-miss-floral-sweet-dreams-soft-doll/',
      price_text: '£19.99',
      age_mark_on_listing: 'Birth +',
      summary_reason: 'Doll.',
      rank_rationale: 'Rank 13: wrong category.',
      missed_top5_reason: 'Doll care category.',
    }),
    backupRow({
      longlist_rank: 14,
      product_name: 'Scrunch Ball',
      brand: 'Scrunch',
      retailer: 'Adventure Toys',
      product_url: 'https://www.adventuretoys.co.uk/scrunch-ball/',
      price_text: '£12.99',
      age_mark_on_listing: 'Toddler',
      summary_reason: 'Ball.',
      rank_rationale: 'Rank 14: wrong category.',
      missed_top5_reason: 'Soft ball category.',
    }),
    backupRow({
      longlist_rank: 15,
      product_name: 'Doidy Cup',
      brand: 'Doidy',
      retailer: 'Boots',
      product_url: 'https://www.boots.com/doidy-cup-10150006',
      price_text: '£4.50',
      age_mark_on_listing: '3 months +',
      summary_reason: 'Cup.',
      rank_rationale: 'Rank 15: meals.',
      missed_top5_reason: 'Open cup category.',
    }),
  ];

  pack(
    picks,
    backups,
    [
      skipRow({
        product_name: 'IKEA MALA wax crayon mixed colours',
        brand: 'IKEA',
        retailer: 'IKEA',
        product_url: 'https://www.ikea.com/gb/en/p/mala-wax-crayon-mixed-colours-00455547/',
        age_mark_on_listing: 'Recommended from 3 years',
        skip_reason: 'Recommended from 3 years; fails 16-18m overlap.',
      }),
      skipRow({
        product_name: 'IKEA MALA coloured pencils',
        brand: 'IKEA',
        retailer: 'IKEA',
        product_url: 'https://www.ikea.com/gb/en/p/mala-coloured-pencil-mixed-colours-70456586/',
        age_mark_on_listing: 'Not suitable under 4 years',
        skip_reason: '4+ coloured pencils; fails age and choking notes.',
      }),
      skipRow({
        product_name: 'School fine crayons and gel pens',
        brand: 'Various',
        retailer: 'Toytastic',
        product_url: 'https://toytastic.co.uk/product/ses-creative-my-first-colourball/',
        skip_reason: 'Fine school tools fail fist grip first scribbles brief.',
        evidence_notes: 'Category exclusion; Colourball URL is host placeholder only.',
      }),
      skipRow({
        product_name: 'Amazon UK crayon listings',
        brand: 'Various',
        retailer: 'Amazon UK',
        product_url: 'https://www.amazon.co.uk/s?k=toddler+chunky+crayons',
        skip_reason: 'Amazon UK bot wall blocked product page verification.',
      }),
      skipRow({
        product_name: 'Moxy Colouring Case 86 Piece',
        brand: 'Moxy',
        retailer: 'Toytastic',
        product_url: 'https://toytastic.co.uk/product/moxy-colouring-case-86-piece-fsc-wood/',
        skip_reason: 'Large school art case; not first scribbles for 16-18m.',
      }),
    ],
    {
      ownership_class: 'single',
      brief_id: '16-18m_cat_chunky_crayons',
      category_entity_id: 'cat_chunky_crayons',
      category_label: 'Chunky crayons and first scribbles',
      cluster_entity_id: 'ent_cluster_making_mark',
      cluster_label: 'I’m making my mark',
      audience_lens: 'both',
      buyer_mode_label: 'Good gift',
      gift_friendly: true,
      show_gift_action: true,
      educational_objective: 'Chunky first crayons and early mark tools for fist grips and short scribbles.',
      age_stage_nuance:
        'Versus earlier mouthing-only toys: now the job is a short mark on paper with a grip that fits a whole hand.',
      what_to_look_for: 'Chunky sticks or fist balls, 1–4y or 12m+ marks, washable options, UK buyable.',
      what_to_avoid: '3+ only MALA crayons, school fine tools, Amazon bot-wall primaries.',
      methodology:
        'Benchmarked SES My First crayon tools on Toytastic and Crayola My First on Smyths/Boots, plus Cerda Bing wax. Captured age marks. Ranked fist ball, cord beads, jumbo sticks, washable sticks, character wax. URL and availability verified 2026-07-24.',
      buying_factor_memo:
        'Order follows fist grip tools first, then classic jumbo sticks, then washable and character variety. Brand caps keep SES and Crayola at two each. Buyable UK specialist and high street PDPs beat Amazon bot-wall listings.',
      source_mix_summary: {
        retailers_checked: ['Toytastic', 'Smyths', 'Boots', 'IKEA GB', 'Amazon UK'],
        brand_sites_checked: ['SES Creative', 'Crayola', 'Cerda', 'IKEA'],
        editorial_sources_checked: [],
        community_sources_checked: [],
        safety_sources_checked: ['Listing age marks'],
        preloved_sources_checked: [],
      },
    },
  );
}

// ——— open cups ———
{
  const picks = [
    pickBase({
      rank: 1,
      longlist_rank: 1,
      public_rank: 1,
      best_for_tag: 'Best for true open rim',
      product_name: 'Doidy Cup',
      brand: 'Doidy',
      retailer: 'Boots',
      product_url: 'https://www.boots.com/doidy-cup-10150006',
      alternate_urls: ['https://growingsmiles.co.uk/shop/doidy-cup/'],
      price_amount: 4.5,
      price_text: '£4.50',
      age_mark_on_listing: '3 months +',
      age_signals: ageRange(3, 36, '3 months +'),
      key_specs: { capacity: '200ml', other: 'Slanted open rim, two handles' },
      product_description_under_30_words:
        'A slanted open cup with two handles that lets toddlers see the drink and sip from an open rim without a spout or valve.',
      ember_verdict:
        'Taking charge at meals at this age often means an open rim, not another valved trainer. The Doidy slant shows the liquid and keeps the sip short. Best when spout cups already live in the cupboard and you want one open cup for supervised table drinks.',
      rank_rationale: '#1 over #2: true open rim; Vital Baby is free flow spout.',
      why_it_fits: 'Open rim first cup.',
      caveats: 'Expect spills; supervise.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Small practical gift.',
      ownership_note: 'Skip a second Doidy if one already sits on the highchair tray.',
      safety_notes: 'Supervise; start with small amounts.',
      ...spec(
        'Boots UK buyable Doidy Cup; Growing Smiles alternate PDP also buyable; 3m+ mark; verified 2026-07-24.',
      ),
      evidence_sources: ['boots.com doidy-cup', 'growingsmiles.co.uk doidy'],
      substitute_if_unavailable: 'Vital Baby Hydrate Free Flow Cup',
    }),
    pickBase({
      rank: 2,
      longlist_rank: 2,
      public_rank: 2,
      best_for_tag: 'Best for free flow spout travel',
      product_name: 'Vital Baby Hydrate Free Flow Cup',
      brand: 'Vital Baby',
      retailer: 'Superdrug',
      product_url: 'https://www.superdrug.com/baby/sippy-cups/vital-baby-hydrate-free flow-cup/p/850654',
      alternate_urls: [
        'https://www.johnlewis.com/vital-baby-hydrate-free flow-cup-200ml-natural-stone/p112856635',
      ],
      price_amount: 2.49,
      price_text: '£2.49',
      age_mark_on_listing: '4 months +',
      age_signals: ageRange(4, 36, '4 months +'),
      key_specs: { capacity: '200ml', other: 'Free-flow spout, flip lid' },
      product_description_under_30_words:
        'A 200ml free flow spout cup with easy-grip handles and a flip lid for bag days when a true open rim is too splashy.',
      ember_verdict:
        'Open rims win at the table; free flow spouts help on short outings without a valve. Vital Baby keeps the flow honest while the flip lid calms bag leaks. Choose when Doidy already covers mealtime and you want a cheap free flow option for the changing bag.',
      rank_rationale: '#2 over #3: free flow spout job; Tommee Tippee Explora is similar with handles.',
      why_it_fits: 'Free-flow travel cup.',
      caveats: 'Not a true open rim.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Low-cost practical gift.',
      ownership_note: 'Skip if a free flow spout cup already lives in the bag.',
      safety_notes: 'Supervise.',
      ...spec(
        'Superdrug UK buyable Vital Baby Hydrate Free Flow Cup; 4m+; John Lewis alternate listed; verified 2026-07-24 after UK host allowlist.',
      ),
      evidence_sources: ['superdrug.com vital-baby-hydrate-free flow'],
      substitute_if_unavailable: 'Tommee Tippee Explora First Cup 2 Pack',
    }),
    pickBase({
      rank: 3,
      longlist_rank: 3,
      public_rank: 3,
      best_for_tag: 'Best for first Explora free flow',
      product_name: 'Tommee Tippee Explora First Cup 2 Pack',
      brand: 'Tommee Tippee',
      retailer: 'Boots',
      product_url: 'https://www.boots.com/tommee-tippee-explora-first-cup-2-pack-10202518',
      alternate_urls: [],
      price_amount: 6.99,
      price_text: '£6.99',
      age_mark_on_listing: '4 months +',
      age_signals: ageRange(4, 36, '4 months +'),
      key_specs: { piece_count: '2 cups', other: 'Soft free flow spout' },
      product_description_under_30_words:
        'A two pack of Tommee Tippee Explora first cups with soft free flow spouts and handles sized for early independent sips.',
      ember_verdict:
        'A two pack means one cup at home and one in the bag without hunting lids. Explora free flow stays kinder to gums than hard valves. Best when Vital Baby stock is thin and you want a familiar high street free flow pair.',
      rank_rationale: '#3 over #4: two pack value; First Cup single is simpler spare.',
      why_it_fits: 'Free-flow Explora pair.',
      caveats: 'Not open rim.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Useful two pack.',
      ownership_note: 'Skip if Explora cups already fill the cupboard.',
      safety_notes: 'Supervise.',
      ...spec(
        'Boots UK buyable Tommee Tippee Explora First Cup 2-pack; free flow first cup; verified 2026-07-24.',
      ),
      evidence_sources: ['boots.com tommee-tippee-explora-first-cup-2-pack'],
      substitute_if_unavailable: 'Tommee Tippee First Cup',
    }),
    pickBase({
      rank: 4,
      longlist_rank: 4,
      public_rank: 4,
      best_for_tag: 'Best for single First Cup spare',
      product_name: 'Tommee Tippee First Cup',
      brand: 'Tommee Tippee',
      retailer: 'Boots',
      product_url: 'https://www.boots.com/tommee-tippee-first-cup-10202516',
      alternate_urls: [],
      price_amount: 4.99,
      price_text: '£4.99',
      age_mark_on_listing: '4 months +',
      age_signals: ageRange(4, 36, '4 months +'),
      key_specs: { other: 'First cup with soft spout' },
      product_description_under_30_words:
        'A single Tommee Tippee First Cup with a soft spout and handles for early sips when you need one spare rather than a two pack.',
      ember_verdict:
        'Sometimes you only need one spare cup for changing bag days. First Cup keeps the Tommee Tippee soft spout idea without buying a pair. Choose when the Explora two pack already covers home and you want a cheaper single spare.',
      rank_rationale: '#4 over #5: second Tommee Tippee under brand cap; Miracle 360 is valve.',
      why_it_fits: 'Single free flow spare.',
      caveats: 'Second Tommee Tippee; brand cap full.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Small spare gift.',
      ownership_note: 'Pick two pack OR single first.',
      safety_notes: 'Supervise.',
      ...spec(
        'Boots UK buyable Tommee Tippee First Cup; verified 2026-07-24.',
      ),
      evidence_sources: ['boots.com tommee-tippee-first-cup'],
      substitute_if_unavailable: 'Tommee Tippee Explora First Cup 2 Pack',
    }),
    pickBase({
      rank: 5,
      longlist_rank: 5,
      public_rank: 5,
      best_for_tag: 'Best for soft spout trainer spare',
      product_name: 'Philips Avent Natural Response Trainer Cup 150ml',
      brand: 'Philips Avent',
      retailer: 'Boots',
      product_url:
        'https://www.boots.com/philips-avent-natural-response-trainer-cup-150ml-10275508',
      alternate_urls: [],
      price_amount: 8.99,
      price_text: '£8.99',
      age_mark_on_listing: '6 months +',
      age_signals: ageRange(6, 36, '6 months +'),
      key_specs: { capacity: '150ml', other: 'Soft spout trainer' },
      product_description_under_30_words:
        'A 150ml Philips Avent trainer cup with a soft spout and handles for early sips when you want a third brand beside Doidy and Tommee Tippee.',
      ember_verdict:
        'Brand variety helps when Boots stock of free flow cups runs thin. Avent keeps a soft spout and small capacity for supervised table drinks. Best as a spare trainer path once open Doidy and free flow Explora already cover the main jobs.',
      rank_rationale: '#5: third brand spare after Doidy open and Tommee Tippee free flow pair.',
      why_it_fits: 'Soft spout trainer spare.',
      caveats: 'Trainer spout; not a true open rim. Check free flow vs valve on the live SKU.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Practical spare.',
      ownership_note: 'Skip if Avent trainers already fill the cupboard.',
      safety_notes: 'Supervise.',
      founder_qa_flag: 'check_age_fit',
      ...spec(
        'Boots UK buyable Philips Avent Natural Response Trainer Cup; 6m+; used as third brand soft spout spare after open and free flow primaries; verified 2026-07-24.',
      ),
      evidence_sources: ['boots.com philips-avent-natural-response-trainer'],
      substitute_if_unavailable: 'Tommee Tippee Explora Easy Drink Cup',
    }),
  ];

  const backups = [
    backupRow({
      longlist_rank: 6,
      product_name: 'Tommee Tippee Explora Easy Drink Cup',
      brand: 'Tommee Tippee',
      retailer: 'Boots',
      product_url: 'https://www.boots.com/tommee-tippee-explora-easy-drink-cup',
      price_text: '£5.99',
      age_mark_on_listing: '4 months +',
      summary_reason: 'Third TT.',
      rank_rationale: 'Rank 6: brand cap.',
      missed_top5_reason: 'Third Tommee Tippee SKU; brand cap already full.',
    }),
    backupRow({
      longlist_rank: 7,
      product_name: 'Munchkin Miracle 360 Trainer Cup',
      brand: 'Munchkin',
      retailer: 'Munchkin UK',
      product_url: 'https://www.munchkin.co.uk/products/miracle-360-sippy-cup-7oz-207ml',
      price_text: '£8.99',
      age_mark_on_listing: '6 months +',
      summary_reason: 'Valve rim.',
      rank_rationale: 'Rank 7: not free flow.',
      missed_top5_reason: '360 valve rim is not open or free flow.',
    }),
    backupRow({
      longlist_rank: 8,
      product_name: 'Nuby No Spill Easy Grip Trainer Cup',
      brand: 'Nuby',
      retailer: 'Boots',
      product_url: 'https://www.boots.com/nuby-no spill-easy-grip-trainer-cup-10220690',
      price_text: '£6.99',
      age_mark_on_listing: '6 months +',
      summary_reason: 'No-spill valve.',
      rank_rationale: 'Rank 8: valve.',
      missed_top5_reason: 'No-spill valve cup; fails free flow brief.',
    }),
    backupRow({
      longlist_rank: 9,
      product_name: 'Doidy Cup (Growing Smiles specialist)',
      brand: 'Doidy',
      retailer: 'Growing Smiles',
      product_url: 'https://growingsmiles.co.uk/shop/doidy-cup/',
      price_text: '£5.99',
      age_mark_on_listing: '3 months +',
      summary_reason: 'Second Doidy retailer.',
      rank_rationale: 'Rank 9: brand duplicate.',
      missed_top5_reason: 'Same Doidy brand already #1 via Boots.',
    }),
    backupRow({
      longlist_rank: 10,
      product_name: 'Boots Munchkin Miracle 360',
      brand: 'Munchkin',
      retailer: 'Boots',
      product_url: 'https://www.boots.com/munchkin-miracle-360-trainer-cup-207ml-10220685',
      price_text: '£8.00',
      age_mark_on_listing: '6 months +',
      summary_reason: 'Valve.',
      rank_rationale: 'Rank 10: valve.',
      missed_top5_reason: 'Valve 360 cup; not free flow.',
    }),
    backupRow({
      longlist_rank: 11,
      product_name: 'Scrunch Ball',
      brand: 'Scrunch',
      retailer: 'Adventure Toys',
      product_url: 'https://www.adventuretoys.co.uk/scrunch-ball/',
      price_text: '£12.99',
      age_mark_on_listing: 'Toddler',
      summary_reason: 'Wrong category.',
      rank_rationale: 'Rank 11: ball.',
      missed_top5_reason: 'Soft ball category.',
    }),
    backupRow({
      longlist_rank: 12,
      product_name: 'Corolle Miss Floral Sweet Dreams Soft Doll',
      brand: 'Corolle',
      retailer: 'Adventure Toys',
      product_url: 'https://www.adventuretoys.co.uk/corolle-miss-floral-sweet-dreams-soft-doll/',
      price_text: '£19.99',
      age_mark_on_listing: 'Birth +',
      summary_reason: 'Doll.',
      rank_rationale: 'Rank 12: care.',
      missed_top5_reason: 'Doll care category.',
    }),
    backupRow({
      longlist_rank: 13,
      product_name: 'SES Creative My First Colourball',
      brand: 'SES Creative',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/ses-creative-my-first-colourball/',
      price_text: '£16.99',
      age_mark_on_listing: '1–4 years',
      summary_reason: 'Crayon.',
      rank_rationale: 'Rank 13: art.',
      missed_top5_reason: 'Crayons category.',
    }),
    backupRow({
      longlist_rank: 14,
      product_name: 'Priddy First 100 Words',
      brand: 'Priddy Books',
      retailer: 'Priddy Books',
      product_url: 'https://priddybooks.com/gb/books/first-100-words/',
      price_text: '£7.99',
      age_mark_on_listing: '0–2 years',
      summary_reason: 'Book.',
      rank_rationale: 'Rank 14: words.',
      missed_top5_reason: 'First-word books category.',
    }),
    backupRow({
      longlist_rank: 15,
      product_name: 'Quercetti FlipCar Racetrack',
      brand: 'Quercetti',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/quercetti-flipcar-racetrack/',
      price_text: '£28.99',
      age_mark_on_listing: '18 months +',
      summary_reason: 'Ramp.',
      rank_rationale: 'Rank 15: ramp.',
      missed_top5_reason: 'Ramp rolling category.',
    }),
  ];

  pack(
    picks,
    backups,
    [
      skipRow({
        product_name: 'Munchkin Miracle 360 Trainer Cup',
        brand: 'Munchkin',
        retailer: 'Munchkin UK',
        product_url: 'https://www.munchkin.co.uk/products/miracle-360-sippy-cup-7oz-207ml',
        skip_reason: 'Valve 360 rim is not open or free flow.',
      }),
      skipRow({
        product_name: 'Nuby No Spill Easy Grip Trainer Cup',
        brand: 'Nuby',
        retailer: 'Boots',
        product_url: 'https://www.boots.com/nuby-no spill-easy-grip-trainer-cup-10220690',
        skip_reason: 'No-spill valve cup; fails free flow brief.',
      }),
      skipRow({
        product_name: 'Hard spout non-spill cups',
        brand: 'Various',
        retailer: 'Boots',
        product_url: 'https://www.boots.com/doidy-cup-10150006',
        skip_reason: 'Hard valve spouts fight open or free flow brief.',
        evidence_notes: 'Category exclusion; Doidy URL is host placeholder only.',
      }),
      skipRow({
        product_name: 'Amazon UK open cup listings',
        brand: 'Various',
        retailer: 'Amazon UK',
        product_url: 'https://www.amazon.co.uk/s?k=doidy+cup',
        skip_reason: 'Amazon UK bot wall blocked product page verification.',
      }),
      skipRow({
        product_name: 'Glass open cups without toddler handles',
        brand: 'Various',
        retailer: 'Boots',
        product_url: 'https://growingsmiles.co.uk/shop/doidy-cup/',
        skip_reason: 'Adult glass tumblers fail toddler grip and spill safety for this band.',
        evidence_notes: 'Category exclusion; Growing Smiles Doidy URL is host placeholder only.',
      }),
    ],
    {
      ownership_class: 'single',
      brief_id: '16-18m_cat_open_cup',
      category_entity_id: 'cat_open_cup',
      category_label: 'Open or free flow cup',
      cluster_entity_id: 'ent_cluster_meals_charge',
      cluster_label: 'I’m taking charge at meals',
      audience_lens: 'conor',
      buyer_mode_label: 'Parent buy',
      gift_friendly: false,
      show_gift_action: false,
      educational_objective: 'Open rim and free flow cups for supervised independent sips at meals and outings.',
      age_stage_nuance:
        'Versus earlier bottle-only drinks: now the job is a short supervised sip from a rim or free flow spout.',
      what_to_look_for: 'Open rim or free flow spout, handles, 3–6m+ marks, UK buyable.',
      what_to_avoid: 'Valve no spill cups as Top 5, Amazon bot-wall primaries, adult glass tumblers.',
      methodology:
        'Benchmarked Doidy open cup, Vital Baby free flow, Tommee Tippee Explora/First Cup and Philips Avent trainer on Boots, Superdrug and Growing Smiles. Captured age marks. Ranked true open rim first, then free flow, then brand spare. URL and availability verified 2026-07-24.',
      buying_factor_memo:
        'Order follows true open rim first, then free flow spout travel, then familiar Tommee Tippee free flow options, then a third brand soft spout spare. Valve 360 and no spill cups stay longlist or skips. Brand caps keep Tommee Tippee at two.',
      source_mix_summary: {
        retailers_checked: ['Boots', 'Superdrug', 'Growing Smiles', 'Munchkin UK', 'Amazon UK'],
        brand_sites_checked: ['Doidy', 'Vital Baby', 'Tommee Tippee', 'Philips Avent', 'Munchkin'],
        editorial_sources_checked: [],
        community_sources_checked: [],
        safety_sources_checked: ['Listing age marks'],
        preloved_sources_checked: [],
      },
    },
  );
}


