/**
 * Mode A builders for remaining 16-18m categories (ramp, dolls, crayons, cups, books).
 * Primaries smoke+availability checked 2026-07-24.
 */
import {
  sharedMeta,
  pickBase,
  longFromPick,
  backupRow,
  skipRow,
  ageRange,
  writeCategory,
} from './_lib.mjs';

const spec = (text) => ({
  rating_value: null,
  rating_count: null,
  rating_source: 'Specialist or brand PDP; on-page review aggregate not published',
  evidence_exemption: 'specialist',
  evidence_notes: text,
});

function pack(picks, backups, skips, meta) {
  writeCategory({
    ...sharedMeta,
    ...meta,
    top_picks: picks,
    longlist: [...picks.map((p, i) => longFromPick(p, i + 1)), ...backups],
    skips,
    guidance_notes: [
      {
        status: 'note',
        title: 'Borrow first',
        body: 'Check what you already own in this format before adding a near duplicate.',
      },
    ],
  });
}

// ——— ramp rolling ———
{
  const picks = [
    pickBase({
      rank: 1,
      longlist_rank: 1,
      public_rank: 1,
      best_for_tag: 'Best for flip and chase',
      product_name: 'Quercetti FlipCar Racetrack',
      brand: 'Quercetti',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/quercetti-flipcar-racetrack/',
      alternate_urls: [],
      price_amount: 28.99,
      price_text: '£28.99',
      age_mark_on_listing: '18 months +',
      age_signals: ageRange(18, 48, '18 months +'),
      key_specs: { other: 'Flip cars and track pieces' },
      product_description_under_30_words:
        'A short track set with chunky flip cars that race, tip and tumble after a push, sized for toddler hands on the floor.',
      ember_verdict:
        'At sixteen to eighteen months, testing what happens often means a push, a roll and a delighted chase. FlipCar keeps the run short enough for living-room floors without a huge circuit. Best near eighteen months when a single ball already feels too simple and hands want a car that flips.',
      rank_rationale: '#1 over #2: clearest ramp-and-roll job with cars; Migoga is drop tower not ramp.',
      why_it_fits: 'Ramp rolling with flip cars.',
      caveats: '18m+ overlaps band at the top only.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Bigger gift box.',
      ownership_note: 'Skip if a short car ramp already lives by the sofa.',
      safety_notes: 'Supervise small track pieces.',
      founder_qa_flag: 'check_age_fit',
      ...spec(
        'Toytastic UK buyable Quercetti FlipCar Racetrack; honest 18m+ mark overlapping 16-18m at upper end; verified 2026-07-24.',
      ),
      evidence_sources: ['toytastic.co.uk quercetti-flipcar-racetrack'],
      substitute_if_unavailable: 'Quercetti Migoga Tower Sound',
    }),
    pickBase({
      rank: 2,
      longlist_rank: 2,
      public_rank: 2,
      best_for_tag: 'Best for drop and sound roll',
      product_name: 'Quercetti Migoga Tower Sound',
      brand: 'Quercetti',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/quercetti-migoga-tower-sound/',
      alternate_urls: [],
      price_amount: 25.99,
      price_text: '£25.99',
      age_mark_on_listing: '18 months +',
      age_signals: ageRange(18, 48, '18 months +'),
      key_specs: { other: 'Sound marble tower' },
      product_description_under_30_words:
        'A clear spiral tower where large balls drop with a short sound trail, inviting toddlers to feed, watch and chase the roll.',
      ember_verdict:
        'When the question is what happens if I drop this, a sound tower answers out loud. Migoga Sound keeps balls large and the path visible on the floor. Choose when FlipCar is too heavy on track pieces and you want drop and roll on a small footprint.',
      rank_rationale: '#2 over #3: guided drop roll with sound; soft balls are freer chase.',
      why_it_fits: 'Drop and roll tower.',
      caveats: 'Second Quercetti; brand cap full. 18m+ upper overlap.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Cause and effect gift.',
      ownership_note: 'Skip if Spiral Tower already bought for stacking play.',
      safety_notes: 'Supervise assembly.',
      founder_qa_flag: 'check_age_fit',
      ...spec(
        'Toytastic UK buyable Quercetti Migoga Tower Sound; 18m+ mark; stock verified 2026-07-24.',
      ),
      evidence_sources: ['toytastic.co.uk quercetti-migoga-tower-sound'],
      substitute_if_unavailable: 'Quercetti Spiral Tower Baby Ball Run',
    }),
    pickBase({
      rank: 3,
      longlist_rank: 3,
      public_rank: 3,
      best_for_tag: 'Best for soft hallway roll',
      product_name: 'Scrunch Ball',
      brand: 'Scrunch',
      retailer: 'Adventure Toys',
      product_url: 'https://www.adventuretoys.co.uk/scrunch-ball/',
      alternate_urls: [],
      price_amount: 12.99,
      price_text: '£12.99',
      age_mark_on_listing: 'Toddler soft play ball',
      age_signals: ageRange(12, 60, 'Toddler soft play ball'),
      key_specs: { dimensions: '23cm inflated', materials: 'PVC' },
      product_description_under_30_words:
        'A light soft PVC ball you inflate with a straw, grippy enough for toddler throws and indoor chase without a heavy sports bounce.',
      ember_verdict:
        'Ramp days still need a free roll that invites a toddle after it. Soft Scrunch weight keeps hallway chase kind on shins and shelves. Bring it out when track sets feel too fussy and you want one ball that packs flat for the bag.',
      rank_rationale: '#3 over #4: freest roll distance; silicone sets win grip not hallway travel.',
      why_it_fits: 'Soft free roll for chase.',
      caveats: 'Also listed under soft balls category.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Easy wrap.',
      ownership_note: 'Skip a second soft ball if one already gets daily chase.',
      safety_notes: 'Adult inflate first uses.',
      ...spec(
        'Adventure Toys UK buyable Scrunch Ball; soft roll fits ramp-and-chase brief; verified 2026-07-24.',
      ),
      evidence_sources: ['adventuretoys.co.uk/scrunch-ball'],
      substitute_if_unavailable: 'Bigjigs Activity Balls',
    }),
    pickBase({
      rank: 4,
      longlist_rank: 4,
      public_rank: 4,
      best_for_tag: 'Best for grasp and roll set',
      product_name: 'Bigjigs Activity Balls',
      brand: 'Bigjigs',
      retailer: 'Adventure Toys',
      product_url: 'https://www.adventuretoys.co.uk/big-jigs-activity-balls/',
      alternate_urls: [],
      price_amount: 9.99,
      price_text: '£9.99',
      age_mark_on_listing: '12 months +',
      age_signals: ageRange(12, 36, '12 months +'),
      key_specs: { materials: 'Silicone', other: 'Set of textured balls' },
      product_description_under_30_words:
        'A set of soft silicone activity balls with open textures for grasp, squash and short rolls across carpet or hard floors.',
      ember_verdict:
        'Some rolling days are about the grab as much as the chase. Bigjigs silicone balls stay soft while textures invite a firmer hold. Useful when one Scrunch already covers hallway distance and you want a set you can leave in two rooms.',
      rank_rationale: '#4 over #5: multi-ball grasp set; fabric ball is quieter single roll.',
      why_it_fits: 'Graspable roll set.',
      caveats: 'Shorter roll than Scrunch.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Small set gift.',
      ownership_note: 'Not a second soft PVC ball.',
      safety_notes: 'Supervise mouthing.',
      ...spec(
        'Adventure Toys UK buyable Bigjigs Activity Balls; 12m+; verified 2026-07-24.',
      ),
      evidence_sources: ['adventuretoys.co.uk big-jigs-activity-balls'],
      substitute_if_unavailable: 'Les Deglingos Melimelos Activity Ball',
    }),
    pickBase({
      rank: 5,
      longlist_rank: 5,
      public_rank: 5,
      best_for_tag: 'Best for quiet fabric roll',
      product_name: 'Les Deglingos Melimelos Activity Ball',
      brand: 'Les Deglingos',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/les-deglingos-activity-ball-melimelos-the-deer/',
      alternate_urls: [],
      price_amount: 18.99,
      price_text: '£18.99',
      age_mark_on_listing: 'Birth to 18 months',
      age_signals: ageRange(0, 18, 'Birth to 18 months'),
      key_specs: { materials: 'Fabric', other: 'Tags and textures' },
      product_description_under_30_words:
        'A soft fabric activity ball with tags and textures, light enough to roll a short way and easy to pick up again after a crawl chase.',
      ember_verdict:
        'Hard floors can make plastic rolls too loud for evening play. This fabric ball keeps the chase soft and the grab interesting with tags. Best when silicone and PVC balls already sit in the basket and you want a quieter indoor option that still overlaps this band.',
      rank_rationale: '#5 completes set: quiet fabric roll after PVC and silicone.',
      why_it_fits: 'Quiet fabric roll.',
      caveats: 'Birth–18m ends at band max.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Soft gift.',
      ownership_note: 'Skip if a fabric activity ball already gets daily use.',
      safety_notes: 'Check tags for wear.',
      ...spec(
        'Toytastic UK buyable Les Deglingos Melimelos activity ball; birth–18m mark overlaps 16-18m; verified 2026-07-24.',
      ),
      evidence_sources: ['toytastic.co.uk les-deglingos-activity-ball'],
      substitute_if_unavailable: 'Scrunch Ball',
    }),
  ];

  const backups = [
    backupRow({
      longlist_rank: 6,
      product_name: 'Quercetti Spiral Tower Baby Ball Run',
      brand: 'Quercetti',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/quercetti-spiral-tower-06501/',
      price_text: '£19.99',
      age_mark_on_listing: '1 year +',
      summary_reason: 'Spiral drop tower backup.',
      rank_rationale: 'Rank 6: third Quercetti format.',
      missed_top5_reason: 'Brand cap already uses FlipCar and Migoga Sound.',
    }),
    backupRow({
      longlist_rank: 7,
      product_name: 'Quercetti Play Eco+ Spiral Tower Evo',
      brand: 'Quercetti',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/quercetti-play-eco-spiral-tower-evo/',
      price_text: '£22.99',
      age_mark_on_listing: '1 year +',
      summary_reason: 'Eco spiral twin.',
      rank_rationale: 'Rank 7: near duplicate.',
      missed_top5_reason: 'Near-duplicate spiral of Spiral Tower backup.',
    }),
    backupRow({
      longlist_rank: 8,
      product_name: 'Hape Stacking Jack',
      brand: 'Hape',
      retailer: 'Adventure Toys',
      product_url: 'https://www.adventuretoys.co.uk/hape-stacking-jack/',
      price_text: '£9.25',
      age_mark_on_listing: '12 months +',
      summary_reason: 'Stacker not ramp.',
      rank_rationale: 'Rank 8: wrong category.',
      missed_top5_reason: 'Stacking pegboard category, not ramp rolling.',
    }),
    backupRow({
      longlist_rank: 9,
      product_name: 'Goki Rainbow Wobble Stacker',
      brand: 'Goki',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/goki-rainbow-wobble-stacker/',
      price_text: '£21.99',
      age_mark_on_listing: '1 year +',
      summary_reason: 'Stacker.',
      rank_rationale: 'Rank 9: wrong category.',
      missed_top5_reason: 'Wobble stacker, not ramp.',
    }),
    backupRow({
      longlist_rank: 10,
      product_name: 'IKEA SANDBI soft ball',
      brand: 'IKEA',
      retailer: 'IKEA',
      product_url: 'https://www.ikea.com/gb/en/p/sandbi-soft-toy-ball-multicolour-20588616/',
      price_text: '£6.00',
      age_mark_on_listing: 'From birth',
      summary_reason: 'Unbuyable at research.',
      rank_rationale: 'Rank 10: stock fail.',
      missed_top5_reason: 'UK listing unbuyable during research.',
    }),
    backupRow({
      longlist_rank: 11,
      product_name: 'Corolle Miss Floral Sweet Dreams Soft Doll',
      brand: 'Corolle',
      retailer: 'Adventure Toys',
      product_url: 'https://www.adventuretoys.co.uk/corolle-miss-floral-sweet-dreams-soft-doll/',
      price_text: '£19.99',
      age_mark_on_listing: 'Birth +',
      summary_reason: 'Doll care.',
      rank_rationale: 'Rank 11: wrong category.',
      missed_top5_reason: 'Soft doll for care category.',
    }),
    backupRow({
      longlist_rank: 12,
      product_name: 'SES Creative My First Colourball',
      brand: 'SES Creative',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/ses-creative-my-first-colourball/',
      price_text: '£16.99',
      age_mark_on_listing: '1–4 years',
      summary_reason: 'Crayon tool.',
      rank_rationale: 'Rank 12: wrong category.',
      missed_top5_reason: 'Mark-making tool, not ramp.',
    }),
    backupRow({
      longlist_rank: 13,
      product_name: 'Doidy Cup',
      brand: 'Doidy',
      retailer: 'Boots',
      product_url: 'https://www.boots.com/doidy-cup-10150006',
      price_text: '£4.50',
      age_mark_on_listing: '3 months +',
      summary_reason: 'Cup.',
      rank_rationale: 'Rank 13: wrong category.',
      missed_top5_reason: 'Open cup category.',
    }),
    backupRow({
      longlist_rank: 14,
      product_name: 'Priddy First 100 Words',
      brand: 'Priddy Books',
      retailer: 'Priddy Books',
      product_url: 'https://priddybooks.com/gb/books/first-100-words/',
      price_text: '£7.99',
      age_mark_on_listing: '0–2 years',
      summary_reason: 'Book.',
      rank_rationale: 'Rank 14: wrong category.',
      missed_top5_reason: 'First-word book category.',
    }),
    backupRow({
      longlist_rank: 15,
      product_name: 'Goki Dolls Bed',
      brand: 'Goki',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/goki-dolls-bed/',
      price_text: '£16.99',
      age_mark_on_listing: '1 year +',
      summary_reason: 'Doll bed.',
      rank_rationale: 'Rank 15: care prop.',
      missed_top5_reason: 'Doll care prop, not ramp.',
    }),
  ];

  pack(
    picks,
    backups,
    [
      skipRow({
        product_name: 'Amazon UK ramp toy search',
        brand: 'Various',
        retailer: 'Amazon UK',
        product_url: 'https://www.amazon.co.uk/s?k=toddler+ramp+toy',
        skip_reason: 'Amazon UK bot wall blocked product page verification.',
      }),
      skipRow({
        product_name: 'IKEA SANDBI soft ball',
        brand: 'IKEA',
        retailer: 'IKEA',
        product_url: 'https://www.ikea.com/gb/en/p/sandbi-soft-toy-ball-multicolour-20588616/',
        skip_reason: 'UK listing returned unbuyable during research.',
      }),
      skipRow({
        product_name: 'Goki Dolphin Balancing Game',
        brand: 'Goki',
        retailer: 'Toytastic',
        product_url: 'https://toytastic.co.uk/product/goki-dolphin-balancing-game/',
        age_mark_on_listing: '3 years +',
        skip_reason: '3+ age mark fails 16-18m overlap.',
      }),
      skipRow({
        product_name: 'Hard match sports balls',
        brand: 'Various',
        retailer: 'Smyths',
        product_url: 'https://toytastic.co.uk/product/quercetti-flipcar-racetrack/',
        skip_reason: 'Hard sports balls fail soft roll brief for this band.',
        evidence_notes: 'Category exclusion; FlipCar URL is host placeholder only.',
      }),
      skipRow({
        product_name: 'Melissa & Doug wooden ramp (24m+)',
        brand: 'Melissa & Doug',
        retailer: 'Amazon UK',
        product_url: 'https://www.amazon.co.uk/dp/B000EGDKI6',
        skip_reason: 'Manufacturer min often 24m+; Amazon primary unreliable here.',
      }),
    ],
    {
      ownership_class: 'single',
      brief_id: '16-18m_cat_ramp_rolling_toys',
      category_entity_id: 'cat_ramp_rolling_toys',
      category_label: 'Ramp and rolling toys',
      cluster_entity_id: 'ent_cluster_testing_what_happens',
      cluster_label: 'I’m testing what happens',
      audience_lens: 'both',
      buyer_mode_label: 'Good gift',
      gift_friendly: true,
      show_gift_action: true,
      educational_objective: 'Short ramp and roll toys that invite push, drop, chase and another try.',
      age_stage_nuance:
        'Versus earlier sit-and-mouth rolls: now the job is a short push or drop that travels just far enough to chase.',
      what_to_look_for: 'Chunky cars or large balls, short tracks, 12–18m marks, UK buyable.',
      what_to_avoid: 'Huge circuits, 3+ only tracks, Amazon bot-wall primaries, hard sports balls.',
      methodology:
        'Benchmarked Quercetti FlipCar and Migoga Sound plus soft roll balls on Toytastic and Adventure Toys. Captured age marks from PDPs. Ranked for ramp job, drop-sound roll, free chase, grasp set, quiet fabric. URL and availability verified 2026-07-24.',
      buying_factor_memo:
        'Order follows clearest ramp-and-roll job first, then guided drop tower, then free soft rolls for chase. Brand cap keeps Quercetti at two. Age overlap with 16-18m beats 3+ balancing games. Buyable UK specialist PDPs beat Amazon bot-wall listings.',
      source_mix_summary: {
        retailers_checked: ['Toytastic', 'Adventure Toys', 'IKEA GB', 'Amazon UK'],
        brand_sites_checked: ['Quercetti', 'Scrunch', 'Bigjigs', 'Les Deglingos'],
        editorial_sources_checked: [],
        community_sources_checked: [],
        safety_sources_checked: ['Listing age marks'],
        preloved_sources_checked: [],
      },
    },
  );
}

console.log('ramp done');
