import {
  sharedMeta,
  pickBase,
  longFromPick,
  backupRow,
  skipRow,
  ageRange,
  writeCategory,
} from './_lib.mjs';

const spec = (text) => ({
  rating_value: null,
  rating_count: null,
  rating_source: 'Specialist or brand PDP; on-page review aggregate not published',
  evidence_exemption: 'specialist',
  evidence_notes: text,
});

function pack(picks, backups, skips, meta) {
  writeCategory({
    ...sharedMeta,
    ...meta,
    top_picks: picks,
    longlist: [...picks.map((p, i) => longFromPick(p, i + 1)), ...backups],
    skips,
    guidance_notes: [
      {
        status: 'note',
        title: 'Borrow first',
        body: 'Check what you already own in this format before adding a near duplicate.',
      },
    ],
  });
}

// ——— stacking pegboard ———
{
  const picks = [
    pickBase({
      rank: 1,
      longlist_rank: 1,
      public_rank: 1,
      best_for_tag: 'Best for first ring stacks',
      product_name: 'Hape Stacking Jack',
      brand: 'Hape',
      retailer: 'Adventure Toys',
      product_url: 'https://www.adventuretoys.co.uk/hape-stacking-jack/',
      alternate_urls: [],
      price_amount: 9.25,
      price_text: '£9.25',
      age_mark_on_listing: '12 months +',
      age_signals: ageRange(12, 36, '12 months +'),
      key_specs: { piece_count: '8 pieces', materials: 'Wood', other: 'Character ring stacker' },
      product_description_under_30_words:
        'A wooden stacking character with chunky rings you dress from toes to hat in any order, sized for toddler hands learning size play.',
      ember_verdict:
        'Busy hands at sixteen to eighteen months want rings that fit, tip and try again on a short pole. Stacking Jack keeps pieces large and friendly without a stiff size rule. A clear first stack when you want wood quality at a small price before bigger wobble towers.',
      rank_rationale: '#1 over #2: simplest first stack with 12m+ mark and low price; wobble towers add challenge later.',
      why_it_fits: 'Classic ring stack for busy hands cluster.',
      caveats: 'Low stock signal on retailer; check before gift wrap.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Small wooden gift.',
      ownership_note: 'Skip if a rainbow ring stacker already lives on the shelf.',
      safety_notes: 'Supervise; no small loose parts beyond rings.',
      ...spec(
        'Adventure Toys UK GBP PDP for Hape Stacking Jack; 12m+ age mark; buyable with low-stock note checked 2026-07-24; strong Stage 2 stacking fit.',
      ),
      evidence_sources: ['adventuretoys.co.uk/hape-stacking-jack'],
      substitute_if_unavailable: 'Goki Rainbow Wobble Stacker',
    }),
    pickBase({
      rank: 2,
      longlist_rank: 2,
      public_rank: 2,
      best_for_tag: 'Best for wobbly towers',
      product_name: 'Goki Rainbow Wobble Stacker',
      brand: 'Goki',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/goki-rainbow-wobble-stacker/',
      alternate_urls: [],
      price_amount: 21.99,
      price_text: '£21.99',
      age_mark_on_listing: '1 year +',
      age_signals: ageRange(12, 36, '1 year +'),
      key_specs: { piece_count: '7 pieces', materials: 'Wood', dimensions: 'Approx 14cm high' },
      product_description_under_30_words:
        'Six chunky rainbow wooden rings on a rounded base that rocks as each piece is added, turning stacking into a balance try.',
      ember_verdict:
        'When steady poles feel too easy, a rocking base asks for slower hands. The Goki wobble stacker keeps rings big while the sway makes each place a small plan. Best once a flat stacker is already familiar and you want a tougher tower job.',
      rank_rationale: '#2 over #3: clearer wobble challenge than bear tower; trails Jack on first-buy simplicity.',
      why_it_fits: 'Wobble stacking for progressing hands.',
      caveats: 'Harder than flat base; may frustrate cautious starters.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Premium wooden gift.',
      ownership_note: 'Not a second flat ring set.',
      safety_notes: 'Supervise rocking play near table edges.',
      ...spec(
        'Toytastic UK buyable Goki Rainbow Wobble Stacker; 1y+ mark; in-stock count verified 2026-07-24; wobble stack fits pegboard/tower brief.',
      ),
      evidence_sources: ['toytastic.co.uk goki-rainbow-wobble-stacker'],
      substitute_if_unavailable: 'Goki Stacking Bear Wobble Tower',
    }),
    pickBase({
      rank: 3,
      longlist_rank: 3,
      public_rank: 3,
      best_for_tag: 'Best for character wobble',
      product_name: 'Goki Stacking Bear Wobble Tower',
      brand: 'Goki',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/goki-stacking-bear-wobble-tower/',
      alternate_urls: [],
      price_amount: 18.99,
      price_text: '£18.99',
      age_mark_on_listing: '1 year +',
      age_signals: ageRange(12, 36, '1 year +'),
      key_specs: { materials: 'Wood', other: 'Bear character stack' },
      product_description_under_30_words:
        'A wooden bear stacking tower with chunky pieces on a gentle wobble, inviting toddlers to build a short character stack on the floor.',
      ember_verdict:
        'Character stacks pull some toddlers in when plain rings look dull. The bear tower keeps the wobble idea while the face gives a finish to aim for. Choose when rainbow rings already sit on the shelf and you want a different wooden stack story.',
      rank_rationale: '#3 over #4: same Goki wobble family with character hook; music stacker is a different job.',
      why_it_fits: 'Character wobble stack.',
      caveats: 'Max two Goki brands in Top 5 already used; still distinct SKU.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Character wooden gift.',
      ownership_note: 'Pick rainbow OR bear wobble, not both.',
      safety_notes: 'Supervise.',
      ...spec(
        'Toytastic UK buyable Goki Stacking Bear Wobble Tower; 1y+; stock verified 2026-07-24; distinct from rainbow wobble via character form.',
      ),
      evidence_sources: ['toytastic.co.uk goki-stacking-bear-wobble-tower'],
      substitute_if_unavailable: 'Goki Rainbow Wobble Stacker',
    }),
    pickBase({
      rank: 4,
      longlist_rank: 4,
      public_rank: 4,
      best_for_tag: 'Best for nest and tap',
      product_name: 'Hape Wooden Musical Instrument Stacking Set',
      brand: 'Hape',
      retailer: 'Adventure Toys',
      product_url: 'https://www.adventuretoys.co.uk/hape-wooden-musical-instrument-stacking-set/',
      alternate_urls: [],
      price_amount: 34.99,
      price_text: '£34.99',
      age_mark_on_listing: '18 months +',
      age_signals: ageRange(18, 48, '18 months +'),
      key_specs: { piece_count: '5 nested instruments + beater', materials: 'Wood' },
      product_description_under_30_words:
        'Five nested wooden instruments that stack to tidy away, with a beater for drum, xylophone, cymbal, scratch and shaker play.',
      ember_verdict:
        'At the top of this band, stacking can mean nested boxes that also make sound. Hape nest and tap gives a tidy stack plus short music tries. Best near eighteen months when quieter ring stackers already feel too simple and you want sound with the stack.',
      rank_rationale: '#4 over #5: richer nested music stack; FlipCar is wrong category backup.',
      why_it_fits: 'Nesting stack with music.',
      caveats: '18m+ only overlaps band max.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Larger gift box.',
      ownership_note: 'Second Hape SKU; still under brand max of two.',
      safety_notes: 'Supervise beater.',
      ...spec(
        'Adventure Toys UK buyable Hape musical stacking set; honest 18m+ mark overlapping 16-18m at upper end; verified 2026-07-24.',
      ),
      evidence_sources: ['adventuretoys.co.uk hape-wooden-musical-instrument-stacking-set'],
      substitute_if_unavailable: 'Hape Stacking Jack',
      founder_qa_flag: 'check_age_fit',
    }),
    pickBase({
      rank: 5,
      longlist_rank: 5,
      public_rank: 5,
      best_for_tag: 'Best for spiral build towers',
      product_name: 'Quercetti Spiral Tower Baby Ball Run',
      brand: 'Quercetti',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/quercetti-spiral-tower-06501/',
      alternate_urls: [],
      price_amount: 19.99,
      price_text: '£19.99',
      age_mark_on_listing: '1 year +',
      age_signals: ageRange(12, 36, '1 year +'),
      key_specs: { piece_count: '9 pieces', dimensions: '40cm assembled' },
      product_description_under_30_words:
        'Snap together coloured spiral sections that build into a tall tower, then drop large balls for a short roll down the path.',
      ember_verdict:
        'Some stacking days are about building the tower itself, not only rings on a peg. Quercetti spiral sections click into a tall build toddlers can help assemble. Useful when wooden rings already feel finished and hands want a taller tower job with a roll at the end.',
      rank_rationale: '#5 completes set: build-the-tower path after wooden ring stackers; distinct from Hape/Goki wood.',
      why_it_fits: 'Tower build with pieces.',
      caveats: 'Also appears in soft-ball / ramp lists; ownership note across categories.',
      buy_borrow_hold_off: 'buy',
      gift_note: 'Cause and effect gift.',
      ownership_note: 'Skip if already bought for ball-run play.',
      safety_notes: 'Supervise assembly.',
      ...spec(
        'Toytastic UK buyable Quercetti Spiral Tower; 1y+; stacking tower assembly fits pegboard/tower brief; verified 2026-07-24.',
      ),
      evidence_sources: ['toytastic.co.uk Quercetti Spiral Tower'],
      substitute_if_unavailable: 'Quercetti Play Eco+ Spiral Tower Evo',
    }),
  ];
  // (dolphin 3+ kept as skip / longlist only)
  const backups = [
    backupRow({
      longlist_rank: 6,
      product_name: 'Quercetti Play Eco+ Spiral Tower Evo',
      brand: 'Quercetti',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/quercetti-play-eco-spiral-tower-evo/',
      price_text: '£22.99',
      age_mark_on_listing: '1 year +',
      summary_reason: 'Eco twin spiral.',
      rank_rationale: 'Rank 6: duplicate spiral format.',
      missed_top5_reason: 'Near-duplicate of Spiral Tower already in Top 5.',
    }),
    backupRow({
      longlist_rank: 7,
      product_name: 'Goki Dolphin Balancing Game',
      brand: 'Goki',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/goki-dolphin-balancing-game/',
      price_text: '£14.99',
      age_mark_on_listing: '3 years +',
      summary_reason: 'Age fail.',
      rank_rationale: 'Rank 7: 3+ balancing.',
      missed_top5_reason: '3+ age mark fails 16-18m overlap.',
    }),
    backupRow({
      longlist_rank: 8,
      product_name: 'Quercetti FlipCar Racetrack',
      brand: 'Quercetti',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/quercetti-flipcar-racetrack/',
      price_text: '£28.99',
      age_mark_on_listing: '18 months +',
      summary_reason: 'Ramp cars.',
      rank_rationale: 'Rank 8: ramp category.',
      missed_top5_reason: 'Flip cars belong in ramp rolling, not pegboard stacking.',
    }),
    backupRow({
      longlist_rank: 9,
      product_name: 'Scrunch Ball',
      brand: 'Scrunch',
      retailer: 'Adventure Toys',
      product_url: 'https://www.adventuretoys.co.uk/scrunch-ball/',
      price_text: '£12.99',
      age_mark_on_listing: 'Toddler soft ball',
      summary_reason: 'Ball not stacker.',
      rank_rationale: 'Rank 9: wrong category.',
      missed_top5_reason: 'Soft ball, not stacking pegboard.',
    }),
    backupRow({
      longlist_rank: 10,
      product_name: 'Bigjigs Activity Balls',
      brand: 'Bigjigs',
      retailer: 'Adventure Toys',
      product_url: 'https://www.adventuretoys.co.uk/big-jigs-activity-balls/',
      price_text: '£9.99',
      age_mark_on_listing: 'Silicone balls',
      summary_reason: 'Balls.',
      rank_rationale: 'Rank 10: wrong category.',
      missed_top5_reason: 'Activity balls, not towers.',
    }),
    backupRow({
      longlist_rank: 11,
      product_name: 'SES Creative My First Colourball',
      brand: 'SES Creative',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/ses-creative-my-first-colourball/',
      price_text: '£16.99',
      age_mark_on_listing: '1–4 years',
      summary_reason: 'Crayon.',
      rank_rationale: 'Rank 11: art tool.',
      missed_top5_reason: 'Crayon tool for mark-making category.',
    }),
    backupRow({
      longlist_rank: 12,
      product_name: 'Corolle Miss Floral Sweet Dreams Soft Doll',
      brand: 'Corolle',
      retailer: 'Adventure Toys',
      product_url: 'https://www.adventuretoys.co.uk/corolle-miss-floral-sweet-dreams-soft-doll/',
      price_text: '£19.99',
      age_mark_on_listing: 'Birth +',
      summary_reason: 'Doll.',
      rank_rationale: 'Rank 12: care play.',
      missed_top5_reason: 'Soft doll for care category.',
    }),
    backupRow({
      longlist_rank: 13,
      product_name: 'Quercetti Migoga Tower Sound',
      brand: 'Quercetti',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/quercetti-migoga-tower-sound/',
      price_text: '£25.99',
      age_mark_on_listing: '18 months +',
      summary_reason: 'Sound ball run.',
      rank_rationale: 'Rank 13: ramp/ball run.',
      missed_top5_reason: 'Ball run focus; Spiral already covers tower build.',
    }),
    backupRow({
      longlist_rank: 14,
      product_name: 'SES Creative My First Crayon Beads',
      brand: 'SES Creative',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/ses-creative-my-first-crayon-beads/',
      price_text: '£9.99',
      age_mark_on_listing: '1–4 years',
      summary_reason: 'Crayons.',
      rank_rationale: 'Rank 14: crayons.',
      missed_top5_reason: 'Mark-making tools.',
    }),
    backupRow({
      longlist_rank: 15,
      product_name: 'Les Deglingos Melimelos Activity Ball',
      brand: 'Les Deglingos',
      retailer: 'Toytastic',
      product_url: 'https://toytastic.co.uk/product/les-deglingos-activity-ball-melimelos-the-deer/',
      price_text: '£18.99',
      age_mark_on_listing: 'Birth to 18 months',
      summary_reason: 'Soft ball.',
      rank_rationale: 'Rank 15: ball.',
      missed_top5_reason: 'Soft activity ball, not pegboard stack.',
    }),
  ];

  pack(
    picks,
    backups,
    [
      skipRow({
        product_name: 'Goki Dolphin Balancing Game',
        brand: 'Goki',
        retailer: 'Toytastic',
        product_url: 'https://toytastic.co.uk/product/goki-dolphin-balancing-game/',
        age_mark_on_listing: '3 years +',
        skip_reason: '3+ age mark fails 16-18m overlap.',
      }),
      skipRow({
        product_name: 'Quercetti Jumbo Peggy',
        brand: 'Quercetti',
        retailer: 'Amazon UK',
        product_url: 'https://www.amazon.co.uk/dp/B084JKBD7J',
        age_mark_on_listing: '2+',
        skip_reason: 'Manufacturer 24 months; no overlap with 16-18m; Amazon primary unreliable here.',
      }),
      skipRow({
        product_name: 'Melissa & Doug Stack and Sort Board',
        brand: 'Melissa & Doug',
        retailer: 'Amazon UK',
        product_url: 'https://www.amazon.co.uk/dp/B00272N8Q2',
        age_mark_on_listing: '24 months / 3+ listing conflict',
        skip_reason: 'Strict manufacturer min 24m fails band overlap.',
      }),
      skipRow({
        product_name: 'Hape Stacking Jill',
        brand: 'Hape',
        retailer: 'Adventure Toys',
        product_url: 'https://www.adventuretoys.co.uk/hape-stacking-jill/',
        age_mark_on_listing: '12 months +',
        skip_reason: 'Out of stock twin of Stacking Jack at research time.',
      }),
      skipRow({
        product_name: 'Tiny loose peg mosaic boards',
        brand: 'Various',
        retailer: 'Toytastic',
        product_url: 'https://toytastic.co.uk/product/goki-rainbow-wobble-stacker/',
        skip_reason: 'Fine peg mosaics with 3+ marks fail age and choking risk for this band.',
        evidence_notes: 'Category exclusion; URL is safe stacker host only.',
      }),
    ],
    {
      ownership_class: 'single',
      brief_id: '16-18m_cat_stacking_pegboard',
      category_entity_id: 'cat_stacking_pegboard',
      category_label: 'Stacking pegboards and block towers',
      cluster_entity_id: 'ent_cluster_hands_busy',
      cluster_label: 'My hands are busy now',
      audience_lens: 'both',
      buyer_mode_label: 'Good gift',
      gift_friendly: true,
      show_gift_action: true,
      educational_objective: 'Chunky stacking and tower play for busy toddler hands.',
      age_stage_nuance:
        'Versus baby mouthing stacks: now the job is place, tip, rebuild and try a slightly taller tower.',
      what_to_look_for: 'Chunky wood rings, wobble towers, 12–18m marks, UK buyable.',
      what_to_avoid: '3+ fine peg mosaics; 24m+ only pegboards; out-of-stock twins.',
      methodology:
        'Benchmarked Hape and Goki stackers plus Quercetti tower builds on Adventure Toys and Toytastic. Captured age marks from PDPs. Ranked for first stack simplicity, wobble challenge, character, nest music, and spiral tower build. URL and availability verified 2026-07-24.',
      buying_factor_memo:
        'Order follows first-stack ease, then wobble challenge, then distinct formats. Age overlap with 16-18m beats 3+ balancing games. Brand cap keeps at most two Hape and two Goki. Buyable UK specialist PDPs beat Amazon bot-wall listings.',
      source_mix_summary: {
        retailers_checked: ['Adventure Toys', 'Toytastic', 'Argos', 'Amazon UK'],
        brand_sites_checked: ['Hape', 'Goki', 'Quercetti'],
        editorial_sources_checked: [],
        community_sources_checked: [],
        safety_sources_checked: ['Listing age marks'],
        preloved_sources_checked: [],
      },
    },
  );
}

console.log('stacking done — continuing in next chunk via import not needed');
