/**
 * Deterministic icon for wrapper tiles. Fallback for "More" section.
 */
import {
  Pencil,
  HeartHandshake,
  Hand,
  Activity,
  CheckCircle2,
  MessageCircle,
  Theater,
  Puzzle,
  CalendarCheck2,
  Users,
  Blocks,
  Shapes,
  Footprints,
  Eye,
  Layers,
  Apple,
  UtensilsCrossed,
  Shield,
  BookOpen,
  CalendarDays,
  Smile,
  Mic,
  HandMetal,
  CloudMoon,
  Milk,
  Moon,
  Stethoscope,
  PersonStanding,
  Sparkles,
  Compass,
  Droplets,
  type LucideIcon,
} from 'lucide-react';

const SLUG_TO_ICON: Record<string, LucideIcon> = {
  'burn-energy': Activity,
  'little-hands': Hand,
  'talk-understand': MessageCircle,
  'pretend-stories': Theater,
  'playing-with-others': Users,
  'big-feelings': HeartHandshake,
  'let-me-help': CheckCircle2,
  'figuring-things-out': Puzzle,
  'build-puzzles': Blocks,
  'shapes-colours': Shapes,
  transitions: CalendarCheck2,
  social_emotional: Users,
  'social-emotional': Users,
  self_care_independence: CheckCircle2,
  'self-care-independence': CheckCircle2,
  fine_motor: Hand,
  'fine-motor': Hand,
  gross_motor: Activity,
  'gross-motor': Activity,
  language_communication: MessageCircle,
  'language-communication': MessageCircle,
  cognitive_problem_solving: Puzzle,
  'cognitive-problem-solving': Puzzle,
  toileting: CalendarCheck2,
  'creative-expression-and-mark-making': Pencil,
  'emotional-regulation-and-self-awareness': HeartHandshake,
  'emotions-and-feelings': HeartHandshake,
  'fine-motor-control-and-hand-coordination': Hand,
  'gross-motor-skills-and-physical-confidence': Activity,
  'gross-motor-and-active-play': Activity,
  'independence-and-practical-skills': CheckCircle2,
  'toilet-training': CalendarCheck2,
  'toilet-training-and-independence': CalendarCheck2,
  'language-development-and-communication': MessageCircle,
  'language-and-questions': MessageCircle,
  'language-and-curiosity': MessageCircle,
  'pretend-play-and-imagination': Theater,
  'pretend-and-social-play': Theater,
  'pretend-and-peer-play': Theater,
  'problem-solving-and-cognitive-skills': Puzzle,
  'early-stem-and-spatial': Puzzle,
  'early-stem-and-matching': Puzzle,
  'routine-understanding-and-cooperation': CalendarCheck2,
  'transitions-and-emotions': CalendarCheck2,
  'visual-timers-and-transition-tools': CalendarCheck2,
  'social-skills-and-peer-interaction': Users,
  'spatial-reasoning-and-construction-play': Blocks,
  'shapes-and-colours': Shapes,
  'shapes-and-colors': Shapes,
  // 4–6m Conor-grade clusters
  ent_cluster_4_6_floor_strength: Activity,
  ent_cluster_4_6_hands: Hand,
  ent_cluster_4_6_faces_sounds: MessageCircle,
  ent_cluster_4_6_cause_effect: Sparkles,
  ent_cluster_4_6_body_world: PersonStanding,
  ent_cluster_4_6_safety: Shield,
  // 6–9m pilot clusters
  cluster_sitting_reaching: Hand,
  cluster_crawling_floor: Footprints,
  cluster_object_permanence: Eye,
  cluster_stacking_containment: Layers,
  cluster_mouth_sensory: Apple,
  cluster_first_foods: UtensilsCrossed,
  cluster_home_safety: Shield,
  cluster_books_sounds: BookOpen,
  // 9–12m pilot clusters
  ent_cluster_move: Footprints,
  ent_cluster_hands: Hand,
  ent_cluster_solve: Eye,
  ent_cluster_words: MessageCircle,
  ent_cluster_feeding: UtensilsCrossed,
  ent_cluster_safety: Shield,
  ent_cluster_stories: BookOpen,
  ent_cluster_days: CalendarDays,
  // 1–3m pilot clusters
  ent_cluster_faces_smiles_chats: Smile,
  ent_cluster_listen_and_coo: Mic,
  ent_cluster_watching_tracking: Eye,
  ent_cluster_tummy_head_control: Activity,
  ent_cluster_kicks_wriggles: Footprints,
  ent_cluster_first_grasps: HandMetal,
  ent_cluster_calm_crying_settling: CloudMoon,
  ent_cluster_feeding_clean_kit: Milk,
  ent_cluster_safe_sleep_setup: Moon,
  ent_cluster_health_first_trips: Stethoscope,
  // 13–15m Conor-grade clusters
  ent_cluster_working_things_out: Puzzle,
  ent_cluster_telling_things: MessageCircle,
  ent_cluster_copying_day: Theater,
  ent_cluster_braver_feet: Footprints,
  ent_cluster_meals_charge: UtensilsCrossed,
  ent_cluster_first_marks: Pencil,
  ent_cluster_joining_in: Users,
  ent_cluster_suddenly_everything: Shield,
  ent_cluster_between_baby_toddler: HeartHandshake,
  ent_cluster_change_scene: CalendarDays,
  // 16–18m clusters
  ent_cluster_16_18_little_adventures: Compass,
  ent_cluster_16_18_busy_hands: Hand,
  ent_cluster_16_18_cause_effect: Sparkles,
  ent_cluster_16_18_words_instructions: MessageCircle,
  ent_cluster_16_18_copying_life: Theater,
  ent_cluster_16_18_mark_mess: Pencil,
  ent_cluster_16_18_daily_practice: CalendarCheck2,
  ent_cluster_16_18_safer_home: Shield,
  // 19–21m clusters
  ent_cluster_19_21_words_pointing: MessageCircle,
  ent_cluster_19_21_pretend_copying: Theater,
  ent_cluster_19_21_busy_hands: Hand,
  ent_cluster_19_21_move_climb: Activity,
  ent_cluster_19_21_pouring_feeding: UtensilsCrossed,
  ent_cluster_19_21_big_feelings: HeartHandshake,
  ent_cluster_19_21_potty_bathroom: CalendarCheck2,
  ent_cluster_19_21_safer_home: Shield,
  // 25–27m clusters
  ent_cluster_talk_stories: MessageCircle,
  ent_cluster_pretend_helper_play: Theater,
  ent_cluster_busy_hands_puzzles: Hand,
  ent_cluster_big_movement: Activity,
  ent_cluster_feelings_turn_taking: Users,
  ent_cluster_independence_practice: CheckCircle2,
  ent_cluster_potty_toilet_practice: CalendarCheck2,
  ent_cluster_home_rhythm_safety: Shield,
  // 31–33m clusters
  ent_cluster_asking_what_happens_next: MessageCircle,
  ent_cluster_telling_my_version: MessageCircle,
  ent_cluster_pretend_worlds_bigger: Theater,
  ent_cluster_playing_with_people: Users,
  ent_cluster_real_job_to_do: CheckCircle2,
  ent_cluster_hands_make_more: Hand,
  ent_cluster_balance_bravery: Activity,
  ent_cluster_water_colour_mess: Droplets,
};

const LABEL_PATTERNS: { test: RegExp; icon: LucideIcon }[] = [
  { test: /the floor is my little gym/i, icon: Activity },
  { test: /talk to me/i, icon: MessageCircle },
  { test: /i can make things happen/i, icon: Sparkles },
  { test: /i.?m finding my body/i, icon: PersonStanding },
  { test: /keep this next stage safe|keep little hands safer/i, icon: Shield },
  { test: /i.?m listening and joining in/i, icon: BookOpen },
  { test: /i.?m finding hidden things/i, icon: Eye },
  { test: /i.?m chatting, clapping/i, icon: MessageCircle },
  { test: /mealtimes are changing/i, icon: UtensilsCrossed },
  { test: /little explorer mode/i, icon: Compass },
  { test: /words are waking up/i, icon: MessageCircle },
  { test: /copying real life|copying everyday life/i, icon: Theater },
  { test: /daily practice/i, icon: CalendarCheck2 },
  { test: /safer home checks|make exploring safer/i, icon: Shield },
  { test: /i.?m finding my words/i, icon: MessageCircle },
  { test: /i.?m having big feelings/i, icon: HeartHandshake },
  { test: /i.?m noticing bathroom routines|i.?m noticing potty signs/i, icon: CalendarCheck2 },
  { test: /i.?m telling you more/i, icon: MessageCircle },
  { test: /i.?m copying the everyday/i, icon: Theater },
  { test: /i.?m moving with (?:more )?confidence|i.?m moving with purpose/i, icon: Activity },
  { test: /i.?m learning to play with others/i, icon: Users },
  { test: /i want to do it myself|i want a real job to do/i, icon: CheckCircle2 },
  { test: /i.?m asking what happens next/i, icon: MessageCircle },
  { test: /i.?m telling you my version/i, icon: MessageCircle },
  { test: /i.?m making pretend worlds bigger/i, icon: Theater },
  { test: /i.?m learning how other people play/i, icon: Users },
  { test: /i.?m testing balance and bravery/i, icon: Activity },
  { test: /i.?m experimenting with water and colour/i, icon: Droplets },
  // Brand voice (1–3m pilot)
  { test: /finding your face|i.?m finding your face/i, icon: Smile },
  { test: /listening to your voice|listening to familiar/i, icon: Mic },
  { test: /watching the world|i.?m watching/i, icon: Eye },
  { test: /stronger on my tummy|getting stronger on my tummy/i, icon: Activity },
  { test: /starting to wriggle|i.?m starting to wriggle/i, icon: Footprints },
  { test: /hands are waking up|hands waking up/i, icon: HandMetal },
  { test: /settle and reconnect|crying, comfort/i, icon: CloudMoon },
  { test: /feeds calm and clean|calm feeds and clean/i, icon: Milk },
  { test: /sleep feel safe|safer sleep made simple/i, icon: Moon },
  { test: /first trips|keep first trips simpler/i, icon: Stethoscope },
  // Brand voice (6–9m / 9–12m pilot)
  { test: /i can sit and reach/i, icon: Hand },
  { test: /getting ready to move/i, icon: Footprints },
  { test: /hide and come back|things can hide/i, icon: Eye },
  { test: /putting things in, out and together/i, icon: Layers },
  { test: /everything goes in my mouth/i, icon: Apple },
  { test: /getting ready for first tastes|first tastes/i, icon: UtensilsCrossed },
  { test: /starting to get everywhere|suddenly into everything/i, icon: Shield },
  { test: /listening, copying|joining in/i, icon: BookOpen },
  { test: /hands can do more/i, icon: Hand },
  { test: /finding things out/i, icon: Puzzle },
  { test: /learning to tell you/i, icon: MessageCircle },
  { test: /noticing faces and feelings/i, icon: Users },
  { test: /good little moment/i, icon: CalendarDays },
  // 13–15m Conor-grade clusters
  { test: /working things out/i, icon: Puzzle },
  { test: /telling you things/i, icon: MessageCircle },
  { test: /copying your day/i, icon: Theater },
  { test: /braver on my feet/i, icon: Footprints },
  { test: /taking charge at meals/i, icon: UtensilsCrossed },
  { test: /making my first marks/i, icon: Pencil },
  { test: /joining in properly/i, icon: Users },
  { test: /between baby and toddler/i, icon: HeartHandshake },
  { test: /change of scene/i, icon: CalendarDays },
  // Legacy labels (other bands)
  { test: /sitting up|reaching for toys/i, icon: Hand },
  { test: /ready to crawl|crawling|on the move/i, icon: Footprints },
  { test: /hidden things|making things happen|figuring out/i, icon: Eye },
  { test: /putting things in|stacking|nesting/i, icon: Layers },
  { test: /chew|mouth|sensory/i, icon: Apple },
  { test: /solids|feeding themselves|feed themselves/i, icon: UtensilsCrossed },
  { test: /home safer|babyproofing|safer for a moving/i, icon: Shield },
  { test: /books|songs|back-and-forth|stories, faces/i, icon: BookOpen },
  { test: /busy little hands/i, icon: Hand },
  { test: /chats|claps|signs/i, icon: MessageCircle },
  { test: /fill the day/i, icon: CalendarDays },
  { test: /play with other|social emotional|big feelings|feelings/i, icon: Users },
  { test: /doing more by myself|independence|myself|let me help/i, icon: CheckCircle2 },
  { test: /hands can|fine motor|little hands/i, icon: Hand },
  { test: /bigger moves|gross motor|physical|burn energy/i, icon: Activity },
  { test: /more to say|talk|language|understand/i, icon: MessageCircle },
  { test: /make.believe|pretend|stories/i, icon: Theater },
  { test: /figuring things|cognitive|problem/i, icon: Puzzle },
  { test: /build|puzzle|blocks/i, icon: Blocks },
  { test: /shapes|colou?rs/i, icon: Shapes },
  { test: /routine|transition|daily/i, icon: CalendarCheck2 },
  { test: /draw|making|mark/i, icon: Pencil },
];

function slugLookupKeys(uxSlug: string): string[] {
  const raw = (uxSlug ?? '').toLowerCase().trim();
  if (!raw) return [];
  const hyphen = raw.replace(/\s+/g, '-').replace(/_/g, '-');
  const underscore = raw.replace(/\s+/g, '_').replace(/-/g, '_');
  return [...new Set([raw, hyphen, underscore])];
}

export function getWrapperIcon(uxSlug: string, uxLabel: string): LucideIcon {
  for (const key of slugLookupKeys(uxSlug)) {
    const icon = SLUG_TO_ICON[key];
    if (icon) return icon;
  }
  const label = (uxLabel ?? '').toLowerCase();
  for (const { test, icon } of LABEL_PATTERNS) {
    if (test.test(label)) return icon;
  }
  return Shapes;
}
