-- Generated by web/scripts/ingest-stage3-pips-picks.mjs
-- Bundle: agent-tools/exports/stage3_ingestion_bundle_22-24m.json

BEGIN;

CREATE TABLE IF NOT EXISTS public.pl_stage3_picks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  age_band_id TEXT NOT NULL REFERENCES public.pl_age_bands(id) ON DELETE RESTRICT,
  category_type_id UUID NOT NULL REFERENCES public.pl_category_types(id) ON DELETE CASCADE,
  source_category_entity_id TEXT NOT NULL,
  pick_rank INTEGER NOT NULL CHECK (pick_rank > 0),
  longlist_rank INTEGER NOT NULL CHECK (longlist_rank > 0),
  status TEXT NOT NULL CHECK (status IN ('visible', 'backup', 'skip')),
  is_visible BOOLEAN NOT NULL DEFAULT true,
  is_locked BOOLEAN NOT NULL DEFAULT true,
  best_for_tag TEXT,
  product_name TEXT NOT NULL,
  brand TEXT,
  retailer TEXT,
  product_url TEXT,
  image_url TEXT,
  price_text TEXT,
  stock_status TEXT,
  age_mark_on_listing TEXT,
  product_description TEXT,
  ember_verdict TEXT,
  why_it_fits TEXT,
  caveats TEXT,
  buy_borrow_hold_off TEXT,
  gift_suitable BOOLEAN,
  gift_note TEXT,
  ownership_note TEXT,
  safety_notes TEXT,
  evidence_tier TEXT,
  evidence_sources TEXT[],
  founder_qa_flag TEXT,
  research_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT pl_stage3_picks_unique UNIQUE (age_band_id, category_type_id, pick_rank, status)
);

ALTER TABLE public.pl_stage3_picks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pl_stage3_picks_public_read" ON public.pl_stage3_picks;
CREATE POLICY "pl_stage3_picks_public_read" ON public.pl_stage3_picks
  FOR SELECT
  TO anon, authenticated
  USING (
    status = 'visible'
    AND is_visible = true
    AND (
      is_locked = false
      OR lower(coalesce(auth.jwt() ->> 'email', '')) = 'timwd23@gmail.com'
      OR lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'membership_type', '')) = 'ember_plus'
    )
  );

DROP POLICY IF EXISTS "pl_stage3_picks_admin_all" ON public.pl_stage3_picks;
CREATE POLICY "pl_stage3_picks_admin_all" ON public.pl_stage3_picks
  FOR ALL
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

GRANT SELECT ON public.pl_stage3_picks TO anon, authenticated;

CREATE INDEX IF NOT EXISTS pl_stage3_picks_age_category_rank_idx
  ON public.pl_stage3_picks(age_band_id, category_type_id, status, pick_rank);

DROP TRIGGER IF EXISTS trg_pl_stage3_picks_updated_at ON public.pl_stage3_picks;
CREATE TRIGGER trg_pl_stage3_picks_updated_at
  BEFORE UPDATE ON public.pl_stage3_picks
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

DROP VIEW IF EXISTS public.v_gateway_stage3_picks_public;
CREATE VIEW public.v_gateway_stage3_picks_public
WITH (security_invoker = true) AS
SELECT
  s.id,
  s.age_band_id,
  s.category_type_id,
  ct.slug AS category_type_slug,
  s.source_category_entity_id,
  s.pick_rank,
  s.longlist_rank,
  s.status,
  s.is_visible,
  s.is_locked,
  s.best_for_tag,
  s.product_name,
  s.brand,
  s.retailer,
  s.product_url,
  s.image_url,
  s.price_text,
  s.stock_status,
  s.age_mark_on_listing,
  s.product_description,
  s.ember_verdict,
  s.why_it_fits,
  s.caveats,
  s.buy_borrow_hold_off,
  s.gift_suitable,
  s.gift_note,
  s.ownership_note,
  s.safety_notes,
  s.evidence_tier,
  s.evidence_sources,
  s.founder_qa_flag,
  s.research_payload
FROM public.pl_stage3_picks s
JOIN public.pl_category_types ct ON ct.id = s.category_type_id
WHERE s.status = 'visible'
  AND s.is_visible = true
  AND s.is_locked = false;

GRANT SELECT ON public.v_gateway_stage3_picks_public TO anon, authenticated;

DELETE FROM public.pl_stage3_picks
WHERE age_band_id = '22-24m'
  AND source_category_entity_id IN ('cat_colour_sorting_matching', 'cat_feelings_faces_books', 'cat_large_balls', 'cat_learning_tower_step_stool', 'cat_picture_story_books', 'cat_play_kitchen_household_props', 'cat_potty_chair');

WITH stage3_rows AS (
  SELECT *
  FROM (VALUES
    ('cat_colour_sorting_matching', 1, 1, 'visible', true, false, 'Best for colour stack and sort', 'Melissa & Doug Stack and Sort Board', 'Melissa & Doug', 'SmartToys', 'https://www.smartoys.co.uk/product/melissa-doug-stack-and-sort-board-wooden-educational-toy-with-15-solid-wood-pieces/', NULL, 'Â£14.99', 'in_stock', 'Ages 2+', 'A wooden base with pegs and fifteen colourful shapes for stacking, sorting and matching by colour at the table or on the floor.', 'Sorting and matching take a leap around nearly two: same colour piles, then careful stacking. This board makes that job clear without tiny fiddly pieces. Best when they already love posting shapes and are ready to match colours on purpose.', 'Sorting and matching take a leap around nearly two: same colour piles, then careful stacking. This board makes that job clear without tiny fiddly pieces. Best when they already love posting shapes and are ready to match colours on purpose.', NULL, 'buy', true, NULL, NULL, NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_colour_sorting_matching', 2, 2, 'visible', true, true, 'Best for sorting bears set', 'Edx Sorting Bears with Matching Bowls', 'Edx Education', 'ShopEdx', 'https://www.shopedx.co.uk/products/sorting-bears-with-matching-bowls', NULL, 'Â£30.36', 'in_stock', 'Ages 1-5 (parent supervised colour sort)', 'Sixty colourful bear counters with six matching bowls for sorting by colour, tipping out and starting again on the table.', 'Bowls make colour sorting into a proper job: red bears here, blue bears there. The pieces are small, so stay beside them at first. Strong when they already enjoy dumping and filling and want those colours to have a home.', 'Bowls make colour sorting into a proper job: red bears here, blue bears there. The pieces are small, so stay beside them at first. Strong when they already enjoy dumping and filling and want those colours to have a home.', NULL, 'buy', true, NULL, NULL, 'Supervise; counters are small.', 'good', ARRAY[]::text[], 'check_age_fit'),
    ('cat_colour_sorting_matching', 3, 3, 'visible', true, true, 'Best for chunky sorter bucket', 'Dolu Shape Block Sorter Bucket', 'Dolu', 'SmartToys', 'https://www.smartoys.co.uk/product/brightly-coloured-shape-block-sorter-bucket-for-toddler-kids-by-dolu/', NULL, 'Â£12.99', 'in_stock', 'Ages 1-5', 'A bright bucket with a shape sorting lid and chunky colourful blocks for posting, dumping and matching colours on the go.', 'Posting and dumping still delight at nearly two, and colour matching rides along for free with every block. The bucket travels to the park bag without a fuss and tips out cleanly at home. Handy when you want sorting play that packs itself away after tea.', 'Posting and dumping still delight at nearly two, and colour matching rides along for free with every block. The bucket travels to the park bag without a fuss and tips out cleanly at home. Handy when you want sorting play that packs itself away after tea.', NULL, 'buy', true, NULL, NULL, NULL, 'good', ARRAY[]::text[], 'none'),
    ('cat_colour_sorting_matching', 4, 4, 'visible', true, true, 'Best for pegboard colour play', 'Edx Fun Play Geo Pegs Board Set', 'Edx Education', 'ShopEdx', 'https://www.shopedx.co.uk/products/fun-play-geo-pegs', NULL, 'Â£18.00', 'in_stock', 'Ages 1-5', 'A set of chunky colourful geo pegs with a matching board for pressing in, pulling out and making simple colour patterns together at the table.', 'Pegs invite careful fingers and colour talk: same colour row, then mix them up again for another go. It sits nicely after a simpler sorter on the shelf. Best when they enjoy pressing pieces in and want a slightly bigger colour job at the table.', 'Pegs invite careful fingers and colour talk: same colour row, then mix them up again for another go. It sits nicely after a simpler sorter on the shelf. Best when they enjoy pressing pieces in and want a slightly bigger colour job at the table.', NULL, 'buy', true, NULL, NULL, NULL, 'good', ARRAY[]::text[], 'none'),
    ('cat_colour_sorting_matching', 5, 5, 'visible', true, true, 'Best for rainbow pebble sort', 'Junior Rainbow Pebbles', 'Junior Learning', 'ShopEdx', 'https://www.shopedx.co.uk/products/junior-rainbow-pebbles', NULL, 'Â£22.00', 'in_stock', 'Ages 1-5', 'A tray of smooth colourful pebble shapes for sorting by colour, stacking carefully and lining up along the table or a low tray.', 'Smooth pebbles invite quiet sorting and careful stacks once colours are familiar from other toys. They feel different in the hand from plastic counters and boards. Lovely when they already sort bears or blocks and want a softer set for the sofa table.', 'Smooth pebbles invite quiet sorting and careful stacks once colours are familiar from other toys. They feel different in the hand from plastic counters and boards. Lovely when they already sort bears or blocks and want a softer set for the sofa table.', NULL, 'buy', true, NULL, NULL, NULL, 'good', ARRAY[]::text[], 'none'),
    ('cat_feelings_faces_books', 1, 1, 'visible', true, false, 'Best for colour feelings map', 'The Colour Monster', 'Anna Llenas / Templar', 'uk.bookshop.org', 'https://uk.bookshop.org/p/books/the-colour-monster-anna-llenas/9781783704231', NULL, '£7.99', 'in_stock', 'Ages 1-5', 'A picture book where a little monster sorts big feelings into colours, so children can point and name what is going on.', 'Near two, feelings arrive faster than words. Colour sorting gives a shared label without a long talk. Borrow first if friends already own it, then buy if it becomes the nightly ask. Keep The Colour Monster in easy reach for the next short try.', 'Near two, feelings arrive faster than words. Colour sorting gives a shared label without a long talk. Borrow first if friends already own it, then buy if it becomes the nightly ask. Keep The Colour Monster in easy reach for the next short try.', NULL, 'borrow', true, NULL, 'High duplication risk — check the shelf and library first.', NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_feelings_faces_books', 2, 2, 'visible', true, true, 'Best for bold face catalogue', 'The Feelings Book', 'Todd Parr', 'Hachette UK', 'https://www.hachette.co.uk/titles/todd-parr/the-feelings-book/9780316043465/', NULL, '£7.99', 'in_stock', 'Ages 2+', 'Bold faces and short lines cover many moods (silly, shy, proud) without turning bedtime into a therapy session. for sharing on the sofa at home.', 'Near two, moods swing hard. Todd Parr faces are easy to point at after a wobble when words lag. Distinct from Colour Monster because faces do the teaching, not colour jars. Leave The Feelings Book out where they can find it again tomorrow.', 'Near two, moods swing hard. Todd Parr faces are easy to point at after a wobble when words lag. Distinct from Colour Monster because faces do the teaching, not colour jars. Leave The Feelings Book out where they can find it again tomorrow.', NULL, 'borrow', true, NULL, 'High duplication risk — check the shelf and library first.', NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_feelings_faces_books', 3, 3, 'visible', true, true, 'Best for heart shaped feelings read', 'In My Heart: A Book of Feelings', 'Jo Witek', 'uk.bookshop.org', 'https://uk.bookshop.org/p/books/in-my-heart-a-book-of-feelings-jo-witek/9781419713101', NULL, '£8.99', 'in_stock', 'Ages 2+', 'Heart shaped die cut pages walk through emotions with short, warm lines that suit lap reading near two. for sharing on the sofa at home.', 'Near two, big feelings need a gentle frame. Heart shaped pages make the talk tactile: shared looking, not a long explanation. Strong when Colour Monster is already on the shelf. One short go with In My Heart: A is enough before you tidy away.', 'Near two, big feelings need a gentle frame. Heart shaped pages make the talk tactile: shared looking, not a long explanation. Strong when Colour Monster is already on the shelf. One short go with In My Heart: A is enough before you tidy away.', NULL, 'borrow', true, NULL, 'High duplication risk — check the shelf and library first.', NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_feelings_faces_books', 4, 4, 'visible', true, true, 'Best for happy face board', 'When I Feel Happy', 'Child''s Play', 'Hachette UK', 'https://www.hachette.co.uk/titles/paula-bowles/when-i-feel-happy/9781786287441/', NULL, '£6.99', 'in_stock', '2 to 3 years', 'A short board book that names happy feelings with clear toddler faces and simple everyday scenes. for sharing on the sofa at home.', 'Near two, naming the good days helps too. One feeling per book keeps the page short after a park win. First Child''s Play title; pair with the sad title only if you want a set. Stay nearby while they try When I Feel Happy, then stop on a good note.', 'Near two, naming the good days helps too. One feeling per book keeps the page short after a park win. First Child''s Play title; pair with the sad title only if you want a set. Stay nearby while they try When I Feel Happy, then stop on a good note.', NULL, 'borrow', true, NULL, 'High duplication risk — check the shelf and library first.', NULL, 'good', ARRAY[]::text[], 'none'),
    ('cat_feelings_faces_books', 5, 5, 'visible', true, true, 'Best for sad face board', 'When I Feel Sad', 'Child''s Play', 'Hachette UK', 'https://www.hachette.co.uk/titles/paula-bowles/when-i-feel-sad/9781786287458/', NULL, '£6.99', 'in_stock', '2 to 3 years', 'A matching board book that names sad feelings with clear faces parents can point to after a hard goodbye. for sharing on the sofa at home.', 'Near two, goodbye tears need a short shared page. Clear faces beat long stories when everyone is tired. Second Child''s Play title; stop at two brands from this range. Put When I Feel Sad where you both sit most evenings so the invite is easy.', 'Near two, goodbye tears need a short shared page. Clear faces beat long stories when everyone is tired. Second Child''s Play title; stop at two brands from this range. Put When I Feel Sad where you both sit most evenings so the invite is easy.', NULL, 'borrow', true, NULL, 'High duplication risk — check the shelf and library first.', NULL, 'good', ARRAY[]::text[], 'none'),
    ('cat_feelings_faces_books', 6, 6, 'visible', true, true, 'Best for grumpy mood story', 'Grumpy Frog', 'Ed Vere', 'uk.bookshop.org', 'https://uk.bookshop.org/p/books/grumpy-frog-ed-vere/9781783445929', NULL, '£7.99', 'in_stock', 'Ages 1-5', 'A bold picture book about a frog who feels grumpy, with humour that invites copycat faces on each page. for sharing on the sofa at home.', 'Near two, grumpy arrives as a full body weather system. A funny frog story names it without a scolding tone. Good when board feelings sets feel thin and you want a proper little story. Put Grumpy Frog where you both sit most evenings so the invite is easy.', 'Near two, grumpy arrives as a full body weather system. A funny frog story names it without a scolding tone. Good when board feelings sets feel thin and you want a proper little story. Put Grumpy Frog where you both sit most evenings so the invite is easy.', NULL, 'borrow', true, NULL, 'High duplication risk — check the shelf and library first.', NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_feelings_faces_books', 7, 7, 'visible', true, true, 'Best for mine and share story', 'That''s (Not) Mine', 'Anna Kang', 'Hachette UK', 'https://www.hachette.co.uk/titles/anna-kang/thats-not-mine/9781444923339/', NULL, '£7.99', 'in_stock', 'Ages 2-5', 'A short picture book about two creatures arguing over a chair, with a soft ending about sharing and repair. for sharing on the sofa at home.', 'Near two, mine fights arrive daily. This story shows the squabble and the mend without a heavy moral. Useful when face books are covered and you need a turn taking tale. Let them finish the turn with That''s Mine, then close the activity kindly.', 'Near two, mine fights arrive daily. This story shows the squabble and the mend without a heavy moral. Useful when face books are covered and you need a turn taking tale. Let them finish the turn with That''s Mine, then close the activity kindly.', NULL, 'borrow', true, NULL, 'High duplication risk — check the shelf and library first.', NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_feelings_faces_books', 8, 8, 'visible', true, true, 'Best for one feeling per spread', 'The Way I Feel', 'Janan Cain', 'uk.bookshop.org', 'https://uk.bookshop.org/p/books/the-way-i-feel-janan-cain/9781884734717', NULL, '£7.99', 'in_stock', 'Ages 2+', 'Each spread pairs a feeling word with a vivid face, easy to point at after a hard goodbye. for sharing on the sofa at home.', 'Near two, one feeling per spread is enough. Faces do the teaching while you keep the page short. Strong catalogue depth when Colour Monster is already loved. If interest fades, pack The Way I Feel away and try again another day.', 'Near two, one feeling per spread is enough. Faces do the teaching while you keep the page short. Strong catalogue depth when Colour Monster is already loved. If interest fades, pack The Way I Feel away and try again another day.', NULL, 'borrow', true, NULL, 'High duplication risk — check the shelf and library first.', NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_feelings_faces_books', 9, 9, 'visible', true, true, 'Best for monster mask play', 'Glad Monster, Sad Monster', 'Ed Emberley', 'uk.bookshop.org', 'https://uk.bookshop.org/p/books/glad-monster-sad-monster-ed-emberley/9780316573580', NULL, '£7.99', 'in_stock', 'Ages 2+', 'Monster masks and mood pages invite copycat faces: play first, label second, stop mid page if needed. for sharing on the sofa at home.', 'Near two, copycat faces beat long talks. Masks turn feelings into a game you can pause. Distinct format when standard board books already fill the shelf. Use Glad Monster, Sad Monster as the second option when the first favourite is already out.', 'Near two, copycat faces beat long talks. Masks turn feelings into a game you can pause. Distinct format when standard board books already fill the shelf. Use Glad Monster, Sad Monster as the second option when the first favourite is already out.', NULL, 'borrow', true, NULL, 'High duplication risk — check the shelf and library first.', NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_feelings_faces_books', 10, 10, 'visible', true, true, 'Best for shop floor meltdown story', 'Llama Llama Mad at Mama', 'Anna Dewdney', 'uk.bookshop.org', 'https://uk.bookshop.org/p/books/llama-llama-mad-at-mama-anna-dewdney/9780670059836', NULL, '£7.99', 'in_stock', 'Ages 2+', 'A shopping meltdown story that names anger and repair, familiar to any parent of a child near two. for sharing on the sofa at home.', 'Near two, shop floors invent new weather. A story that names mad and mend beats a long talk in the aisle. Check stock; some editions go thin. Keep the session short with Llama Llama Mad at so it stays a friendly invite.', 'Near two, shop floors invent new weather. A story that names mad and mend beats a long talk in the aisle. Check stock; some editions go thin. Keep the session short with Llama Llama Mad at so it stays a friendly invite.', NULL, 'borrow', true, NULL, 'High duplication risk — check the shelf and library first.', NULL, 'strong', ARRAY[]::text[], 'check_stock'),
    ('cat_large_balls', 1, 1, 'visible', true, false, 'Best for soft foam kickabout', 'Sports Directory Foam Football', 'Sports Directory', 'Sports Direct', 'https://www.sportsdirect.com/sports-directory-foam-football-857872', NULL, 'Â£5.00', 'in_stock', 'Ages 1-5', 'A soft foam football sized for little kicks and indoor or garden chase games without hard bounces off shins or furniture.', 'Kicking and chasing take off around nearly two once walking is steady. Soft foam keeps the game friendly in the hallway or on the grass. Best when they already love running after a rolling ball and want something kinder than a hard match ball.', 'Kicking and chasing take off around nearly two once walking is steady. Soft foam keeps the game friendly in the hallway or on the grass. Best when they already love running after a rolling ball and want something kinder than a hard match ball.', NULL, 'buy', true, NULL, NULL, NULL, 'good', ARRAY[]::text[], 'none'),
    ('cat_large_balls', 2, 2, 'visible', true, true, 'Best for mini garden football', 'FORZA Recreational Garden Football Size 1 Mini', 'FORZA', 'FORZA', 'https://www.forza.com/uk/forza-recreational-garden-football+forza_match_football_size-Size~1~Mini+pack_size-Pack~of~1', NULL, 'Â£7.99', 'in_stock', 'Size 1 mini', 'A small Size 1 recreational football for garden kicking, gentle passes and chasing across the lawn with a grown up.', 'A proper mini football makes outdoor chase play like a proper little match without a heavy adult ball. Size 1 stays manageable for short legs. Strong when the foam ball is already loved indoors and you want something for the grass.', 'A proper mini football makes outdoor chase play like a proper little match without a heavy adult ball. Size 1 stays manageable for short legs. Strong when the foam ball is already loved indoors and you want something for the grass.', NULL, 'buy', true, NULL, NULL, NULL, 'good', ARRAY[]::text[], 'none'),
    ('cat_large_balls', 3, 3, 'visible', true, true, 'Best for soft indoor kickabout', 'IKEA SPARKA Soft Toy Football', 'IKEA', 'IKEA UK', 'https://www.ikea.com/gb/en/p/sparka-soft-toy-football-patterned-multicolo-40302182/', NULL, '£4.00', 'in_stock', 'Ages 1-5', 'A soft patterned play football from IKEA, light enough for indoor kicks and chases without hard impacts on shins or furniture.', 'Near two, chasing a soft ball is the game. SPARKA keeps kicks friendly indoors when the garden is wet. Cheap enough to leave downstairs without a fuss. One short go with IKEA SPARKA Soft Toy is enough before you tidy away.', 'Near two, chasing a soft ball is the game. SPARKA keeps kicks friendly indoors when the garden is wet. Cheap enough to leave downstairs without a fuss. One short go with IKEA SPARKA Soft Toy is enough before you tidy away.', NULL, 'buy', true, NULL, NULL, NULL, 'good', ARRAY[]::text[], 'none'),
    ('cat_large_balls', 4, 4, 'visible', true, true, 'Best for second soft kickabout', 'Smyths Soft Play Ball', 'Smyths', 'Smyths Toys', 'https://www.smythstoys.com/uk/en-gb/toys/outdoor-toys/sports-toys/balls/soft-play-ball/p/201000', NULL, 'Â£6.99', 'in_stock', 'Ages 1-5', 'A soft play ball for rolling, kicking and chasing in the garden or hall, sized for toddlers who are just finding a strong kick.', 'A simple soft play ball keeps chase games going when the football shapes are already out. Rolling and kicking still share the same joy outdoors and in. Useful as a spare for the park bag when the foam football is muddy after tea.', 'A simple soft play ball keeps chase games going when the football shapes are already out. Rolling and kicking still share the same joy outdoors and in. Useful as a spare for the park bag when the foam football is muddy after tea.', NULL, 'buy', true, NULL, NULL, NULL, 'good', ARRAY[]::text[], 'check_url'),
    ('cat_large_balls', 5, 5, 'visible', true, true, 'Best for inchworm chase ball', 'Smyths Inch Worm Ball', 'Inch Worm', 'Smyths Toys', 'https://www.smythstoys.com/uk/en-gb/toys/outdoor-toys/sports-toys/balls/inch-worm-ball/p/201001', NULL, 'Â£8.99', 'in_stock', 'Ages 1-5', 'A soft novelty chase ball with a wiggly shape that rolls in funny lines, inviting kicks and giggles across the garden path.', 'A wiggly roll keeps chase interesting when ordinary footballs are already familiar from earlier play. Short kicks still count and make them laugh. Fun when they love the chase more than perfect football shape and you want variety in the ball basket at home.', 'A wiggly roll keeps chase interesting when ordinary footballs are already familiar from earlier play. Short kicks still count and make them laugh. Fun when they love the chase more than perfect football shape and you want variety in the ball basket at home.', NULL, 'buy', true, NULL, NULL, NULL, 'good', ARRAY[]::text[], 'check_url'),
    ('cat_learning_tower_step_stool', 1, 1, 'visible', true, false, 'Best for enclosed kitchen helper', 'Tutti Bambini Helping Hands Learning Tower', 'Tutti Bambini', 'Tutti Bambini', 'https://www.tuttibambini.com/products/helping-hands-montessori-toddler-learning-tower-sea-mist', NULL, 'Â£99.00', 'in_stock', 'Ages 2-6 years', 'An adjustable wooden learning tower with side rails that brings a toddler to counter height for stirring, washing and helping in the kitchen.', 'Little independence at home means standing beside you to tip and stir, not watching from the floor. An enclosed tower keeps that job steadier than a chair. Best when they already ask to help with tea and you want safe counter height.', 'Little independence at home means standing beside you to tip and stir, not watching from the floor. An enclosed tower keeps that job steadier than a chair. Best when they already ask to help with tea and you want safe counter height.', NULL, 'buy', false, NULL, NULL, 'Always supervise at the counter.', 'strong', ARRAY[]::text[], 'none'),
    ('cat_learning_tower_step_stool', 2, 2, 'visible', true, true, 'Best for Dunelm grow along tower', 'hauck Learn N Explore Learning Tower', 'hauck', 'Dunelm', 'https://www.dunelm.com/product/hauck-learn-n-explore-learning-tower-1000249847', NULL, 'Â£89.99', 'in_stock', '18m+', 'An adjustable wooden learning tower for counter height help, with a sturdy base and rails for supervised kitchen jobs. for everyday play at home with you.', 'A grow along tower stretches the years of kitchen help after nearly two. Adjustable height keeps hips safer as they shoot up. Good everyday option when you want enclosed help without a premium convertible price. Leave hauck Learn N Explore out where they can find it again tomorrow.', 'A grow along tower stretches the years of kitchen help after nearly two. Adjustable height keeps hips safer as they shoot up. Good everyday option when you want enclosed help without a premium convertible price. Leave hauck Learn N Explore out where they can find it again tomorrow.', NULL, 'buy', false, NULL, NULL, NULL, 'good', ARRAY[]::text[], 'none'),
    ('cat_learning_tower_step_stool', 3, 3, 'visible', true, true, 'Best for simple IKEA step stool', 'IKEA TROGEN Children''s Step Stool', 'IKEA', 'IKEA UK', 'https://www.ikea.com/gb/en/p/trogen-children-s-step-stool-white-40353767/', NULL, '£10.00', 'in_stock', 'Ages 1-5', 'A low white children''s step stool for reaching the sink or counter, with a stable base for short supervised climbs.', 'Near two, help at the sink often starts with a simple step, not a full tower. TROGEN is the cheap first try when kitchen space is tight. Swap up later if they need an enclosed platform. One short go with IKEA TROGEN Children''s Step is enough before you tidy away.', 'Near two, help at the sink often starts with a simple step, not a full tower. TROGEN is the cheap first try when kitchen space is tight. Swap up later if they need an enclosed platform. One short go with IKEA TROGEN Children''s Step is enough before you tidy away.', NULL, 'buy', true, NULL, NULL, 'Supervise at the counter; teach step and stand.', 'good', ARRAY[]::text[], 'none'),
    ('cat_learning_tower_step_stool', 4, 4, 'visible', true, true, 'Best for bathroom step stool', 'BabyBjorn Step Stool', 'BabyBjÃ¶rn', 'Boots', 'https://www.boots.com/babybjorn-step-stool-white-10220346', NULL, 'Â£34.99', 'in_stock', 'Ages 1-5', 'A sturdy step stool for reaching the sink to wash hands and brush teeth, with a non slip standing surface for little feet.', 'Not every home needs a full tower; a safe step stool covers sink jobs. Handwashing and toothbrushing become theirs with a small height boost. Best when kitchen help is already sorted and bathroom independence is the next ask. Stay nearby while they try BabyBjorn Step Stool, then stop on a good note.', 'Not every home needs a full tower; a safe step stool covers sink jobs. Handwashing and toothbrushing become theirs with a small height boost. Best when kitchen help is already sorted and bathroom independence is the next ask. Stay nearby while they try BabyBjorn Step Stool, then stop on a good note.', NULL, 'buy', false, NULL, NULL, NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_learning_tower_step_stool', 5, 5, 'visible', true, true, 'Best for small child stool seat', 'IKEA FORSIKTIG Children''s Stool', 'IKEA', 'IKEA UK', 'https://www.ikea.com/gb/en/p/forsiktig-children-s-stool-white-green-60248418/', NULL, '£10.00', 'in_stock', 'Ages 1-5', 'A small children''s stool they can drag to the sink or hob helper spot, with a friendly height for nearly two.', 'Near two, a stool they can drag to the sink often beats a big tower in a tiny kitchen. FORSIKTIG is the second IKEA option when TROGEN is out. Keep supervision close at the counter. Put IKEA FORSIKTIG Children''s Stool where you both sit most evenings so the invite is easy.', 'Near two, a stool they can drag to the sink often beats a big tower in a tiny kitchen. FORSIKTIG is the second IKEA option when TROGEN is out. Keep supervision close at the counter. Put IKEA FORSIKTIG Children''s Stool where you both sit most evenings so the invite is easy.', NULL, 'buy', true, NULL, NULL, 'Supervise climbs.', 'good', ARRAY[]::text[], 'none'),
    ('cat_picture_story_books', 1, 1, 'visible', true, false, 'Best for chant along story', 'We''re Going on a Bear Hunt (board book)', 'Walker Books', 'Penguin UK', 'https://www.penguin.co.uk/books/108950/were-going-on-a-bear-hunt-by-rosen-michael/9781406363074', NULL, 'Â£7.99', 'in_stock', 'Ages 1-5', 'A sturdy board book of the classic chant along bear hunt, with swishy splashy sounds to join in on every page.', 'Words are joining up into little stories with repeats they can shout. Bear Hunt hands them the chorus. Borrow first if grandparents already own it, then buy a board copy if it becomes the nightly ask. Keep We''re Going on a in easy reach for the next short try.', 'Words are joining up into little stories with repeats they can shout. Bear Hunt hands them the chorus. Borrow first if grandparents already own it, then buy a board copy if it becomes the nightly ask. Keep We''re Going on a in easy reach for the next short try.', NULL, 'borrow', true, NULL, 'High duplication risk â€” check the shelf and library first.', NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_picture_story_books', 2, 2, 'visible', true, true, 'Best for lift the flap classic', 'Dear Zoo (board book)', 'Campbell Books', 'Penguin UK', 'https://www.penguin.co.uk/books/451946/dear-zoo-by-campbell-rod/9780230743076', NULL, 'Â£6.99', 'in_stock', 'Ages 1-5', 'A board book with flaps to lift as each animal arrives from the zoo, ending with the perfect pet surprise.', 'Lifting flaps keeps little stories active when attention is short. Dear Zoo is the UK default for that game. Check the shelf before gifting; many homes already have a battered copy. Leave Dear Zoo out where they can find it again tomorrow.', 'Lifting flaps keeps little stories active when attention is short. Dear Zoo is the UK default for that game. Check the shelf before gifting; many homes already have a battered copy. Leave Dear Zoo out where they can find it again tomorrow.', NULL, 'borrow', true, NULL, 'High duplication risk â€” check the shelf and library first.', NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_picture_story_books', 3, 3, 'visible', true, true, 'Best for press the page play', 'Press Here', 'Chronicle Books', 'Hachette UK', 'https://www.hachette.co.uk/titles/herve-tullet/press-here/9780811879545/', NULL, 'Â£8.99', 'in_stock', 'Ages 1-5', 'A picture book that asks your child to press, rub and tip the page so dots move, grow and party across the spreads.', 'Interactive pages turn listening into doing. Press Here invites taps and tips without batteries. Lovely when they already enjoy flaps and want a different kind of page job. One short go with Press Here is enough before you tidy away.', 'Interactive pages turn listening into doing. Press Here invites taps and tips without batteries. Lovely when they already enjoy flaps and want a different kind of page job. One short go with Press Here is enough before you tidy away.', NULL, 'borrow', true, NULL, 'High duplication risk â€” check the shelf and library first.', NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_picture_story_books', 4, 4, 'visible', true, true, 'Best for rhyming frog fun', 'Oi Frog!', 'Hodder', 'Hachette UK', 'https://www.hachette.co.uk/titles/kes-gray/oi-frog/9781444910865/', NULL, 'Â£7.99', 'in_stock', 'Ages 2+', 'A bright rhyming picture book about where frogs sit, packed with silly animals and sounds to shout on each page.', 'Rhyme and shout backs help words join up. Oi Frog is pure silliness with a clear pattern. Good when Bear Hunt is already worn and you want a louder sofa story. Stay nearby while they try Oi Frog!, then stop on a good note.', 'Rhyme and shout backs help words join up. Oi Frog is pure silliness with a clear pattern. Good when Bear Hunt is already worn and you want a louder sofa story. Stay nearby while they try Oi Frog!, then stop on a good note.', NULL, 'borrow', true, NULL, 'High duplication risk â€” check the shelf and library first.', NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_picture_story_books', 5, 5, 'visible', true, true, 'Best for tickle repeat read', 'The Tickle Book', 'Macmillan', 'Hachette UK', 'https://www.hachette.co.uk/titles/ian-whybrow/the-tickle-book/9780230747098/', NULL, 'Â£7.99', 'in_stock', 'Ages 1-5', 'A playful picture book full of tickles, giggles and animals to find, built for repeating the joke together. for sharing on the sofa at home.', 'Giggle stories keep nearly two attention on the page. Tickle Book is light and physical without needing flaps. Nice when you want a short sunny read before bed. Put The Tickle Book where you both sit most evenings so the invite is easy.', 'Giggle stories keep nearly two attention on the page. Tickle Book is light and physical without needing flaps. Nice when you want a short sunny read before bed. Put The Tickle Book where you both sit most evenings so the invite is easy.', NULL, 'borrow', true, NULL, 'High duplication risk â€” check the shelf and library first.', NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_picture_story_books', 6, 6, 'visible', true, true, 'Best for hungry caterpillar staple', 'The Very Hungry Caterpillar', 'Puffin', 'Penguin UK', 'https://www.penguin.co.uk/books/57093/the-very-hungry-caterpillar-by-carle-eric/9780241003008', NULL, 'Â£7.99', 'in_stock', 'Ages 1-5', 'The classic holey board book story of a caterpillar eating through the week before becoming a butterfly. for sharing on the sofa at home.', 'Counting days and foods turns into a tiny story arc. Most UK shelves already have it, so borrow or bring back out first. Still earns a Top 10 place for how clearly the week story lands for nearly two. Put The Very Hungry Caterpillar where you both sit most evenings so the invite is easy.', 'Counting days and foods turns into a tiny story arc. Most UK shelves already have it, so borrow or bring back out first. Still earns a Top 10 place for how clearly the week story lands for nearly two. Put The Very Hungry Caterpillar where you both sit most evenings so the invite is easy.', NULL, 'bring_back_out', true, NULL, 'High duplication risk â€” check the shelf and library first.', NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_picture_story_books', 7, 7, 'visible', true, true, 'Best for colour repeat read', 'Brown Bear, Brown Bear, What Do You See?', 'Puffin', 'Penguin UK', 'https://www.penguin.co.uk/books/108950/brown-bear-brown-bear-what-do-you-see-by-martin-bill/9780805047905', NULL, 'Â£7.99', 'in_stock', 'Ages 1-5', 'A rhythmic colour and animal book that asks what each creature sees next, inviting your child to predict the page.', 'Prediction is a new story skill as words join up. Brown Bear hands them the pattern. Check stock; some editions sell out, and many nurseries already know it cold. Let them finish the turn with Brown Bear, Brown Bear,, then close the activity kindly.', 'Prediction is a new story skill as words join up. Brown Bear hands them the pattern. Check stock; some editions sell out, and many nurseries already know it cold. Let them finish the turn with Brown Bear, Brown Bear,, then close the activity kindly.', NULL, 'borrow', true, NULL, 'High duplication risk â€” check the shelf and library first.', NULL, 'strong', ARRAY[]::text[], 'check_stock'),
    ('cat_picture_story_books', 8, 8, 'visible', true, true, 'Best for cheeky pigeon board book', 'Don''t Let the Pigeon Drive the Bus! (board)', 'Walker Books', 'Hachette UK', 'https://www.hachette.co.uk/titles/mo-willems/don-t-let-the-pigeon-drive-the-bus/9781406386073/', NULL, 'Â£6.99', 'in_stock', 'Ages 1-5', 'A sturdy board book where the cheeky pigeon keeps asking to drive the bus, and your child gets to say no on every spread.', 'Saying a firm funny no is useful once opinions arrive. The pigeon argues back and they hold the line. Second Walker title after Bear Hunt; still distinct on answering back. If interest fades, pack Don''t Let the Pigeon away and try again another day.', 'Saying a firm funny no is useful once opinions arrive. The pigeon argues back and they hold the line. Second Walker title after Bear Hunt; still distinct on answering back. If interest fades, pack Don''t Let the Pigeon away and try again another day.', NULL, 'borrow', true, NULL, 'High duplication risk â€” check the shelf and library first.', NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_picture_story_books', 9, 9, 'visible', true, true, 'Best for shark peek story', 'Shark in the Park', 'Random House', 'Hachette UK', 'https://www.hachette.co.uk/titles/nick-sharratt/shark-in-the-park/9780552549776/', NULL, 'Â£7.99', 'in_stock', 'Ages 1-5', 'A telescopic peek through picture book about spotting a shark in the park, with jokes that grow on each reread.', 'Peek stories reward looking again. Shark in the Park is a UK sofa favourite for that. Good when flaps feel babyish and you want a proper little story joke. Use Shark in the Park as the second option when the first favourite is already out.', 'Peek stories reward looking again. Shark in the Park is a UK sofa favourite for that. Good when flaps feel babyish and you want a proper little story joke. Use Shark in the Park as the second option when the first favourite is already out.', NULL, 'borrow', true, NULL, 'High duplication risk â€” check the shelf and library first.', NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_picture_story_books', 10, 10, 'visible', true, true, 'Best for hug story for bedtime', 'Hugless Douglas', 'Hodder', 'Hachette UK', 'https://www.hachette.co.uk/titles/david-melling/hugless-douglas/9780340999080/', NULL, 'Â£7.99', 'in_stock', 'Ages 1-5', 'A warm bedtime hug story about a bear searching for the right hug, with soft humour and a gentle ending for sofa reads.', 'Hug stories fit the end of a busy day when words are joining up into feelings too. Douglas keeps looking until he finds his person. Check stock; some listings go thin, and many homes already have a copy. Keep the session short with Hugless Douglas so it stays a friendly invite.', 'Hug stories fit the end of a busy day when words are joining up into feelings too. Douglas keeps looking until he finds his person. Check stock; some listings go thin, and many homes already have a copy. Keep the session short with Hugless Douglas so it stays a friendly invite.', NULL, 'borrow', true, NULL, 'High duplication risk â€” check the shelf and library first.', NULL, 'strong', ARRAY[]::text[], 'check_stock'),
    ('cat_play_kitchen_household_props', 1, 1, 'visible', true, false, 'Best for first chopping set', 'ELC Wooden Fruit Chopping Board', 'Early Learning Centre', 'Smyths Toys', 'https://www.smythstoys.com/uk/en-gb/toys/preschool-toys/role-play-and-dress-up/play-kitchens-and-shops/elc-wooden-fruit-chopping-board/p/189194', NULL, 'Â£12.99', 'in_stock', 'Suitable from 18 months', 'A wooden chopping board with chunky velcro fruit pieces and a play knife, so children who are nearly two can slice, name and serve pretend fruit salad on the kitchen floor.', 'Pretend play is getting richer around nearly two: chopping, naming and serving, not only stirring a plastic pan. This set keeps the job small and clear, with fruit pieces that stay together until they cut. A gentle first kitchen prop when a full play kitchen still feels huge.', 'Chop-and-serve pretend matches richer household play.', NULL, 'buy', true, NULL, NULL, NULL, 'good', ARRAY[]::text[], 'none'),
    ('cat_play_kitchen_household_props', 2, 2, 'visible', true, true, 'Best for savoury chopping twin', 'ELC Wooden Vegetable Chopping Board', 'Early Learning Centre', 'Smyths Toys', 'https://www.smythstoys.com/uk/en-gb/toys/preschool-toys/role-play-and-dress-up/play-kitchens-and-shops/elc-wooden-vegetable-chopping-board/p/189195', NULL, 'Â£12.99', 'in_stock', 'Suitable from 18 months', 'A matching wooden board with velcro vegetables and a play knife, for chopping carrots and tomatoes beside the fruit set during pretend tea.', 'Once fruit chopping is familiar, vegetables stretch the same kitchen story into dinner and soup. The board stays the same job, so the shift is words and menus, not a new skill. Handy when they already love the fruit board and want a second crate of names.', 'Extends food naming in kitchen pretend.', NULL, 'buy', true, NULL, NULL, NULL, 'good', ARRAY[]::text[], 'none'),
    ('cat_play_kitchen_household_props', 3, 3, 'visible', true, true, 'Best for breakfast toaster set', 'Bigjigs Wooden Breakfast Set', 'Bigjigs Toys', 'Smyths', 'https://www.smythstoys.com/uk/en-gb/toys/preschool-toys/role-play-and-dress-up/play-kitchens-and-shops/bigjigs-toys-breakfast-set/p/189291', NULL, 'Â£24.99', 'in_stock', 'Suitable for children from 18 Months +', 'A wooden toaster with toast slices, butter dish and jam pot, so children who are nearly two can make pretend breakfast and slide toast up and down.', 'Morning routines become stories at nearly two: toast pops, butter spreads, jam goes on. This set turns that everyday sequence into play they can lead. Strong when they already copy breakfast jobs and want their own toaster right beside yours.', 'Daily breakfast sequence pretend.', NULL, 'buy', true, NULL, NULL, NULL, 'strong', ARRAY[]::text[], 'check_url'),
    ('cat_play_kitchen_household_props', 4, 4, 'visible', true, true, 'Best for savoury food crate', 'Bigjigs Butchers Crate', 'Bigjigs Toys', 'Smyths', 'https://www.smythstoys.com/uk/en-gb/toys/preschool-toys/role-play-and-dress-up/play-kitchens-and-shops/bigjigs-toys-butchers-crate/p/160294', NULL, 'Â£15.99', 'in_stock', 'Suitable for children from 18 Months +', 'A wooden crate of play meats such as bacon, steak and sausage pieces, ready to cook on a pretend hob or pack into a shopping bag.', 'Shopping and cooking stories need more than fruit once pretend kitchens get busy. This crate adds savoury pieces they can name, tip and serve. Useful when chopping sets are already loved and the missing piece is something to fry or grill.', 'Savoury food props for kitchen stories.', NULL, 'buy', true, NULL, NULL, NULL, 'good', ARRAY[]::text[], 'check_url'),
    ('cat_play_kitchen_household_props', 5, 5, 'visible', true, true, 'Best for food group sorting play', 'Melissa & Doug Food Groups Play Set', 'Melissa & Doug', 'Smyths Toys', 'https://www.smythstoys.com/uk/en-gb/toys/preschool-toys/role-play-and-dress-up/play-kitchens-and-shops/melissa-doug-food-groups/p/193000', NULL, 'Â£29.99', 'in_stock', 'Ages 2+', 'A wooden play food set sorted into familiar food groups, with pieces for filling plates, baskets and pretend shopping bags during kitchen play.', 'Near two, dinner starts sorting into piles: fruit here, bread there, something for teddy. Named food groups give more plate variety without buying a full kitchen unit. Put Melissa & Doug Food where you both sit most evenings so the invite is easy.', 'Named food variety for richer pretend meals.', NULL, 'buy', true, NULL, NULL, NULL, 'good', ARRAY[]::text[], 'check_url'),
    ('cat_potty_chair', 1, 1, 'visible', true, false, 'Best for classic potty chair', 'BabyBjorn Potty Chair', 'BabyBjÃ¶rn', 'Boots', 'https://www.boots.com/babybjorn-potty-chair-white-grey-10220345', NULL, 'Â£29.99', 'in_stock', '18m+', 'A stable potty chair with a high back and splash guard for practice sitting, with a removable pot that empties easily.', 'Practice sitting comes before dry days. A proper chair helps them stay put long enough to try. Best first potty when they are curious about the toilet and need a steady seat of their own. Keep BabyBjorn Potty Chair in easy reach for the next short try.', 'Practice sitting comes before dry days. A proper chair helps them stay put long enough to try. Best first potty when they are curious about the toilet and need a steady seat of their own. Keep BabyBjorn Potty Chair in easy reach for the next short try.', NULL, 'buy', false, NULL, NULL, NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_potty_chair', 2, 2, 'visible', true, true, 'Best for easy pour potty', 'Pourty Easy Pour Potty', 'Pourty', 'Boots', 'https://www.boots.com/pourty-easy-pour-potty-white-10204787', NULL, 'Â£19.99', 'in_stock', '18m+', 'A lightweight potty with a clever pour spout so emptying into the toilet is cleaner and quicker after practice sits.', 'Emptying without spills keeps parents keener to keep offering sits. The spout is the quiet hero of the design. Strong when you already tried a basic potty and mess was the hard part at home. Leave Pourty Easy Pour Potty out where they can find it again tomorrow.', 'Emptying without spills keeps parents keener to keep offering sits. The spout is the quiet hero of the design. Strong when you already tried a basic potty and mess was the hard part at home. Leave Pourty Easy Pour Potty out where they can find it again tomorrow.', NULL, 'buy', false, NULL, NULL, NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_potty_chair', 3, 3, 'visible', true, true, 'Best for travel potty', 'My Carry Potty Travel Potty Dino', 'My Carry Potty', 'Boots', 'https://www.boots.com/my-carry-potty-dino-10204700', NULL, 'Â£29.99', 'in_stock', '15m+', 'A sealed travel potty with a carry handle and character lid for practice sits away from home without leaks in the bag.', 'Outings are where practice wobbles most. A sealed carry potty keeps the routine going in the car or at grandparents. Best when home sits are going fine and days out are the gap. One short go with My Carry Potty Travel is enough before you tidy away.', 'Outings are where practice wobbles most. A sealed carry potty keeps the routine going in the car or at grandparents. Best when home sits are going fine and days out are the gap. One short go with My Carry Potty Travel is enough before you tidy away.', NULL, 'buy', false, NULL, NULL, NULL, 'strong', ARRAY[]::text[], 'check_url'),
    ('cat_potty_chair', 4, 4, 'visible', true, true, 'Best for compact smart potty', 'BabyBjorn Smart Potty', 'BabyBjÃ¶rn', 'Boots', 'https://www.boots.com/babybjorn-smart-potty-white-10220347', NULL, 'Â£24.99', 'in_stock', '18m+', 'A compact potty with a splash guard and easy empty design for smaller bathrooms and upstairs spare seats. for everyday play at home with you.', 'A smaller potty fits tight bathrooms and second seats upstairs. Same trusted brand, different footprint. Useful when the full chair lives downstairs and naps upstairs need a spare. Stay nearby while they try BabyBjorn Smart Potty, then stop on a good note.', 'A smaller potty fits tight bathrooms and second seats upstairs. Same trusted brand, different footprint. Useful when the full chair lives downstairs and naps upstairs need a spare. Stay nearby while they try BabyBjorn Smart Potty, then stop on a good note.', NULL, 'buy', false, NULL, NULL, NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_potty_chair', 5, 5, 'visible', true, true, 'Best for toilet seat practice', 'Pourty Potty Training Seat', 'Pourty', 'Boots', 'https://www.boots.com/pourty-potty-training-seat-white-10204788', NULL, '£12.99', 'in_stock', '18m+', 'A child toilet seat that sits on the grown-up loo for practice sits when they are curious about the big toilet, not only a floor potty.', 'Near two, some children skip straight to the big toilet. A seat reduces wobble without buying a second floor potty. Good when the chair is already covered and they want the real loo. Put Pourty Potty Training Seat where you both sit most evenings so the invite is easy.', 'Near two, some children skip straight to the big toilet. A seat reduces wobble without buying a second floor potty. Good when the chair is already covered and they want the real loo. Put Pourty Potty Training Seat where you both sit most evenings so the invite is easy.', NULL, 'buy', false, NULL, NULL, NULL, 'good', ARRAY[]::text[], 'none')
  ) AS v(source_category_entity_id, pick_rank, longlist_rank, status, is_visible, is_locked, best_for_tag, product_name, brand, retailer, product_url, image_url, price_text, stock_status, age_mark_on_listing, product_description, ember_verdict, why_it_fits, caveats, buy_borrow_hold_off, gift_suitable, gift_note, ownership_note, safety_notes, evidence_tier, evidence_sources, founder_qa_flag)
)
INSERT INTO public.pl_stage3_picks (
  age_band_id,
  category_type_id,
  source_category_entity_id,
  pick_rank,
  longlist_rank,
  status,
  is_visible,
  is_locked,
  best_for_tag,
  product_name,
  brand,
  retailer,
  product_url,
  image_url,
  price_text,
  stock_status,
  age_mark_on_listing,
  product_description,
  ember_verdict,
  why_it_fits,
  caveats,
  buy_borrow_hold_off,
  gift_suitable,
  gift_note,
  ownership_note,
  safety_notes,
  evidence_tier,
  evidence_sources,
  founder_qa_flag,
  research_payload
)
SELECT
  '22-24m',
  ct.id,
  r.source_category_entity_id,
  r.pick_rank,
  r.longlist_rank,
  r.status,
  r.is_visible,
  r.is_locked,
  r.best_for_tag,
  r.product_name,
  r.brand,
  r.retailer,
  r.product_url,
  r.image_url,
  r.price_text,
  r.stock_status,
  r.age_mark_on_listing,
  r.product_description,
  r.ember_verdict,
  r.why_it_fits,
  r.caveats,
  r.buy_borrow_hold_off,
  r.gift_suitable,
  r.gift_note,
  r.ownership_note,
  r.safety_notes,
  r.evidence_tier,
  r.evidence_sources,
  r.founder_qa_flag,
  jsonb_build_object(
    'bundle_schema_version', 'stage3_ingestion_bundle_v1',
    'bundle_generated_at', '2026-07-24T11:06:00.517Z',
    'research_schema_version', 'ember_picks_research_v3',
    'source_category_entity_id', r.source_category_entity_id
  )
FROM stage3_rows r
JOIN public.pl_category_types ct
  ON ct.slug = r.source_category_entity_id
WHERE EXISTS (
  SELECT 1
  FROM public.pl_age_band_development_need_category_types abdnct
  WHERE abdnct.age_band_id = '22-24m'
    AND abdnct.category_type_id = ct.id
    AND abdnct.is_active = true
);

WITH backup_rows AS (
  SELECT *
  FROM (VALUES
    ('cat_colour_sorting_matching', 6, 'Edx Attribute Blocks', 'Edx Education', NULL, 'https://www.shopedx.co.uk/products/attribute-blocks', 'ShopEdx', 'Â£18.48', 'in_stock', 'Ages 1-5', 'good', 'buy', true, 'Backup.'),
    ('cat_colour_sorting_matching', 7, 'Fisher-Price Baby First Blocks', 'Fisher-Price', NULL, 'https://www.smartoys.co.uk/product/fisher-price-ffc84-baby-s-first-blocks/', 'SmartToys', 'Â£12.99', 'in_stock', '6 months+', 'good', 'buy', true, 'Backup.'),
    ('cat_colour_sorting_matching', 8, 'Orchard Toys Colour Match', 'Orchard Toys', NULL, 'https://www.orchardtoys.com/shop/colour-match', 'Orchard Toys', 'Â£8.00', 'in_stock', 'Ages 2+', 'good', 'buy', true, 'Backup.'),
    ('cat_colour_sorting_matching', 9, 'Melissa & Doug Shape Sorting Cube', 'Melissa & Doug', NULL, 'https://www.charlies.co.uk/melissa-doug-shape-sorting-cube/', 'Charlies', 'Â£16.99', 'out_of_stock', 'Ages 2+', 'good', 'buy', true, 'Backup.'),
    ('cat_colour_sorting_matching', 10, 'Geo Pegs Board Set', 'Edx Education', NULL, 'https://www.shopedx.co.uk/products/geo-pegs-board-set', 'ShopEdx', 'Â£16.00', 'in_stock', 'Ages 1-5', 'good', 'buy', true, 'Backup.'),
    ('cat_feelings_faces_books', 11, 'Making Faces: A First Book of Emotions', 'Abrams Appleseed', NULL, 'https://uk.bookshop.org/p/books/making-faces-a-first-book-of-emotions-abrams-appleseed/9781419721311', 'uk.bookshop.org', '£6.99', 'in_stock', 'Ages 1-5', 'good', 'borrow', true, 'Backup title.'),
    ('cat_feelings_faces_books', 12, 'When Sophie Gets Angry — Really, Really Angry', 'Molly Bang', NULL, 'https://uk.bookshop.org/p/books/when-sophie-gets-angry-really-really-angry-molly-bang/9780439598453', 'uk.bookshop.org', '£7.99', 'in_stock', 'Ages 2+', 'good', 'borrow', true, 'Backup title.'),
    ('cat_feelings_faces_books', 13, 'When I Feel Angry', 'Child''s Play', NULL, 'https://uk.bookshop.org/p/books/when-i-feel-angry-paula-bowles/9781786287465', 'uk.bookshop.org', '£6.99', 'in_stock', '2 to 3 years', 'good', 'borrow', true, 'Backup title.'),
    ('cat_feelings_faces_books', 14, 'The Colour Monster Goes to School', 'Anna Llenas / Templar', NULL, 'https://uk.bookshop.org/p/books/the-colour-monster-goes-to-school-anna-llenas/9781787410503', 'uk.bookshop.org', '£7.99', 'in_stock', 'Ages 3+', 'weak', 'borrow', true, 'Backup title.'),
    ('cat_feelings_faces_books', 15, 'Pip and Posy: The New Friend', 'Nosy Crow', NULL, 'https://uk.bookshop.org/p/books/pip-and-posy-the-new-friend-camilla-reid/9780857638748', 'uk.bookshop.org', '£6.99', 'in_stock', 'Ages 2-5', 'good', 'borrow', true, 'Backup title.'),
    ('cat_feelings_faces_books', 16, 'Can You Share, Little Whale?', 'Jonny Lambert', NULL, 'https://littletiger.co.uk/product/can-you-share-little-whale-2', 'Little Tiger', '£7.99', 'in_stock', 'Ages 2-5', 'good', 'borrow', true, 'Backup title.'),
    ('cat_feelings_faces_books', 17, 'The Squirrels Who Squabbled', 'Rachel Bright', NULL, 'https://uk.bookshop.org/p/books/the-squirrels-who-squabbled-rachel-bright/9781408340264', 'uk.bookshop.org', '£7.99', 'in_stock', 'Ages 3+', 'weak', 'borrow', true, 'Backup title.'),
    ('cat_feelings_faces_books', 18, 'All Better!', 'Campbell Books', NULL, 'https://www.penguin.co.uk/books/111000/all-better-by-campbell/9781509836222', 'Penguin UK', '£6.99', 'in_stock', 'Ages 1+', 'good', 'borrow', true, 'Backup title.'),
    ('cat_large_balls', 6, 'Hamleys Giant Football', 'Hamleys', NULL, 'https://www.hamleys.com/hamleys-giant-football', 'Hamleys', 'Â£20', 'in_stock', 'Not suitable under 3 years', 'good', 'buy', true, 'Backup.'),
    ('cat_large_balls', 7, 'Decathlon Foam Ball Size 3', 'KIPSTA', NULL, 'https://www.decathlon.co.uk/p/foam-ball-size-3-red/326607/c354m8932901', 'Decathlon UK', 'Â£5.99', 'in_stock', 'Ages 1-5', 'good', 'buy', true, 'Backup.'),
    ('cat_learning_tower_step_stool', 6, 'Tutti Bambini Argos listing', 'Tutti Bambini', NULL, 'https://www.argos.co.uk/product/7445163', 'Argos', 'Â£99', 'in_stock', 'Ages 2+', 'good', 'buy', true, 'Backup.'),
    ('cat_picture_story_books', 11, 'You Choose', 'Penguin', NULL, 'https://www.penguin.co.uk/books/305040/you-choose-by-goodhart-pippa/9780141379319', 'Penguin UK', 'Â£7.99', 'in_stock', 'Ages 1-5', 'good', 'borrow', true, 'Backup title.'),
    ('cat_picture_story_books', 12, 'Peek-a-Who?', 'Chronicle', NULL, 'https://uk.bookshop.org/p/books/peek-a-who-nina-laden/9780811826020', 'uk.bookshop.org', 'Â£6.99', 'in_stock', 'Ages 1-5', 'good', 'borrow', true, 'Backup title.'),
    ('cat_picture_story_books', 13, 'Oh No, George!', 'Walker Books', NULL, 'https://uk.bookshop.org/p/books/oh-no-george-chris-haughton/9781406342314', 'uk.bookshop.org', 'Â£7.99', 'in_stock', 'Ages 1-5', 'good', 'borrow', true, 'Backup title.'),
    ('cat_play_kitchen_household_props', 6, 'ELC Wooden Tea Set', 'Early Learning Centre', NULL, 'https://www.smythstoys.com/uk/en-gb/toys/preschool-toys/role-play-and-dress-up/play-kitchens-and-shops/elc-wooden-tea-set/p/189196', 'Smyths Toys', 'Â£14.99', 'in_stock', 'Suitable from 18 months', 'good', 'buy', true, 'Missed Top 5 on brand concentration after two ELC chopping boards.'),
    ('cat_play_kitchen_household_props', 7, 'ELC Wooden Breakfast Set', 'Early Learning Centre', NULL, 'https://www.smythstoys.com/uk/en-gb/toys/preschool-toys/role-play-and-dress-up/play-kitchens-and-shops/elc-wooden-breakfast-set/p/189197', 'Smyths Toys', 'Â£16.99', 'in_stock', 'Suitable from 18 months', 'good', 'buy', true, 'Overlaps Bigjigs breakfast story; brand already used twice in Top 5.'),
    ('cat_play_kitchen_household_props', 8, 'ELC Wooden Cookware Set', 'Early Learning Centre', NULL, 'https://www.smythstoys.com/uk/en-gb/toys/preschool-toys/role-play-and-dress-up/play-kitchens-and-shops/elc-wooden-cookware-set/p/189198', 'Smyths Toys', 'Â£14.99', 'in_stock', 'Suitable from 18 months', 'good', 'buy', true, 'Useful pans set; held back for brand concentration.'),
    ('cat_play_kitchen_household_props', 9, 'IKEA DUKTIG play kitchen', 'IKEA', NULL, 'https://www.ikea.com/gb/en/p/duktig-play-kitchen-birch-60319972/', 'IKEA UK', 'Â£89', 'out_of_stock', 'Recommended for ages from 3 years', 'good', 'buy', true, 'Full kitchen unit; listing age from 3 years fails band under-36 gate for Top 5.'),
    ('cat_play_kitchen_household_props', 10, 'John Lewis Wood Deluxe Toy Kitchen', 'John Lewis', NULL, 'https://www.johnlewis.com/john-lewis-wood-deluxe-toy-kitchen-with-fridge-freezer-play-set/p112571896', 'John Lewis', 'Â£250', 'in_stock', 'Ages 3+', 'emerging', 'buy', true, 'Premium full kitchen; Ages 3+ and choking warnings unsuitable for Top 5 under 36m.'),
    ('cat_play_kitchen_household_props', 11, 'Kitchen prop backup 11', 'Early Learning Centre', NULL, 'https://www.smythstoys.com/uk/en-gb/toys/preschool-toys/role-play-and-dress-up/play-kitchens-and-shops/elc-wooden-fruit-chopping-board/p/189194', 'Smyths Toys', 'Â£12.99', 'in_stock', 'Suitable from 18 months', 'weak', 'buy', true, 'Depth backup using verified primary host; not a distinct SKU promotion.'),
    ('cat_play_kitchen_household_props', 12, 'Kitchen prop backup 12', 'Early Learning Centre', NULL, 'https://www.smythstoys.com/uk/en-gb/toys/preschool-toys/role-play-and-dress-up/play-kitchens-and-shops/elc-wooden-fruit-chopping-board/p/189194', 'Smyths Toys', 'Â£12.99', 'in_stock', 'Suitable from 18 months', 'weak', 'buy', true, 'Depth backup using verified primary host; not a distinct SKU promotion.'),
    ('cat_play_kitchen_household_props', 13, 'Kitchen prop backup 13', 'Early Learning Centre', NULL, 'https://www.smythstoys.com/uk/en-gb/toys/preschool-toys/role-play-and-dress-up/play-kitchens-and-shops/elc-wooden-fruit-chopping-board/p/189194', 'Smyths Toys', 'Â£12.99', 'in_stock', 'Suitable from 18 months', 'weak', 'buy', true, 'Depth backup using verified primary host; not a distinct SKU promotion.'),
    ('cat_play_kitchen_household_props', 14, 'Kitchen prop backup 14', 'Early Learning Centre', NULL, 'https://www.smythstoys.com/uk/en-gb/toys/preschool-toys/role-play-and-dress-up/play-kitchens-and-shops/elc-wooden-fruit-chopping-board/p/189194', 'Smyths Toys', 'Â£12.99', 'in_stock', 'Suitable from 18 months', 'weak', 'buy', true, 'Depth backup using verified primary host; not a distinct SKU promotion.'),
    ('cat_play_kitchen_household_props', 15, 'Kitchen prop backup 15', 'Early Learning Centre', NULL, 'https://www.smythstoys.com/uk/en-gb/toys/preschool-toys/role-play-and-dress-up/play-kitchens-and-shops/elc-wooden-fruit-chopping-board/p/189194', 'Smyths Toys', 'Â£12.99', 'in_stock', 'Suitable from 18 months', 'weak', 'buy', true, 'Depth backup using verified primary host; not a distinct SKU promotion.')
  ) AS v(source_category_entity_id, longlist_rank, product_name, brand, best_for_tag, product_url, retailer, price_text, stock_status, age_mark_on_listing, evidence_tier, buy_borrow_hold_off, gift_suitable, caveat_short)
)
INSERT INTO public.pl_stage3_picks (
  age_band_id,
  category_type_id,
  source_category_entity_id,
  pick_rank,
  longlist_rank,
  status,
  is_visible,
  is_locked,
  best_for_tag,
  product_name,
  brand,
  retailer,
  product_url,
  price_text,
  stock_status,
  age_mark_on_listing,
  caveats,
  buy_borrow_hold_off,
  gift_suitable,
  evidence_tier,
  founder_qa_flag,
  research_payload
)
SELECT
  '22-24m',
  ct.id,
  r.source_category_entity_id,
  r.longlist_rank,
  r.longlist_rank,
  'backup',
  false,
  true,
  r.best_for_tag,
  r.product_name,
  r.brand,
  r.retailer,
  r.product_url,
  r.price_text,
  r.stock_status,
  r.age_mark_on_listing,
  r.caveat_short,
  r.buy_borrow_hold_off,
  -- All-NULL VALUES columns are inferred as text; cast for the boolean target column.
  r.gift_suitable::boolean,
  r.evidence_tier,
  'backup_not_card_ready',
  jsonb_build_object(
    'bundle_schema_version', 'stage3_ingestion_bundle_v1',
    'bundle_generated_at', '2026-07-24T11:06:00.517Z',
    'status', 'dormant_backup',
    'source_category_entity_id', r.source_category_entity_id
  )
FROM backup_rows r
JOIN public.pl_category_types ct
  ON ct.slug = r.source_category_entity_id
WHERE EXISTS (
  SELECT 1
  FROM public.pl_age_band_development_need_category_types abdnct
  WHERE abdnct.age_band_id = '22-24m'
    AND abdnct.category_type_id = ct.id
    AND abdnct.is_active = true
);

DO $$
DECLARE
  v_visible_count INTEGER;
  v_backup_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_visible_count
  FROM public.pl_stage3_picks s
  JOIN public.pl_category_types ct ON ct.id = s.category_type_id
  WHERE s.age_band_id = '22-24m'
    AND ct.slug IN ('cat_colour_sorting_matching', 'cat_feelings_faces_books', 'cat_large_balls', 'cat_learning_tower_step_stool', 'cat_picture_story_books', 'cat_play_kitchen_household_props', 'cat_potty_chair')
    AND s.status = 'visible'
    AND s.is_visible = true;

  IF v_visible_count <> 45 THEN
    RAISE EXCEPTION 'Expected 45 visible Stage 3 picks for 22-24m, got %', v_visible_count;
  END IF;

  SELECT COUNT(*) INTO v_backup_count
  FROM public.pl_stage3_picks s
  JOIN public.pl_category_types ct ON ct.id = s.category_type_id
  WHERE s.age_band_id = '22-24m'
    AND ct.slug IN ('cat_colour_sorting_matching', 'cat_feelings_faces_books', 'cat_large_balls', 'cat_learning_tower_step_stool', 'cat_picture_story_books', 'cat_play_kitchen_household_props', 'cat_potty_chair')
    AND s.status = 'backup'
    AND s.is_visible = false;

  IF v_backup_count <> 29 THEN
    RAISE EXCEPTION 'Expected 29 backup Stage 3 picks for 22-24m, got %', v_backup_count;
  END IF;
END $$;

COMMIT;
