-- Generated by web/scripts/ingest-stage3-pips-picks.mjs
-- Bundle: agent-tools/exports/stage3_ingestion_bundle_28-30m.json

BEGIN;

CREATE TABLE IF NOT EXISTS public.pl_stage3_picks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  age_band_id TEXT NOT NULL REFERENCES public.pl_age_bands(id) ON DELETE RESTRICT,
  category_type_id UUID NOT NULL REFERENCES public.pl_category_types(id) ON DELETE CASCADE,
  source_category_entity_id TEXT NOT NULL,
  pick_rank INTEGER NOT NULL CHECK (pick_rank > 0),
  longlist_rank INTEGER NOT NULL CHECK (longlist_rank > 0),
  status TEXT NOT NULL CHECK (status IN ('visible', 'backup', 'skip')),
  is_visible BOOLEAN NOT NULL DEFAULT true,
  is_locked BOOLEAN NOT NULL DEFAULT true,
  best_for_tag TEXT,
  product_name TEXT NOT NULL,
  brand TEXT,
  retailer TEXT,
  product_url TEXT,
  image_url TEXT,
  price_text TEXT,
  stock_status TEXT,
  age_mark_on_listing TEXT,
  product_description TEXT,
  ember_verdict TEXT,
  why_it_fits TEXT,
  caveats TEXT,
  buy_borrow_hold_off TEXT,
  gift_suitable BOOLEAN,
  gift_note TEXT,
  ownership_note TEXT,
  safety_notes TEXT,
  evidence_tier TEXT,
  evidence_sources TEXT[],
  founder_qa_flag TEXT,
  research_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT pl_stage3_picks_unique UNIQUE (age_band_id, category_type_id, pick_rank, status)
);

ALTER TABLE public.pl_stage3_picks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pl_stage3_picks_public_read" ON public.pl_stage3_picks;
CREATE POLICY "pl_stage3_picks_public_read" ON public.pl_stage3_picks
  FOR SELECT
  TO anon, authenticated
  USING (
    status = 'visible'
    AND is_visible = true
    AND (
      is_locked = false
      OR lower(coalesce(auth.jwt() ->> 'email', '')) = 'timwd23@gmail.com'
      OR lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'membership_type', '')) = 'ember_plus'
    )
  );

DROP POLICY IF EXISTS "pl_stage3_picks_admin_all" ON public.pl_stage3_picks;
CREATE POLICY "pl_stage3_picks_admin_all" ON public.pl_stage3_picks
  FOR ALL
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

GRANT SELECT ON public.pl_stage3_picks TO anon, authenticated;

CREATE INDEX IF NOT EXISTS pl_stage3_picks_age_category_rank_idx
  ON public.pl_stage3_picks(age_band_id, category_type_id, status, pick_rank);

DROP TRIGGER IF EXISTS trg_pl_stage3_picks_updated_at ON public.pl_stage3_picks;
CREATE TRIGGER trg_pl_stage3_picks_updated_at
  BEFORE UPDATE ON public.pl_stage3_picks
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

DROP VIEW IF EXISTS public.v_gateway_stage3_picks_public;
CREATE VIEW public.v_gateway_stage3_picks_public
WITH (security_invoker = true) AS
SELECT
  s.id,
  s.age_band_id,
  s.category_type_id,
  ct.slug AS category_type_slug,
  s.source_category_entity_id,
  s.pick_rank,
  s.longlist_rank,
  s.status,
  s.is_visible,
  s.is_locked,
  s.best_for_tag,
  s.product_name,
  s.brand,
  s.retailer,
  s.product_url,
  s.image_url,
  s.price_text,
  s.stock_status,
  s.age_mark_on_listing,
  s.product_description,
  s.ember_verdict,
  s.why_it_fits,
  s.caveats,
  s.buy_borrow_hold_off,
  s.gift_suitable,
  s.gift_note,
  s.ownership_note,
  s.safety_notes,
  s.evidence_tier,
  s.evidence_sources,
  s.founder_qa_flag,
  s.research_payload
FROM public.pl_stage3_picks s
JOIN public.pl_category_types ct ON ct.id = s.category_type_id
WHERE s.status = 'visible'
  AND s.is_visible = true
  AND s.is_locked = false;

GRANT SELECT ON public.v_gateway_stage3_picks_public TO anon, authenticated;

DELETE FROM public.pl_stage3_picks
WHERE age_band_id = '28-30m'
  AND source_category_entity_id IN ('cat_feelings_faces_books', 'cat_picture_story_books', 'cat_play_kitchen_household_props', 'cat_potty', 'cat_shape_sorters_puzzles', 'cat_soft_graspable_balls', 'cat_step_stool');

WITH stage3_rows AS (
  SELECT *
  FROM (VALUES
    ('cat_feelings_faces_books', 1, 1, 'visible', true, false, 'Best for naming surprise', 'When I Feel Surprised', 'Child''s Play', 'Waterstones', 'https://www.waterstones.com/book/when-i-feel-surprised/paula-bowles/childs-play/9781786287496', NULL, '£5.99', 'in_stock', '2 to 3 years', 'A sturdy board book that names the feeling of surprise through colourful creatures and short, warm lines little hands can hold at sofa or bedtime story time.', 'At nearly two and a half, feelings start as faces and simple names, not friendship repair chats. A short board book that sticks to surprise gives you one clear word to practise together. Naming surprise stays light, without turning evening into a behaviour chat.', 'Directly addresses emotion identification and is part of a series covering core feelings, ideal for 28-30m. The simple, non-gendered approach supports early emotional literacy.', 'While highly relevant, the number of online reviews is low, suggesting it might be a newer or less widely reviewed title. However, the expert backing from a child psychologist provides strong validation.', 'buy', true, 'A thoughtful gift for a child with big feelings or a new sibling.', 'Pick gentle stories rather than moral lessons.', '(none)', 'good', ARRAY['https://www.amazon.co.uk/When-Feel-Surprised-First-Feelings/dp/1786287498', 'https://www.waterstones.com/book/when-i-feel-surprised/paula-bowles/childs-play/9781786287496']::text[], 'none'),
    ('cat_feelings_faces_books', 2, 2, 'visible', true, true, 'Best for mood matching', 'Happy as a Lamb: Choose Your Mood, Express Your Feelings', 'Mama Makes Books', 'Waterstones', 'https://www.waterstones.com/book/happy-as-a-lamb-choose-your-mood-express-your-feelings/teresa-bellon/mama-makes-books/9781916780002', NULL, '£7.99', 'in_stock', '2 to 5 years', 'An interactive board book with chunky puzzle pieces so your child can pick a mood face, match a feeling, and try a simple idea of what to do next.', 'Mood matching is new once they can point at a face and try a word. Puzzle pieces turn naming into a hands on game rather than a quiz on the sofa. Useful when you want them to choose a feeling, not sit through a long talk about emotions.', 'Interactive format and broad emotional vocabulary are excellent for this age. The focus on identifying and expressing feelings through play is highly relevant to the cluster objective.', 'The listed age range extends to 5 years, but the interactive board book format and simple concepts are well-suited for the younger end of this spectrum. Limited public reviews, but strong editorial praise.', 'buy', true, 'A thoughtful gift for a child with big feelings or a new sibling.', 'Pick gentle stories rather than moral lessons.', '(none)', 'good', ARRAY['https://www.booktrust.org.uk/book-recommendations/bookfinder/happy-as-a-lamb-choose-your-mood-express-your-feelings/', 'https://www.waterstones.com/book/happy-as-a-lamb-choose-your-mood-express-your-feelings/teresa-bellon/mama-makes-books/9781916780002']::text[], 'none'),
    ('cat_feelings_faces_books', 3, 3, 'visible', true, true, 'Best for a breathe together try', 'Just Breathe, Bear', 'Curious Fox', 'BookTrust (listed)', 'https://www.booktrust.org.uk/book-recommendations/bookfinder/just-breathe-bear/', NULL, 'Price not found on BookTrust', 'in_stock', '2 to 3 years', 'A soft picture book where Bear shows a simple breathe in and breathe out pattern when worry, sadness or cross feelings turn up, with clear faces to recognise.', 'Big feelings arrive faster than words at nearly two and a half. A short breathe together story gives you a shared action to try when the house is noisy, without turning it into a therapy chat. Handy for a breathe together try before you reach for screens or scolding.', 'Offers a practical coping strategy for managing emotions, which is an important aspect of emotional development at this age. Clear, simple illustrations aid emotion recognition.', 'Price and retail availability need further checking as BookTrust is an editorial site. However, the content is highly relevant.', 'buy', true, 'A thoughtful gift for a child with big feelings or a new sibling.', 'Pick gentle stories rather than moral lessons.', '(none)', 'good', ARRAY['https://www.booktrust.org.uk/book-recommendations/bookfinder/just-breathe-bear/']::text[], 'check_price'),
    ('cat_feelings_faces_books', 4, 4, 'visible', true, true, 'Best for happy naming', 'I am Happy', 'Walker Books', 'BookTrust (listed)', 'https://www.booktrust.org.uk/book-recommendations/bookfinder/i-am-happy/', NULL, 'Price not found on BookTrust', 'in_stock', '2 to 3 years', 'A rhyming Michael Rosen picture book that celebrates everyday happiness, with bold pictures and short lines that invite your child to say what makes them glad.', 'Positive feelings need names too, not only the sticky ones. A lively rhyme keeps happy naming playful so you can practise the word without it sounding like homework. Good when you want joy on the page, not another big feelings chart.', 'Focuses on a positive core emotion with simple, engaging text and illustrations, suitable for early emotion identification.', 'Price and retail availability need further checking as BookTrust is an editorial site. However, the content is highly relevant.', 'buy', true, 'A thoughtful gift for a child with big feelings or a new sibling.', 'Pick gentle stories rather than moral lessons.', '(none)', 'good', ARRAY['https://www.booktrust.org.uk/book-recommendations/bookfinder/i-am-happy/']::text[], 'check_price'),
    ('cat_feelings_faces_books', 5, 5, 'visible', true, true, 'Best for question led feelings', 'Big Feelings (Why? Questions And Answers For Toddlers)', 'Yoyo Books', 'Waterstones', 'https://www.waterstones.com/book/big-feelings-why-questions-and-answers-for-toddlers/9789465055190', NULL, '£8.99', 'in_stock', 'Toddlers', 'A toddler board book that pairs short questions and answers about big feelings, so you can read a page, pause, and let your child point or try a word.', 'Question led reading fits this age better than long explanations. Short question and answer pages leave space for pointing and a first try at a feeling word. Question led feelings work when you want a chat that stays short and shared at nearly two and a half.', 'Addresses ''big feelings'' directly with a Q&A format, promoting understanding and discussion, suitable for the age band.', 'General ''Toddlers'' age marking, but content aligns with 28-30m. No specific review data found, but the concept is strong.', 'buy', true, 'A thoughtful gift for a child with big feelings or a new sibling.', 'Pick gentle stories rather than moral lessons.', '(none)', 'good', ARRAY['https://www.waterstones.com/book/big-feelings-why-questions-and-answers-for-toddlers/9789465055190']::text[], 'none'),
    ('cat_picture_story_books', 1, 1, 'visible', true, false, 'Best for what next presses', 'Press Here', 'Chronicle Books', 'Waterstones', 'https://www.waterstones.com/book/press-here/herve-tullet/9781452178592', NULL, '£7.99', 'in_stock', '0-3 years (implied)', 'An interactive board book where coloured dots appear to respond when you press, tap, shake or tip the page, so your child helps the story move on with their hands.', 'At nearly two and a half, little stories grow from cause and effect more than long plots. Pressing a page and asking what happens next keeps talk playful, not a quiz. What next presses invite joining in without needing a full narrative yet.', 'Perfectly aligns with the 28-30m stage by encouraging question-led naming and understanding of simple actions and reactions, a precursor to short story arcs.', NULL, 'buy', true, 'A strong gift if the family enjoys books. Look for sturdy pages and familiar scenes.', 'If you already have lots of board books, choose ones with clearer stories or more to talk about.', NULL, 'strong', ARRAY['https://www.waterstones.com/book/press-here/herve-tullet/9781452178592']::text[], 'none'),
    ('cat_picture_story_books', 2, 2, 'visible', true, true, 'Best for animal sound questions', 'On the Farm: A push pull slide board book', 'Campbell Books', 'Amazon UK', 'https://www.amazon.co.uk/Axel-Scheffler-Farm/dp/1509866949', NULL, '£4.50', 'in_stock', '1-4 years', 'A push, pull and slide board book that hides and reveals farm animals, so you can ask who is under the flap and what sound they make as each page opens.', 'Farm favourites still earn their keep when the job is linking a name to a sound. Push and pull bits turn naming into a game you share on the sofa. Animal sound questions stay friendly, without turning talk into a test.', 'Encourages question-led naming and action words, directly supporting the 28-30m stage of linking words together without turning talk into a test.', NULL, 'buy', true, 'A strong gift if the family enjoys books. Look for sturdy pages and familiar scenes.', 'If you already have lots of board books, choose ones with clearer stories or more to talk about.', NULL, 'good', ARRAY['https://www.amazon.co.uk/Axel-Scheffler-Farm/dp/1509866949']::text[], 'none'),
    ('cat_picture_story_books', 3, 3, 'visible', true, true, 'Best for home object spotting', 'Very First Book of Things to Spot At Home', 'Usborne', 'Amazon UK', 'https://www.amazon.co.uk/Very-First-Things-Spot-Home/dp/147492209X', NULL, '£8.00', 'in_stock', '18 months +', 'A bright Usborne spotter book packed with everyday home objects to find and name, from soft toys to cups, so pointing and simple questions stay close to daily life.', 'Familiar rooms make the best first spotters once they want to show you what they know. Finding the teddy or the cup links words to things they already touch. Home object spotting respects what is already in the house at nearly two and a half.', 'Directly supports question-led naming and early explanations by focusing on familiar objects, making it easy for toddlers to engage and form simple questions.', NULL, 'buy', true, 'A strong gift if the family enjoys books. Look for sturdy pages and familiar scenes.', 'If you already have lots of board books, choose ones with clearer stories or more to talk about.', NULL, 'good', ARRAY['https://www.amazon.co.uk/Very-First-Things-Spot-Home/dp/147492209X']::text[], 'none'),
    ('cat_picture_story_books', 4, 4, 'visible', true, true, 'Best for rhyme prediction', 'Oi Frog', 'Hachette Children''s Group', 'Amazon UK', 'https://www.amazon.co.uk/Oi-Frog-Friends/dp/1444910868', NULL, '£7.00', 'in_stock', '2-5 years', 'A hilarious rhyming picture book about a frog who learns where animals are meant to sit, with punchy page turns that beg for a guess before the next rhyme arrives.', 'Rhyme prediction is a step on from naming single words at nearly two and a half. A funny sit where rule invites guesses and giggles without needing a long plot. Rhyme prediction keeps language play silly and shared at bedtime or sofa story time.', 'The repetitive and rhyming nature encourages toddlers to anticipate and ask questions, reinforcing early language patterns and linking words together in a playful context.', NULL, 'buy', true, 'A strong gift if the family enjoys books. Look for sturdy pages and familiar scenes.', 'If you already have lots of board books, choose ones with clearer stories or more to talk about.', NULL, 'strong', ARRAY['https://www.amazon.co.uk/Oi-Frog-Friends/dp/1444910868']::text[], 'none'),
    ('cat_picture_story_books', 5, 5, 'visible', true, true, 'Best for flap and tickle turns', 'The Tickle Book', 'Macmillan Children''s Books', 'Amazon UK', 'https://www.amazon.co.uk/Tickle-Book-Ian-Whybrow/dp/0230747092', NULL, '£7.00', 'in_stock', '1-4 years', 'A lift the flap book full of animals and ticklish surprises, so you lift, tickle and ask who is hiding next in a short, physical read aloud you share together.', 'Interactive turns still build little stories when flaps and tickles do half the talking. Asking who is under here keeps participation high before they can follow a long plot. Flap and tickle turns help on busy evenings when you want joining in more than a long chapter.', 'The interactive elements and simple narrative encourage toddlers to ask questions about actions and characters, fostering early story comprehension and conversational skills, aligning with the 28-30m stage of telling little stories.', NULL, 'buy', true, 'A strong gift if the family enjoys books. Look for sturdy pages and familiar scenes.', 'If you already have lots of board books, choose ones with clearer stories or more to talk about.', NULL, 'good', ARRAY['https://www.amazon.co.uk/Tickle-Book-Ian-Whybrow/dp/0230747092']::text[], 'none'),
    ('cat_play_kitchen_household_props', 1, 1, 'visible', true, false, 'Best for full kitchen scenes', 'Little Dutch Wooden Play Kitchen - Mint', 'Little Dutch', 'Scandiborn', 'https://www.scandiborn.co.uk/products/little-dutch-wooden-play-kitchen-mint', NULL, '£129.95', 'in_stock', '3+', 'A wooden standing play kitchen in mint with oven, hob, sink and microwave, plus simple accessories, so your child can cook, wash and serve in one pretend kitchen corner.', 'At nearly two and a half, pretend play shifts from single actions to short scenes with a job. A full kitchen corner puts oven, sink and hob in one place so tea and washing up can happen together. Full kitchen scenes when you have floor space and want lasting helper play.', 'The Little Dutch kitchen is highly rated for its quality and aesthetic, fitting perfectly with the ''I''m making pretend worlds'' cluster. Its realistic features encourage detailed role-play, which is crucial for this age band''s cognitive development. The durable wooden design ensures it will withstand enthusiastic play.', 'While listed as 3+, many reviews indicate it''s suitable for younger toddlers, especially with supervision. It''s a larger item, so consider space availability.', 'buy', true, 'A strong gift if there is space and the family does not already have one.', 'If space is tight, a small tea set or pan-and-spoon basket can do the same job.', NULL, 'strong', ARRAY['https://learningbugs.co.uk/blogs/play-and-learning/little-dutch-kitchen-is-it-worth-it-uk-review-2026', 'https://www.scandiborn.co.uk/products/little-dutch-wooden-play-kitchen-mint', 'https://thekidcollective.co.uk/products/little-dutch-wooden-play-kitchen-mint-1']::text[], 'none'),
    ('cat_play_kitchen_household_props', 2, 2, 'visible', true, true, 'Best for small spaces', 'Chad Valley Wooden Table Top Mini Kitchen Roleplay', 'Chad Valley', 'Argos', 'https://www.argos.co.uk/product/7658747', NULL, '£18.00', 'in_stock', '3+', 'A compact wooden tabletop kitchen with a mini hob and sink, sized for floor or low table play when a full standing kitchen would take over the room.', 'Not every flat can host a full kitchen at nearly two and a half. A tabletop set still lets them run short cook and wash scenes beside the sofa. Small spaces keep helper play going without claiming a whole wall of the living room.', 'Its small footprint makes it accessible for many homes, and its wooden construction offers durability. It''s a great entry-level option for pretend play, aligning with the cluster''s focus on simple props for imaginative worlds.', 'Accessories are minimal, so additional play food or utensils might be desired. Best suited for floor play or a low table.', 'buy_pre_loved', true, 'A good gift for families with limited space or as an add-on to existing play sets.', 'Excellent for small spaces; can be easily stored away when not in use.', NULL, 'good', ARRAY['https://www.argos.co.uk/product/7658747']::text[], 'none'),
    ('cat_play_kitchen_household_props', 3, 3, 'visible', true, true, 'Best for busy helper detail', 'KidKraft Vintage Play Kitchen - White', 'KidKraft', 'Amazon UK', 'https://www.amazon.co.uk/dp/B004A2QTRC', NULL, '£119.99', 'in_stock', '3+', 'A classic wooden play kitchen with hob, oven, sink, ice maker and phone details, so pretend cooking can stretch into longer helper scenes with storage for pots and pans.', 'Once short tea parties stick at nearly two and a half, extra detail keeps scenes going. Phone and ice maker bits invite more roles without you directing every step. Busy helper detail for children who already like standing at a pretend hob.', 'This kitchen is consistently praised for its robust construction and engaging features, making it a staple for pretend play. It provides a rich environment for children to explore ''helper jobs'' and ''little figures'' within their pretend worlds.', 'Assembly can be time-consuming. While recommended for 3+, many parents introduce it earlier with supervision. It''s a significant investment, so consider long-term play value.', 'buy', true, 'A strong gift that offers lasting play value and can be passed down.', 'A larger item that requires dedicated play space, but its durability makes it a worthwhile investment.', NULL, 'strong', ARRAY[]::text[], 'check_reviews'),
    ('cat_play_kitchen_household_props', 4, 4, 'visible', true, true, 'Best for cook and serve kits', 'Hape Multi Function Kids Play Kitchen', 'Hape', 'Kiddies Kingdom', 'https://www.kiddies-kingdom.com/toys-accessories/51012-hape-multi-function-kids-play-kitchen.html', NULL, '£119.99', 'in_stock', '3+', 'A sturdy wooden play kitchen with cooker, oven, sink and storage, plus a starter pot, pan and utensils so cook and serve play can start on day one.', 'Accessories in the box mean they are not staring at empty hobs. Pot, pan and ladle let cook and serve scenes begin before you hunt for extra play food. A practical cook and serve kit when you want the first scene ready without a second shop.', 'Hape is known for its high-quality wooden toys, and this kitchen is no exception. It offers a good balance of features and durability, making it an excellent choice for developing imaginative play skills at this age.', 'Some assembly required. While rated 3+, it''s often introduced to younger toddlers with supervision. Accessories are basic, so additional play food might be desired.', 'buy', true, 'A strong gift that provides a complete play experience.', 'A good size for most playrooms, offering ample features without being overly bulky.', NULL, 'good', ARRAY['https://www.kiddies-kingdom.com/toys-accessories/51012-hape-multi-function-kids-play-kitchen.html']::text[], 'none'),
    ('cat_play_kitchen_household_props', 5, 5, 'visible', true, true, 'Best for oven only corners', 'Le Toy Van Honeybake Oven & Hob Set', 'Le Toy Van', 'Le Toy Van (direct)', 'https://letoyvan.co.uk/collections/role-play-cooking-wooden-kitchens/products/honeybake-oven-hob-set', NULL, '£69.95', 'in_stock', '3+', 'A compact wooden oven and hob set with a clock and utensils, made for a small kitchen corner or tabletop when a full standing unit is more than you need.', 'Sometimes the oven is the whole game at nearly two and a half. A hob and oven block still supports baking and stirring scenes beside other toys you already own. Oven only corners work well when floor space is short and imagination is not.', 'Le Toy Van is renowned for its quality and design. This set, while smaller, offers significant play value, encouraging children to use their imagination to create full kitchen scenes. It aligns with the cluster''s focus on providing props for pretend worlds.', 'This is a smaller set, so it may not be suitable as a standalone kitchen for all children. Additional play food and accessories would enhance the experience.', 'buy', true, 'A thoughtful gift for smaller homes or as an addition to an existing play area.', 'Its compact size makes it easy to store and move, ideal for versatile play spaces.', NULL, 'good', ARRAY['https://letoyvan.co.uk/collections/role-play-cooking-wooden-kitchens/products/honeybake-oven-hob-set']::text[], 'none'),
    ('cat_potty', 1, 1, 'visible', true, false, 'Best for supported sitting', 'Potty Chair', 'BabyBjörn', 'Amazon UK', 'https://www.amazon.co.uk/BabyBj%C3%B6rn-Potty-Chair-White-Grey/dp/B00005842W', NULL, '£28.00', 'in_stock', '18m+', 'A sturdy potty chair with a high backrest, armrests and a removable inner bowl, so early practice sitting stays steady and emptying stays straightforward after use.', 'Early potty tries at nearly two and a half need a seat that stays put while they sit and wait. High back and arms give support when legs still swing. Supported sitting for readiness led practice, without musical gimmicks getting in the way.', 'Provides the stability and comfort needed for a 28-30 month old who is just starting to practice sitting on a potty.', 'It is quite bulky, so it''s not ideal for small bathrooms or travel.', 'buy', false, 'This is a parent buy, not a default gift.', NULL, NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_potty', 2, 3, 'visible', true, true, 'Best for small bathrooms', 'Smart Potty', 'BabyBjörn', 'Amazon UK', 'https://www.amazon.co.uk/BabyBj%C3%B6rn-Smart-Potty-White-Grey/dp/B00005842X', NULL, '£25.00', 'in_stock', '18m+', 'A compact potty with a rubber non-slip base and removable inner bowl, shaped for tight bathroom corners where a high backed chair would crowd the floor.', 'Small bathrooms still need a stable first potty at nearly two and a half. The non-slip base keeps wriggly sits safer while the bowl lifts out to empty. Small bathrooms get readiness practice without claiming the whole bathroom floor space.', 'Simple and stable, perfect for readiness-led practice without taking up too much room.', 'Lacks the high back support of the Potty Chair.', 'buy', false, 'This is a parent buy, not a default gift.', NULL, NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_potty', 3, 6, 'visible', true, true, 'Best for pour out emptying', 'Easy Pour Potty', 'Pourty', 'Amazon UK', 'https://www.amazon.co.uk/Pourty-Easy-Pour-Potty-White/dp/B003V1W2R0', NULL, '£10.00', 'in_stock', '18m+', 'A one piece plastic potty with a rear pouring spout, so you tip contents into the toilet cleanly, with a wide seat for early practice sits at home.', 'Emptying is half the job of early practice at nearly two and a half. A rear spout means fewer spills than tipping a flat bowl. Pour out emptying keeps the adult side kinder on messy first weeks of potty tries.', 'Meets the need for an easy-to-clean, simple potty for early practice.', 'One-piece design means you have to wash the whole unit, not just an inner bowl.', 'buy', false, 'This is a parent buy, not a default gift.', NULL, NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_potty', 4, 7, 'visible', true, true, 'Best for travel practice', 'Travel Potty', 'My Carry Potty', 'John Lewis', 'https://www.johnlewis.com/my-carry-potty-travel-potty-dino/p5521669', NULL, '£29.99', 'in_stock', '15m+', 'A lightweight sealed travel potty with a carry handle and animal lid designs, so practice can continue on days out without needing a public toilet straight away.', 'Consistency wobbles when you leave the house at nearly two and a half. A sealed carry potty keeps the same sit available in the car or park. Travel practice when home sits are starting to stick and you want the familiar seat nearby.', 'Provides a familiar, stable potty option for toddlers practicing outside the home.', 'More expensive than basic potties and slightly harder to empty than two-piece designs.', 'buy', false, 'This is a parent buy, not a default gift.', NULL, NULL, 'strong', ARRAY['https://www.johnlewis.com/browse/baby-child/bathing-changing/baby-changing/potties/_/N-nth8Z1z0reba']::text[], 'none'),
    ('cat_potty', 5, 8, 'visible', true, true, 'Best for folding travel', '2-in-1 Convertible Travel Potty', 'Potette Plus', 'Amazon UK', 'https://www.amazon.co.uk/Potette-Plus-2-in-1-Travel-Potty/dp/B0016L0MMS', NULL, '£18.00', 'in_stock', '15m+', 'A foldable travel potty that converts into a toilet trainer seat and uses disposable absorbent bags when you need a standalone option packed in a bag.', 'Packing light still needs a familiar sit away from home at nearly two and a half. Folding into a bag, then opening as a seat or standalone potty, covers both jobs. Folding travel for families who need the dual option without a bulky chair.', 'Offers a practical, portable solution for potty practice away from home.', 'Requires purchasing disposable bags for use as a standalone potty.', 'buy', false, 'This is a parent buy, not a default gift.', NULL, NULL, 'strong', ARRAY[]::text[], 'none'),
    ('cat_shape_sorters_puzzles', 1, 1, 'visible', true, false, 'Best for chunky farm puzzles', 'Melissa & Doug Chunky Wooden Jigsaw Puzzle - Farm Animals', 'Melissa & Doug', 'Amazon UK', 'https://www.amazon.co.uk/Melissa-Doug-Chunky-Wooden-Jigsaw/dp/B00005B54W', NULL, '£12.99', 'in_stock', '2+', 'A wooden lift out farm animal puzzle with thick pegged pieces sized for little hands, so matching animals into the tray stays a clear fitting job on the floor.', 'Hands can solve more at nearly two and a half once pieces are chunky and the picture is familiar. Farm animals give a name and fit game without fiddly thin card. Chunky farm puzzles when they are ready for matching beyond a basic posting box.', 'Encourages problem-solving and fine motor development, fitting the stage shift towards more purposeful hand-eye coordination.', 'Ensure pieces are large enough to prevent choking hazards.', 'buy', true, 'A safe, classic gift when pieces are large and age-fit.', 'If they already have easy puzzles, look for one extra step: pegs, colour sorting or animals.', NULL, 'strong', ARRAY['https://www.amazon.co.uk/Melissa-Doug-Chunky-Wooden-Jigsaw/dp/B00005B54W']::text[], 'none'),
    ('cat_shape_sorters_puzzles', 2, 2, 'visible', true, true, 'Best for classic shape posting', 'Melissa & Doug Wooden Shape Sorting Cube - Classic Toy With 12 Shapes', 'Melissa & Doug', 'Amazon UK', 'https://www.amazon.co.uk/Melissa-Doug-Wooden-Shape-Sorting/dp/B00005B552', NULL, '£15.99', 'in_stock', '2+', 'A classic wooden sorting cube with twelve shaped blocks to post through matching holes, then tip out and try again when the box fills up on the living-room floor.', 'Posting still belongs in play when the challenge is more shapes, not a thinner puzzle. Twelve holes ask for a proper look before each push at nearly two and a half. Classic shape posting for children who have outgrown three shape sorters.', 'Encourages problem-solving and fine motor development, fitting the stage shift towards more purposeful hand-eye coordination.', 'Ensure pieces are large enough to prevent choking hazards.', 'buy', true, 'A safe, classic gift when pieces are large and age-fit.', 'If they already have easy puzzles, look for one extra step: pegs, colour sorting or animals.', NULL, 'strong', ARRAY['https://www.amazon.co.uk/Melissa-Doug-Wooden-Shape-Sorting/dp/B00005B552']::text[], 'none'),
    ('cat_shape_sorters_puzzles', 3, 3, 'visible', true, true, 'Best for first farm trays', 'Galt Toys Chunky Farm Puzzle', 'Galt Toys', 'Amazon UK', 'https://www.amazon.co.uk/Galt-Toys-Chunky-Farm-Puzzle/dp/B00005B55A', NULL, '£9.99', 'in_stock', '2+', 'A chunky wooden farm puzzle with large animal pieces that lift out of a tray, made for early fitting and matching without fiddly thin cardboard bits.', 'First farm trays should forgive clumsy fingers at nearly two and a half. Big pieces keep the work in the fit, not in fragile edges. A gentler farm tray when denser sets still ask too much of little hands and patience.', 'Encourages problem-solving and fine motor development, fitting the stage shift towards more purposeful hand-eye coordination.', 'Ensure pieces are large enough to prevent choking hazards.', 'buy', true, 'A safe, classic gift when pieces are large and age-fit.', 'If they already have easy puzzles, look for one extra step: pegs, colour sorting or animals.', NULL, 'strong', ARRAY['https://www.amazon.co.uk/Galt-Toys-Chunky-Farm-Puzzle/dp/B00005B55A']::text[], 'none'),
    ('cat_shape_sorters_puzzles', 4, 4, 'visible', true, true, 'Best for pegged animal lifts', 'Bigjigs Toys Wooden Chunky Lift Out Puzzle - Farm Animals', 'Bigjigs Toys', 'Wooden Toy Shop', 'https://www.woodentoyshop.co.uk/products/bigjigs-toys-wooden-chunky-lift-out-puzzle-farm-animals', NULL, '£14.99', 'in_stock', '2+', 'A wooden chunky farm puzzle with pegged animals you pull up and seat again, so grasping and placing get equal play on the tray during floor time.', 'Pegs change the job from sliding to lifting at nearly two and a half. That grip and place rhythm matches hands that want a clearer hold. Pegged animal lifts when posting boxes are already easy and they want a new fitting job.', 'Encourages problem-solving and fine motor development, fitting the stage shift towards more purposeful hand-eye coordination.', 'Ensure pieces are large enough to prevent choking hazards.', 'buy', true, 'A safe, classic gift when pieces are large and age-fit.', 'If they already have easy puzzles, look for one extra step: pegs, colour sorting or animals.', NULL, 'good', ARRAY['https://www.woodentoyshop.co.uk/products/bigjigs-toys-wooden-chunky-lift-out-puzzle-farm-animals']::text[], 'none'),
    ('cat_shape_sorters_puzzles', 5, 5, 'visible', true, true, 'Best for colour and shape sorting', 'Early Learning Centre Wooden Shape Sorter', 'Early Learning Centre', 'Early Learning Centre', 'https://www.elc.co.uk/c/wooden-toys/wooden-puzzles', NULL, '£10.00', 'in_stock', '2+', 'A wooden shape sorter with bright blocks to match by shape and colour through the lid holes, then empty and sort again on the living-room floor.', 'Colour plus shape doubles the look before you post job at nearly two and a half. A simple wooden sorter keeps that practice close without needing a full puzzle tray. Colour and shape sorting when you want posting with a second clue on each block.', 'Encourages problem-solving and fine motor development, fitting the stage shift towards more purposeful hand-eye coordination.', 'Ensure pieces are large enough to prevent choking hazards.', 'buy', true, 'A safe, classic gift when pieces are large and age-fit.', 'If they already have easy puzzles, look for one extra step: pegs, colour sorting or animals.', NULL, 'good', ARRAY['https://www.elc.co.uk/c/wooden-toys/wooden-puzzles']::text[], 'none'),
    ('cat_soft_graspable_balls', 1, 1, 'visible', true, false, 'Best for soft first kicks', 'Mini Football Sunny 300 Size 1 - Pastel Pink', 'KIPSTA', 'Decathlon', 'https://www.decathlon.co.uk/p/mini-football-sunny-300-size-1-pastel-pink/146095/c174c344c227m8753526', NULL, '£2.99', 'in_stock', 'Size 1', 'A lightweight soft foam size 1 football in pastel pink, easy for little feet to connect with indoors or on short garden kicks without a heavy match ball.', 'At nearly two and a half, kicking gets a proper job: send the ball, then chase it. Soft foam keeps first kicks kind on toes and furniture. Soft first kicks when you want solo chase play, not a team drill.', 'Perfectly sized and soft enough for a 28-30 month old to practice kicking without frustration or injury.', 'Foam may degrade over time with heavy outdoor use.', 'buy', true, 'A simple gift that works indoors or outdoors.', 'If the family has balls already, this is about giving movement a job, not adding duplicates.', NULL, 'strong', ARRAY['https://www.decathlon.co.uk/p/mini-football-sunny-300-size-1-pastel-pink/146095/c174c344c227m8753526']::text[], 'none'),
    ('cat_soft_graspable_balls', 2, 2, 'visible', true, true, 'Best for garden kickabouts', 'Garden Football - Size 1 (Mini)', 'FORZA', 'FORZA', 'https://www.forza.com/uk/forza-recreational-garden-football+forza_match_football_size-Size~1~Mini+pack_size-Pack~of~1', NULL, '£3.60', 'in_stock', 'Size 1', 'A soft, durable size 1 football made for casual garden kickabouts, tougher than pure foam so outdoor grass and patio play lasts longer between washes.', 'Garden play needs a ball that survives wet grass at nearly two and a half. A tougher size 1 still stays soft enough for toddler kicks. Garden kickabouts when indoor foam already gets them chasing and you want outdoor durability.', 'Durable enough for outdoor use while remaining soft enough for a toddler''s developing kick.', 'Might be slightly heavier than pure foam options.', 'buy', true, 'A simple gift that works indoors or outdoors.', 'If the family has balls already, this is about giving movement a job, not adding duplicates.', NULL, 'good', ARRAY['https://www.forza.com/uk/forza-recreational-garden-football+forza_match_football_size-Size~1~Mini+pack_size-Pack~of~1']::text[], 'none'),
    ('cat_soft_graspable_balls', 3, 3, 'visible', true, true, 'Best for little foot targets', '5-inch Soccer Ball (from Pack of 4 Toddler Balls)', 'INPODAK', 'Amazon UK', 'https://www.amazon.co.uk/INPODAK-Toddlers-Football-Basketball-Backyard/dp/B0BX24P61T', NULL, '£17.99', 'in_stock', '6 months - 5 years', 'A soft five inch soccer ball from a toddler multi ball pack, small enough for little feet to find and kick in a hallway or on the patio.', 'Smaller targets help when a full size 1 still looks huge at nearly two and a half. A five inch soft ball makes contact easier while chasing stays the game. Little foot targets for early accuracy without a heavy ball.', 'Small size and soft material are ideal for early kicking practice.', 'Comes as part of a set, which might be more than needed.', 'buy', true, 'A simple gift that works indoors or outdoors.', 'If the family has balls already, this is about giving movement a job, not adding duplicates.', NULL, 'strong', ARRAY['https://www.amazon.co.uk/INPODAK-Toddlers-Football-Basketball-Backyard/dp/B0BX24P61T']::text[], 'check_url'),
    ('cat_soft_graspable_balls', 4, 4, 'visible', true, true, 'Best for living-room chase', 'Foam Football', 'Sports Directory', 'Sports Direct', 'https://www.sportsdirect.com/sports-directory-foam-football-857872', NULL, '£6.00', 'in_stock', 'Not specified', 'A lightweight twenty centimetre foam football for indoor and outdoor play, big enough to see and soft enough to kick across a living-room carpet without hard edges.', 'Living-room chase needs soft bounce and a clear target at nearly two and a half. Twenty centimetres is easy to spot and send without worrying about shins. Living-room chase when the weather keeps you inside and kicking still wants a job.', 'The 20cm size is a good target for toddlers learning to kick with more purpose.', 'Foam can be picked at or bitten by some toddlers.', 'buy', true, 'A simple gift that works indoors or outdoors.', 'If the family has balls already, this is about giving movement a job, not adding duplicates.', NULL, 'good', ARRAY['https://www.sportsdirect.com/sports-directory-foam-football-857872']::text[], 'none'),
    ('cat_soft_graspable_balls', 5, 5, 'visible', true, true, 'Best for indoor soft foam', 'Soft Foam Football Blue - 20 cm', 'Twisk', 'Planet Happy Toys', 'https://www.planethappytoys.co.uk/product/13319/twisk-soft-foam-football-blue-20-cm-kids-play-ball.html', NULL, '£5.94', 'in_stock', '3 years+', 'A sturdy yet light twenty centimetre soft foam football in blue, made for little feet and hands when you want safe indoor kicks and short outdoor goes.', 'Another soft foam option if pink or branded kits are not your style at nearly two and a half. Same indoor friendly give with a simple blue ball. Indoor soft foam when you mainly need carpet safe kicking without a heavy match ball.', 'Soft foam construction is safe for indoor kicking practice.', 'Age mark is 3+, likely due to foam material which could be bitten off.', 'buy', true, 'A simple gift that works indoors or outdoors.', 'If the family has balls already, this is about giving movement a job, not adding duplicates.', 'Supervise to ensure child does not bite or pick off pieces of foam.', 'good', ARRAY['https://www.planethappytoys.co.uk/product/13319/twisk-soft-foam-football-blue-20-cm-kids-play-ball.html']::text[], 'check_age_fit'),
    ('cat_step_stool', 1, 1, 'visible', true, false, 'Best for low steady steps', 'Step Stool', 'BabyBjorn', NULL, 'https://www.babybjorn.co.uk/products/bathroom/step-stool/', 'https://a.storyblok.com/f/187315/1667x2500/2f2fa2de78/step-stool-deep-green-white-lookbook-04-pp-babybjorn.jpg/m/673.5x1010.0479904019196/smart/filters:quality(80)', '£24.90', 'in_stock', 'Not explicitly stated, but designed for toddlers learning independence.', 'A classic toddler step stool about fifteen centimetres high with a full non-slip top and stable base, so your child can reach the sink or toilet and move the stool themselves.', 'I want to do it myself peaks hard at nearly two and a half. A low steady step lets them reach handwashing without a tall learning tower. Low steady steps for daily sink and toothbrush jobs they insist on owning.', 'This stool is excellent for 28-30 month olds due to its low height, exceptional stability, and full non-slip coverage. It''s easy for little ones to move themselves, fostering independence in daily routines like handwashing and teeth brushing. Its simple, sturdy design aligns perfectly with the independence-seeking phase. The low height (6 inches) is ideal for this age band, differentiating it from taller learning towers, which are more suitable for older toddlers.', NULL, 'buy', false, NULL, 'Supervise step use and keep away from hot, sharp or unstable surfaces.', 'Use a stable stool with supervision.', 'strong', ARRAY[]::text[], 'none'),
    ('cat_step_stool', 2, 2, 'visible', true, true, 'Best for smaller budgets', 'FÖRSIKTIG children''s stool, white/turquoise', 'IKEA', NULL, 'https://www.ikea.com/gb/en/p/foersiktig-childrens-stool-white-turquoise-10591318/', 'https://www.ikea.com/gb/en/images/products/foersiktig-childrens-stool-white-turquoise__0727451_pe735777_s5.jpg', '£5.00', 'in_stock', 'Not explicitly stated, but reviews indicate suitability for toddlers.', 'A simple IKEA children''s stool with a wide curved base, grip on the underside and a non-slip top, standing about thirteen centimetres high for sink and toilet reach.', 'Not every first step needs a premium brand at nearly two and a half. A wide base and low height still cover handwashing and toilet reach. Kinder on smaller budgets when you want a no fuss first stool for daily jobs.', 'This stool is an excellent budget-friendly option for 28-30 month olds. Its wide, curved base and anti-slip features make it very stable, crucial for this age. The low height is perfect for promoting early independence without being too tall, aligning with the stage shift note of focusing on low, stable steps. It''s a practical choice for families seeking a no-frills, safe solution.', NULL, 'buy', false, NULL, 'Supervise step use and keep away from hot, sharp or unstable surfaces.', 'Use a stable stool with supervision.', 'strong', ARRAY[]::text[], 'none'),
    ('cat_step_stool', 3, 3, 'visible', true, true, 'Best for a slightly higher step', 'Step Stool', 'OXO Tot', NULL, 'https://www.amazon.co.uk/OXO-Tot-Step-Stool-White/dp/B0759QF6T2', 'https://m.media-amazon.com/images/I/51p0v7w-z8L._AC_SX679_.jpg', '£22.00', 'in_stock', 'Not explicitly stated, but designed for toddlers.', 'A sturdy single step stool about eighteen centimetres high with a non-slip step, a grip base and side handles, for sink and toilet reach as legs get longer.', 'A little more height helps once the lowest stools leave them on tiptoe at nearly two and a half. Handles make it easier for them to drag into place. A slightly higher step when the shortest stools already leave them stretching.', 'The OXO Tot Step Stool is a solid choice for 28-30 month olds, offering a good balance of height, stability, and safety features. Its 7-inch height provides a slightly higher boost than the BabyBjorn or IKEA options, which can be beneficial as toddlers grow. The non-slip surface and anti-skid bottom ensure secure use, supporting the child''s growing independence in daily tasks. It''s a reliable, well-designed option that fits the criteria for this age band.', NULL, 'buy', false, NULL, 'Supervise step use and keep away from hot, sharp or unstable surfaces.', 'Use a stable stool with supervision.', 'strong', ARRAY[]::text[], 'none'),
    ('cat_step_stool', 4, 4, 'visible', true, true, 'Best for toilet side footing', 'Step Stool', 'Bumbo', NULL, 'https://www.amazon.co.uk/Bumbo-Step-Stool-Hemlock-Size/dp/B0877B7Q63', 'https://m.media-amazon.com/images/I/61t-Xw+s6GL._AC_SX679_.jpg', '£16.00', 'in_stock', 'Not explicitly stated, but suitable for toddlers.', 'A lightweight single step stool with a contoured front that sits snug against the toilet base, plus a non-slip standing surface for potty practice reach.', 'Toilet side footing is its own job during potty weeks at nearly two and a half. The contoured edge hugs the base so the step stays useful beside the bowl. Toilet side footing when sink reach is already sorted elsewhere.', 'This stool is an excellent option for 28-30 month olds, particularly for potty training due to its contour design. Its stability and good anti-skid properties are key for this age, providing a safe platform for developing independence. The lightweight nature allows toddlers to move it themselves, reinforcing their desire to do things themselves. Its low height is appropriate for the age band, focusing on simple, steady steps rather than taller learning towers.', NULL, 'buy', false, NULL, 'Supervise step use and keep away from hot, sharp or unstable surfaces.', 'Use a stable stool with supervision.', 'strong', ARRAY[]::text[], 'none'),
    ('cat_step_stool', 5, 5, 'visible', true, true, 'Best for bamboo fibre builds', 'Kids Step Stool', 'EKOBO', NULL, 'https://ekobo.co/products/bamboo-kids-step-stool-lemon', 'https://ekobo.co/cdn/shop/files/yellow_stool_92cedc4d-1ab3-4554-a92f-d0e624b5ddb6.jpg?v=1783939783&width=1000', '£34.00', 'in_stock', 'Not explicitly stated, but suitable for toddlers.', 'A lightweight step stool made from bamboo fibre and food grade melamine, with a textured non-slip top about fifteen centimetres high for sink and counter reach.', 'Some families want materials beyond basic plastic at nearly two and a half. Bamboo fibre keeps the stool light enough for them to carry, with grip on top for wet feet. Bamboo fibre builds when the height and stability brief is already met.', 'The EKOBO Kids Step Stool is a great choice for 28-30 month olds, especially for families prioritizing eco-friendly materials. Its low height and anti-slip features provide the necessary stability and safety for this age group to practice independence in daily tasks. The lightweight design allows toddlers to easily move it, aligning with their desire to do things themselves. Its focus on low, stable steps makes it appropriate for the 28-30 month age band, distinguishing it from taller learning towers.', NULL, 'buy', false, NULL, 'Supervise step use and keep away from hot, sharp or unstable surfaces.', 'Use a stable stool with supervision.', 'good', ARRAY[]::text[], 'none')
  ) AS v(source_category_entity_id, pick_rank, longlist_rank, status, is_visible, is_locked, best_for_tag, product_name, brand, retailer, product_url, image_url, price_text, stock_status, age_mark_on_listing, product_description, ember_verdict, why_it_fits, caveats, buy_borrow_hold_off, gift_suitable, gift_note, ownership_note, safety_notes, evidence_tier, evidence_sources, founder_qa_flag)
)
INSERT INTO public.pl_stage3_picks (
  age_band_id,
  category_type_id,
  source_category_entity_id,
  pick_rank,
  longlist_rank,
  status,
  is_visible,
  is_locked,
  best_for_tag,
  product_name,
  brand,
  retailer,
  product_url,
  image_url,
  price_text,
  stock_status,
  age_mark_on_listing,
  product_description,
  ember_verdict,
  why_it_fits,
  caveats,
  buy_borrow_hold_off,
  gift_suitable,
  gift_note,
  ownership_note,
  safety_notes,
  evidence_tier,
  evidence_sources,
  founder_qa_flag,
  research_payload
)
SELECT
  '28-30m',
  ct.id,
  r.source_category_entity_id,
  r.pick_rank,
  r.longlist_rank,
  r.status,
  r.is_visible,
  r.is_locked,
  r.best_for_tag,
  r.product_name,
  r.brand,
  r.retailer,
  r.product_url,
  r.image_url,
  r.price_text,
  r.stock_status,
  r.age_mark_on_listing,
  r.product_description,
  r.ember_verdict,
  r.why_it_fits,
  r.caveats,
  r.buy_borrow_hold_off,
  r.gift_suitable,
  r.gift_note,
  r.ownership_note,
  r.safety_notes,
  r.evidence_tier,
  r.evidence_sources,
  r.founder_qa_flag,
  jsonb_build_object(
    'bundle_schema_version', 'stage3_ingestion_bundle_v1',
    'bundle_generated_at', '2026-07-23T20:57:38.347Z',
    'research_schema_version', 'ember_picks_research_v3',
    'source_category_entity_id', r.source_category_entity_id
  )
FROM stage3_rows r
JOIN public.pl_category_types ct
  ON ct.slug = r.source_category_entity_id
WHERE EXISTS (
  SELECT 1
  FROM public.pl_age_band_development_need_category_types abdnct
  WHERE abdnct.age_band_id = '28-30m'
    AND abdnct.category_type_id = ct.id
    AND abdnct.is_active = true
);

WITH backup_rows AS (
  SELECT *
  FROM (VALUES
    ('cat_feelings_faces_books', 6, 'What to Do When You Feel Like Biting', 'Cara Goodwin', NULL, 'https://www.waterstones.com/book/what-to-do-when-you-feel-like-biting/cara-goodwin/katie-turner/9798886081534', NULL, '£7.99', NULL, NULL, NULL, NULL, NULL, 'Addresses a common toddler behavior linked to strong feelings, offering guidance.'),
    ('cat_feelings_faces_books', 7, 'What to Do When You Feel Like Hitting', 'Cara Goodwin', NULL, 'https://www.waterstones.com/book/what-to-do-when-you-feel-like-hitting/cara-goodwin/katie-turner/9798886081657', NULL, '£7.99', NULL, NULL, NULL, NULL, NULL, 'Similar to the biting book, provides guidance for another challenging behavior driven by emotions.'),
    ('cat_feelings_faces_books', 8, 'Moodypuffs: A Feelings Book For Toddlers', 'Karmen Tartt', NULL, 'https://www.waterstones.com/book/moodypuffs/karmen-tartt/9798349503924', NULL, '£11.99', NULL, NULL, NULL, NULL, NULL, 'General feelings book for toddlers, good for expanding emotional vocabulary.'),
    ('cat_feelings_faces_books', 9, 'Just Now I Feel Angry', 'Adrian Laurent', NULL, 'https://www.waterstones.com/book/just-now-i-feel-angry/adrian-laurent/9798886081657', NULL, '£13.99', NULL, NULL, NULL, NULL, NULL, 'Focuses on anger and frustration, offering strategies for managing these specific emotions.'),
    ('cat_feelings_faces_books', 10, 'What to Do When It''s Time to Calm Down', 'Cara Goodwin', NULL, 'https://www.waterstones.com/book/what-to-do-when-its-time-to-calm-down/cara-goodwin/katie-turner/9798886081541', NULL, '£7.99', NULL, NULL, NULL, NULL, NULL, 'Provides practical calming strategies, complementing emotion identification.'),
    ('cat_feelings_faces_books', 11, 'I Count to 5. I Am Bigger Than Anger!', 'Suzanne T Christian', NULL, 'https://www.waterstones.com/book/i-count-to-5-i-am-bigger-than-anger/suzanne-t-christian/9798886081657', NULL, '£9.99', NULL, NULL, NULL, NULL, NULL, 'Offers a specific technique for managing anger, useful for this age.'),
    ('cat_feelings_faces_books', 12, 'Pea & Carrot: The Sad Book', 'Martin King', NULL, 'https://www.waterstones.com/book/pea-and-carrot-the-sad-book/martin-king/9798886081657', NULL, '£9.99', NULL, NULL, NULL, NULL, NULL, 'Part of a series focusing on individual emotions, good for targeted learning.'),
    ('cat_feelings_faces_books', 13, 'Pea & Carrot: The Happy Book', 'Martin King', NULL, 'https://www.waterstones.com/book/pea-and-carrot-the-happy-book/martin-king/9798886081657', NULL, '£9.99', NULL, NULL, NULL, NULL, NULL, 'Part of a series focusing on individual emotions, good for targeted learning.'),
    ('cat_feelings_faces_books', 14, 'Pea & Carrot: The Angry Book', 'Martin King', NULL, 'https://www.waterstones.com/book/pea-and-carrot-the-angry-book/martin-king/9798886081657', NULL, '£9.99', NULL, NULL, NULL, NULL, NULL, 'Part of a series focusing on individual emotions, good for targeted learning.'),
    ('cat_feelings_faces_books', 15, 'Pea & Carrot: The Scared Book', 'Martin King', NULL, 'https://www.waterstones.com/book/pea-and-carrot-the-scared-book/martin-king/9798886081657', NULL, '£9.99', NULL, NULL, NULL, NULL, NULL, 'Part of a series focusing on individual emotions, good for targeted learning.'),
    ('cat_picture_story_books', 6, 'National Trust: My Very First Spotter''s Guide: I Spot a Rabbit', 'Nosy Crow Ltd', NULL, 'https://www.amazon.co.uk/National-Trust-Spotters-Rabbit-Guides/dp/1805132733', NULL, '£7.99', NULL, NULL, NULL, NULL, NULL, 'Spotter guide encourages observation and naming, fostering questions and vocabulary development. Age-appropriate (2-3 years).'),
    ('cat_picture_story_books', 7, 'Let’s go home, Baby Chick', 'Nosy Crow', NULL, 'https://www.amazon.co.uk/Lets-Go-Home-Baby-Chick/dp/1839949937', NULL, '£7.49', NULL, NULL, NULL, NULL, NULL, 'Interactive board book with moving sliders, encourages children to help animals find their way home, fostering questions and problem-solving. Age-appropriate (2-4 years).'),
    ('cat_picture_story_books', 8, 'Story Path: An Interactive Board Book for Toddlers Where You Choose Your Own Adventure', 'Little Tiger Press', NULL, 'https://www.amazon.co.uk/Story-Path-Kate-Baker/dp/1835872867', NULL, '£9.99', NULL, NULL, NULL, NULL, NULL, 'Choose-your-own-adventure format encourages decision-making and imagination, leading to questions about choices and outcomes. Highly interactive.'),
    ('cat_picture_story_books', 9, 'We''re Going on a Bear Hunt: My First Opposites', 'Walker Books Ltd', NULL, 'https://www.amazon.co.uk/Were-Going-Bear-Hunt-Opposites/dp/1406399531', NULL, '£6.99', NULL, NULL, NULL, NULL, NULL, 'Interactive adventure based on a classic, teaches opposites and encourages finger-tracing. Good for early concepts and conversation.'),
    ('cat_picture_story_books', 10, 'We''re Going on a Bear Hunt: My First 123', 'Walker Books Ltd', NULL, 'https://www.amazon.co.uk/Were-Going-Bear-Hunt-First/dp/1406391301', NULL, '£6.99', NULL, NULL, NULL, NULL, NULL, 'Similar to the opposites book, focuses on early counting and number recognition in an interactive format.'),
    ('cat_picture_story_books', 11, 'Shark in the Park', 'Puffin', NULL, 'https://www.amazon.co.uk/Shark-Park-Nick-Sharratt/dp/0141322420', NULL, '£7.00', NULL, NULL, NULL, NULL, NULL, NULL),
    ('cat_picture_story_books', 12, 'Two Little Dicky Birds: A play-along adventure', 'Little Tiger Press', NULL, 'https://www.amazon.co.uk/Little-Dicky-Birds-Anna-Brooke/dp/183913352X', NULL, '£5.38', NULL, NULL, NULL, NULL, NULL, NULL),
    ('cat_picture_story_books', 13, 'Five Little Friends: A Collection of Finger Rhymes', 'Walker Books', NULL, 'https://www.amazon.co.uk/Five-Little-Friends-Collection-Finger/dp/1406395811', NULL, '£7.99', NULL, NULL, NULL, NULL, NULL, NULL),
    ('cat_picture_story_books', 14, 'Spooky Little Halloween: A Finger Wiggle Book', 'Walker Books Ltd', NULL, 'https://www.amazon.co.uk/Spooky-Little-Halloween-Finger-Wiggle/dp/1529512662', NULL, '£7.35', NULL, NULL, NULL, NULL, NULL, NULL),
    ('cat_picture_story_books', 15, 'Baby’s First Puzzle Books: Set of Interactive Baby Books for Sensory Learning', 'Highlights', NULL, 'https://www.amazon.co.uk/Babys-First-Puzzle-Books-Highlights/dp/1639622845', NULL, '£23.75', NULL, NULL, NULL, NULL, NULL, NULL),
    ('cat_play_kitchen_household_props', 6, 'IKEA Duktig Play Kitchen', 'IKEA', NULL, 'https://www.ikea.com/gb/en/p/duktig-play-kitchen-birch-60319972/', NULL, '£70.00', NULL, NULL, NULL, NULL, NULL, 'Popular, customizable, and good value for money. Excellent base for personalization.'),
    ('cat_play_kitchen_household_props', 7, 'Teamson Kids Little Chef Chelsea Modern Play Kitchen', 'Teamson Kids', NULL, 'https://www.wayfair.co.uk/children-nursery/pdp/teamson-kids-little-chef-chelsea-modern-play-kitchen-w005230999.html', NULL, '£119.99', NULL, NULL, NULL, NULL, NULL, 'Modern design with good features, appealing to parents looking for a contemporary aesthetic.'),
    ('cat_play_kitchen_household_props', 8, 'Melissa & Doug Wooden Chef''s Pretend Play Kitchen', 'Melissa & Doug', NULL, 'https://www.amazon.co.uk/Melissa-Doug-Wooden-Chefs-Kitchen/dp/B0032J2T3Q', NULL, '£149.99', NULL, NULL, NULL, NULL, NULL, 'Reputable brand, durable construction, and classic design for sustained play.'),
    ('cat_play_kitchen_household_props', 9, 'Tidlo Wooden Play Kitchen', 'Tidlo', NULL, 'https://www.argos.co.uk/product/7658747', NULL, '£135.00', NULL, NULL, NULL, NULL, NULL, 'Sturdy wooden construction, good size for toddlers, and encourages imaginative play.'),
    ('cat_play_kitchen_household_props', 10, 'Smoby Tefal Studio Kitchen XL', 'Smoby', NULL, 'https://www.smythstoys.com/uk/en-gb/toys/fashion-and-dolls/kitchens-and-household/smoby-tefal-studio-kitchen-xl/p/167280', NULL, '£100.00', NULL, NULL, NULL, NULL, NULL, 'Feature-rich with electronic sounds, appealing to children who enjoy interactive elements.'),
    ('cat_play_kitchen_household_props', 11, 'Janod Macaron Wooden Cooker', 'Janod', NULL, 'https://www.johnlewis.com/janod-macaron-wooden-cooker/p4926600', NULL, '£89.99', NULL, NULL, NULL, NULL, NULL, 'Stylish design and good quality, suitable for smaller spaces.'),
    ('cat_play_kitchen_household_props', 12, 'Little Tikes First Market Play Kitchen', 'Little Tikes', NULL, 'https://www.smythstoys.com/uk/en-gb/toys/fashion-and-dolls/kitchens-and-household/little-tikes-first-market-play-kitchen/p/187010', NULL, '£69.99', NULL, NULL, NULL, NULL, NULL, 'Combines kitchen and market stall play, offering varied role-play opportunities.'),
    ('cat_play_kitchen_household_props', 13, 'Step2 Grand Walk-In Play Kitchen', 'Step2', NULL, 'https://www.amazon.co.uk/Step2-Grand-Walk-Kitchen-Accessories/dp/B0042RU76O', NULL, '£299.99', NULL, NULL, NULL, NULL, NULL, 'Large, immersive play space for multiple children, with many interactive features.'),
    ('cat_play_kitchen_household_props', 14, 'Chad Valley Wooden Modern Kitchen Playset', 'Chad Valley', NULL, 'https://www.argos.co.uk/product/7480898', NULL, '£90.00', NULL, NULL, NULL, NULL, NULL, 'Affordable wooden option with a modern design, good for budget-conscious buyers.'),
    ('cat_play_kitchen_household_props', 15, 'Le Toy Van Honeybake Mixer Set', 'Le Toy Van', NULL, 'https://letoyvan.co.uk/collections/role-play-cooking-wooden-kitchens/products/honeybake-mixer-set', NULL, '£39.95', NULL, NULL, NULL, NULL, NULL, 'High-quality accessory set that complements any play kitchen, encouraging baking role-play.'),
    ('cat_potty', 9, 'Family Toilet Seat with Child Seat Built-in', 'Generic', NULL, 'https://www.amazon.co.uk/Family-Toilet-Seat-Child-Built/dp/B07P8B2Y2Z', NULL, '£19.00', NULL, NULL, NULL, NULL, NULL, 'Space-saving, replaces entire loo seat.'),
    ('cat_potty', 10, 'My Size Potty Pro', 'Ingenuity', NULL, 'https://www.johnlewis.com/ingenuity-my-size-potty-pro/p112625053', NULL, '£19.99', NULL, NULL, NULL, NULL, NULL, 'Realistic toilet design.'),
    ('cat_potty', 11, 'Potty, White', 'John Lewis', NULL, 'https://www.johnlewis.com/john-lewis-potty-white/p111715557', NULL, '£6.30', NULL, NULL, NULL, NULL, NULL, 'Budget-friendly, simple design.'),
    ('cat_potty', 12, 'My Little Trainer Seat, Green Dino', 'My Carry Potty', NULL, 'https://www.johnlewis.com/my-carry-potty-my-little-trainer-seat-green-dino/p6335704', NULL, '£15.00', NULL, NULL, NULL, NULL, NULL, 'Trainer seat, fun design.'),
    ('cat_potty', 13, 'Sturdy™ Potty Seat', 'Munchkin', NULL, 'https://www.johnlewis.com/munchkin-sturdy-potty-seat/p111566097', NULL, '£10.00', NULL, NULL, NULL, NULL, NULL, 'Potty seat, sturdy.'),
    ('cat_potty', 14, 'Prepare to Potty 3-in-1 Potty Training System', 'Ingenuity', NULL, 'https://www.johnlewis.com/ingenuity-prepare-to-potty-3-in-1-potty-training-system/p112653567', NULL, '£19.99', NULL, NULL, NULL, NULL, NULL, 'Multi-functional, grows with child.'),
    ('cat_potty', 15, 'Foldaway Travel Potty', 'Ingenuity', NULL, 'https://www.johnlewis.com/ingenuity-foldaway-travel-potty/p110194838', NULL, '£9.99', NULL, NULL, NULL, NULL, NULL, 'Foldable, travel-friendly.'),
    ('cat_shape_sorters_puzzles', 6, 'Melissa & Doug Geometric Stacker', 'Melissa & Doug', NULL, 'https://www.amazon.co.uk/Melissa-Doug-Geometric-Stacker-Educational/dp/B00005B54Y', NULL, '£14.99', NULL, NULL, NULL, NULL, NULL, 'Meets quality bar: Rating 4.7 with 8000 reviews.'),
    ('cat_shape_sorters_puzzles', 7, 'Melissa & Doug First Play Wooden Chunky Farm Animal Puzzle', 'Melissa & Doug', NULL, 'https://www.amazon.co.uk/Melissa-Doug-First-Chunky-Animal/dp/B079Z41R6G', NULL, '£10.99', NULL, NULL, NULL, NULL, NULL, 'Meets quality bar: Rating 4.6 with 3000 reviews.'),
    ('cat_shape_sorters_puzzles', 8, 'Bigjigs Toys Wooden Shape Sorter - Farm Animals', 'Bigjigs Toys', NULL, 'https://www.woodentoyshop.co.uk/products/bigjigs-toys-wooden-shape-sorter-farm-animals', NULL, '£12.99', NULL, NULL, NULL, NULL, NULL, 'Hidden gem potential: Rating 4.6 with 80 reviews.'),
    ('cat_shape_sorters_puzzles', 9, 'Galt Toys First Puzzle - Pets', 'Galt Toys', NULL, 'https://www.amazon.co.uk/Galt-Toys-First-Puzzle-Pets/dp/B00005B55B', NULL, '£8.99', NULL, NULL, NULL, NULL, NULL, 'Meets quality bar: Rating 4.5 with 2000 reviews.'),
    ('cat_shape_sorters_puzzles', 10, 'John Lewis & Partners Wooden Shape Sorter', 'John Lewis & Partners', NULL, 'https://www.johnlewis.com/john-lewis-partners-wooden-shape-sorter/p500000000', NULL, '£18.00', NULL, NULL, NULL, NULL, NULL, 'Hidden gem potential: Rating 4.6 with 60 reviews.'),
    ('cat_shape_sorters_puzzles', 11, 'Early Learning Centre Wooden Peg Puzzle - Vehicles', 'Early Learning Centre', NULL, 'https://www.elc.co.uk/c/wooden-toys/wooden-puzzles', NULL, '£8.00', NULL, NULL, NULL, NULL, NULL, 'Hidden gem potential: Rating 4.5 with 50 reviews.'),
    ('cat_shape_sorters_puzzles', 12, 'Melissa & Doug Wooden Animal Grabber Puzzle', 'Melissa & Doug', NULL, 'https://www.amazon.co.uk/Melissa-Doug-Wooden-Animal-Grabber/dp/B00005B54X', NULL, '£11.99', NULL, NULL, NULL, NULL, NULL, 'Meets quality bar: Rating 4.7 with 7000 reviews.'),
    ('cat_shape_sorters_puzzles', 13, 'Bigjigs Toys Wooden Chunky Lift Out Puzzle - Numbers', 'Bigjigs Toys', NULL, 'https://www.woodentoyshop.co.uk/products/bigjigs-toys-wooden-chunky-lift-out-puzzle-numbers', NULL, '£14.99', NULL, NULL, NULL, NULL, NULL, 'Hidden gem potential: Rating 4.6 with 90 reviews.'),
    ('cat_shape_sorters_puzzles', 14, 'Galt Toys Chunky Alphabet Puzzle', 'Galt Toys', NULL, 'https://www.amazon.co.uk/Galt-Toys-Chunky-Alphabet-Puzzle/dp/B00005B55C', NULL, '£11.99', NULL, NULL, NULL, NULL, NULL, 'Meets quality bar: Rating 4.5 with 4000 reviews.'),
    ('cat_shape_sorters_puzzles', 15, 'John Lewis & Partners Wooden Peg Puzzle - Animals', 'John Lewis & Partners', NULL, 'https://www.johnlewis.com/john-lewis-partners-wooden-peg-puzzle-animals/p500000001', NULL, '£15.00', NULL, NULL, NULL, NULL, NULL, 'Hidden gem potential: Rating 4.5 with 70 reviews.'),
    ('cat_soft_graspable_balls', 6, 'Soft Football (125mm)', 'Gompels', NULL, 'https://www.gompels.co.uk/soft-football.html', NULL, '£5.00', NULL, NULL, NULL, NULL, NULL, 'Small, soft football ideal for infant/primary settings. Good for various activities, but might be a bit small for primary kicking and chasing focus for 28-30m.'),
    ('cat_soft_graspable_balls', 7, 'Soft Foam Football - 12cm', 'Live4Sport', NULL, 'https://www.live4sport.co.uk/product/soft-foam-football-12cm/', NULL, '£2.00', NULL, NULL, NULL, NULL, NULL, 'Safe, lightweight 12cm ball. Promotes hand-eye coordination and balance, but similar to Gompels, potentially too small for primary kicking focus for 28-30m.'),
    ('cat_soft_graspable_balls', 8, 'Playground Balls for Toddlers 1-3 (2 Pack)', 'U&C Planet', NULL, 'https://www.u-buy.co.uk/product/DRU7VFY-kickball-playground-ball-8-5-inches-upgraded-rubber-bouncy-dodgeball-for-indoor-outdoor-ball-games-square-ball-for-kids-age-3-4-5-6-with-1-pump', NULL, '£15.00', NULL, NULL, NULL, NULL, NULL, 'Durable, non-toxic rubber balls, suitable for indoor/outdoor play. Good for toddlers aged 1 and above, but rubber might be harder than foam, and less ''soft'' for the category.'),
    ('cat_soft_graspable_balls', 9, 'Polka Dot Balls 20cm Pack of 4', 'First-Play', NULL, 'https://www.first-play.com/products/polka-dot-balls-20cm-pack-of-4', NULL, '£15.00', NULL, NULL, NULL, NULL, NULL, 'Soft, 20cm balls, good for playdates and general ball play. Suitable for toddlers, but a pack of 4 might be more than needed for a single child.'),
    ('cat_soft_graspable_balls', 10, 'Soft Spikey Balls 4pk', 'TTS', NULL, 'https://www.tts-group.co.uk/primary/pe-sports/balls/sensory-balls/', NULL, '£11.99', NULL, NULL, NULL, NULL, NULL, 'Sensory balls that can also be kicked and chased. Good for tactile stimulation and active play, but the primary focus is sensory, not pure kicking/chasing.'),
    ('cat_soft_graspable_balls', 11, 'Soft Sensory Balls', 'Early Learning Centre', NULL, 'https://www.elc.co.uk/early-learning-centre-soft-sensory-balls/p/554521', NULL, '£8.00', NULL, NULL, NULL, NULL, NULL, 'Soft and squeezy balls for sensory stimulation, but also suitable for gentle kicking and rolling. BPA free. Similar to TTS, more sensory focused.'),
    ('cat_soft_graspable_balls', 12, 'Prehistoric Land Play Ball', 'Rex London', NULL, 'https://smallkind.co.uk/collections/play-balls/products/prehistoric-land-play-ball', NULL, '£12.95', NULL, NULL, NULL, NULL, NULL, 'Inflatable rubber ball, soft and easy for little hands to grip.'),
    ('cat_soft_graspable_balls', 13, 'Sharks Play Ball', 'Rex London', NULL, 'https://smallkind.co.uk/collections/play-balls/products/sharks-play-ball', NULL, '£9.71', NULL, NULL, NULL, NULL, NULL, 'Inflatable rubber ball, soft and easy to grip, suitable for active play.'),
    ('cat_soft_graspable_balls', 14, 'Wild Wonders Play Ball', 'Rex London', NULL, 'https://smallkind.co.uk/collections/play-balls/products/wild-wonders-play-ball', NULL, '£12.95', NULL, NULL, NULL, NULL, NULL, 'Inflatable rubber ball, soft, easy to grip, suitable for active play.'),
    ('cat_soft_graspable_balls', 15, 'Foam Football (200mm)', 'Chad Valley', NULL, 'https://www.argos.co.uk/product/9203000', NULL, '£1.00', NULL, NULL, NULL, NULL, NULL, 'Very affordable soft foam football, good for indoor and outdoor play.'),
    ('cat_step_stool', 8, 'Single Step Stool', 'KEPLIN', NULL, NULL, NULL, '£14.00', NULL, NULL, NULL, NULL, NULL, 'Decent stability, but not as aesthetically pleasing as other options.'),
    ('cat_step_stool', 9, 'Toddler Step Stool', 'HomlyPro', NULL, NULL, NULL, '£18.00', NULL, NULL, NULL, NULL, NULL, 'Good non-slip features, but slightly heavier than ideal for toddler self-movement.'),
    ('cat_step_stool', 11, 'Wooden Step Stool', 'Tidlo', NULL, NULL, NULL, '£25.00', NULL, NULL, NULL, NULL, NULL, 'Natural wood, but heavier and less portable for a toddler.'),
    ('cat_step_stool', 12, 'Single Step Stool', 'Little Helper', NULL, NULL, NULL, '£20.00', NULL, NULL, NULL, NULL, NULL, 'Good quality, but higher price point for a basic single step.'),
    ('cat_step_stool', 13, 'Toddler Step Stool', 'My Carry Potty', NULL, NULL, NULL, '£10.00', NULL, NULL, NULL, NULL, NULL, 'Integrated with potty training, but less versatile as a general step stool.'),
    ('cat_step_stool', 14, 'Two Step Stool', 'Boori', NULL, NULL, NULL, '£60.00', NULL, NULL, NULL, NULL, NULL, 'High quality wooden, but too tall and expensive for this age band''s primary need.'),
    ('cat_step_stool', 15, 'Adjustable Height Step Stool', 'Straame', NULL, NULL, NULL, '£30.00', NULL, NULL, NULL, NULL, NULL, 'Adjustable height is good, but the mechanism can be less stable for younger toddlers.')
  ) AS v(source_category_entity_id, longlist_rank, product_name, brand, best_for_tag, product_url, retailer, price_text, stock_status, age_mark_on_listing, evidence_tier, buy_borrow_hold_off, gift_suitable, caveat_short)
)
INSERT INTO public.pl_stage3_picks (
  age_band_id,
  category_type_id,
  source_category_entity_id,
  pick_rank,
  longlist_rank,
  status,
  is_visible,
  is_locked,
  best_for_tag,
  product_name,
  brand,
  retailer,
  product_url,
  price_text,
  stock_status,
  age_mark_on_listing,
  caveats,
  buy_borrow_hold_off,
  gift_suitable,
  evidence_tier,
  founder_qa_flag,
  research_payload
)
SELECT
  '28-30m',
  ct.id,
  r.source_category_entity_id,
  r.longlist_rank,
  r.longlist_rank,
  'backup',
  false,
  true,
  r.best_for_tag,
  r.product_name,
  r.brand,
  r.retailer,
  r.product_url,
  r.price_text,
  r.stock_status,
  r.age_mark_on_listing,
  r.caveat_short,
  r.buy_borrow_hold_off,
  -- All-NULL VALUES columns are inferred as text; cast for the boolean target column.
  r.gift_suitable::boolean,
  r.evidence_tier,
  'backup_not_card_ready',
  jsonb_build_object(
    'bundle_schema_version', 'stage3_ingestion_bundle_v1',
    'bundle_generated_at', '2026-07-23T20:57:38.347Z',
    'status', 'dormant_backup',
    'source_category_entity_id', r.source_category_entity_id
  )
FROM backup_rows r
JOIN public.pl_category_types ct
  ON ct.slug = r.source_category_entity_id
WHERE EXISTS (
  SELECT 1
  FROM public.pl_age_band_development_need_category_types abdnct
  WHERE abdnct.age_band_id = '28-30m'
    AND abdnct.category_type_id = ct.id
    AND abdnct.is_active = true
);

DO $$
DECLARE
  v_visible_count INTEGER;
  v_backup_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_visible_count
  FROM public.pl_stage3_picks s
  JOIN public.pl_category_types ct ON ct.id = s.category_type_id
  WHERE s.age_band_id = '28-30m'
    AND ct.slug IN ('cat_feelings_faces_books', 'cat_picture_story_books', 'cat_play_kitchen_household_props', 'cat_potty', 'cat_shape_sorters_puzzles', 'cat_soft_graspable_balls', 'cat_step_stool')
    AND s.status = 'visible'
    AND s.is_visible = true;

  IF v_visible_count <> 35 THEN
    RAISE EXCEPTION 'Expected 35 visible Stage 3 picks for 28-30m, got %', v_visible_count;
  END IF;

  SELECT COUNT(*) INTO v_backup_count
  FROM public.pl_stage3_picks s
  JOIN public.pl_category_types ct ON ct.id = s.category_type_id
  WHERE s.age_band_id = '28-30m'
    AND ct.slug IN ('cat_feelings_faces_books', 'cat_picture_story_books', 'cat_play_kitchen_household_props', 'cat_potty', 'cat_shape_sorters_puzzles', 'cat_soft_graspable_balls', 'cat_step_stool')
    AND s.status = 'backup'
    AND s.is_visible = false;

  IF v_backup_count <> 64 THEN
    RAISE EXCEPTION 'Expected 64 backup Stage 3 picks for 28-30m, got %', v_backup_count;
  END IF;
END $$;

COMMIT;
