-- Generated by web/scripts/ingest-stage3-pips-picks.mjs
-- Bundle: agent-tools/exports/stage3_ingestion_bundle_1-3m.json

BEGIN;

CREATE TABLE IF NOT EXISTS public.pl_stage3_picks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  age_band_id TEXT NOT NULL REFERENCES public.pl_age_bands(id) ON DELETE RESTRICT,
  category_type_id UUID NOT NULL REFERENCES public.pl_category_types(id) ON DELETE CASCADE,
  source_category_entity_id TEXT NOT NULL,
  pick_rank INTEGER NOT NULL CHECK (pick_rank > 0),
  longlist_rank INTEGER NOT NULL CHECK (longlist_rank > 0),
  status TEXT NOT NULL CHECK (status IN ('visible', 'backup', 'skip')),
  is_visible BOOLEAN NOT NULL DEFAULT true,
  is_locked BOOLEAN NOT NULL DEFAULT true,
  best_for_tag TEXT,
  product_name TEXT NOT NULL,
  brand TEXT,
  retailer TEXT,
  product_url TEXT,
  image_url TEXT,
  price_text TEXT,
  stock_status TEXT,
  age_mark_on_listing TEXT,
  product_description TEXT,
  ember_verdict TEXT,
  why_it_fits TEXT,
  caveats TEXT,
  buy_borrow_hold_off TEXT,
  gift_suitable BOOLEAN,
  gift_note TEXT,
  ownership_note TEXT,
  safety_notes TEXT,
  evidence_tier TEXT,
  evidence_sources TEXT[],
  founder_qa_flag TEXT,
  research_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT pl_stage3_picks_unique UNIQUE (age_band_id, category_type_id, pick_rank, status)
);

ALTER TABLE public.pl_stage3_picks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pl_stage3_picks_public_read" ON public.pl_stage3_picks;
CREATE POLICY "pl_stage3_picks_public_read" ON public.pl_stage3_picks
  FOR SELECT
  TO anon, authenticated
  USING (
    status = 'visible'
    AND is_visible = true
    AND (
      is_locked = false
      OR lower(coalesce(auth.jwt() ->> 'email', '')) = 'timwd23@gmail.com'
      OR lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'membership_type', '')) = 'ember_plus'
    )
  );

DROP POLICY IF EXISTS "pl_stage3_picks_admin_all" ON public.pl_stage3_picks;
CREATE POLICY "pl_stage3_picks_admin_all" ON public.pl_stage3_picks
  FOR ALL
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

GRANT SELECT ON public.pl_stage3_picks TO anon, authenticated;

CREATE INDEX IF NOT EXISTS pl_stage3_picks_age_category_rank_idx
  ON public.pl_stage3_picks(age_band_id, category_type_id, status, pick_rank);

DROP TRIGGER IF EXISTS trg_pl_stage3_picks_updated_at ON public.pl_stage3_picks;
CREATE TRIGGER trg_pl_stage3_picks_updated_at
  BEFORE UPDATE ON public.pl_stage3_picks
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

DROP VIEW IF EXISTS public.v_gateway_stage3_picks_public;
CREATE VIEW public.v_gateway_stage3_picks_public
WITH (security_invoker = true) AS
SELECT
  s.id,
  s.age_band_id,
  s.category_type_id,
  ct.slug AS category_type_slug,
  s.source_category_entity_id,
  s.pick_rank,
  s.longlist_rank,
  s.status,
  s.is_visible,
  s.is_locked,
  s.best_for_tag,
  s.product_name,
  s.brand,
  s.retailer,
  s.product_url,
  s.image_url,
  s.price_text,
  s.stock_status,
  s.age_mark_on_listing,
  s.product_description,
  s.ember_verdict,
  s.why_it_fits,
  s.caveats,
  s.buy_borrow_hold_off,
  s.gift_suitable,
  s.gift_note,
  s.ownership_note,
  s.safety_notes,
  s.evidence_tier,
  s.evidence_sources,
  s.founder_qa_flag,
  s.research_payload
FROM public.pl_stage3_picks s
JOIN public.pl_category_types ct ON ct.id = s.category_type_id
WHERE s.status = 'visible'
  AND s.is_visible = true
  AND s.is_locked = false;

GRANT SELECT ON public.v_gateway_stage3_picks_public TO anon, authenticated;

DELETE FROM public.pl_stage3_picks
WHERE age_band_id = '1-3m'
  AND source_category_entity_id IN ('cat_baby_safe_mirror', 'cat_board_books', 'cat_burp_cloths_muslins', 'cat_firm_flat_mattress', 'cat_high_contrast_cards', 'cat_reach_grab_toys', 'cat_rear_facing_car_seat', 'cat_soft_carrier_sling', 'cat_washable_floor_play_mat');

WITH stage3_rows AS (
  SELECT *
  FROM (VALUES
    ('cat_baby_safe_mirror', 1, 1, 'visible', true, false, 'Engaging floor play and visual stimulation', 'Activity Floor Mirror - Pigee Colour Mix', 'Done by Deer', 'Natural Baby Shower', 'https://www.naturalbabyshower.co.uk/products/done-by-deer-activity-floor-mirror-pigee-colour-mix', NULL, 'GBP 34.95', 'in_stock', NULL, 'A vibrant floor mirror designed to encourage self-recognition and visual engagement during tummy time and supervised play.', 'This mirror is specifically designed for floor play, promoting visual focus and interaction. Its engaging design aligns with the Stage 1 need for shared moments and early communication.', 'This mirror is specifically designed for floor play, promoting visual focus and interaction. Its engaging design aligns with the Stage 1 need for shared moments and early communication.', NULL, NULL, true, 'Good gift', NULL, 'Use only during supervised awake play; do not place loose mirrors or toys in the sleep space.', NULL, ARRAY[]::text[], 'none'),
    ('cat_baby_safe_mirror', 2, 2, 'visible', true, true, 'Versatile tummy time and sensory play', 'Tummy-Time Baby Mirror Book', 'Taf Toys', 'Halilit', 'https://halilit.co.uk/products/taf-toys-tummy-time-baby-mirror-book', NULL, 'GBP 14.99', 'in_stock', NULL, 'A double-sided fabric book with a large baby-safe mirror, high-contrast patterns, and colorful illustrations to stimulate developing senses.', 'The mirror book offers dual-stage development with high-contrast for newborns and a mirror for older infants, supporting visual development and self-awareness, directly addressing the ''finding your face'' cluster.', 'The mirror book offers dual-stage development with high-contrast for newborns and a mirror for older infants, supporting visual development and self-awareness, directly addressing the ''finding your face'' cluster.', NULL, NULL, true, 'Good gift', NULL, 'Use only during supervised awake play; do not place loose mirrors or toys in the sleep space.', NULL, ARRAY[]::text[], 'none'),
    ('cat_baby_safe_mirror', 3, 3, 'visible', true, true, 'Budget-friendly and stimulating floor mirror', 'Activity Floor Mirror - Wally - Powder', 'Done by Deer', 'Done by Deer UK', 'https://donebydeer.com/en-gb/products/activity-floor-mirror-wally-powder', NULL, 'GBP 19.30', 'in_stock', NULL, 'An engaging floor mirror with a friendly Wally design, perfect for encouraging babies to lift their heads and explore their reflections during tummy time.', 'This mirror provides a good value option for encouraging visual engagement and self-discovery during tummy time, aligning with the core need at an accessible price point.', 'This mirror provides a good value option for encouraging visual engagement and self-discovery during tummy time, aligning with the core need at an accessible price point.', NULL, NULL, true, 'Good gift', NULL, 'Use only during supervised awake play; do not place loose mirrors or toys in the sleep space.', NULL, ARRAY[]::text[], 'none'),
    ('cat_baby_safe_mirror', 4, 4, 'visible', true, true, 'Portable and engaging on-the-go play', 'To Go Activity Mirror - Happy Clouds - Blue', 'Done by Deer', 'Done by Deer UK', 'https://donebydeer.com/en-gb/products/to-go-activity-mirror-happy-clouds-blue', NULL, 'GBP 26.00', 'in_stock', NULL, 'A portable activity mirror with a cheerful cloud design, ideal for attaching to prams or car seats for entertainment and self-discovery during outings.', 'Its portability makes it suitable for stimulating visual interaction and self-awareness beyond the home environment, supporting continuous engagement with faces and expressions.', 'Its portability makes it suitable for stimulating visual interaction and self-awareness beyond the home environment, supporting continuous engagement with faces and expressions.', NULL, NULL, true, 'Good gift', NULL, 'Use only during supervised awake play; do not place loose mirrors or toys in the sleep space.', NULL, ARRAY[]::text[], 'none'),
    ('cat_baby_safe_mirror', 5, 5, 'visible', true, true, 'Clip-on versatility for various play settings', 'Activity Mirror w/Clip - Tiny Farm - Green', 'Done by Deer', 'Done by Deer UK', 'https://donebydeer.com/en-gb/products/activity-mirror-w-clip-tiny-farm-green', NULL, 'GBP 26.95', 'in_stock', NULL, 'A versatile activity mirror with a convenient clip, allowing it to be attached to playmats, car seats, or cots for interactive play and self-discovery.', 'The clip-on feature provides flexibility for parents to position the mirror in various locations, maximizing opportunities for the baby to engage with their reflection and fostering early communication.', 'The clip-on feature provides flexibility for parents to position the mirror in various locations, maximizing opportunities for the baby to engage with their reflection and fostering early communication.', NULL, NULL, true, 'Good gift', NULL, 'Use only during supervised awake play; do not place loose mirrors or toys in the sleep space.', NULL, ARRAY[]::text[], 'none'),
    ('cat_board_books', 1, 1, 'visible', true, false, 'Best for visual stimulation and early development', 'Baby Touch: Faces: a black-and white-book', 'Ladybird', 'Bookshop.org UK', 'https://uk.bookshop.org/p/books/baby-touch-faces-a-black-and-white-book-ladybird/cfee1c58ca5fa534?ean=9780241391723', NULL, 'GBP 6.64', 'in_stock', NULL, 'A black-and-white board book with large, friendly faces designed to stimulate vision from birth and aid in early visual development.', 'This book directly addresses the developmental needs of 1-3 month olds by providing high-contrast images of faces, which are known to be highly engaging for newborns and support visual development. The sturdy board book format is durable for early handling.', 'This book directly addresses the developmental needs of 1-3 month olds by providing high-contrast images of faces, which are known to be highly engaging for newborns and support visual development. The sturdy board book format is durable for early handling.', NULL, NULL, true, 'Good gift', NULL, NULL, NULL, ARRAY[]::text[], 'none'),
    ('cat_board_books', 2, 2, 'visible', true, true, 'Best value multi-book set for visual development', 'Usborne Baby’s Very First Black & White Books – 4 Board Book Set (Animals, Hello!, Outdoors, Bedtime)', 'Usborne', 'Books4People.co.uk', 'https://www.books4people.co.uk/products/usborne-babys-very-first-black-and-white-4-books-set?srsltid=AfmBOorONokiobWgKxFHSwlSpjeK3Jj6nzKGgCSHfLMBfNK-FUKM9yBB', NULL, 'GBP 9.89', 'in_stock', NULL, 'A set of four high-contrast board books featuring animals, greetings, outdoors, and bedtime themes, perfect for stimulating newborn vision.', 'This set offers a variety of high-contrast themes (animals, greetings, outdoors, bedtime) in a robust board book format, catering to the visual development needs of 1-3 month olds. The multiple books provide extended engagement and value.', 'This set offers a variety of high-contrast themes (animals, greetings, outdoors, bedtime) in a robust board book format, catering to the visual development needs of 1-3 month olds. The multiple books provide extended engagement and value.', NULL, NULL, true, 'Good gift', NULL, NULL, NULL, ARRAY[]::text[], 'none'),
    ('cat_board_books', 3, 3, 'visible', true, true, 'Best interactive peekaboo experience', 'Peekaboo Bear', 'Nosy Crow', 'Amazon UK', 'https://www.amazon.co.uk/Peekaboo-Bear-Ingela-P-Arrhenius/dp/1788005767', NULL, 'GBP 2.76', 'in_stock', NULL, 'An interactive board book with easy-to-use sliders and a surprise mirror ending, featuring friendly faces and forest animals.', 'The interactive sliders and mirror ending provide engaging peekaboo play, which is excellent for early interaction and developing object permanence. The focus on faces and animals aligns with early visual and cognitive development.', 'The interactive sliders and mirror ending provide engaging peekaboo play, which is excellent for early interaction and developing object permanence. The focus on faces and animals aligns with early visual and cognitive development.', NULL, NULL, true, 'Good gift', NULL, NULL, NULL, ARRAY[]::text[], 'none'),
    ('cat_board_books', 4, 4, 'visible', true, true, 'Clear, simple high-contrast faces', 'Hello Baby: Faces', 'Roger Priddy', 'Priddy Books (via Google Shopping fallback)', 'https://priddybooks.com/gb/books/hello-baby-faces/', NULL, 'GBP 4.99', 'unknown', NULL, 'A high-contrast board book featuring various faces and expressions, designed to be easy for babies to focus on and stimulate developing sight.', 'This book focuses specifically on faces with high contrast, which is ideal for newborn visual development and social skill building. The simple design aids focus for very young infants.', 'This book focuses specifically on faces with high contrast, which is ideal for newborn visual development and social skill building. The simple design aids focus for very young infants.', NULL, NULL, true, 'Good gift', NULL, NULL, NULL, ARRAY[]::text[], 'google_shopping_fallback'),
    ('cat_board_books', 5, 5, 'visible', true, true, 'Engaging black and white patterns', 'Amazing Baby: Black and White', 'Emma Dodd', 'BookTrust (via Google Shopping fallback)', 'https://www.booktrust.org.uk/book-recommendations/bookfinder/amazing-baby-black-and-white/', NULL, 'GBP 5.99', 'unknown', NULL, 'An interactive board book with cut-out pages featuring high-contrast patterns, dots, and stripes to engage babies and introduce them to new sounds.', 'The cut-out pages and high-contrast patterns are excellent for visual stimulation and interaction, which is crucial for early development. The simple rhyme also encourages auditory engagement.', 'The cut-out pages and high-contrast patterns are excellent for visual stimulation and interaction, which is crucial for early development. The simple rhyme also encourages auditory engagement.', NULL, NULL, true, 'Good gift', NULL, NULL, NULL, ARRAY[]::text[], 'google_shopping_fallback'),
    ('cat_burp_cloths_muslins', 1, 1, 'visible', true, false, 'Versatile everyday use and stylish designs', 'Essentials Cotton Muslin Squares - 5 Pack - Blushing Bunnies', 'aden + anais', 'Natural Baby Shower', 'https://www.naturalbabyshower.co.uk/products/aden-anais-essentials-5-pack-cotton-muslin-squares-blushing-bunnies', NULL, 'GBP 22.95', 'in_stock', NULL, 'Soft, breathable, and absorbent 100% cotton muslin squares, perfect for burping, feeding, and quick clean-ups. Comes in a pack of five with charming designs.', 'A well-known and trusted brand for baby kit, offering versatile and durable muslin squares that are soft and breathable. The 5-pack provides good value for everyday use.', 'A well-known and trusted brand for baby kit, offering versatile and durable muslin squares that are soft and breathable. The 5-pack provides good value for everyday use.', NULL, NULL, false, 'Parent buy', NULL, NULL, NULL, ARRAY[]::text[], 'none'),
    ('cat_burp_cloths_muslins', 2, 2, 'visible', true, true, 'Highly absorbent and NICU trusted', 'Cotton Muslin Burp Cloths (3 Pack)', 'MuslinZ', 'MuslinZ', 'https://muslinz.co.uk/products/cotton-muslin-burp-cloths', NULL, 'GBP 9.99', 'in_stock', NULL, 'Soft, breathable, and highly absorbent 100% cotton muslin burp cloths, trusted by NICUs across the UK.', 'Excellent absorbency with 6 layers of cotton muslin, Oeko-Tex certified, and trusted by medical professionals.', 'Excellent absorbency with 6 layers of cotton muslin, Oeko-Tex certified, and trusted by medical professionals.', NULL, NULL, false, 'Parent buy', NULL, NULL, NULL, ARRAY[]::text[], 'none'),
    ('cat_burp_cloths_muslins', 3, 3, 'visible', true, true, 'Good value and everyday use', '5 Pack Pure Cotton Muslin Squares', 'M&S', 'Marks & Spencer', 'https://www.marksandspencer.com/5pk-pure-cotton-muslin-squares/p/clp60616744', NULL, 'GBP 8.00', 'in_stock', NULL, 'A practical 5-pack of pure cotton muslin squares, soft and gentle for baby''s delicate skin, ideal for everyday spills and clean-ups.', 'Excellent value for a 5-pack of pure cotton muslins with a strong customer rating and review count, indicating good quality and parent satisfaction.', 'Excellent value for a 5-pack of pure cotton muslins with a strong customer rating and review count, indicating good quality and parent satisfaction.', NULL, NULL, false, 'Parent buy', NULL, NULL, NULL, ARRAY[]::text[], 'none'),
    ('cat_burp_cloths_muslins', 4, 4, 'visible', true, true, 'Essential basic, excellent value', 'Muslin Squares, Pack of 6, White', 'John Lewis', 'John Lewis', 'https://www.johnlewis.com/john-lewis-muslin-squares-pack-of-6-white/p230650111', NULL, 'GBP 8.00', 'in_stock', NULL, 'A practical 6-pack of pure cotton muslin squares, gentle on baby''s skin and ideal for everyday spills and feeding. a useful basic for any new parent.', 'Highly rated with a significant number of reviews, offering excellent value for a 6-pack of pure cotton muslins. A reliable and affordable option from a trusted retailer.', 'Highly rated with a significant number of reviews, offering excellent value for a 6-pack of pure cotton muslins. A reliable and affordable option from a trusted retailer.', NULL, NULL, false, 'Parent buy', NULL, NULL, NULL, ARRAY[]::text[], 'none'),
    ('cat_burp_cloths_muslins', 5, 5, 'visible', true, true, 'Hypoallergenic, ultra-absorbent, and eco-friendly', 'Bamboo Muslin Squares', 'Panda London', 'Panda London', 'https://pandalondon.com/products/bamboo-muslin-squares', NULL, 'GBP 24.00', 'in_stock', NULL, 'Dual-layer 100% bamboo muslin squares, super soft, naturally antibacterial, and ultra-absorbent for all baby spills and messes. Comes in a gift box.', 'Made from 100% bamboo, offering superior softness, absorbency, and natural antibacterial properties. Ideal for sensitive skin and eco-conscious parents. Gift-boxed and pre-washed for convenience.', 'Made from 100% bamboo, offering superior softness, absorbency, and natural antibacterial properties. Ideal for sensitive skin and eco-conscious parents. Gift-boxed and pre-washed for convenience.', NULL, NULL, false, 'Parent buy', NULL, NULL, NULL, ARRAY[]::text[], 'none'),
    ('cat_firm_flat_mattress', 1, 1, 'visible', true, false, 'Best budget-friendly option with integrated waterproofing', 'CuddleCo Lullaby Hypo-Allergenic Firm Baby Cot Bed Mattress (140x70cm)', 'CuddleCo', 'Amazon UK', 'https://www.amazon.co.uk/CuddleCo-Lullaby-Hypo-Allergenic-Bamboo-Mattress/dp/B07TKJMD9Q', NULL, 'GBP 69.99', 'in_stock', NULL, 'A firm, hypoallergenic, and anti-microbial cot bed mattress with a waterproof side, designed for safe and comfortable sleep from birth.', 'This mattress offers excellent value for money while meeting key safety and comfort criteria. The integrated waterproof side is a significant advantage for new parents, and the positive reviews confirm its quality and suitability for newborns.', 'This mattress offers excellent value for money while meeting key safety and comfort criteria. The integrated waterproof side is a significant advantage for new parents, and the positive reviews confirm its quality and suitability for newborns.', NULL, NULL, false, 'Parent buy', NULL, 'A new mattress is preferred where possible. Avoid soft, uneven or poorly fitting surfaces.', NULL, ARRAY[]::text[], 'none'),
    ('cat_firm_flat_mattress', 2, 2, 'visible', true, true, 'Best dual-sided mattress for extended use', 'SnuzSurface Duo Dual Sided Cot Bed Mattress SnuzKot', 'Snüz', 'Snüz Official Website', 'https://www.snuz.co.uk/products/snuzsurface-duo-dual-sided-cot-bed-mattress-snuzkot', NULL, 'GBP 155.00', 'in_stock', NULL, 'A versatile dual-sided cot bed mattress with a firm side for babies and a softer side for toddlers, featuring a waterproof surface and washable cover.', 'The dual-sided design provides longevity and adaptability as the child grows, offering optimal firmness for newborns and a softer option for toddlers. The waterproof surface and washable cover enhance practicality and hygiene.', 'The dual-sided design provides longevity and adaptability as the child grows, offering optimal firmness for newborns and a softer option for toddlers. The waterproof surface and washable cover enhance practicality and hygiene.', NULL, NULL, false, 'Parent buy', NULL, 'A new mattress is preferred where possible. Avoid soft, uneven or poorly fitting surfaces.', NULL, ARRAY[]::text[], 'none'),
    ('cat_firm_flat_mattress', 3, 3, 'visible', true, true, 'Best for allergy sufferers with integrated waterproofing', 'Mother & Baby Pure Gold Anti Allergy Coir Pocket Sprung Cot Bed Mattress', 'Mother&Baby', 'Boots', 'https://www.google.com/search?tbm=shop&q=Mother+%26+Baby+Pure+Gold+Anti+Allergy+Coir+Pocket+Sprung+Cot+Bed+Mattress+UK', NULL, 'GBP 129.99', 'in_stock', NULL, 'An anti-allergy pocket sprung cot bed mattress with Purotex® technology and a moveable waterproof membrane, ensuring a clean and dry sleep environment.', 'This mattress stands out for its anti-allergy properties and the innovative moveable waterproof membrane, which provides excellent protection without compromising breathability. The pocket springs offer good support, and the washable cover adds to its practicality.', 'This mattress stands out for its anti-allergy properties and the innovative moveable waterproof membrane, which provides excellent protection without compromising breathability. The pocket springs offer good support, and the washable cover adds to its practicality.', NULL, NULL, false, 'Parent buy', NULL, 'A new mattress is preferred where possible. Avoid soft, uneven or poorly fitting surfaces.', NULL, ARRAY[]::text[], 'google_shopping'),
    ('cat_firm_flat_mattress', 4, 4, 'visible', true, true, 'Best for advanced moisture and temperature regulation', 'Obaby Moisture Management Dual Core Mattress -140x70cm', 'Obaby', 'Obaby Official Website', 'https://www.obaby.co.uk/products/moisture-management-dual-core-mattress', NULL, 'GBP 180.00', 'in_stock', NULL, 'A dual-core mattress with a coir side for babies and pocket springs for toddlers, featuring a Tencel top panel for superior moisture and humidity management.', 'This mattress offers advanced features for moisture and temperature regulation, which are crucial for infant comfort and safety. The dual-core design provides appropriate support for both newborns and toddlers, making it a long-term investment. The Made For Mums Gold award adds credibility.', 'This mattress offers advanced features for moisture and temperature regulation, which are crucial for infant comfort and safety. The dual-core design provides appropriate support for both newborns and toddlers, making it a long-term investment. The Made For Mums Gold award adds credibility.', NULL, NULL, false, 'Parent buy', NULL, 'A new mattress is preferred where possible. Avoid soft, uneven or poorly fitting surfaces.', NULL, ARRAY[]::text[], 'none'),
    ('cat_firm_flat_mattress', 5, 5, 'visible', true, true, 'Best premium hybrid mattress with excellent support', 'Simba Hybrid Cot Bed Mattress', 'Simba', 'Simba Sleep Official Website', 'https://simbasleep.com/products/cot-bed-mattress', NULL, 'GBP 249.00', 'in_stock', NULL, 'A premium dual-sided hybrid mattress with 8 layers, offering firm support for babies and a softer side for toddlers, along with superior breathability and a washable cover.', 'The Simba Hybrid mattress provides a high-quality, multi-layered construction designed for optimal support and comfort. Its dual-sided nature ensures suitability from birth through toddlerhood, and the breathability and washable cover are key practical benefits. The strong customer reviews and awards reinforce its premium positioning.', 'The Simba Hybrid mattress provides a high-quality, multi-layered construction designed for optimal support and comfort. Its dual-sided nature ensures suitability from birth through toddlerhood, and the breathability and washable cover are key practical benefits. The strong customer reviews and awards reinforce its premium positioning.', NULL, NULL, false, 'Parent buy', NULL, 'A new mattress is preferred where possible. Avoid soft, uneven or poorly fitting surfaces.', NULL, ARRAY[]::text[], 'none'),
    ('cat_high_contrast_cards', 1, 1, 'visible', true, false, 'Best overall value and strong reviews', 'Baby Sensory Cards - 60 Black and White High Contrast Baby Flash Cards', 'Little Seeds', 'Amazon UK', 'https://www.amazon.co.uk/Newborn-Essentials-Sensory-Contrast-Stimulation/dp/B0GWSNZ6R5', NULL, 'GBP 6.99', 'in_stock', NULL, 'A set of 60 durable, non-toxic black and white flash cards designed to stimulate visual development and cognitive growth from birth. Perfect for tummy time and on-the-go entertainment.', 'These cards offer a comprehensive set of high-contrast patterns suitable for newborns, backed by a high rating and significant number of reviews on Amazon UK, indicating strong retail proof and parent satisfaction. The versatility for various play activities makes them a practical choice for early visual stimulation.', 'These cards offer a comprehensive set of high-contrast patterns suitable for newborns, backed by a high rating and significant number of reviews on Amazon UK, indicating strong retail proof and parent satisfaction. The versatility for various play activities makes them a practical choice for early visual stimulation.', NULL, NULL, true, 'Good gift', NULL, NULL, NULL, ARRAY[]::text[], 'none'),
    ('cat_high_contrast_cards', 2, 2, 'visible', true, true, 'Premium quality and artistic designs', 'Wee Gallery Baby Art Cards, Black and White, 0-12 Months', 'Wee Gallery', 'Amazon UK', 'https://www.amazon.co.uk/Wee-Gallery-Art-Cards-Baby/dp/B07SVC4NV3', NULL, 'GBP 34.59', 'in_stock', NULL, 'A set of durable, FSC certified art cards featuring eye-catching black and white animal designs to support early visual development and brain growth. Designed for safe handling and versatile play.', 'Wee Gallery is a well-regarded brand known for its artistic and high-quality baby products. These cards meet the quality bar with good ratings and reviews, offering a premium option for parents seeking aesthetically pleasing and durable high-contrast cards. The focus on animal designs adds an engaging element for infants.', 'Wee Gallery is a well-regarded brand known for its artistic and high-quality baby products. These cards meet the quality bar with good ratings and reviews, offering a premium option for parents seeking aesthetically pleasing and durable high-contrast cards. The focus on animal designs adds an engaging element for infants.', NULL, NULL, true, 'Good gift', NULL, NULL, NULL, ARRAY[]::text[], 'none'),
    ('cat_high_contrast_cards', 3, 3, 'visible', true, true, 'Most comprehensive set with staged learning', 'beiens Newborn Essentials Sensory Toys Cards, 160 Page Black White Visual Stimulation Learning Activity Cards', 'beiens', 'Amazon UK', 'https://www.amazon.co.uk/beiens-Contrast-Flashcard-Stimulation-Educational/dp/B07WZT8DTD', NULL, 'GBP 13.99', 'in_stock', NULL, 'An extensive set of 160-page black and white visual stimulation cards designed for babies aged 0-36 months, with staged learning for different developmental phases. Features anti-glare surface and eco-friendly ink.', 'This product stands out for its sheer volume of cards and staged approach to visual development, covering a wide age range. The exceptionally high number of positive reviews on Amazon UK provides strong retail proof of its effectiveness and popularity among parents. The anti-glare and eco-friendly features are also positive attributes.', 'This product stands out for its sheer volume of cards and staged approach to visual development, covering a wide age range. The exceptionally high number of positive reviews on Amazon UK provides strong retail proof of its effectiveness and popularity among parents. The anti-glare and eco-friendly features are also positive attributes.', NULL, NULL, true, 'Good gift', NULL, NULL, NULL, ARRAY[]::text[], 'none'),
    ('cat_high_contrast_cards', 4, 4, 'visible', true, true, 'Independent brand with focus on newborn development', 'Priya & Peanut 0+ Month Newborn Sensory Cards', 'Priya & Peanut', 'Priya & Peanut', 'https://www.priyaandpeanut.com/products/0-6-month-newborn-sensory-flashcard-collection', NULL, 'GBP 14.00', 'in_stock', NULL, 'A collection of sensory flashcards specifically designed for newborns from 0+ months, focusing on high-contrast black and white patterns to aid visual development. Made with durable materials.', 'Priya & Peanut offers a dedicated newborn sensory card collection from an independent brand, which can appeal to parents looking for specialist products. While direct review counts were not found on their site, the product aligns well with the 0-3 month age band and the brand''s focus on early development is a strong positive.', 'Priya & Peanut offers a dedicated newborn sensory card collection from an independent brand, which can appeal to parents looking for specialist products. While direct review counts were not found on their site, the product aligns well with the 0-3 month age band and the brand''s focus on early development is a strong positive.', NULL, NULL, true, 'Good gift', NULL, NULL, NULL, ARRAY[]::text[], 'none'),
    ('cat_high_contrast_cards', 5, 5, 'visible', true, true, 'Multi-stage visual development', 'hahaland Baby Flash Cards Visual Stimulation Cards 0-3-6-12-36 Months', 'hahaland', 'hahaland', 'https://hahaland.com/products/baby-flash-cards-baby-visual-stimulation-cards-0-3-6-12-36-months', NULL, 'GBP 12.99', 'in_stock', NULL, 'A set of baby flash cards offering four stages of visual stimulation, starting with high-contrast black and white for newborns and progressing to colors for older infants. Made from thick card with an anti-glare surface.', 'The hahaland cards provide a clear progression through different visual stages, making them a long-term investment for parents. The inclusion of specific 0-3 month high-contrast cards, along with features like thick card and anti-glare surface, makes them a suitable and practical choice for this category.', 'The hahaland cards provide a clear progression through different visual stages, making them a long-term investment for parents. The inclusion of specific 0-3 month high-contrast cards, along with features like thick card and anti-glare surface, makes them a suitable and practical choice for this category.', NULL, NULL, true, 'Good gift', NULL, NULL, NULL, ARRAY[]::text[], 'none'),
    ('cat_reach_grab_toys', 1, 1, 'visible', true, false, 'Early grasping and sensory exploration', 'Oball Classic™ Easy-Grasp Toy', 'Bright Starts', 'Boots', 'https://www.boots.com/baby-einstein-oball-classic-easy-grasp-toy-10307276', NULL, 'GBP 3.99', 'in_stock', NULL, 'A flexible, lightweight ball with 32 finger holes, perfect for tiny hands to grip, roll, and throw. Its soft construction and easy-care material make it ideal for early playtime.', 'Excellent design for early grasping with numerous finger holes, promoting fine motor skills and sensory development. High rating and review count indicate strong retail proof.', 'Excellent design for early grasping with numerous finger holes, promoting fine motor skills and sensory development. High rating and review count indicate strong retail proof.', NULL, NULL, true, 'Good gift', NULL, NULL, NULL, ARRAY[]::text[], 'none'),
    ('cat_reach_grab_toys', 2, 2, 'visible', true, true, 'Teething and grasping development', 'Winkel Rattle & Sensory Teether Toy', 'Manhattan Toy', 'Jojo Maman Bébé', 'https://www.manhattantoy.com/products/winkel', NULL, 'GBP 14.00', 'in_stock', NULL, 'An award-winning teether and rattle with a mesmerizing maze of soft, continuous, BPA-free loops that are easy for tiny hands to grasp, hold, and chew. Can be refrigerated for added soothing.', 'Unique design with bendable loops makes it exceptionally easy for infants to grasp and manipulate, supporting fine motor skills and providing teething relief.', 'Unique design with bendable loops makes it exceptionally easy for infants to grasp and manipulate, supporting fine motor skills and providing teething relief.', NULL, NULL, true, 'Good gift', NULL, NULL, NULL, ARRAY[]::text[], 'none'),
    ('cat_reach_grab_toys', 3, 3, 'visible', true, true, 'Sensory stimulation and fine motor skills', 'Freddie the Firefly Activity Toy', 'Lamaze', 'John Lewis', 'https://www.johnlewis.com/lamaze-freddie-the-firefly-activity-toy/p109915929', NULL, 'GBP 14.99', 'in_stock', NULL, 'A friendly firefly with a soft velour body, bright colors, patterns, and textures. Features a peek-a-boo mirror, squeaker, clinking rings, and a tethered ladybug teether. Easily clips to strollers and carriers.', 'Multi-sensory features (crinkle, squeaker, teether, mirror, varied textures) engage multiple senses and encourage reaching, grasping, and tactile exploration. Clip-on design adds versatility.', 'Multi-sensory features (crinkle, squeaker, teether, mirror, varied textures) engage multiple senses and encourage reaching, grasping, and tactile exploration. Clip-on design adds versatility.', NULL, NULL, true, 'Good gift', NULL, 'Remove all packaging and tags before giving to a child', NULL, ARRAY[]::text[], 'none'),
    ('cat_reach_grab_toys', 4, 4, 'visible', true, true, 'Comprehensive sensory and motor development', 'Hello Baby Newborn Kit', 'Taf Toys', 'John Lewis', 'https://www.johnlewis.com/taf-toys-hello-baby-newborn-kit/p111759988', NULL, 'GBP 32.99', 'in_stock', NULL, 'A 12-piece kit designed to meet newborns'' developmental needs, encouraging sensory exploration and tummy time. Includes flash cards, a baby-safe mirror, tummy time pillow, rattle ring, crinkling lion cub, and a soft lion blankie.', 'Offers a comprehensive set of developmental toys for newborns, covering visual, auditory, and tactile stimulation, as well as supporting tummy time and early grasping.', 'Offers a comprehensive set of developmental toys for newborns, covering visual, auditory, and tactile stimulation, as well as supporting tummy time and early grasping.', NULL, NULL, true, 'Good gift', NULL, NULL, NULL, ARRAY[]::text[], 'none'),
    ('cat_reach_grab_toys', 5, 5, 'visible', true, true, 'Tactile exploration and motor skill development', 'Grasping Ball - Newborn Naturals', 'Little Dutch', 'Scandiborn', 'https://www.scandiborn.co.uk/products/little-dutch-grasping-ball-newborn-naturals', NULL, 'GBP 12.71', 'in_stock', NULL, 'A beautifully soft grasping ball with varied textures and subtle colors, designed to support sensory exploration and motor skills from birth. Easy for little hands to grab, roll, and explore.', 'Soft fabric and varied textures provide gentle tactile stimulation, while its design encourages grasping, rolling, and motor skill development.', 'Soft fabric and varied textures provide gentle tactile stimulation, while its design encourages grasping, rolling, and motor skill development.', NULL, NULL, true, 'Good gift', NULL, NULL, NULL, ARRAY[]::text[], 'none'),
    ('cat_rear_facing_car_seat', 1, 1, 'visible', true, false, 'Overall safety, comfort, and ease of use with lie-flat and SlideTech features.', 'Pebble 360 Pro2', 'Maxi-Cosi', 'John Lewis', 'https://www.johnlewis.com/maxi-cosi-pebble-360-pro2-car-seat/twillic-black/p112093409', NULL, 'GBP 207.99', 'in_stock', NULL, 'A premium i-Size infant car seat offering a full lie-flat position for maximum sleep comfort, 360-degree rotation, and SlideTech for easy access. Suitable from birth to approximately 15 months.', 'This seat excels in safety (Good ADAC rating), comfort (lie-flat), and user-friendliness (SlideTech, 360 rotation), directly addressing the need for safe and prepared early outings.', 'This seat excels in safety (Good ADAC rating), comfort (lie-flat), and user-friendliness (SlideTech, 360 rotation), directly addressing the need for safe and prepared early outings.', NULL, NULL, false, 'Parent buy', NULL, 'ISOFIX base sold separately; Always check car seat compatibility with your vehicle before purchase.', NULL, ARRAY[]::text[], 'none'),
    ('cat_rear_facing_car_seat', 2, 2, 'visible', true, true, 'Ergonomic lie-flat position and superior side-impact protection.', 'Cloud T i-Size Rotating Baby Car Seat', 'Cybex', 'John Lewis', 'https://www.johnlewis.com/cybex-cloud-t-i-size-rotating-baby-car-seat/p110535706', NULL, 'GBP 199.95', 'in_stock', NULL, 'An i-Size infant car seat with an innovative lie-flat recline for use in and out of the car, 180-degree rotation (with Base T), and enhanced side-impact protection. Suitable from birth to approximately 24 months.', 'Its lie-flat technology and ADAC Test Winner status provide excellent comfort and safety for newborns, making early journeys more comfortable and secure.', 'Its lie-flat technology and ADAC Test Winner status provide excellent comfort and safety for newborns, making early journeys more comfortable and secure.', NULL, NULL, false, 'Parent buy', NULL, 'ISOFIX Base T sold separately; Always check car seat compatibility with your vehicle before purchase.', NULL, ARRAY[]::text[], 'none'),
    ('cat_rear_facing_car_seat', 3, 3, 'visible', true, true, 'Ultra-lightweight and baseless ISOFIX installation for easy transfers.', 'PIPA URBN R129 Baby Car Seat', 'Nuna', 'John Lewis', 'https://www.johnlewis.com/nuna-pipa-urbn-r129-baby-car-seat-caviar/p110165707', NULL, 'GBP 300.00', 'in_stock', NULL, 'An ultra-lightweight infant car seat (3.3kg) with integrated baseless ISOFIX installation, allowing for quick and secure fitting without a separate base. Ideal for urban parents and frequent car changes.', 'Its unique baseless ISOFIX and ultra-lightweight design make it exceptionally convenient for parents needing to frequently move the car seat between vehicles or use ride-shares, simplifying early outings.', 'Its unique baseless ISOFIX and ultra-lightweight design make it exceptionally convenient for parents needing to frequently move the car seat between vehicles or use ride-shares, simplifying early outings.', NULL, NULL, false, 'Parent buy', NULL, 'Always check car seat compatibility with your vehicle before purchase.', NULL, ARRAY[]::text[], 'none'),
    ('cat_rear_facing_car_seat', 4, 4, 'visible', true, true, 'Extreme lightness, ergonomic design, and suitability for premature babies.', 'Pixel PRO 2.0 C Infant Carrier', 'Avionaut', 'Pramworld', 'https://www.pramworld.co.uk/avionaut-pixel-pro-2-0-c-infant-carrier-black/', NULL, 'GBP 209.00', 'in_stock', NULL, 'The lightest i-Size infant car seat on the market (2.5kg) featuring a modular insert with Cloud Care System for ergonomic positioning and superior safety, even for premature babies.', 'Its ultra-lightweight design and ergonomic insert specifically cater to the delicate needs of newborns and premature babies, ensuring optimal comfort and safety during early travels.', 'Its ultra-lightweight design and ergonomic insert specifically cater to the delicate needs of newborns and premature babies, ensuring optimal comfort and safety during early travels.', NULL, NULL, false, 'Parent buy', NULL, 'ISOFIX base sold separately; Always check car seat compatibility with your vehicle before purchase.', NULL, ARRAY[]::text[], 'none'),
    ('cat_rear_facing_car_seat', 5, 5, 'visible', true, true, 'Budget-friendly extended rear-facing with 360-degree rotation.', 'Turn2Me DLX i-Size R129 360° Rotating Car Seat', 'Graco', 'Amazon UK', 'https://www.amazon.co.uk/Graco-Rotating-Rearward-40-105cm-76-105cm/dp/B0D2LMQR5F', NULL, 'GBP 125.99', 'in_stock', NULL, 'An affordable i-Size car seat offering 360-degree rotation and extended rear-facing capability from birth up to approximately 4 years. Features easy installation and multiple recline positions.', 'Provides excellent value as a budget-friendly option that doesn''t compromise on key features like 360-degree rotation and extended rear-facing, making it accessible for more families.', 'Provides excellent value as a budget-friendly option that doesn''t compromise on key features like 360-degree rotation and extended rear-facing, making it accessible for more families.', NULL, NULL, false, 'Parent buy', NULL, 'Side-impact protection pod needs to be fitted separately each time; Always check car seat compatibility with your vehicle before purchase.', NULL, ARRAY[]::text[], 'none'),
    ('cat_soft_carrier_sling', 1, 1, 'visible', true, false, 'newborns and early months', 'Embrace Baby Carrier', 'Ergobaby', 'Mamas & Papas', 'https://www.mamasandpapas.com/products/ergobaby-embrace-carrier-black-617825300', NULL, 'GBP 88.00', 'in_stock', NULL, 'A soft, simple, and easy-to-use newborn-ready carrier designed for baby''s first 12 months, providing ergonomic support and a close, comforting hold.', 'Consistently recommended for newborns due to its soft fabric, ease of use (3 clicks, no tying), and ergonomic design that supports healthy hip development. Ideal for the 1-3 month age band to promote bonding and provide hands-free comfort.', 'Consistently recommended for newborns due to its soft fabric, ease of use (3 clicks, no tying), and ergonomic design that supports healthy hip development. Ideal for the 1-3 month age band to promote bonding and provide hands-free comfort.', NULL, NULL, false, 'Parent buy', NULL, 'Always follow recognised safe babywearing guidance and fit checks (TICKS guidelines).', NULL, ARRAY[]::text[], 'none'),
    ('cat_soft_carrier_sling', 2, 2, 'visible', true, true, 'back support and longer wearing sessions', 'Baby Carrier Harmony', 'BabyBjörn', 'John Lewis', 'https://www.johnlewis.com/babybjorn-harmony-baby-carrier/p5612075', NULL, 'GBP 167.12', 'in_stock', NULL, 'A soft, flexible, and ergonomic baby carrier with a luxurious feel, featuring a waist belt, padded back support, and padded shoulder straps for ultimate comfort.', 'Highly rated for its excellent back support and comfort, making it suitable for parents who wear their baby for extended periods. It''s designed for hip health and grows with the baby from newborn to 3 years.', 'Highly rated for its excellent back support and comfort, making it suitable for parents who wear their baby for extended periods. It''s designed for hip health and grows with the baby from newborn to 3 years.', NULL, NULL, false, 'Parent buy', NULL, 'Always follow recognised safe babywearing guidance and fit checks.', NULL, ARRAY[]::text[], 'none'),
    ('cat_soft_carrier_sling', 3, 3, 'visible', true, true, 'budget-friendly, close contact, and early newborn stage', 'Essential Baby Wrap - Mid Grey', 'Izmi', 'Argos', 'https://www.argos.co.uk/product/9566569', NULL, 'GBP 35.00', 'in_stock', NULL, 'A soft and stretchy cotton-blend wrap designed for newborns and infants, providing a comforting hold and even weight distribution across the wearer''s back and shoulders.', 'An excellent budget-friendly option for parents seeking the close, comforting contact of a wrap. Suitable from birth (2.3kg) and machine washable. While it requires some practice to tie, it''s highly rated for comfort and effectiveness in settling newborns.', 'An excellent budget-friendly option for parents seeking the close, comforting contact of a wrap. Suitable from birth (2.3kg) and machine washable. While it requires some practice to tie, it''s highly rated for comfort and effectiveness in settling newborns.', NULL, NULL, false, 'Parent buy', NULL, 'Always follow recognised safe babywearing guidance and fit checks (TICKS guidelines).; Fit indoors to prevent fabric from touching the floor.', NULL, ARRAY[]::text[], 'none'),
    ('cat_soft_carrier_sling', 4, 4, 'visible', true, true, 'versatility and all-season comfort', 'Omni 360 Cool Air Mesh Baby Carrier', 'Ergobaby', 'John Lewis', 'https://www.johnlewis.com/ergobaby-omni-360-mesh-baby-carrier/p3501816', NULL, 'GBP 164.90', 'in_stock', NULL, 'A four-position, newborn-ready carrier designed for baby''s first 48 months, offering patented ergonomic support and a breathable mesh fabric for comfort in all seasons.', 'This carrier is highly versatile, suitable from birth without an infant insert, and offers four carrying positions. The Cool Air Mesh makes it ideal for the UK''s varying climate, and its ergonomic design supports healthy hip development. It''s a great all-rounder for parents seeking a long-term solution.', 'This carrier is highly versatile, suitable from birth without an infant insert, and offers four carrying positions. The Cool Air Mesh makes it ideal for the UK''s varying climate, and its ergonomic design supports healthy hip development. It''s a great all-rounder for parents seeking a long-term solution.', NULL, NULL, false, 'Parent buy', NULL, 'Always follow recognised safe babywearing guidance and fit checks (TICKS guidelines).', NULL, ARRAY[]::text[], 'none'),
    ('cat_soft_carrier_sling', 5, 5, 'visible', true, true, 'micro-adjustability and longevity from newborn to toddler', 'X Baby Carrier', 'Boba', 'Boba Baby UK', 'https://bobababy.co.uk/collections/boba-x-baby-carrier', NULL, 'GBP 99.99', 'in_stock', NULL, 'An all-in-one adjustable baby carrier that offers comfort and support for newborns and toddlers, featuring micro-adjustments for a perfect fit as your baby grows.', 'The Boba X is highly praised for its exceptional adjustability, making it suitable from birth (7lbs) through to toddlerhood (45lbs) without the need for an infant insert. Its soft, breathable fabric and ergonomic design ensure comfort for both baby and wearer, making it a long-lasting and versatile choice.', 'The Boba X is highly praised for its exceptional adjustability, making it suitable from birth (7lbs) through to toddlerhood (45lbs) without the need for an infant insert. Its soft, breathable fabric and ergonomic design ensure comfort for both baby and wearer, making it a long-lasting and versatile choice.', NULL, NULL, false, 'Parent buy', NULL, 'Always follow recognised safe babywearing guidance and fit checks.', NULL, ARRAY[]::text[], 'none'),
    ('cat_washable_floor_play_mat', 1, 1, 'visible', true, false, 'stylish and durable investment', 'The Mariner Playmat', 'Totter + Tumble', 'Totter + Tumble UK', 'https://totterandtumble.co.uk/products/the-mariner-playmat', NULL, 'GBP 160.00', 'in_stock', NULL, 'A high-density, cushioned, and reversible playmat that is easy to wipe clean and designed to complement modern interiors.', 'Offers excellent cushioning and a wipe-clean surface, crucial for early movements and easy maintenance. The reversible design provides versatility and aesthetic appeal, making it a long-term investment.', 'Offers excellent cushioning and a wipe-clean surface, crucial for early movements and easy maintenance. The reversible design provides versatility and aesthetic appeal, making it a long-term investment.', NULL, NULL, true, 'Good gift', NULL, 'Use only during awake, supervised play.', NULL, ARRAY[]::text[], 'none'),
    ('cat_washable_floor_play_mat', 2, 2, 'visible', true, true, 'best overall budget-friendly option', 'Nuby Foldable Playmat Road Map', 'Nuby', 'Amazon UK', 'https://www.amazon.co.uk/Nuby-Foldable-Playmat-Road-Map/dp/B0FLPZG8JG', NULL, 'GBP 39.99', 'in_stock', NULL, 'A lightweight, reversible XPE foam playmat with an engaging road map design, perfect for tummy time and easy storage.', 'Highly practical and affordable, offering a safe and stimulating surface for early play. Its foldable nature makes it convenient for small spaces and travel.', 'Highly practical and affordable, offering a safe and stimulating surface for early play. Its foldable nature makes it convenient for small spaces and travel.', NULL, NULL, true, 'Good gift', NULL, 'Use only during awake, supervised play.', NULL, ARRAY[]::text[], 'none'),
    ('cat_washable_floor_play_mat', 3, 3, 'visible', true, true, 'sensory development', 'Etta Loves Plant Print Reversible Playmat', 'Etta Loves', 'John Lewis', 'https://www.johnlewis.com/etta-loves-plant-print-reversible-sensory-playmat/p110367711', NULL, 'GBP 66.00', 'in_stock', NULL, 'An organic cotton playmat with scientifically inspired patterns designed to support babies'' visual and cognitive development, reversible for different age stages.', 'Its focus on sensory development with high-contrast patterns is ideal for newborns. The organic, machine-washable material ensures comfort and hygiene.', 'Its focus on sensory development with high-contrast patterns is ideal for newborns. The organic, machine-washable material ensures comfort and hygiene.', NULL, NULL, true, 'Good gift', NULL, 'Use only during awake, supervised play.', NULL, ARRAY[]::text[], 'none'),
    ('cat_washable_floor_play_mat', 4, 4, 'visible', true, true, 'thick cushioning and minimalist design', 'Gus + Beau Rainbow Playmat', 'Gus + Beau', 'Gus + Beau', 'https://www.gusandbeau.com/products/rainbow-playmat-set-in-cream', NULL, 'GBP 75.00', 'in_stock', NULL, 'A thick, non-toxic EVA foam puzzle playmat with a minimalist rainbow design, providing excellent cushioning for hard floors.', 'Offers superior cushioning for safety and comfort during active play, while its minimalist design blends well with modern home decor.', 'Offers superior cushioning for safety and comfort during active play, while its minimalist design blends well with modern home decor.', NULL, NULL, true, 'Good gift', NULL, 'Use only during awake, supervised play.', NULL, ARRAY[]::text[], 'none'),
    ('cat_washable_floor_play_mat', 5, 5, 'visible', true, true, 'portability and large play area', 'Skip Hop Roll-up Playmat', 'Skip Hop', 'John Lewis', 'https://www.google.com/search?tbm=shop&q=Skip+Hop+Roll-up+Playmat+UK', NULL, 'GBP 81.51', 'in_stock', NULL, 'A large, reversible, wipe-clean playmat that easily rolls up for storage and portability, offering ample space for baby''s movements.', 'Its large size provides plenty of room for babies to explore and move, while its roll-up design makes it highly convenient for storage and travel.', 'Its large size provides plenty of room for babies to explore and move, while its roll-up design makes it highly convenient for storage and travel.', NULL, NULL, true, 'Good gift', NULL, 'Use only during awake, supervised play.', NULL, ARRAY[]::text[], 'google_shopping')
  ) AS v(source_category_entity_id, pick_rank, longlist_rank, status, is_visible, is_locked, best_for_tag, product_name, brand, retailer, product_url, image_url, price_text, stock_status, age_mark_on_listing, product_description, ember_verdict, why_it_fits, caveats, buy_borrow_hold_off, gift_suitable, gift_note, ownership_note, safety_notes, evidence_tier, evidence_sources, founder_qa_flag)
)
INSERT INTO public.pl_stage3_picks (
  age_band_id,
  category_type_id,
  source_category_entity_id,
  pick_rank,
  longlist_rank,
  status,
  is_visible,
  is_locked,
  best_for_tag,
  product_name,
  brand,
  retailer,
  product_url,
  image_url,
  price_text,
  stock_status,
  age_mark_on_listing,
  product_description,
  ember_verdict,
  why_it_fits,
  caveats,
  buy_borrow_hold_off,
  gift_suitable,
  gift_note,
  ownership_note,
  safety_notes,
  evidence_tier,
  evidence_sources,
  founder_qa_flag,
  research_payload
)
SELECT
  '1-3m',
  ct.id,
  r.source_category_entity_id,
  r.pick_rank,
  r.longlist_rank,
  r.status,
  r.is_visible,
  r.is_locked,
  r.best_for_tag,
  r.product_name,
  r.brand,
  r.retailer,
  r.product_url,
  r.image_url,
  r.price_text,
  r.stock_status,
  r.age_mark_on_listing,
  r.product_description,
  r.ember_verdict,
  r.why_it_fits,
  r.caveats,
  r.buy_borrow_hold_off,
  r.gift_suitable,
  r.gift_note,
  r.ownership_note,
  r.safety_notes,
  r.evidence_tier,
  r.evidence_sources,
  r.founder_qa_flag,
  jsonb_build_object(
    'bundle_schema_version', 'stage3_ingestion_bundle_v1',
    'bundle_generated_at', '2026-07-18T09:49:09.534Z',
    'research_schema_version', 'ember_picks_research_v2',
    'source_category_entity_id', r.source_category_entity_id
  )
FROM stage3_rows r
JOIN public.pl_category_types ct
  ON ct.slug = r.source_category_entity_id
WHERE EXISTS (
  SELECT 1
  FROM public.pl_age_band_development_need_category_types abdnct
  WHERE abdnct.age_band_id = '1-3m'
    AND abdnct.category_type_id = ct.id
    AND abdnct.is_active = true
);

WITH backup_rows AS (
  SELECT *
  FROM (VALUES
    ('cat_baby_safe_mirror', 7, 'To Go Activity Mirror - Happy Clouds - Papaya', 'Done by Deer', NULL, 'https://donebydeer.com/en-gb/products/to-go-activity-mirror-happy-clouds-papaya', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Portable, activity mirror.'),
    ('cat_baby_safe_mirror', 8, 'Activity Floor Mirror - Wally - Blue', 'Done by Deer', NULL, 'https://donebydeer.com/en-gb/products/activity-floor-mirror-wally-blue', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Floor mirror, good for tummy time.'),
    ('cat_baby_safe_mirror', 9, 'Activity Floor Mirror - Croco - Green', 'Done by Deer', NULL, 'https://donebydeer.com/en-gb/products/activity-floor-mirror-croco-green', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Floor mirror, good for tummy time.'),
    ('cat_baby_safe_mirror', 10, 'Sensory Rattle Mirror - Jelly - Powder', 'Done by Deer', NULL, 'https://donebydeer.com/en-gb/products/sensory-rattle-mirror-jelly-powder', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Affordable, sensory features, rattle.'),
    ('cat_baby_safe_mirror', 12, 'Sensory Rattle Mirror Set - Celebration - Colour Mix', 'Done by Deer', NULL, 'https://donebydeer.com/en-gb/products/sensory-rattle-mirror-set-celebration-colour-mix', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Set with sensory features.'),
    ('cat_baby_safe_mirror', 14, 'Vicloon Tummy Time Mirror Toys for Babies', 'Vicloon', NULL, 'https://www.amazon.co.uk/Vicloon-Newborn-Development-Crinkle-Contrast/dp/B09BJW2GQN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Foldable, high contrast patterns, good reviews on Amazon.'),
    ('cat_baby_safe_mirror', 15, 'Sassy Crib & Floor Mirror', 'Sassy', NULL, 'https://www.amazon.co.uk/Sassy-Crib-Floor-Mirror-Black/dp/B00005BMLD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Versatile for crib or floor use, soft frame.'),
    ('cat_board_books', 6, 'Where’s Spot?', 'Eric Hill', NULL, 'https://www.booktrust.org.uk/book-recommendations/bookfinder/wheres-spot/', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Classic interactive lift-the-flap book, good for engagement and early exploration.'),
    ('cat_board_books', 7, 'Little Truck', 'Taro Gomi', NULL, 'https://www.booktrust.org.uk/book-recommendations/bookfinder/little-truck/', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Simple, concise story with effective illustrations, good for reading aloud.'),
    ('cat_board_books', 8, 'Where’s Mr Lion', 'Nosy Crow', NULL, 'https://www.booktrust.org.uk/book-recommendations/bookfinder/wheres-mr-lion/', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Interactive felt flaps and a mirror provide sensory engagement and peekaboo play.'),
    ('cat_board_books', 9, 'Everywhere Babies', 'Susan Meyers', NULL, 'https://www.booktrust.org.uk/book-recommendations/bookfinder/everywhere-babies/', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Celebrates babies and diverse family life, good for emotional connection and recognizing faces.'),
    ('cat_board_books', 10, 'Who?', 'Robie H Harris', NULL, 'https://www.booktrust.org.uk/book-recommendations/bookfinder/who/', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Focuses on family members and faces, aiding social recognition and early vocabulary.'),
    ('cat_board_books', 11, 'Baby’s First Stories', 'Lily Murray', NULL, 'https://www.booktrust.org.uk/book-recommendations/bookfinder/babys-first-stories/', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Charming board book for early bonding and development, with simple rhymes.'),
    ('cat_board_books', 12, 'Look Out! Hungry Snake: A hide-and-seek flap book', 'Paul Delaney', NULL, 'https://www.booktrust.org.uk/book-recommendations/bookfinder/look-out-hungry-snake-a-hide-and-seek-flap-book/', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Colorful lift-the-flap book introducing animals and their sounds/actions, promoting interaction.'),
    ('cat_board_books', 13, 'Clip-Clop', 'Nicola Smee', NULL, 'https://www.booktrust.org.uk/book-recommendations/bookfinder/clip-clop/', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Engaging story with animal characters, good for sound imitation and rhythm.'),
    ('cat_board_books', 14, 'Goodnight Moon', 'Margaret Wise Brown', NULL, 'https://www.booktrust.org.uk/book-recommendations/bookfinder/goodnight-moon/', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Classic comforting bedtime story with rhythmical text, ideal for winding down.'),
    ('cat_board_books', 15, 'Playtime: A Tummy Time Play Book for Babies', 'Mama Makes Books', NULL, 'https://www.booktrust.org.uk/book-recommendations/bookfinder/playtime-a-tummy-time-play-book-for-babies/', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Specifically designed for tummy time, supporting physical development and engagement.'),
    ('cat_burp_cloths_muslins', 6, 'Lewis Muslin Cloth 2-Pack - Mini Panda / Sandy Mix', 'Liewood', NULL, 'https://www.naturalbabyshower.co.uk/products/liewood-lewis-muslin-cloth-2-pack-mini-panda-sandy-mix', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Stylish design, organic cotton, currently on sale.'),
    ('cat_burp_cloths_muslins', 7, 'Daydream Bear Breakfast Print Muslin Squares, Pack of 6', 'John Lewis', NULL, 'https://www.johnlewis.com/john-lewis-daydream-bear-breakfast-print-muslin-squares-pack-of-6/p114887910', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Good value, cute design, John Lewis own brand.'),
    ('cat_burp_cloths_muslins', 8, '3 Pack Pure Cotton Paddington™ Muslins', 'M&S', NULL, 'https://www.marksandspencer.com/3-pack-pure-cotton-paddington-muslins/p/clp60914918', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Popular character, good for gifting.'),
    ('cat_burp_cloths_muslins', 9, 'Burp Cloth 2 Pack - Playground Powder', 'Done By Deer', NULL, 'https://www.naturalbabyshower.co.uk/products/done-by-deer-burp-cloth-2-pack-playground-powder', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Practical, cute design, good for burping.'),
    ('cat_burp_cloths_muslins', 10, '100% bamboo muslins, White, pack of 3', 'Bambuu Baby', NULL, 'https://www.bambuubaby.co.uk/milk-muslins/p/basic-package-mjd2d', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Bamboo for extra softness and absorbency.'),
    ('cat_burp_cloths_muslins', 11, 'Essentials Cotton Muslin Squares - 5 Pack - Tanzania', 'aden + anais', NULL, 'https://www.naturalbabyshower.co.uk/products/aden-anais-essentials-5-pack-cotton-muslin-squares-tanzania', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Popular brand, different design option.'),
    ('cat_burp_cloths_muslins', 12, 'Muslin Cloth (3pack) - Bloomy', 'Jollein', NULL, 'https://www.naturalbabyshower.co.uk/products/jollein-muslin-cloth-3pack-bloomy', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Affordable and practical.'),
    ('cat_burp_cloths_muslins', 13, 'Muslin Squares - 3 Pack - Wild Chamomile', 'Avery Row', NULL, 'https://www.naturalbabyshower.co.uk/products/avery-row-muslin-squares-3-pack-wild-chamomile', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Organic cotton, stylish design.'),
    ('cat_burp_cloths_muslins', 14, 'Daydream Moon Large Muslin Squares, Pack of 3', 'John Lewis', NULL, 'https://www.johnlewis.com/john-lewis-daydream-moon-large-muslin-squares-pack-of-3/p114887908', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Larger size for more coverage.'),
    ('cat_burp_cloths_muslins', 15, 'Baby Muslin Squares, Pack of 6, Grey Star', 'John Lewis', NULL, 'https://www.johnlewis.com/john-lewis-baby-muslin-squares-pack-of-6-grey-star/p429429', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Very affordable, good basic option.'),
    ('cat_firm_flat_mattress', 6, 'Naturalmat The Latex Mat (Cotbed size)', 'Naturalmat', NULL, 'https://naturalmat.co.uk/products/latex-mat', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Natural latex, organic coir, organic lambswool, chemical-free, hypoallergenic, removable/washable cotton cover, firm and flat. Rated 4.6 stars with 22 reviews. *Note: Waterproof mattress protector recommended by manufacturer.*'),
    ('cat_firm_flat_mattress', 7, 'Babymore Eco Fibre Cot Mattress – 140 x 70 cm', 'Babymore', NULL, 'https://babymore.co.uk/shop/baby-mattresses/cot-bed-mattresses/eco-fibre-cot-mattress-140-x-70-cm/', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Chemical-free, eco-friendly, water-resistant, breathable, removable/washable hypoallergenic cover, dent-resistant fibre pad, complies to BS EN 16890:2017.'),
    ('cat_firm_flat_mattress', 8, 'Clevamama ClevaFoam Support Cot Bed Mattress 140 x 70cm', 'Clevamama', NULL, 'https://www.hellobabydirect.com/products/clevamama-clevafoam-support-mattress?srsltid=AfmBOoo3bHbKLvrBNJUVhCizdCu5QQ1cCcmlxfZ2N8CCqbMYlLv1cOz2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ClevaFoam® technology, scientifically proven to reduce pressure on baby''s head, breathable, lightweight, hypoallergenic, pH balanced, toxin-free, removable/machine washable cover. Suitable from birth.'),
    ('cat_firm_flat_mattress', 9, 'CuddleCo Signature Hypo Allergenic Bamboo Pocket Sprung Cot Bed Mattress', 'CuddleCo', NULL, 'https://www.littlewoods.com/cuddleco-signature-hypo-allergenic-bamboo-pocket-sprung-cot-bed-mattress/1600673825.prd', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Pocket springs, dual-sided (bamboo hypoallergenic and waterproof training layer), anti-allergy, breathable, removable/machine washable cover. Rated 5 out of 5 stars with 3 reviews.'),
    ('cat_firm_flat_mattress', 12, 'John Lewis Basic Fibre Cot Mattress, 120 x 60cm', 'John Lewis', NULL, 'https://www.johnlewis.com/john-lewis-basic-fibre-cot-mattress-120-x-60cm/p6410037', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Firm mattress, fibre core, suitable from birth, removable and washable cover. Originally £30.00.'),
    ('cat_firm_flat_mattress', 13, 'Obaby Fibre Mattress - 140 x 70cm', 'Obaby', NULL, 'https://www.obaby.co.uk/products/fibre-mattress-140-x-40-cm', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Breathable, hypoallergenic, 100% recyclable polyester fibre pad, removable/washable cover. Suitable from birth. Complies with UK fire safety regulations and standards for nursery mattresses.'),
    ('cat_firm_flat_mattress', 14, 'MHG Textiles Baby Cot Mattress 140 x 70 x 15 cm', 'MHG Textiles', NULL, 'https://www.amazon.co.uk/MHG-Textiles-Baby-Mattress-140x70x15cm/dp/B0FLLQ8P2F', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Firm, breathable & hypoallergenic, waterproof with removable zipped cover, washable, fits standard UK cot beds. Rated 4.3 stars with 79 reviews.'),
    ('cat_firm_flat_mattress', 15, 'Mamas & Papas Essential Airflow Fibre Cotbed Mattress', 'Mamas & Papas', NULL, 'https://www.mamasandpapas.com/products/essential-fibre-cotbed-mattress-esfbmcb04', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Fibre core for superior airflow, wipe-clean fixed inner protector, airmesh outer top cover, toxin-free, all-round zip-off washable cover.'),
    ('cat_high_contrast_cards', 6, 'Joygoodta Contrast Cards for Infants 0-3 Months', 'Joygoodta', NULL, 'https://www.amazon.co.uk/Joygoodta-Contrast-Infants-Newborns-Stimulation/dp/B0GYF7BX6N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Affordable option with specific 0-3 month focus, but limited review data on Amazon UK.'),
    ('cat_high_contrast_cards', 7, 'URMYWO Baby Toys 0-6 Months, Black and White Sensory Toys', 'URMYWO', NULL, 'https://www.amazon.co.uk/URMYWO-Sensory-Contrast-Stimulation-Education-Essentials/dp/B0CHNY9Q7N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Soft baby book format offers a different tactile experience, suitable for tummy time. Limited review data.'),
    ('cat_high_contrast_cards', 8, 'Done by Deer Contrast Cards', 'Done by Deer', NULL, 'https://www.johnlewis.com/done-by-deer-contrast-cards/p112912341', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Well-known brand available at a reputable retailer (John Lewis), but limited product details and reviews on the page.'),
    ('cat_high_contrast_cards', 9, 'Taf Toys My First Tummy Time Cards', 'Taf Toys', NULL, 'https://www.argos.co.uk/product/7611313', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Specifically designed for tummy time, with a good rating on Argos, but lower review count than top picks.'),
    ('cat_high_contrast_cards', 10, 'ZazzyKid Baby Visual Stimulation Flash Cards', 'ZazzyKid', NULL, 'https://www.amazon.co.uk/ZazzyKid-High-Contrast-Flash-Cards/dp/B0D93JWFCK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Good rating and review count on Amazon UK, specifically for 0-3 months, offering a solid option.'),
    ('cat_high_contrast_cards', 11, 'The Little Sensory Box - Black & White Sensory Cards', 'The Little Sensory Box', NULL, 'https://thelittlesensorybox.com/products/black-white-sensory-cards', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Specialist sensory brand, offering a focused product for newborns. Good quality materials and design.'),
    ('cat_high_contrast_cards', 12, 'MAMIMU High Contrast Baby Flash Cards', 'MAMIMU', NULL, 'https://www.amazon.co.uk/MAMIMU-Contrast-Flashcards-Stimulation-Educational/dp/B0C9G8L22Q', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Good rating and review count on Amazon UK, covers 0-36 months with different stages.'),
    ('cat_high_contrast_cards', 13, 'Tiny Love Black & White High Contrast Cards', 'Tiny Love', NULL, 'https://www.amazon.co.uk/Tiny-Love-Black-White-Contrast/dp/B08P26L1P1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Reputable baby brand, offers a simple and effective set of high-contrast cards. Limited reviews for this specific product.'),
    ('cat_high_contrast_cards', 14, 'Galt Baby Playnest High Contrast Cards', 'Galt', NULL, 'https://www.galttoys.com/baby-playnest-high-contrast-cards.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Well-established toy brand, cards designed to be used with their Playnest, offering a structured play experience.'),
    ('cat_high_contrast_cards', 15, 'Baby Einstein Take Along Discovery Cards', 'Baby Einstein', NULL, 'https://www.amazon.co.uk/Baby-Einstein-Take-Along-Discovery/dp/B00005B54P', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Popular educational baby brand, cards are portable and designed for on-the-go stimulation. Mixed reviews on Amazon.'),
    ('cat_reach_grab_toys', 6, 'Sophie La Girafe Teether', 'Sophie La Girafe', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Popular teether, often used for grasping and mouthing.'),
    ('cat_reach_grab_toys', 8, 'Mini Mizzie Kangaroo Teether', 'Mini Mizzie', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Good for grasping and mouthing, suitable for early development.'),
    ('cat_reach_grab_toys', 10, 'Ring Rattle Deer - Fairy Garden', 'Little Dutch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Easy to grasp, provides auditory stimulation.'),
    ('cat_reach_grab_toys', 11, 'Rain Rattle - Fairy Garden', 'Little Dutch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Provides gentle auditory and visual stimulation, easy to grasp.'),
    ('cat_reach_grab_toys', 12, 'Flower Rattle - Fairy Garden', 'Little Dutch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Easy to grasp, soft textures, gentle rattle sound.'),
    ('cat_reach_grab_toys', 13, 'Rattle Toy - Flower', 'Little Dutch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Soft plush, easy to grasp, gentle sensory sounds.'),
    ('cat_reach_grab_toys', 14, 'My First Gift Set New Baby Toys', 'VTech', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Likely includes graspable items for newborns, good for early development.'),
    ('cat_reach_grab_toys', 15, 'Spiral Activity Toy Raccoon', 'Infantino', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Encourages reaching and grasping, versatile for attachment to various baby gear.'),
    ('cat_rear_facing_car_seat', 6, 'Dualfix Plus i-Size', 'Britax Römer', NULL, 'https://www.argos.co.uk/product/6246985', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Extended rear-facing, 360 swivel, good safety features, but less focused on infant-specific portability than top picks.'),
    ('cat_rear_facing_car_seat', 7, 'Coral 360 i-Size', 'Maxi-Cosi', NULL, 'https://www.maxi-cosi.co.uk/car-seats/coral-360', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Modular design with lightweight soft carrier, 360 rotation, good for travel systems.'),
    ('cat_rear_facing_car_seat', 8, 'Dream i-Size', 'Silver Cross', NULL, 'https://www.kiddies-kingdom.com/birth-15m/59218-silver-cross-dream-i-size-group-0-car-seat-with-isofix-base-lunar.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Awarded best-ever rating by ADAC (with base), good safety, but less unique features than top picks.'),
    ('cat_rear_facing_car_seat', 9, 'i-Spin 360 i-Size', 'Joie', NULL, 'https://www.mamasandpapas.com/products/joie-i-spin-360-car-seat-56071j400', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '360 rotation, i-Size certified, good value, but slightly heavier than some infant-specific carriers.'),
    ('cat_rear_facing_car_seat', 10, 'Cloud G i-Size +', 'Cybex', NULL, 'https://www.johnlewis.com/cybex-cloud-t-i-size-rotating-baby-car-seat/p110535706', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Traditional infant carrier, 180-degree rotation, good padding, but newer T model has more advanced lie-flat.'),
    ('cat_rear_facing_car_seat', 11, 'Pipa Lite', 'Nuna', NULL, 'https://www.johnlewis.com/nuna-pipa-lite-i-size-baby-car-seat-caviar/p111608731', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Very lightweight (2.5kg), good ADAC rating, but Pipa Urbn offers baseless ISOFIX which is a stronger differentiator.'),
    ('cat_rear_facing_car_seat', 12, 'All in All Ultra 360 Rotate i-Size', 'Cosatto', NULL, 'https://www.amazon.co.uk/Cosatto-Ultra-Swivel-Stage-iSize/dp/B0D37LTDB1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Multi-stage seat (birth to 12 years), 360 rotation, good for long-term use.'),
    ('cat_rear_facing_car_seat', 13, 'Motion 3 All Size 360', 'Silver Cross', NULL, 'https://www.amazon.co.uk/Silver-Cross-Newborn-Harness-Rotation/dp/B0GRWTZGP2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'All-size seat, 360 rotation, good for long-term use.'),
    ('cat_rear_facing_car_seat', 14, 'Acorn 2', 'Cosatto', NULL, 'https://www.cosatto.com/products/acorn-i-size-0-car-seat-masquerade', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Good for long journeys, i-Size, travel system compatible.'),
    ('cat_rear_facing_car_seat', 15, 'Pebble S i-Size', 'Maxi-Cosi', NULL, 'https://www.amazon.co.uk/dp/B0D35W3PLM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Budget-friendly i-Size option, good for basic infant carrier needs.'),
    ('cat_soft_carrier_sling', 6, 'Savvy Air 4-in-1 Baby Carrier', 'Joie', NULL, 'https://www.argos.co.uk/product/7337415', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Multi-position carrier suitable from birth.'),
    ('cat_soft_carrier_sling', 7, 'Explore', 'Tula', NULL, 'https://www.amazon.co.uk/Tula-Explore-Ergonomic-Adjustable-3-2-20-4/dp/B0DGH4ZBT9', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ergonomic and adjustable, suitable from 3.2kg.'),
    ('cat_soft_carrier_sling', 8, 'CUDL Clik 2 Baby Carrier', 'Nuna', NULL, 'https://www.johnlewis.com/nuna-cudl-clik-2-baby-carrier-caviar/p113207171', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Good for back support, suitable from birth.'),
    ('cat_soft_carrier_sling', 9, 'Seren 3-in-1 Baby Carrier', 'Ickle Bubba', NULL, 'https://www.amazon.co.uk/Ickle-Bubba-Seren-Carrier-Stone/dp/B0F8VTQ6ZJ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Lightweight, multi-use value, three carry positions.'),
    ('cat_soft_carrier_sling', 10, 'Gaia Organic Cotton Stretchy Wrap Baby Carrier', 'Gaia Baby', NULL, 'https://www.johnlewis.com/gaia-baby-organic-cotton-stretchy-wrap-baby-carrier/forest-green/p110412690', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Stretchy wrap, organic cotton, good for newborns.'),
    ('cat_soft_carrier_sling', 11, 'Upsie Sling Carrier', 'Ergobaby', NULL, 'https://www.johnlewis.com/ergobaby-upsie-sling-carrier/natural-beige/p110412690', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Sling carrier, easy to use, suitable from birth.'),
    ('cat_soft_carrier_sling', 12, 'Limas Baby Carrier', 'Stokke', NULL, 'https://www.johnlewis.com/stokke-limas-baby-carrier/black/p110412690', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Hybrid carrier, suitable from birth.'),
    ('cat_soft_carrier_sling', 13, 'Baby Woven Mini Carrier', 'BabyBjörn', NULL, 'https://www.johnlewis.com/babybjorn-baby-woven-mini-carrier/black/p110412690', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Compact, suitable for newborns, easy to use.'),
    ('cat_soft_carrier_sling', 14, 'Omni Breeze Baby Carrier', 'Ergobaby', NULL, 'https://www.boots.com/ergobaby-omni-breeze-baby-carrier-onyx-black-10334843', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Versatile, great fit range, four carry positions, breathable, suitable from birth.'),
    ('cat_soft_carrier_sling', 15, 'Integra Baby Carrier', 'Integra Baby', NULL, 'https://integrababy.co.uk/products/black-essential-integra-size-1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Compact, suitable from birth.'),
    ('cat_washable_floor_play_mat', 6, 'Tiny Love Meadow Days Super Play Mat', 'Tiny Love', NULL, 'https://www.boots.com/tiny-love-unicorn-wonderlands-developmental-gymini-play-mat-10376047', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Good for travel, machine washable. Available at Boots UK.'),
    ('cat_washable_floor_play_mat', 7, 'DockATot MiniMat', 'DockATot', NULL, 'https://www.johnlewis.com/dockatot-deluxe-plus-pod-spare-cover/p109191397', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Raised edges, padded, OEKO-TEX Standard cotton, machine-washable mat. Available at John Lewis.'),
    ('cat_washable_floor_play_mat', 8, 'Nuby Reversible Playmat', 'Nuby', NULL, 'https://www.amazon.co.uk/Nuby-Reversible-Playmat-Road-Map/dp/B0FLPZG8JG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Lightweight, reversible foam, wipe-clean, foldable. Available via Amazon UK and Argos.'),
    ('cat_washable_floor_play_mat', 9, 'Tutti Bambini Puzzle Playmat', 'Tutti Bambini', NULL, 'https://www.amazon.co.uk/Tutti-Bambini-Puzzle-Playmat-Grey/dp/B09YVB5DJN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Non-toxic EVA foam, wipeable. Best budget according to The Independent. Available via Amazon UK.'),
    ('cat_washable_floor_play_mat', 10, 'Avery Row Activity Mat Wildflower Garden', 'Avery Row', NULL, 'https://www.johnlewis.com/avery-row-wildflower-garden-activity-mat/p114803738', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Best for travelling according to The Independent. Available at John Lewis.'),
    ('cat_washable_floor_play_mat', 11, 'Baby Einstein 4-in-1 Kickin'' Tunes Music and Language Discovery Activity Gym', 'Baby Einstein', NULL, 'https://www.johnlewis.com/baby-einstein-4-in-1-kickin-tunes-music-and-language-discovery-activity-gym/p3845072', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Best activity play mat according to The Independent. Available at John Lewis.'),
    ('cat_washable_floor_play_mat', 12, 'Lalo Quilted Play Mat', 'Lalo', NULL, 'https://www.meetlalo.com/products/mat', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Lyocell, machine washable, eco-friendly. UK stockists mentioned (Harrods, Selfridges).'),
    ('cat_washable_floor_play_mat', 13, 'Totter + Tumble Morris & Co. The Bullerswood Stone Woad Playmat', 'Totter + Tumble', NULL, 'https://totterandtumble.co.uk/products/morris-co-the-bullerswood-stone-playmat', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Patented, non-toxic, PVA-sealed memory foam, reversible, wipe clean. Best versatile according to The Independent.'),
    ('cat_washable_floor_play_mat', 14, 'The Fable Playmat', 'Totter + Tumble', NULL, 'https://totterandtumble.co.uk/collections/all/products/the-fable-playmat', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'New in, stylish, reversible, wipe-clean design from a reputable brand.'),
    ('cat_washable_floor_play_mat', 15, 'The Aster Playmat', 'Totter + Tumble', NULL, 'https://totterandtumble.co.uk/collections/all/products/the-aster-playmat', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'New in, stylish, reversible, wipe-clean design from a reputable brand.')
  ) AS v(source_category_entity_id, longlist_rank, product_name, brand, best_for_tag, product_url, retailer, price_text, stock_status, age_mark_on_listing, evidence_tier, buy_borrow_hold_off, gift_suitable, caveat_short)
)
INSERT INTO public.pl_stage3_picks (
  age_band_id,
  category_type_id,
  source_category_entity_id,
  pick_rank,
  longlist_rank,
  status,
  is_visible,
  is_locked,
  best_for_tag,
  product_name,
  brand,
  retailer,
  product_url,
  price_text,
  stock_status,
  age_mark_on_listing,
  caveats,
  buy_borrow_hold_off,
  gift_suitable,
  evidence_tier,
  founder_qa_flag,
  research_payload
)
SELECT
  '1-3m',
  ct.id,
  r.source_category_entity_id,
  r.longlist_rank,
  r.longlist_rank,
  'backup',
  false,
  true,
  r.best_for_tag,
  r.product_name,
  r.brand,
  r.retailer,
  r.product_url,
  r.price_text,
  r.stock_status,
  r.age_mark_on_listing,
  r.caveat_short,
  r.buy_borrow_hold_off,
  r.gift_suitable,
  r.evidence_tier,
  'backup_not_card_ready',
  jsonb_build_object(
    'bundle_schema_version', 'stage3_ingestion_bundle_v1',
    'bundle_generated_at', '2026-07-18T09:49:09.534Z',
    'status', 'dormant_backup',
    'source_category_entity_id', r.source_category_entity_id
  )
FROM backup_rows r
JOIN public.pl_category_types ct
  ON ct.slug = r.source_category_entity_id
WHERE EXISTS (
  SELECT 1
  FROM public.pl_age_band_development_need_category_types abdnct
  WHERE abdnct.age_band_id = '1-3m'
    AND abdnct.category_type_id = ct.id
    AND abdnct.is_active = true
);

DO $$
DECLARE
  v_visible_count INTEGER;
  v_backup_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_visible_count
  FROM public.pl_stage3_picks s
  JOIN public.pl_category_types ct ON ct.id = s.category_type_id
  WHERE s.age_band_id = '1-3m'
    AND ct.slug IN ('cat_baby_safe_mirror', 'cat_board_books', 'cat_burp_cloths_muslins', 'cat_firm_flat_mattress', 'cat_high_contrast_cards', 'cat_reach_grab_toys', 'cat_rear_facing_car_seat', 'cat_soft_carrier_sling', 'cat_washable_floor_play_mat')
    AND s.status = 'visible'
    AND s.is_visible = true;

  IF v_visible_count <> 45 THEN
    RAISE EXCEPTION 'Expected 45 visible Stage 3 picks for 1-3m, got %', v_visible_count;
  END IF;

  SELECT COUNT(*) INTO v_backup_count
  FROM public.pl_stage3_picks s
  JOIN public.pl_category_types ct ON ct.id = s.category_type_id
  WHERE s.age_band_id = '1-3m'
    AND ct.slug IN ('cat_baby_safe_mirror', 'cat_board_books', 'cat_burp_cloths_muslins', 'cat_firm_flat_mattress', 'cat_high_contrast_cards', 'cat_reach_grab_toys', 'cat_rear_facing_car_seat', 'cat_soft_carrier_sling', 'cat_washable_floor_play_mat')
    AND s.status = 'backup'
    AND s.is_visible = false;

  IF v_backup_count <> 83 THEN
    RAISE EXCEPTION 'Expected 83 backup Stage 3 picks for 1-3m, got %', v_backup_count;
  END IF;
END $$;

COMMIT;
